### ISSUE TITLE
Create wiki

### ISSUE THREAD

**Issue by GrowtopiaNoobs** [GrowtopiaNoobs/GrowtopiaServer#10]
There should be wiki with basic step by step tutorials, which will guide newbies how to setup server.

**Comment by ritzysw** [comment]
well if newbies cant even set server up then it would be better to just use your pre built server.exe

**Comment by GrowtopiaNoobs** [comment]
> well if newbies cant even set server up then it would be better to just use your pre built server.exe

Yeah, but most of them doesn't even know how to setup http server, so they can't connect.

**Comment by GrowtopiaNoobs** [comment]
Well some basic wiki is here, probably I wont add more stuff to it, so I am closing this issue now.
