### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ItzFrozee** [GrowtopiaNoobs/GrowtopiaServer#100]
how to make a private server using Visual studio

**Comment by Mempler** [comment]
This is invalid, if you really want to know how then go here https://github.com/GrowtopiaNoobs/GrowtopiaServer/wiki/Basic-setup and read how it works!

**Comment by ItzFrozee** [comment]
How do i do it idk how 
![image](https://user-images.githubusercontent.com/44836745/48974369-5ada9a00-f091-11e8-94c7-1c523680ca39.png)
I have this but idk how to fix it
