### ISSUE TITLE
How to Rat like playingey help pls

### ISSUE THREAD

**Issue by kingawesomed2** [GrowtopiaNoobs/GrowtopiaServer#1000]
How pls i watch pleyingeyhdgaming and i see dark comet rat in his desktop how rat omg help pls me want be pro ratter like pleyingey and i want be indoggg noob like pleyingey helpp

**Comment by kingawesomed2** [comment]
![Screenshot_20191030-233852_YouTube](https://user-images.githubusercontent.com/55334843/67896989-881bac00-fb6e-11e9-9070-e66b3bc033e4.jpg)
![Screenshot_20191030-233839_YouTube](https://user-images.githubusercontent.com/55334843/67896997-8c47c980-fb6e-11e9-8a47-0e9bd78f42f9.jpg)
![Uploading Screenshot_20191030-233701_YouTube.jpg…]()

**Comment by kingawesomed2** [comment]
Pro ratter umggg

**Comment by kingawesomed2** [comment]
Maybw he bind cpp with rat??? Someone stupid say ita not possible its possible
Someone noob say ce. File cant bind with virus too but its possible if you dont know search in youtube dont be stupid pls. U can bind .png .jng file with keylogger too lmaoo

**Comment by playingo** [comment]
you cant fucking bind a .cpp file with a fucking rat turkish 11 year old immigrant kid this is the wrong section, mr migrant

**Comment by Devops12321** [comment]
@playingo  I do not think that he is a child I agree that what he says is true

**Comment by Devops12321** [comment]
in ur desktop have darkcomet :V

**Comment by GrowtopiaNoobs** [comment]
This isn't anyhow related to GTPS. Closing.

**Comment by atomiclucky** [comment]
damn, the 1000th issue.

**Comment by iProgramMC** [comment]
wasted the #1000 spot on this...
