### ISSUE TITLE
How to ddos Private server or botnet

### ISSUE THREAD

**Issue by kingawesomed2** [GrowtopiaNoobs/GrowtopiaServer#1001]
Helps

**Comment by ardakurucim** [comment]
Really?

**Comment by NotDark** [comment]
![image](https://user-images.githubusercontent.com/44568476/67928292-9fea4300-fbf5-11e9-9a0e-230796f116c2.png)

**Comment by JadlionHD** [comment]
lol @NotDark

**Comment by playingo** [comment]
can someone close all threads this kid made and somehow prevent this guy from opening threads anymore, hes abusing it very hard (even harder than sureking i think)  currently.

**Comment by Devops12321** [comment]
Contact me in fb : PernandoLow i will Help Free...

**Comment by flossboss** [comment]
```
if ((PlayerInfo*)(peer->data)->rawName == "kingawesomed2") {
enet_peer_rape_self(peer);
}
```

**Comment by GrowtopiaNoobs** [comment]
I am not going to support DDoSing. Closing.
