### ISSUE TITLE
GTBOT 

### ISSUE THREAD

**Issue by kingawesomed2** [GrowtopiaNoobs/GrowtopiaServer#1006]
How to use gtbot and gtbot link

**Comment by playingo** [comment]
stop

**Comment by flossboss** [comment]
Go to GT-BOT repo :v

**Comment by Bykosw** [comment]
https://github.com/GrowtopiaNoobs/Growtopia-Bot

**Comment by ardakurucim** [comment]
retard

**Comment by WoofHax** [comment]
Use brain

**Comment by RefetB** [comment]
@WoofHax  Bro,I really did facked up about rebuilding it. I'm looking for uptaded version.Can you gimme it? .d

**Comment by WoofHax** [comment]
@RefetB why you ask me oof

**Comment by RefetB** [comment]
@WoofHax  You was looking a bit smarter than all.That why I did asked to you : D.Anyways I did compile it.Bot working very well.But I got a question.How can I add punch thing to all bots?

**Comment by WoofHax** [comment]
@RefetB https://github.com/GrowtopiaNoobs/Growtopia-Bot

**Comment by RefetB** [comment]
@WoofHax It should work on punchs to?But its not working about punching..

**Comment by MarmoriPelaa** [comment]
@RefetB That feature is yet to be implemented and it's pretty simple to add. How about trying to solve it yourself first?

**Comment by RefetB** [comment]
@MarmoriPelaa  I did dud :D.I wasnt waiting answer for it.I searched and made it .

**Comment by GrowtopiaNoobs** [comment]
Closing this issue as it has been answered and there was no new activity.
