### ISSUE TITLE
[BUG] Stopped Working when run in Virtual Box.

### ISSUE THREAD

**Issue by Jdsawf** [GrowtopiaNoobs/GrowtopiaServer#1007]
When I start the EXE file on  the 2.998 version it immediately crashes and says "Growtopia.exe has stopped working". Keep in mind it's working on 2.996 and I just reinstalled it to check and yes, it's indeed working on version 2.996. Using Virtual Box with Windows 7 works perfectly on my normal host machine with Windows 10. Tried reinstalling with a clean install of the game and deleted Temp files yet the problem still persists. Please help. Thank you.

**Comment by NotDark** [comment]
that not server problem

**Comment by iProgramMC** [comment]
post on gt forums WITHOUT MENTIONING PRIVATE SERVERS. They will ban you if you do.

**Comment by WoofHax** [comment]
Only one way to fix them destroy you PC

**Comment by MarmoriPelaa** [comment]
Additional info: Using Virtual Box in normal GT servers is illegal since it is considered as ban evading.

**Comment by GrowtopiaNoobs** [comment]
As said, this is not server problem, closing.
