### ISSUE TITLE
[BUG] Build enet on Termux (Android))

### ISSUE THREAD

**Issue by WoofHax** [GrowtopiaNoobs/GrowtopiaServer#1009]
![IMG_20191107_112007](https://user-images.githubusercontent.com/52075701/68357780-606daa80-0151-11ea-9d24-1489230dcdef.jpg)
@GrowtopiaNoobs So I am trying build enet test server on termux (Android)
But the os is missing idk how to fix them

**Comment by Granger-spec** [comment]
家庭马克哦他啊而死么

**Comment by WoofHax** [comment]
@Granger-spec English plz
