### ISSUE TITLE
How to setup microsoft azure vps.

### ISSUE THREAD

**Issue by coldtopia** [GrowtopiaNoobs/GrowtopiaServer#1010]
So i tried to setup a azure vps but when i try to login it says : connection timed out
how to fix it?

**Comment by NotDark** [comment]
firewall

**Comment by coldtopia** [comment]
![image](https://user-images.githubusercontent.com/53939657/68377430-368b9800-00ff-11ea-9e06-e922890dce97.png)
like this? @NotDark

**Comment by Switchry** [comment]
Simple fix: Dont use gcp or azure or aws trial

**Comment by JadlionHD** [comment]
He's using azure cuz of gcloud is lagging or something like that. So that why he's using azure vps.

**Comment by coldtopia** [comment]
btw where can i found server_data.php for xampp?

**Comment by JadlionHD** [comment]
> btw where can i found server_data.php for xampp?

i send you the server_data.php at dm

**Comment by WolfPT** [comment]
> So i tried to setup a azure vps but when i try to login it says : connection timed out
> how to fix it?

Add me DARK#8280

**Comment by coldtopia** [comment]
> > So i tried to setup a azure vps but when i try to login it says : connection timed out
> > how to fix it?
> 
> Add me DARK#8280

ok

**Comment by atomiclucky** [comment]
omg enigma owner

**Comment by WoofHax** [comment]
Wow setup azure is easily 
just add inbound and outbound on website host azure anywhere

**Comment by coldtopia** [comment]
i'm not enigma owner.. 
btw problem solved closing..
