### ISSUE TITLE
What is memcpy

### ISSUE THREAD

**Issue by IndogLelele** [GrowtopiaNoobs/GrowtopiaServer#1015]
What is memcpy for? how its work? can you explain me?

**Comment by NotDark** [comment]
memory copy

**Comment by IndogLelele** [comment]
i dont know how to use:(

**Comment by playingo** [comment]
copy memory from specific source to specific destination.
Example: we wanna copy the integer 1 into a byte pointer so it would look like:

int one = 1; // create new integer variable and assign 1 to it (or easier: set it to 1)
BYTE* bytepointer = new BYTE[4]; // create new byte pointer with length 4
for (int i = 0; i < 4; i++)  bytepointer[i] = 0; // set each byte to 0 in the pointer so BYTE[0] = 0, BYTE[1] = 0, BYTE[2] = 0 etc.. (basically making sure the byte we've created is full of zero's so we can use this to copy values into this cleanfully).
memcpy(bytepointer, &one, 2); // we cannot simply just stupidly do it like "bytepointer = 1" (thats not the purpose of a byte) thats why we have to copy memory/the value from 'one' (which is 1 in this case) into it. This basically gets the value from the value that the variable 'one' currently holds in the memory, and copies into with the size of 2 into the bytepointer.
//you may wanna use offsets if you want to, this will specify where you wanna specifically set the values in, but make sure that the source fits into the destination then.

**Comment by IndogLelele** [comment]
@playingo thx you :)
