### ISSUE TITLE
Windows 2012, or 2016 or 2019 is better ? 

### ISSUE THREAD

**Issue by Devops12321** [GrowtopiaNoobs/GrowtopiaServer#1016]
Windows 2012, or 2016 or 2019 is better ?  what's the difference

**Comment by arshizx** [comment]
2012 is better for me

**Comment by WoofHax** [comment]
2012 and 2019 can host server 
If 2016 cannot host the server using xampp

**Comment by JadlionHD** [comment]
Better use 2012

**Comment by RajehTXD** [comment]
2012 is cheaper if host outside...

**Comment by GrowtopiaNoobs** [comment]
Question was answered, closing.
