### ISSUE TITLE
host private server in amazon vps possible ?

### ISSUE THREAD

**Issue by Devops12321** [GrowtopiaNoobs/GrowtopiaServer#1018]
i try but no work anyone know how ?

**Comment by cmdocmd** [comment]
if u want to host ur server u can host it with any vps BUT u should open the ports

**Comment by NotDark** [comment]
add tcp 80 udp 17091 to firewall in the website

**Comment by WoofHax** [comment]
Inbound 17091 and http port 80
Outbound http port 80

**Comment by GrowtopiaNoobs** [comment]
Question was answered, closing.
