### ISSUE TITLE
[BUG] Sign after click OK Text nothing 

### ISSUE THREAD

**Issue by FarhanGT** [GrowtopiaNoobs/GrowtopiaServer#1020]
Bug this Who know?

**Comment by Bykosw** [comment]
what

**Comment by playingo** [comment]
close due to inproper language.

**Comment by cmdocmd** [comment]
lol make it work..

**Comment by JadlionHD** [comment]
wdym

**Comment by noobes1337** [comment]
k

**Comment by iProgramMC** [comment]
just write the code goddamnit

**Comment by GrowtopiaNoobs** [comment]
This bug isn't related to this server, as it doesn't support signs and you haven't provided any code.
