### ISSUE TITLE
Discord Bot Status that count player online

### ISSUE THREAD

**Issue by JadlionHD** [GrowtopiaNoobs/GrowtopiaServer#1021]
![1231232](https://user-images.githubusercontent.com/48410066/68543948-5f0ddd80-03f0-11ea-80be-a13300f7da13.PNG)
how do i make bot status like @NotDark

**Comment by NotDark** [comment]
make onlinecount.txt and discord bot read that every second

**Comment by WoofHax** [comment]
Also you can use 
https://github.com/yourWaifu/sleepy-discord is libary c++ if you pro :D

**Comment by IndogLelele** [comment]
Ez just use onlinepeople.txt to count people and use updown.txt if down or up just use random number in updown.txt if the number not changing the server is down :)

**Comment by JadlionHD** [comment]
Just made the bot, thanks for helping. closing issue
