### ISSUE TITLE
Take gems

### ISSUE THREAD

**Issue by IndogLelele** [GrowtopiaNoobs/GrowtopiaServer#1022]
Why if i take gems my gems not changing and i use on sendTake if item == 112 then bla bla bla is not working too :(

and one more how to make gems if 5 is change to blue if 10 is change to red if 50 change to green and if 100 change to purple

**Comment by Bykosw** [comment]
((PlayerInfo*)(peer->data))->gems = ((PlayerInfo*)(peer->data))->gems + takedgem;

**Comment by IndogLelele** [comment]
@Bykosw Iknow but if i take is not showing id of gems (112)

**Comment by cmdocmd** [comment]
try to find it ur self

**Comment by IndogLelele** [comment]
idk ok ok thx for your nothing help xD

**Comment by IndogLelele** [comment]
Help pls :(
sendTake(bla bla bla, int item)
{
    cout << item << endl; 
    //Is not showing id item but showing another number :(
}

**Comment by cmdocmd** [comment]
exactly... fix it lol

**Comment by cmdocmd** [comment]
i think it show uid number ...

**Comment by WoofHax** [comment]
Idk what is mean sendTake(bla bla bla, int item)

**Comment by IndogLelele** [comment]
hm if i take gems my gems not changing

**Comment by NotDark** [comment]
u cant do like this only  if item == 112

**Comment by IndogLelele** [comment]
so how?

**Comment by ardakurucim** [comment]
@IndogLelele save tiles with item id then cout tiles->droppedItem etc etc

**Comment by IndogLelele** [comment]
Uh ok i think have a simple code
