### ISSUE TITLE
Indoglelel= playingey

### ISSUE THREAD

**Issue by kingawesomed2** [GrowtopiaNoobs/GrowtopiaServer#1028]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by playingo** [comment]
no

**Comment by ZentaiZber** [comment]
???????????????????

**Comment by IndogLelele** [comment]
Nope.

**Comment by GrowtopiaNoobs** [comment]
Closing this issue as it is nonsense.
