### ISSUE TITLE
[Help] Compiler messed up!

### ISSUE THREAD

**Issue by Orbit4682** [GrowtopiaNoobs/GrowtopiaServer#1029]
![image](https://user-images.githubusercontent.com/52362615/69000650-87865380-0898-11ea-9d62-363f797bc7f9.png)

**Comment by InjectionZ** [comment]
try to Batch Build -> Win32

**Comment by Orbit4682** [comment]
> try to Batch Build -> Win32

Can we have a convo in discord? Orbit#4682

**Comment by Orbit4682** [comment]
Didnt work

**Comment by InjectionZ** [comment]
Injection.#4898

**Comment by GrowtopiaNoobs** [comment]
I am closing this issue, as there was no new activity and isn't any code attached, so it would be hard to figure out what is causing the issue. If you still have this issue, then please open new one with same content.
