### ISSUE TITLE
Fix for leaked byko's bot

### ISSUE THREAD

**Issue by raiterjaki** [GrowtopiaNoobs/GrowtopiaServer#1032]
Most of you know that indo gamers are using leaked byko/mine bot to crash servers. I will share a fix for you guys that they will be not able to get in your private servers anymore. 
```
else if (id == "game_version")
                        {
                            if (act != "2.998") {
sendConsoleMsg(peer, "update gt ok");
enet_peer_disconnect_later(peer, 0);
}
}
```
Since leaked bot's version is 2.996 and if you make your server 2.998 only then, bots will be not able to get in your servers and use b1g crash features. If you don't know where to place it then, you deserve to get your server crashed or someone in comments can help you. I'm sharing it for my self and other server developers who are done with these indo gamers crashing their server.

Thank us later for code ;)

Edited: They can't change the version using hex editor because they can't find 2.996

**Comment by Bykosw** [comment]
you made valkrie cry

**Comment by ritzysw** [comment]
>Thank us later for code ;)
peak

**Comment by IndogLelele** [comment]
lol nice @raiterjaki

**Comment by WoofHax** [comment]
Move to 2.97 version 😂👌

**Comment by coldtopia** [comment]
tysm ;)

**Comment by ardakurucim** [comment]
@raiterjaki what about update gtbot version?

**Comment by ardakurucim** [comment]
@raiterjaki ouch its exe

**Comment by playingo** [comment]
how to fix this retarded skid bot part 1 : open bot, search ce for string "2.996" change to "2.998" enjoy.

**Comment by raiterjaki** [comment]
> how to fix this retarded skid bot part 1 (so it can join servers again) : open bot, search ce for string "2.996" change to "2.998" enjoy. (or use hex viewer)

you cant change it because its 256 bit encrypted ;)
http://prntscr.com/q0o7k4
