### ISSUE TITLE
VPS HELP ME

### ISSUE THREAD

**Issue by Orbit4682** [GrowtopiaNoobs/GrowtopiaServer#1034]
Inbound Rules:
![image](https://user-images.githubusercontent.com/52362615/69016975-0ba80c00-0969-11ea-8ff4-bcf116c2c115.png)

Outbound Rules:
![image](https://user-images.githubusercontent.com/52362615/69016980-1d89af00-0969-11ea-81f5-a5234508a2e6.png)

Outcome : 
![image](https://user-images.githubusercontent.com/52362615/69016987-2c706180-0969-11ea-9144-88dfd7ba7893.png)

**Comment by WoofHax** [comment]
Did you add port too on website ?

**Comment by NotDark** [comment]
do you have web server?

**Comment by JadlionHD** [comment]
i think he buy the vps from someone else, idk

**Comment by IndogLelele** [comment]
if you using gcloud ope gcloud console and write `g cloud compute firewall-rules create allow-rdp --allow udp:17091`

**Comment by Orbit4682** [comment]
All taken care of

**Comment by Farhan1907s** [comment]
> if you using gcloud ope gcloud console and write `g cloud compute firewall-rules create allow-rdp --allow udp:17091`

If azure?

**Comment by Farhan1907s** [comment]
> Did you add port too on website ?

how add in Microsoft azure? Soo confusing
