### ISSUE TITLE
NEW CODE WITH A LOT OF NEW THINGS :)

### ISSUE THREAD

**Issue by OverallGod** [GrowtopiaNoobs/GrowtopiaServer#104]
https://github.com/OverallGod/GrowtopiaServer
https://github.com/OverallGod/GrowtopiaServer

**Comment by zsmidori** [comment]
LOL That was War's Private Server

**Comment by WolfPT** [comment]
@OverallGod Can you Fix a Erors i compile but he give a error

**Comment by Mempler** [comment]
But you're the same mistake as Growtopia Noobs did... Put everything in the same file.
