### ISSUE TITLE
Coredata

### ISSUE THREAD

**Issue by agsa15** [GrowtopiaNoobs/GrowtopiaServer#1041]
Give me new coredata pls

**Comment by DrOreo002** [comment]
Atm there's no free CoreData available, since its really hard to get. No one is willing to give it for free..

**Comment by Switchry** [comment]
https://github.com/ServerRelated/GrowtopiaItemDatabase/blob/master/CoreData.txt

**Comment by DrOreo002** [comment]
> https://github.com/ServerRelated/GrowtopiaItemDatabase/blob/master/CoreData.txt

Is this the latest version?. Or its just a fork from TK69?

**Comment by ardakurucim** [comment]
@DrOreo002 its latest lmao
