### ISSUE TITLE
[BUG] Place block on yourself crash

### ISSUE THREAD

**Issue by SSebia** [GrowtopiaNoobs/GrowtopiaServer#1043]
**When you place a block on yourself enet server test crashes. Anyone know fix?**

**Comment by Bykosw** [comment]
stop using leaked sources = fix, there is no crash for original source

**Comment by SSebia** [comment]
Bug fixed -> there was problem with respawn code.

**Comment by RajehTXD** [comment]
> stop using leaked sources = fix, there is no crash for original source

TRUEEE
@SSebia nobody I mean NOBODY will give you codes...

**Comment by GrowtopiaNoobs** [comment]
If it is solved, then please close your issue.
