### ISSUE TITLE
[BUG] When I update/build my gameversion in Virtual Machine. This happens!

### ISSUE THREAD

**Issue by Orbit4682** [GrowtopiaNoobs/GrowtopiaServer#1044]
![image](https://user-images.githubusercontent.com/52362615/69393152-f222ff00-0c9d-11ea-8c6a-d38ed458d135.png)
How do I fix this issue? Look at "Error List"  ↓ ↓ ↓ ↓

**Comment by ardakurucim** [comment]
use vs2017

**Comment by Devops12321** [comment]
use vs 2015

**Comment by GrowtopiaNoobs** [comment]
Use `#define _SILENCE_EXP...`. I am lazy to write that long thing here.

**Comment by Orbit4682** [comment]
> Use `#define _SILENCE_EXP...`. I am lazy to write that long thing here.

I tried that yesterday, but it didn’t work. Just Incase I put it in the wrong place, where do I place it?

**Comment by Orbit4682** [comment]
![image](https://user-images.githubusercontent.com/52362615/69470405-16ddac00-0d5c-11ea-90db-34581a3fd697.png)

**Comment by WoofHax** [comment]
Is that visual studio 2019?

**Comment by Krazuto** [comment]
> Is that visual studio 2019?

Yeah it is

**Comment by coldtopia** [comment]
Don't use build + intelisense, use build only..

**Comment by Orbit4682** [comment]
Nevermind, managed to figure it out!
