### ISSUE TITLE
[BUG] crypt Blowfish help

### ISSUE THREAD

**Issue by Orbit4682** [GrowtopiaNoobs/GrowtopiaServer#1045]
![image](https://user-images.githubusercontent.com/52362615/69473042-59f94880-0d77-11ea-8f7b-c813c23211c7.png)

**Comment by NotDark** [comment]
delete that and download from https://github.com/GrowtopiaNoobs/GrowtopiaServer/

**Comment by flossboss** [comment]
when you use leaked cpps and copy + paste
