### ISSUE TITLE
I found this error on my cpp....

### ISSUE THREAD

**Issue by coldtopia** [GrowtopiaNoobs/GrowtopiaServer#1046]
Does someone know how to fix this?
![image](https://user-images.githubusercontent.com/53939657/69503156-9a102500-0f49-11ea-8503-9b695ff15916.png)

**Comment by flossboss** [comment]
LOL

**Comment by coldtopia** [comment]
![image](https://user-images.githubusercontent.com/53939657/69503165-bc09a780-0f49-11ea-84d4-469fd8c260c0.png)

**Comment by coldtopia** [comment]
uh

**Comment by WoofHax** [comment]
https://stackoverflow.com/questions/3335841/what-is-the-binary-representation-of-a-boolean-value-in-c-sharp

**Comment by IndogLelele** [comment]
only small error you cant fix it xD

**Comment by iProgramMC** [comment]
What are the arguments to the '==' operator? If you were to take your time to actually look you'd realize that some values simply cannot be checked for equality against a 'char'. These may include structs, byte arrays, ints, floats and doubles. May I please have a look at the offending code + declarations?

**Comment by coldtopia** [comment]
When i click that error it will bring me to xutility

**Comment by coldtopia** [comment]
also it's not a small error

**Comment by iProgramMC** [comment]
Try redownloading the project and adding everything you've done, see where the xutility starts bugging out.

**Comment by atomiclucky** [comment]
that's not the case, he just fucked up the code. Happened to me a few times.

**Comment by Zlarex** [comment]
Is there no IDE warning?

**Comment by GrowtopiaNoobs** [comment]
There was suggested solution from @iProgramMC and I dont think that we can give you more help based on info you gave us. Please create this issue again with more info if you still have this problem.
