### ISSUE TITLE
Nodejs 

### ISSUE THREAD

**Issue by kingawesomed2** [GrowtopiaNoobs/GrowtopiaServer#1048]
How host server in node.js?

**Comment by DrOreo002** [comment]
This is a cpp server, you can't host it on node since its a different thing. But you can try to make one, maybe there's a nodejs wrapper for enet out there?

**Comment by WoofHax** [comment]
Why you don't just ask how to host server on python

**Comment by kingawesomed2** [comment]
Nodejs better anyone know how to code nodejs?

**Comment by Bykosw** [comment]
do you mean nodejs web server instead of python. xampp

**Comment by LaYellow** [comment]
> Why you don't just ask how to host server on python

gdn1337 what is your discord,me need find u so long is hard ok say discord or b4n.

**Comment by WoofHax** [comment]
@LaYellow I am not sure who is gdn1337

**Comment by LaYellow** [comment]
> @LaYellow I am not sure who is gdn1337

![Screenshot_20191125-192455_YouTube](https://user-images.githubusercontent.com/48283030/69678863-b941ba80-10e1-11ea-9081-19afa0660f77.jpg)

**Comment by LaYellow** [comment]
> @LaYellow I am not sure who is gdn1337

![Screenshot_20191125-192433_YouTube](https://user-images.githubusercontent.com/48283030/69678922-d70f1f80-10e1-11ea-83cf-5045aa53e120.jpg)

**Comment by WoofHax** [comment]
@LaYellow idk

**Comment by LaYellow** [comment]
> @LaYellow idk

see discord

**Comment by Cojeb** [comment]
you can easily use express
```js
const express = require("express");
const app = express();

app.post("*", (req, res) => {
  return res.send("server|127.0.0.1\nport|17091\ntype|1\n#maint|Mainetrance message (Not used for now) -- Growtopia Noobs\n\nbeta_server|127.0.0.1\nbeta_port|17091\n\nbeta_type|1\nmeta|localhost\nRTENDMARKERBS1001");
});

app.listen(80);
```

Install express by running `npm install express` in same directory as this file.
Tip: If you are on linux you may want to launch it with `sudo node...`.

**Comment by GrowtopiaNoobs** [comment]
If you still have this question, then please move to #1253
