### ISSUE TITLE
[BUG] Connection Timed Out - Azure - 2012 Server

### ISSUE THREAD

**Issue by JustinAkaru** [GrowtopiaNoobs/GrowtopiaServer#1051]
We are stuck on "Connection Timed Out". We have taken into account what causes this error, and have patched them.
We have done:
- Setup port forwarding
- Setup firewall with both rules
- Set IP of python file to the server ip
- Get latest CoreData, Descriptions, and Items.dat 

I don't know of any other way to fix this. It works when using localhost, but we can connect to the ip of the server via web browser. If you can help, please let me know.

**Comment by WoofHax** [comment]
Did you change localhost to vps ip?

**Comment by NotDark** [comment]
> We are stuck on "Connection Timed Out". We have taken into account what causes this error, and have patched them.
> We have done:
> 
> * Setup port forwarding
> * Setup firewall with both rules
> * Set IP of python file to the server ip
> * Get latest CoreData, Descriptions, and Items.dat
> 
> I don't know of any other way to fix this. It works when using localhost, but we can connect to the ip of the server via web browser. If you can help, please let me know.

FIREWALL in the vps panel website

**Comment by JustinAkaru** [comment]
> Did you change localhost to vps ip?

Yes I have.

**Comment by JustinAkaru** [comment]
> > We are stuck on "Connection Timed Out". We have taken into account what causes this error, and have patched them.
> > We have done:
> > 
> > * Setup port forwarding
> > * Setup firewall with both rules
> > * Set IP of python file to the server ip
> > * Get latest CoreData, Descriptions, and Items.dat
> > 
> > I don't know of any other way to fix this. It works when using localhost, but we can connect to the ip of the server via web browser. If you can help, please let me know.
> 
> FIREWALL in the vps panel website

I've changed both the firewall on the vps, and on azure website

**Comment by JustinAkaru** [comment]
Fixed the issue, forgot what it was.
