### ISSUE TITLE
[HELP NEEDED] Does anyone know how to get the royal rainbow effect?

### ISSUE THREAD

**Issue by flossboss** [GrowtopiaNoobs/GrowtopiaServer#1053]
![July2017](https://user-images.githubusercontent.com/49786970/69762780-45330100-1139-11ea-903c-5d73f7e4c9c2.gif)

I have already tried changing data.characterState and data.plantingTree
but still haven't found it.

**Comment by WoofHax** [comment]
Just use Gt bot you can get the answer on there

**Comment by Granger-spec** [comment]
> Just use Gt bot you can get the answer on there
> (if you have royals lock in really gt)

How does it work?

**Comment by WoofHax** [comment]
> > Just use Gt bot you can get the answer on there
> > (if you have royals lock in really gt)
> 
> How does it work?

Nvm 

This issues was same with this issues https://github.com/GrowtopiaNoobs/GrowtopiaServer/issues/998

**Comment by flossboss** [comment]
No one knows so I'm closing
