### ISSUE TITLE
[BUG] Critical issue while XAMPP is installed.

### ISSUE THREAD

**Issue by Ironozd** [GrowtopiaNoobs/GrowtopiaServer#1055]
I built and hosted the server but now, I have a critical security issue. I have installed xampp on the same computer to make a website for growtopia server. But now if you search like this:

```
http://<ip_adress>/server.exe
```
You can download my server.exe file. How can I solve this bug? Also I want to make a website using port 80 but at the same time private server. 

Thank you :)

(Worked pretty much on it but couldn't find a solution.)

**Comment by NotDark** [comment]
just no put exe to htdocs folder

**Comment by Ironozd** [comment]
@NotDark Now, They both are in different folders. The server files are not in the xampp's htdocs folder.

**Comment by Ironozd** [comment]
The server.exe allows to download right now.

**Comment by WoofHax** [comment]
Just move you exe to desktop

**Comment by JadlionHD** [comment]
remove the server.exe

**Comment by Ironozd** [comment]
@WoofHax Oh, yeah that will work. I have to change the directory in py file than done. Thank You !

**Comment by Ironozd** [comment]
@JadlionHD No need for trolling!

**Comment by Ironozd** [comment]
That didn't work because server.exe allows. @WoofHax

**Comment by arshizx** [comment]
move your server file to desktop or something, it works for me

**Comment by Ironozd** [comment]
Does not work because The Server.exe file hosts the server

3 Ara 2019 Sal 10:52 tarihinde arshizx <notifications@github.com> şunu
yazdı:

**Comment by GrowtopiaNoobs** [comment]
Answer was given and it is correct way. If you still have this problem, then open new issue.
