### ISSUE TITLE
[HELP NEEDED] can I create better find system?

### ISSUE THREAD

**Issue by DrKfir** [GrowtopiaNoobs/GrowtopiaServer#1057]
I want to create better find system like in this picture is it possible if is possible can someone send me the code, please
![Screenshot_7](https://user-images.githubusercontent.com/46719896/69831557-8a872980-1232-11ea-975a-170d02d0b35c.png)

**Comment by WoofHax** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/pull/624

**Comment by DrKfir** [comment]
> #624

When I put /find it's work when I"m trying to find something is work but when I click on an item it's do nothing.

**Comment by ardakurucim** [comment]
@DrKfir make button working

**Comment by WoofHax** [comment]
btn substr isFind 
push back inventory
