### ISSUE TITLE
[HOW TO] How can I both run webserver in XAMPP and both run a website in port 80

### ISSUE THREAD

**Issue by Ironozd** [GrowtopiaNoobs/GrowtopiaServer#1058]
How can I both run the server and run a website using XAMPP?

**Comment by Switchry** [comment]
no

**Comment by WoofHax** [comment]
php....

**Comment by Ironozd** [comment]
@Switchry There are ways, many private server does this. But idk how.

**Comment by ardakurucim** [comment]
@Ironozd damn just change index

**Comment by Ironozd** [comment]
@ardakurucim Life doesn't work like that!

**Comment by Switchry** [comment]
> @Switchry There are ways, many private server does this. But idk how.

You cant run 2 programs that use same ports at the same time

**Comment by flossboss** [comment]
Then use XAMPP to run server...

**Comment by Ironozd** [comment]
@flossboss not working.

@Switchry You are totally wrong. Growtopia v3 is doing this.

**Comment by Switchry** [comment]
> 
> 
> @flossboss not working.
> 
> @Switchry You are totally wrong. Growtopia v3 is doing this.

You are the person who is wrong. you cant run 2 program that use the same port at same time

**Comment by WoofHax** [comment]
@Ironozd if you want to try make website pls go learn php and html or js

**Comment by Ironozd** [comment]
@Switchry First of all I found how to manage it. There are things called private ports & public ports. I am redirecting the website to 80 and the server to 120 as private than redirecting both to 80. This will not work till you configure it.

You guys really don't know what the f*ck you are doing. Thank you for answering this issue without having a knowledge. 

I know html css php js They all are easy languages, I am going to coding course every week. And everyday in summers. 

Go f*cking away. Do not answer any issue if you guys don't know what are you doing!

The only thing I want to say is:
F*ck off.

@WoofHax @Switchry

**Comment by Ironozd** [comment]
Thank you for not answering the thing I ask!

**Comment by WoofHax** [comment]
@Ironozd 
>> run the server and run a website using XAMPP

**Comment by Ironozd** [comment]
@WoofHax I am foreign and still learning. Thank you for your disrespect. You couldn't find anything else to tell right?
