### ISSUE TITLE
New Commands And things (FIXED)

### ISSUE THREAD

**Issue by OverallGod** [GrowtopiaNoobs/GrowtopiaServer#106]
https://github.com/OverallGod/GrowtopiaServer
https://github.com/OverallGod/GrowtopiaServer

**Comment by ritzysw** [comment]
if you want to contribute pls use pull requests and not issues

**Comment by Mempler** [comment]
Exactly, i'm not gonna reopen that issue which means Please, make a pull request if you're done.
