### ISSUE TITLE
[BUG] C1061 compiler limit: blocks nested too deeply

### ISSUE THREAD

**Issue by SSebia** [GrowtopiaNoobs/GrowtopiaServer#1061]
https://imgur.com/KVcLjuG

**C1061 compiler limit: blocks nested too deeply

Weird thing that happens when i add new command, basically if i delete else if anywhere in the code the error disappears, is there a way to bypass the limit?**

**Comment by arshizx** [comment]
change else if to if

**Comment by arshizx** [comment]
change else if to if

**Comment by GrowtopiaNoobs** [comment]
No reply for long time, I am assuming this is solved
