### ISSUE TITLE
CPP

### ISSUE THREAD

**Issue by kingawesomed2** [GrowtopiaNoobs/GrowtopiaServer#1063]
Can anyone give me cpp (sign working) Just asking dont bully please

**Comment by LaYellow** [comment]
What the actual fuck are u opening this issue for?

**Comment by playingo** [comment]
@kingawesomed2 no and no one will and you said "Just asking dont bully please" but you will obviously get bullied if you do shit like this and even label this as a bug retard kid

**Comment by kingawesomed2** [comment]
@playingo ur fucking stupjd mom retard bitch nigga  skids ratter noob darkcometrat ahahahaahahaa

**Comment by kingawesomed2** [comment]
@layellow for get free cpp

**Comment by playingo** [comment]
ur so fucking retarded kid also cpp means c plus plus and not the source itself kid

**Comment by playingo** [comment]
someone please close this bullshit

**Comment by WoofHax** [comment]
cpp = c++

**Comment by kingawesomed2** [comment]
Enet server cpp/source

**Comment by GrowtopiaNoobs** [comment]
There are already issues and even PR about this. Closing

**Comment by IndogLelele** [comment]
lolololol nuuuuuuub
