### ISSUE TITLE
Is possible to make using mysql database?

### ISSUE THREAD

**Issue by IndogLelele** [GrowtopiaNoobs/GrowtopiaServer#1068]
CAPTION NAB

**Comment by DrOreo002** [comment]
Rip my remaining 2 brain cells...

**Comment by Mempler** [comment]
^

Yes, it is possible. you just hate to figure out how to Replace the Json DB with [MariaDB](https://mariadb.com/kb/en/library/mariadb-connector-c/) (don't use MySQL as it's slightly outdated, around 5 years)

**Comment by IndogLelele** [comment]
Ok thx you so little
