### ISSUE TITLE
Can Update Growtopia server to v2.985

### ISSUE THREAD

**Issue by WolfPT** [GrowtopiaNoobs/GrowtopiaServer#107]
Can Update Growtopia server to v2.985

**Comment by ritzysw** [comment]
nenkai discontinued creating gt items database, so updating to 2.985 would actually be useless cuz items won't work (in fact you can already enter 2.984 server from 2.985 so there's no need in "updating" it)

**Comment by Kevlar6307** [comment]
how to enter?
