### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by agsa15** [GrowtopiaNoobs/GrowtopiaServer#1075]
![Screenshot_20191207-103903](https://user-images.githubusercontent.com/56504487/70368495-ce86c800-18dd-11ea-9c9a-09e3b9e91972.png)
Help pls

**Comment by JadlionHD** [comment]
what the problem?

**Comment by agsa15** [comment]
Can't make server online

**Comment by JadlionHD** [comment]
Did you already open port 80 TCP and 17091 UDP in the firewall/website?

**Comment by agsa15** [comment]
> Did you already open port 80 TCP and 17091 UDP in the firewall/website?

Yes i did but nothing happen

**Comment by NotDark** [comment]
> > Did you already open port 80 TCP and 17091 UDP in the firewall/website?
> 
> Yes i did but nothing happen

in your vps panel website too
