### ISSUE TITLE
How to fix stuck at connecting

### ISSUE THREAD

**Issue by GuckTubeYT** [GrowtopiaNoobs/GrowtopiaServer#1076]
i just done setup vps, firewall, xampp, all is set up, but why i still stuck at connecting

**Comment by WoofHax** [comment]
Firewall on website host

**Comment by GuckTubeYT** [comment]
where?

**Comment by GuckTubeYT** [comment]
i done setup firewall, but still stuck

**Comment by WoofHax** [comment]
> i done setup firewall, but still stuck

Where you get from vps?

**Comment by GuckTubeYT** [comment]
from kocak z

**Comment by WoofHax** [comment]
> from kocak z

Ask him add firewall on website host

**Comment by GuckTubeYT** [comment]
wait ok

**Comment by GuckTubeYT** [comment]
what should i add firewall?

**Comment by WoofHax** [comment]
17091 udp 
80 tcp

**Comment by GuckTubeYT** [comment]
done

**Comment by GuckTubeYT** [comment]
![Capture](https://user-images.githubusercontent.com/56192597/70612008-f9fa0300-1bba-11ea-964d-72d721fed834.PNG)

**Comment by GuckTubeYT** [comment]
and then, what should i do again?

**Comment by WoofHax** [comment]
https://cloud.google.com/filestore/docs/configuring-firewall

**Comment by WoofHax** [comment]
This is example add firewall but is for gpc

**Comment by GuckTubeYT** [comment]
he didnt buy vps on gpc

**Comment by WoofHax** [comment]
You can use python to run server

**Comment by GuckTubeYT** [comment]
still stuck at connecting

**Comment by GuckTubeYT** [comment]
or, xampp wrong set?

**Comment by WoofHax** [comment]
Or did you add server_data.php ?

**Comment by GuckTubeYT** [comment]
i did add

**Comment by GuckTubeYT** [comment]
wait i screen shot

**Comment by GuckTubeYT** [comment]
![Capture](https://user-images.githubusercontent.com/56192597/70612345-99b79100-1bbb-11ea-89a4-3758056acb48.PNG)

**Comment by WoofHax** [comment]
If have you have discord pls add me some more information.  null#5824

**Comment by GuckTubeYT** [comment]
ok

**Comment by GuckTubeYT** [comment]
i add you

**Comment by WoofHax** [comment]
You can close this issues

**Comment by GuckTubeYT** [comment]
add me GuckTubeYT#8912
