### ISSUE TITLE
How to Add items in Coredata.txt

### ISSUE THREAD

**Issue by askgt0553** [GrowtopiaNoobs/GrowtopiaServer#1080]
I cant find the item overlay color and base color

**Comment by WoofHax** [comment]
You can find it on Wiki

**Comment by askgt0553** [comment]
Thx

**Comment by askgt0553** [comment]
But i can't add items with id more then 9145
Why??

**Comment by GuckTubeYT** [comment]
Download items dat: https://github.com/ServerRelated/GrowtopiaItemDatabase

**Comment by askgt0553** [comment]
Thx for help ;)
