### ISSUE TITLE
Free Custom  Items

### ISSUE THREAD

**Issue by hadiGTPS** [GrowtopiaNoobs/GrowtopiaServer#1084]
DM Me On Discord 
Hadi#0002

**Comment by MarmoriPelaa** [comment]
@GrowtopiaNoobs please close this issue. It's not related.

**Comment by playingo** [comment]
they wont work either + its prob the shit ama leaked @hadiGTPS cant do anything related to that

**Comment by GrowtopiaNoobs** [comment]
Please create PR or issue containing how to do this. Closing
