### ISSUE TITLE
I'M BACK!

### ISSUE THREAD

**Issue by ipr0gr4mipas2** [GrowtopiaNoobs/GrowtopiaServer#1089]
I was @iProgramMC the whole time lol

It's not a comment, but I used to contribute to this server back in 2018, so be glad that the server looks at least a little bit professional now.

**Comment by noobes1337** [comment]
does anyone knew u before lol?

**Comment by Orbit4682** [comment]
irrelevant

**Comment by MarmoriPelaa** [comment]
Why do people keep thinking this is a forum!?

**Comment by iProgramMC** [comment]
No idea

**Comment by WoofHax** [comment]
Who are you? Lol

**Comment by GrowtopiaNoobs** [comment]
Closing this issue as it got enough time to get attention.
