### ISSUE TITLE
items.dat

### ISSUE THREAD

**Issue by Boujee0040** [GrowtopiaNoobs/GrowtopiaServer#109]
Anyone knows where can i get the items.dat, coredata.txt and descriptions.txt? ty

**Comment by DrOreo002** [comment]
Nenkai discountinued his project, but well there's an updated version for that. You can see it here
https://github.com/NotDark/GrowtopiaItemDatabase

**Comment by FocusedSG** [comment]
items.dat is in your growtopia\cache folder
coredata.txt was discontinued by nenkai so u gotta update it manually. description.txt same case as coredata.txt

**Comment by Kevlar6307** [comment]
can i login on this 2.984 server on 2.985?

**Comment by FocusedSG** [comment]
Yea of course, both 2.984 and 2.985 have the same log on packet. However, u will need to update your item data before logging on.

**Comment by Kevlar6307** [comment]
kk ty

**Comment by Kevlar6307** [comment]
why is it when im logging in. i disconnect?
