### ISSUE TITLE
[HELP] UI Name

### ISSUE THREAD

**Issue by Zlarex** [GrowtopiaNoobs/GrowtopiaServer#1091]
1. What is the ui name for clickable button with icon like when you find item using growscan (label button?)
2. What is the ui name when you doing surgery (clickable tools)

**Comment by JadlionHD** [comment]
try to see /find, there is a clickable icon items thing when u finding some stuff using /find. Idk correct me if i wrong

**Comment by Zlarex** [comment]
Not clickable icons like growscan, just a large button with item id pic

**Comment by WoofHax** [comment]
add label with icon?

**Comment by Zlarex** [comment]
> add label with icon?

Umm, i think its not clickable

**Comment by ardakurucim** [comment]
@Zlarex it is

**Comment by ardakurucim** [comment]
name it and use action|dialog_return

**Comment by iProgramMC** [comment]
add_label_with_button_icon or stmh

**Comment by Zlarex** [comment]
Oh, i will try it later

**Comment by Zlarex** [comment]
What's the formatting?

**Comment by Zlarex** [comment]
I found it
