### ISSUE TITLE
Invalid config.

### ISSUE THREAD

**Issue by Cojeb** [GrowtopiaNoobs/GrowtopiaServer#1096]
**Describe the bug**
Added config.json with correct contents and json syntax and upon starting the server, `invalid config` is displayed.

**Expected behavior**
To parse and confirm validity of config.

**Screenshots**
![Screenshot from 2019-12-28 16-15-00](https://user-images.githubusercontent.com/59312183/71544911-47cd8400-298d-11ea-8f44-5df9b15ac81d.png)

**Server environment (please complete the following information):**
 - OS: Linux Ubuntu 18.04 Server
 - Experience: Beginner
 - Modifications: None

**Client environment (please complete the following information):**
 - Growtopia version: v2.999

**Additional context**
config.json is placed in same folder as the server, there are `players` and `worlds` folders - the server was builded on distro from master a few minutes ago
Firewall is set to accept connections on respective ports, python script is running properly.
CoreData.txt, Descriptions.txt and items.dat are there as well.
When trying to connect it says 'Located server, connecting...' and then it displays 'Error connecting! Timed out. Click....'

*`config.json` contents:*
```js
{
  "port": 17091
}
```

**Comment by NotDark** [comment]
replace this 
{
"port": 17091, 
"cdn": "0098/CDNContent37/cache/"
}

**Comment by Cojeb** [comment]
> replace this
> {
> "port": 17091,
> "cdn": "0098/CDNContent37/cache/"
> }

Fixed the issue, thank you.
