### ISSUE TITLE
[BUG] End of My Journey 

### ISSUE THREAD

**Issue by hadiGTPS** [GrowtopiaNoobs/GrowtopiaServer#1097]
Hello, as you all heard what happened our friends playingo and iprogramincpp there cpp got leaked by ama sorry for there loss. Lets go straight in what i wanted to say, i decided this few days ago with a friend CMD, i am officailly quiting growtopia private server coding and i never returning back again. The only reason i am is i don't belong over this community and after what happened to playingo and his friends gave me more power to stop coding. That wasnt how it shouldve beeen actually growtopia private server should not have went that far having alot of kids and code beggers as well as tough people crashing. My work started when first gtps was out i started working with dark a good coder of gtps and then i decided to leave dark after he got a new teammate and this man is annoying ashell so i decided to leave dark code by my own without making server up just coding for own bases i started coding with cmd but we never made a server up because we know other people can crash. As well as i got alot of help to do what i ever did in gtps the help was vyte first to help mee with signs and dark for custom items (using hex) and all this happened when cmd was helping me too. I dont care what playingo talks about me no hate toward you bro even if ur cpp was leaked u was a legend ur cpp always helped me with some bugs i faced thanks for that. Iprogramincpp idk u alot but u was first to help me and dark in onsetbux as i recall. Raiterjacke XD u hate me and act tough on me for nthng no hates too. Nabsi a good guy! Cmd you was always by my side. Wry/abood/noobes/secret/lucifer/steak and more other people great people i met who works hard. Vyte you was always mad from me doing dumb stuff but still u helped me alot ty vyte. Dark/Timecold thanks for everything guys. And more alot of other people who was by my journey! You can always dm me On discord. This is Hadi signning out from growtopia private server!

**Comment by iProgramMC** [comment]
oh yes I was the one who found OnSetBux and OnSetCurrentWeather? cool

**Comment by noobes1337** [comment]
that's a poem? it could be lol <3

**Comment by xXAbood** [comment]
ur the best hadi whatever u decide ill always support you.

**Comment by iProgramMC** [comment]
@noobes1337 its actually a real thing

**Comment by flossboss** [comment]
❤

**Comment by ama6nen** [comment]
so sad

**Comment by VyteGTPS** [comment]
🖤

**Comment by WoofHax** [comment]
Me: juantlo is alive on dark server 
Juantlo: hammer ban

**Comment by GuckTubeYT** [comment]
@hadiGTPS Just Sign Out lol, why you make story

**Comment by koirapallo32** [comment]
who are you

**Comment by GrowtopiaNoobs** [comment]
Closing this issue as it is too old.
