### ISSUE TITLE
[BUG] Stuck

### ISSUE THREAD

**Issue by Cojeb** [GrowtopiaNoobs/GrowtopiaServer#1098]
**Describe the bug**
When i attempt to login into my server it says `Logging on [Name]` and it's stuck there, regardless of how much i wait, its stuck there. The console does not throw any errors.

**Expected behavior**
To enter the worlds screen.

**Server environment (please complete the following information):**
 - OS: Ubuntu 18.04 Server
 - Experience: Beginner
 - Modifications: None
 - Hash: 240123390

**Client environment (please complete the following information):**
 - Growtopia version: v2.91

**Additional context**
The growtopia server is set accordingly and running smoothly on the VPS and the http server is set correctly and points to correct ip and port.

**Comment by iProgramMC** [comment]
Well, the `OnSuperMainStartAcceptLogonHrdxs...` string wasn't always this way. Before it was `OnSuperMainStartAcceptLogonFB211131ddf`. So you need to check the game version and if it is below 2.983 send THIS string instead of the current one. The syntaxes are the same though

**Comment by NotDark** [comment]
use latest items.dat file

**Comment by Cojeb** [comment]
> use latest items.dat file

I used the one linked in the wiki.

**Comment by Cojeb** [comment]
> Well, the `OnSuperMainStartAcceptLogonHrdxs...` string wasn't always this way. Before it was `OnSuperMainStartAcceptLogonFB211131ddf`. So you need to check the game version and if it is below 2.983 send THIS string instead of the current one. The syntaxes are the same though (I guess)

Let me see.

**Comment by Cojeb** [comment]
> OnSuperMainStartAcceptLogonFB211131ddf

![Screenshot from 2019-12-28 17-53-41](https://user-images.githubusercontent.com/59312183/71546039-047a1200-299b-11ea-8fca-7388b6b9433f.png)

Now the game crashes upon trying to log in, no errors in console either.

**Comment by NotDark** [comment]
> > OnSuperMainStartAcceptLogonFB211131ddf
> 
> ![Screenshot from 2019-12-28 17-53-41](https://user-images.githubusercontent.com/59312183/71546039-047a1200-299b-11ea-8fca-7388b6b9433f.png)
> 
> Now the game crashes upon trying to log in, no errors in console either. (Yes, i did save then re-compile it.)

dont use items.dat in wikia 

and use this OnSuperMainStartAcceptLogonHrdxs47254722215a not  OnSuperMainStartAcceptLogonFB211131ddf

**Comment by Cojeb** [comment]
> dont use items.dat in wikia

And well, which should i am supposed to use then?

**Comment by NotDark** [comment]
> > dont use items.dat in wikia
> 
> And well, which should i am supposed to use then?
> For instance my growtopia version is v2.91.

login growtopia and you will get the new items.dat on your growtopia folder

**Comment by Cojeb** [comment]
> > > dont use items.dat in wikia
> > 
> > 
> > And well, which should i am supposed to use then?
> > For instance my growtopia version is v2.91.
> 
> login growtopia and you will get the new items.dat on your growtopia folder

I use ubuntu both on server and my pc :[

**Comment by iProgramMC** [comment]
@NotDark he's using 2.91 not 2.983+

**Comment by Cojeb** [comment]
Hold on, i will be updating growtopia to v2.999 and will get the items.dat from my android device, will post when i am done.

**Comment by Cojeb** [comment]
Updated growtopia to v2.999 and updated items.dat to latest version, we are back where we were. It's stuck on that screen, it wont go into the world selection screen.

**Comment by Cojeb** [comment]
After a second look at `SupperMainStart..` string i noticed there was an extra gt, i removed it, built the server again and now seems to work all fine. I was able to connect. Thank you @NotDark.
