### ISSUE TITLE
Consider removing Windows.h

### ISSUE THREAD

**Issue by damianmcclure** [GrowtopiaNoobs/GrowtopiaServer#11]
Make it mutli platform so you can host it on Linux servers and so on

**Comment by ritzysw** [comment]
how about learn to install WinDoWS

**Comment by mcclureski** [comment]
Yeah I don't want to buy another vps just to make it shitty windows, Linux is better for vps use.

**Comment by GrowtopiaNoobs** [comment]
You can try to use wine (I think it should work fine) or remove Windows.h yourself.
If I remember corretly you just would need to add following line of code:
`#define BYTE char` or maybe `typedef char BYTE`
and then remove SetCtrlHandler call + HandlerRoutine.

**Comment by GrowtopiaNoobs** [comment]
Closing this issue, as linux support has been added.
