### ISSUE TITLE
cant login on 2.984 android but can on pc

### ISSUE THREAD

**Issue by Boujee0040** [GrowtopiaNoobs/GrowtopiaServer#111]

**Comment by Mempler** [comment]
That is weird. could you give us some more information ?

**Comment by Mempler** [comment]
No information in the last 2 days. i'll close this issue as i'm assuming it's fixed.

**Comment by Boujee0040** [comment]
can you reopen @Mempler 
so my issue was: i cant login on any versions. using the latest code, used the items.dat of gt 2.985
coredata and descriptions from NotDark's Anything wrong?

**Comment by Mempler** [comment]
it sounds like your items.dat hash is wrong.

**Comment by Boujee0040** [comment]
why is it wrong

**Comment by Boujee0040** [comment]
i used the items.dat on 2.985

**Comment by Mempler** [comment]
I dont feel like i need to answer this anymore.
just look at other issues.
