### ISSUE TITLE
UPDATED Growtopia 3.00

### ISSUE THREAD

**Issue by meffa1** [GrowtopiaNoobs/GrowtopiaServer#1112]
Hello!,
I Have Issue Growtopia 3.00!
1)What CdnContent Growtopia 3.00?
2)What GameVersion Growtopia 3.00?
Thanks For Reply:)

**Comment by Cojeb** [comment]
You only need to update the items.dat with the newer obe and thats it.

**Comment by Zlarex** [comment]
1. idk, 45?
2. 3

**Comment by noobes1337** [comment]
CDNContent : CDNContent37
Gameversikn : 3

**Comment by GrowtopiaNoobs** [comment]
Answer was given and there was no new activity on this issue, I take it as solved.
