### ISSUE TITLE
GTPS CRASHER 1.0(THIS CAN CRASH VPS!)

### ISSUE THREAD

**Issue by meffa1** [GrowtopiaNoobs/GrowtopiaServer#1113]
NEW GTPS CRASHER MADE BY MEFFA
GTPS CRASHER REPO>>[Download Here](https://github.com/meffa1/gtps-crasher)

**Comment by GuckTubeYT** [comment]
anjay

**Comment by meffa1** [comment]
sorry guys for this exe, i only share
