### ISSUE TITLE
GTPS RESTARTING 1.0

### ISSUE THREAD

**Issue by meffa1** [GrowtopiaNoobs/GrowtopiaServer#1114]
This GTPS Restarting Created By **Meffa**
### THIS REPOSITORIES >>[DOWNLOAD HERE](https://github.com/meffa1/gtps-reset)

**Comment by Cojeb** [comment]
Uh?

**Comment by WoofHax** [comment]
Is was exe raterad

**Comment by Cojeb** [comment]
> Is was exe raterad

A questionable exe, yes.

**Comment by atomiclucky** [comment]
come on, you could've gave the .bat file. Now it's obvious, that it's a virus. But, personally, I don't need it.

**Comment by Mempler** [comment]
Please do not share any Executable in this Repository. this is off-topic!
