### ISSUE TITLE
Connecting Error

### ISSUE THREAD

**Issue by AirFU** [GrowtopiaNoobs/GrowtopiaServer#1116]
![Screenshot (69)](https://user-images.githubusercontent.com/37872714/71670924-16492400-2da4-11ea-943c-c28cf8482c37.png)
how to fix this?

i already change the ip to mine

**Comment by Cojeb** [comment]
The ip points correctly.
You have to run your server executable.

**Comment by AirFU** [comment]
> The ip points correctly.
> You have to run your server executable.

how?

**Comment by Cojeb** [comment]
Are you sure config.json and the python script point correctly?

**Comment by AirFU** [comment]
> Are you sure config.json and the python script point correctly?

my json

{
"port": 17091,
"cdn": "0098/CDNContent37/cache/"
}

**Comment by AirFU** [comment]
> Are you sure config.json and the python script point correctly?

![Screenshot (73)](https://user-images.githubusercontent.com/37872714/71678601-1ce19680-2db8-11ea-9d7a-c12f745f0604.png)
my py script

**Comment by Cojeb** [comment]
Change in your python script (python2)

`\nport|1194` to `\nport|17091`

**Comment by Cojeb** [comment]
If its solved, please close the issue.

**Comment by ardakurucim** [comment]
also don't forget to turn the 17091 port on

**Comment by noobes1337** [comment]
@ardakurucim you don't need to open port using .py

**Comment by WoofHax** [comment]
@AirFU change the IP to 127.0.0.1 and the port too

**Comment by ardakurucim** [comment]
@noobes1337 he need because he is using his public ip

**Comment by noobes1337** [comment]
If he's using it for localhost is not a problem

**Comment by ardakurucim** [comment]
5 Oca 2020 Paz 12:32 tarihinde noobes1337 <notifications@github.com> şunu
yazdı:

**Comment by GrowtopiaNoobs** [comment]
I assume this is solved as there was no new activity.
