### ISSUE TITLE
Why to use Python 2 if you can use Python 3

### ISSUE THREAD

**Issue by PeterGardas** [GrowtopiaNoobs/GrowtopiaServer#112]
Its easy to compile from Py2 to Py3 with 2to3 python library, but i want to now if there is any deeper meaning why to use Py2 before i do pull request.

Regards

Petr Gardas

**Comment by Mempler** [comment]
There is actually no big reason.

**Comment by ritzysw** [comment]
In fact you don't even need to use python, just set up xampp server

**Comment by PeterGardas** [comment]
Python is the easiest, so the less time consuming to do.

**Comment by Mempler** [comment]
@ritzysw really, xampp? Why not simply nginx ? ^^

**Comment by Boujee0040** [comment]
xampp uses apache, which is super easy

**Comment by Mempler** [comment]
Yea but why using windows in the first place? I love nginx and wont switch to a heavy weighted HTTPServer.

**Comment by Mempler** [comment]
Looks like this topic is inactive. I'll close it for now.
