### ISSUE TITLE
  error MSB8020: The build tools for v142 (Platform Toolset = 'v142')

### ISSUE THREAD

**Issue by GuckTubeYT** [GrowtopiaNoobs/GrowtopiaServer#1121]
error MSB8020: The build tools for v142 (Platform Toolset = 'v142') 
    cannot be found. To build using the v142 build tools, please install 
    v142 build tools.
how to fix that?

**Comment by WoofHax** [comment]
I think this project build with v141

**Comment by Zlarex** [comment]
Install your build tools, i think it can be retargeted to your own configuration (like upgraded v140 to v142, idk if degraded)

**Comment by JadlionHD** [comment]
like error said "To build using the v142 build tools, please install v142 build tools"
if u still dont know how to fix it, google the answer

**Comment by GuckTubeYT** [comment]
Thanks everyone, its work!
