### ISSUE TITLE
[BUG] I try add /find but I have a problem with account password

### ISSUE THREAD

**Issue by DrKfir** [GrowtopiaNoobs/GrowtopiaServer#1123]
I try to make the /find like #624 and I had a problem with the account but I try to fix it and now it's ok but I have other problem I have this problem 
![Screenshot_4](https://user-images.githubusercontent.com/46719896/71766761-15cb9d00-2f0c-11ea-8756-f94340163c44.png) it's not showing password when I create an account but when I try to connect with no password it's work and when I put the password it does not work please help.
also, I think it's important: https://pastebin.com/mqYSZsu0

**Comment by WoofHax** [comment]
Just check back the code 👌

**Comment by DrKfir** [comment]
ok
