### ISSUE TITLE
Pls make new shop and /find 

### ISSUE THREAD

**Issue by omggt** [GrowtopiaNoobs/GrowtopiaServer#1126]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cmdocmd** [comment]
wym pls make new shop and /find you make them by ur self wtf

**Comment by JadlionHD** [comment]
> wym pls make new shop and /find you make them by ur self wtf

lol

**Comment by WoofHax** [comment]
2020 Indonesia developer

**Comment by JadlionHD** [comment]
> 2020 Indonesia developer

:thinking:

**Comment by DrKfir** [comment]
@omggt 
Do you really think they will do it for you?
lol

**Comment by DrOreo002** [comment]
Hi my fellow indonesians. If you cant code please give up. Thanks

**Comment by iProgramMC** [comment]
@DrOreo002 I wouldn't just encourage people to give up, instead I'd encourage them to LEARN C++ and not use publicly available ("Leaked") source code.

**Comment by iProgramMC** [comment]
Anyone can make a proper growtopia private server if u think. It can be done but it takes effort depending on your experience in coding.

**Comment by GrowtopiaNoobs** [comment]
Just closing this issue, as it was created before I announced banning.

**Comment by iProgramMC** [comment]
@GrowtopiaNoobs banning for what?
