### ISSUE TITLE
Leaked (Gtv3 New Cpp 03.01.2020

### ISSUE THREAD

**Issue by kingawesomed2** [GrowtopiaNoobs/GrowtopiaServer#1128]
I will add soon

**Comment by GuckTubeYT** [comment]
wtf? where

**Comment by DEERUX** [comment]
skid theres only 1 of our gtv3 source leaked and its the old 0.15 one

**Comment by iProgramMC** [comment]
lol @DEERUX where are you? you haven't been online on discord in what feels like decades bro

**Comment by DEERUX** [comment]
@iProgramMC ye didnt feel like going onto discord cuz ppl will keep dming me and im like someone who feels like I should respond to all of them and since I cant keep control of that I rather just not go online at all when I am very busy.

**Comment by iProgramMC** [comment]
alright when you're not busy anymore come talk

**Comment by DEERUX** [comment]
sure @iProgramMC anything new/left to talk about tho?

**Comment by Vilius48** [comment]
Hello Deerux it's me Tough
I thought u died or arrasted haha xd

**Comment by DEERUX** [comment]
whats up tough yo?

**Comment by Vilius48** [comment]
Nothing good 
School is hard
I have been worried about u

**Comment by DEERUX** [comment]
lol, for how many days was I inactive i feel like it wasnt that long even

**Comment by Vilius48** [comment]
I haven't talked to u like 2weeks in discord

**Comment by Vilius48** [comment]
1week

**Comment by DEERUX** [comment]
yeah well my old discord got suspended and I didnt go on my new one for a week so

**Comment by Vilius48** [comment]
I know ur new one

**Comment by DEERUX** [comment]
oh yes right

**Comment by Vilius48** [comment]
How life going deerux?

**Comment by DEERUX** [comment]
pretty good but we're spamming this git page rn ill talk to u on discord soon if required.

**Comment by Vilius48** [comment]
OKay. I sent friend request.

**Comment by Vilius48** [comment]
My discord Tough#4400

**Comment by iProgramMC** [comment]
@DEERUX i have an idea, lets create a private github repo and chat in issues when something is wrong in discord or smth

**Comment by DEERUX** [comment]
yeah great idea btw @iProgramMC my discord (new one) recently got banned again so idk if I should ever rely on discord now.

**Comment by iProgramMC** [comment]
oh my
no

**Comment by iProgramMC** [comment]
really?

also https://github.com/iProgramMC/Private-Deerux-Chat/ which is only valid for @DEERUX aka you

**Comment by DEERUX** [comment]
yeah really.

**Comment by iProgramMC** [comment]
just go alr @DEERUX

**Comment by iProgramMC** [comment]
alright ur in

**Comment by GrowtopiaNoobs** [comment]
Closing this issue as it have no purpose.
