### ISSUE TITLE
stuck in the login screen

### ISSUE THREAD

**Issue by Zfee** [GrowtopiaNoobs/GrowtopiaServer#113]
im stuck in the login screen, i think i have evertything set up as they should, 
![image](https://user-images.githubusercontent.com/29163247/50375411-78a20d00-0605-11e9-82f7-f0be00637c3a.png)
gt v2.984

**Comment by Zfee** [comment]
any ideas how to fix this?

**Comment by Mempler** [comment]
Duplicate of #56
