### ISSUE TITLE
how to edit pictures to rttex?

### ISSUE THREAD

**Issue by GuckTubeYT** [GrowtopiaNoobs/GrowtopiaServer#1131]
how to edit pictures to rttex?

**Comment by WoofHax** [comment]
https://tools.cernodile.com/rttex.html

I think is this

**Comment by LaYellow** [comment]
wow woofhax genius

**Comment by WoofHax** [comment]
> wow woofhax genius

Wtf you want fp

**Comment by iProgramMC** [comment]
`RTPack.exe -8888 your_file.rttex` if I'm not wrong.

Get RTpack from here:
https://GitHub.com/sethrobinson/proton/

**Comment by GrowtopiaNoobs** [comment]
Answers were given and this issue is old, so I am closing this.
