### ISSUE TITLE
Can we make Growtopia Client support other language?

### ISSUE THREAD

**Issue by InjectionZ** [GrowtopiaNoobs/GrowtopiaServer#1132]
💯

**Comment by NotDark** [comment]
no

**Comment by JadlionHD** [comment]
> no

any reason?

**Comment by NotDark** [comment]
> > no
> 
> any reason?

you need make your own growtopia client

**Comment by iProgramMC** [comment]
The items' names could be fully replaced with another language using an items.dat decoder and encoder set, and have the server fully write stuff in another language, however you can't change the Growtopia UI on the server side - you'd have to hex-edit it yourself.

**Comment by ardakurucim** [comment]
hex editor

**Comment by GrowtopiaNoobs** [comment]
Issue was answered, so I am closing this.
