### ISSUE TITLE
GTOS CPP [MUST CREDIT SEBIA]

### ISSUE THREAD

**Issue by SSebia** [GrowtopiaNoobs/GrowtopiaServer#1133]
**BY USING GTOS CPP YOU MUST CREDIT Sebia#1337 AS A OWNER WHO ADDED ALL THOSE FEATURES TO THAT CPP.**

https://www30.zippyshare.com/v/ueo9gyHy/file.html

**NO CREDITS = YOUR SERVER RIP**

**IF YOU NEED HELP DM Sebia#1337**

**Comment by SSebia** [comment]
FEATURES:
MAILBOX
DISPLAY BLOCKS
SIGNS
INVENTORY SAVES TO .JSON
IDK A LOT

**Comment by DrKfir** [comment]
Do you have discord? I need help.
@SSebia

**Comment by SSebia** [comment]
> Do you have discord? I need help.
> @SSebia

Sebia#1337

**Comment by DrKfir** [comment]
> > Do you have discord? I need help.
> > @SSebia
> 
> Sebia#1337

I send u friend request
from
DrKfir#2703

**Comment by Krazuto** [comment]
Thank you for informing us about such an amazing cpp!!!!!!

**Comment by InjectionZ** [comment]
CPP = C PLUSPLUS, C++
WOOOWOWOWOWOWOW

**Comment by JadlionHD** [comment]
@GrowtopiaNoobs can you take care of this?

**Comment by SSebia** [comment]
How to chance label to enhancement...

**Comment by iProgramMC** [comment]
just make repo with your source code and license it so ppl can use it but they must credit

**Comment by iProgramMC** [comment]
ideally you'd use GNU Affero GPL

**Comment by MTNDStudios** [comment]
**### Bruh, Sebia, You're the one who leaked the CPP not TimeTopia... Stop lyin' dude it's not good.
(No Hate).**

**Comment by MTNDStudios** [comment]
@SSebia

**Comment by SSebia** [comment]
> **### Bruh, Sebia, You're the one who leaked the CPP not TimeTopia... Stop lyin' dude it's not good. (No Hate).**

Yes I did, because Timetopia stole the .cpp From Speed VPS Without my or his permission. Then Timetopia decided to start sharing .cpp to friends, as I know even selling for cash.

**Comment by iProgramMC** [comment]
@SSebia just release this as a GitHub clone of this repo (not fork) and place your source file as "ENet server test.cpp" and release it with a license. This will allow you to cause harm to anyone who does not credit your source code.

**Comment by SSebia** [comment]
> @SSebia just release this as a GitHub clone of this repo (not fork) and place your source file as "ENet server test.cpp" and release it with a license. This will allow you to cause harm to anyone who does not credit your source code.

Thanks for the suggestion.

**Comment by iProgramMC** [comment]
yw

**Comment by ardakurucim** [comment]
40k lines of copy+paste

**Comment by flossboss** [comment]
LOL @ardakurucim 👏

**Comment by xXAbood** [comment]
imagine publishing ur cpp without a license and telling ppl to credit + using someone else's vps. (no hate tho)

**Comment by TimeTopia** [comment]
Yeah blamming me infact u did not know the whole story but after u know u still ask me to credit it but I did help 2% in the coding and u say tht most of it did not help well I only can say is it's yr fault to leak it and got fake information from Speed

**Comment by WoofHax** [comment]
> 40k lines of copy+paste

That Jobs for Indonesia copying pasted 👏

**Comment by noobes1337** [comment]
crasher?

**Comment by xXAbood** [comment]
> crasher?

wry codes and its literally the same as what he said

**Comment by TimeTopia** [comment]
So hacking wry what did u get @SSsebia

**Comment by TimeTopia** [comment]
Guys Sebia hacked Wry#9999 if u wanna see proofs just DM me at discord OniiChan [TimeTopia]#9999

**Comment by White-Scorp** [comment]
Old Link.
https://www.mediafire.com/file/9ts6wgj28ewduuq/orginal-backup.cpp/file

**Comment by LustsPS** [comment]
how to update the cdncontent?

**Comment by GrowtopiaNoobs** [comment]
Please create github repository with this code.
This has also enough time to get noticed by people, so I am closing this.

**Comment by FeryN77** [comment]
how i add  in cpp @SSebia
