### ISSUE TITLE
[BUG] /mod not working

### ISSUE THREAD

**Issue by Onlyin2** [GrowtopiaNoobs/GrowtopiaServer#1137]
When i do /mod it doesn't let me go through blocks and i don't seem to find anything wrong with the code anyone help?

**Comment by WoofHax** [comment]
can you search /mod then screen shot or send the /mod code in here

**Comment by Onlyin2** [comment]
> can you search /mod then screen shot or send the /mod code in here

Sure 1 min

**Comment by Onlyin2** [comment]
> can you search /mod then screen shot or send the /mod code in here

![Screenshot_20200119_024533_com microsoft rdc android](https://user-images.githubusercontent.com/49758646/72672650-e4071a00-3a65-11ea-9158-3858aec06947.jpg)

**Comment by WoofHax** [comment]
Add } under end of code

**Comment by Onlyin2** [comment]
> Add } under end of code On /mod and I am not sure why you sendClothes is error
> 
> If you have discord you can direct message to me NotWoofHax#5300

Ok sure i'll dm you on discord
