### ISSUE TITLE
How to make admins can break in any world? 

### ISSUE THREAD

**Issue by Onlyin2** [GrowtopiaNoobs/GrowtopiaServer#1140]
Sorry to ask but, is there anyway to make that admins aka creators can break in any world?

**Comment by cmdocmd** [comment]
void sendtileupdate make || admin level with the owner

**Comment by Onlyin2** [comment]
> void sendtileupdate make || admin level with the owner

Have discord?

**Comment by cmdocmd** [comment]
yes

**Comment by GrowtopiaNoobs** [comment]
@Onlyin2 Please close this issue, if you have it solved.

**Comment by Onlyin2** [comment]
> @Onlyin2 Please close this issue, if you have it solved.

Not quite solved, i'll close it either ways.
