### ISSUE TITLE
how to make Server Maintenance info

### ISSUE THREAD

**Issue by GuckTubeYT** [GrowtopiaNoobs/GrowtopiaServer#1141]
How to make Server Maintenance info

**Comment by DrOreo002** [comment]
> How to make Server Maintenance info

define a bool `boolean maintenance = true` when user connects check if maintenance is true then kick the player by sending action logon fail (packet type3) also send a console message saying that server is under maintenance

**Comment by GuckTubeYT** [comment]
> boolean maintenance

when search boolean maintenance, i didnt found

**Comment by DrOreo002** [comment]
Ok. I'm not 100% sure that u can't code, not gonna help you anymore now. Good luck!

**Comment by GuckTubeYT** [comment]
YEY OMG TY

**Comment by GuckTubeYT** [comment]
thanks @DrOreo002

**Comment by JadlionHD** [comment]
nih hint pake bhs indo
intinya bila player msuk ke server lu lalu maintenancenya true nnti kick playernya menggunakan action login fail, nah lalu put juga onconsolemessage buat text "The server is maintenance"

once again im using indo to make him understand
