### ISSUE TITLE
I need a coder to our GTPS..

### ISSUE THREAD

**Issue by wonder-ww** [GrowtopiaNoobs/GrowtopiaServer#1143]
I'm trying to find a coder and a co-owner to our GTPS. We already have VDS, if you can be dm me in Discord.
My Discord: ! Ä Wonder#1234

**Comment by xXAbood** [comment]
what the fuck is a VDS

**Comment by DrKfir** [comment]
lol, he means a VPS bro WTF ! lol

**Comment by ardakurucim** [comment]
its virtual dediacted server

**Comment by wonder-ww** [comment]
VPS or VDS is same. Maybe some features different.

**Comment by GrowtopiaNoobs** [comment]
Closing this search, because it is too old.
