### ISSUE TITLE
[BUG] I run enet server test and it says: "Loading config from config.json Invalid config."

### ISSUE THREAD

**Issue by Furkan125** [GrowtopiaNoobs/GrowtopiaServer#1144]
Guys  i run enet server test and it says: "Loading config from config.json Invalid config.",
also i try login to my private server but game stucks at "Located server connecting..."

**Comment by NotDark** [comment]
make new file with name config.json

and paste this

{
"port": 17091,
"cdn": "0098/CDNContent41/cache/"
}

**Comment by Furkan125** [comment]
I make new config.json

and i paste

{
"port": 17091,
"cdn": "0098/CDNContent41/cache/"
}

i try to connect my server but thats stack at Located server connecting...

**Comment by GuckTubeYT** [comment]
> 
> 
> I make new config.json
> 
> and i paste
> 
> {
> "port": 17091,
> "cdn": "0098/CDNContent41/cache/"
> }
> 
> i try to connect my server but thats stack at Located server connecting...

make firewall
17091 UDP
80 TCP
