### ISSUE TITLE
[Question] 65536 Block Visual 

### ISSUE THREAD

**Issue by WoofHax** [GrowtopiaNoobs/GrowtopiaServer#1147]
How can I get 65536 block visual?

**Comment by arshizx** [comment]
666

**Comment by GuckTubeYT** [comment]
> 
> 
> 666

lol revenge, good

**Comment by WoofHax** [comment]
> 666

6969696969

**Comment by InjectionZ** [comment]
0x00010000
I think

**Comment by NotDark** [comment]
??????

**Comment by WoofHax** [comment]
@InjectionZ are you sure is 0x00010000? 
i am tired to get this infomation https://github.com/GrowtopiaNoobs/GrowtopiaServer/issues/869

**Comment by InjectionZ** [comment]
i think that is id not visual

**Comment by InjectionZ** [comment]
idk then
