### ISSUE TITLE
[Question] Do anyone have linux rewrite server?

### ISSUE THREAD

**Issue by NotDark** [GrowtopiaNoobs/GrowtopiaServer#115]
Do anyone have server for linux that i can use?

i used willi123yao's linux server but i cant wear any clothes by use the inventory but i can use command to set the clothes

**Comment by Mempler** [comment]
That is currently the only linux compatible server.

**Comment by willi123yao** [comment]
You might also want to look at [this linux fork by coldchip](https://github.com/coldchip/growtopiaserver) even though it might be quite outdated and you will need to add some things before it can be used.
