### ISSUE TITLE
[INFO] New Growtopia Server is released

### ISSUE THREAD

**Issue by GrowtopiaNoobs** [GrowtopiaNoobs/GrowtopiaServer#1151]
I have finally released first version of Growtopia Server.
https://github.com/GrowtopiaNoobs/GrowtopiaServer2
https://github.com/GrowtopiaNoobs/GrowtopiaServer2-Module
Right now it is somewhat a beta version, so except changes in API and new features. Also I have made discord server, so those who have some knowledge about Growtopia Servers can discuss new features: https://discord.gg/r4RPFD8
For sure tell me your thoughts and also create new issues. Btw, this server is not ready to run out of box. You need to create your own modules to implement even basic functionality. I will eventually release set of basic standard modules.

**Comment by noobes1337** [comment]
i have no idea how to use the new one.

**Comment by GrowtopiaNoobs** [comment]
Closing this issue as it got enough attention.
