### ISSUE TITLE
XP potions

### ISSUE THREAD

**Issue by Onlyin2** [GrowtopiaNoobs/GrowtopiaServer#1153]
Any clues on how to make actual XP potions that lasts for a certain time?

**Comment by DrOreo002** [comment]
xp potions..., hmmmm. It should be consumable item then right?. Not sure how consumable is applied to player tho, but I think using a proxy is the best way to find out how

**Comment by Onlyin2** [comment]
> xp potions..., hmmmm. It should be consumable item then right?. Not sure how consumable is applied to player tho, but I think using a proxy is the best way to find out how. I do have a proxy, I might check on how the server do it later

I already know how to make a consumable (i have tons), the problem is i don't know how to add that when it's clicked the extra xp effect is added for a certain time.

**Comment by DrOreo002** [comment]
> > xp potions..., hmmmm. It should be consumable item then right?. Not sure how consumable is applied to player tho, but I think using a proxy is the best way to find out how. I do have a proxy, I might check on how the server do it later
> 
> I already know how to make a consumable (i have tons), the problem is i don't know how to add that when it's clicked the extra xp effect is added for a certain time.

Maybe try this?
- Log timestamp when used
- Run a repeating task
- On repeating task check if timestamp is passed

Not sure how to make it in cpp tho xD

**Comment by Onlyin2** [comment]
> > > xp potions..., hmmmm. It should be consumable item then right?. Not sure how consumable is applied to player tho, but I think using a proxy is the best way to find out how. I do have a proxy, I might check on how the server do it later
> > 
> > 
> > I already know how to make a consumable (i have tons), the problem is i don't know how to add that when it's clicked the extra xp effect is added for a certain time.
> 
> Maybe try this?
> 
> * Log timestamp when used
> * Run a repeating task
> * On repeating task check if timestamp is passed
> 
> Not sure how to make it in cpp tho xD

Probably won't work, i'll try to figure it out.

**Comment by Onlyin2** [comment]
> > > xp potions..., hmmmm. It should be consumable item then right?. Not sure how consumable is applied to player tho, but I think using a proxy is the best way to find out how. I do have a proxy, I might check on how the server do it later
> > 
> > 
> > I already know how to make a consumable (i have tons), the problem is i don't know how to add that when it's clicked the extra xp effect is added for a certain time.
> 
> Maybe try this?
> 
> * Log timestamp when used
> * Run a repeating task
> * On repeating task check if timestamp is passed
> 
> Not sure how to make it in cpp tho xD

Just an update, i figured it out and thanks for trying to help. I'll close this.

**Comment by lixorhaxz** [comment]
Are XP Potion Is Same like Gems? If Gems OnSetBux and xp just edit json?

**Comment by Onlyin2** [comment]
> Are XP Potion Is Same like Gems? If Gems OnSetBux and xp just edit json?

Wdym.
