### ISSUE TITLE
SELL PROJECT COLD SOURCE!

### ISSUE THREAD

**Issue by gtdk** [GrowtopiaNoobs/GrowtopiaServer#1156]
SELL PROJECT COLD FULL CPP! DM TO ME! Restark#0001

**Comment by Onlyin2** [comment]
> SELL PROJECT COLD FULL CPP! DM TO ME! Restark#0001

It's already leaked.

**Comment by GuckTubeYT** [comment]
> SELL PROJECT COLD FULL CPP! DM TO ME! Restark#0001

Bruh bruh

**Comment by GuckTubeYT** [comment]
I just leaked gtog, but i dont want to sell it, because gtog cpp its already publicly hehe

**Comment by WoofHax** [comment]
this is not issues.... close it and dont sell you cpp at github

**Comment by Onlyin2** [comment]
If anyone wants the cpp he's selling hmu it's free. SNOWMOBILE#8470
