### ISSUE TITLE
[BUG] IOS is stuck at logging in. 

### ISSUE THREAD

**Issue by Onlyin2** [GrowtopiaNoobs/GrowtopiaServer#1157]
Looks like i'm having something wrong, any hints?

**Comment by WoofHax** [comment]
bcz of custom items noice

**Comment by Onlyin2** [comment]
> bcz of custom items noice

I'm not using custom items for this server.

**Comment by GuckTubeYT** [comment]
hmmmmmmm.... reinstall growtopia?

**Comment by Onlyin2** [comment]
> hmmmmmmm.... reinstall growtopia?

What does reinstalling growtopia have to do with this
