### ISSUE TITLE
What should i add for GTPSController?

### ISSUE THREAD

**Issue by GuckTubeYT** [GrowtopiaNoobs/GrowtopiaServer#1159]
What should i add for GTPSLauncher?

**Comment by DrOreo002** [comment]
Auto upload for cdn content.

**Comment by GuckTubeYT** [comment]
> 
> 
> Auto upload for cdn content.

hmmmm ok ill try it

**Comment by GuckTubeYT** [comment]
> 
> 
> Auto upload for cdn content.

do you have Discord? Add me GuckTubeYT#8912

**Comment by GuckTubeYT** [comment]
![Capture](https://user-images.githubusercontent.com/56192597/73585563-e1c8a500-44d4-11ea-9bae-1b9da957376d.PNG)

This is Features, before i uploaded to public, what should i add?

**Comment by DrOreo002** [comment]
Proper english

**Comment by GuckTubeYT** [comment]
> 
> 
> Proper english

huh?

**Comment by GuckTubeYT** [comment]
@DrOreo002 add discord

**Comment by GuckTubeYT** [comment]
> 
> 
> Auto upload for cdn content.

i dont understand
what do you mean?

**Comment by GuckTubeYT** [comment]
> 
> 
> Auto upload for cdn content.

can you make example?

**Comment by GuckTubeYT** [comment]
@DrOreo002 i just released gtpscontroller https://github.com/GuckTubeYT/GTPSController

**Comment by GuckTubeYT** [comment]
this is not a virus, why detected virus?
becuase i just embed batch file and registry
