### ISSUE TITLE
How can I make my own CDN

### ISSUE THREAD

**Issue by DrKfir** [GrowtopiaNoobs/GrowtopiaServer#1160]
I want to make my own CDN to create my own cache I know how to change the CDN in Growtopia private server CPP and I want to ask if someone knows, so please if you know to tell me how.
Sorry for asking.
EDIT: Also, if you didn't understand me right IDK what do I need to do with the cache folder if I need VPS don't warry I have one so...

**Comment by flossboss** [comment]
#1158 ;)

**Comment by DrKfir** [comment]
yes I know bro but IDK how to host CDN @flossboss 
>Put ur custom rttx file in ur custom cdn content that you've hosted over http
that's what he said and IDK how to create custom CDN contact

**Comment by kingawesomed2** [comment]
Cdn = cache upload ur cache too xampp htdocs and rcustomitem.rttex

**Comment by DrKfir** [comment]
kk TYSM @kingawesomed2

**Comment by DrOreo002** [comment]
Any web hosting should do the job, put ur custom cache folder inside public folder of the website

**Comment by GuckTubeYT** [comment]
or you can use XAMPP

**Comment by DrOreo002** [comment]
Here's a example
http://droreo002.me/growtopia/server_data.php

I hosted it using DewaWeb and I added growtopia/server_data.php inside the public_html folder

**Comment by DrKfir** [comment]
thank you guys I was sleep so I cannot read that so sorry also yes I am using Xampp and I will try that today.
@DrOreo002 
@GuckTubeYT

**Comment by DrKfir** [comment]
hi @GuckTubeYT did you solve the problem about updating item and just this nothing happens anymore it's just stuck and do that again lol.

**Comment by DrKfir** [comment]
Also, should I add all cache or just the game folder and inside my custom RTTEX for the custom item?
