### ISSUE TITLE
GTPSController Has Been Released!

### ISSUE THREAD

**Issue by GuckTubeYT** [GrowtopiaNoobs/GrowtopiaServer#1161]
Hello guys, i just released GTPSController
Made By Me
Btw, this is not virus, idk why my app detected virus
if you dont beleive, use virtual machine, like virtual box
and dont forget to star my project

How to Use This App
1.Place this app to your GTPS Folder
2.Change enet server test.exe to enet

Features
-Turn On GTPS
-Turn Off GTPS
-server_data.php (XAMPP)
-Auto Restarter
-Auto Setting Firewall
-Bypass Error Reporting
-Check XAMPP Logs
-Crash Auto Restarter
Download Link: https://github.com/GuckTubeYT/GTPSController

**Comment by JadlionHD** [comment]
is there any source file?, not the exe thing

**Comment by GuckTubeYT** [comment]
> 
> 
> is there any source file?, not the exe thing

hmmmmmmm.... i cant :V

**Comment by GuckTubeYT** [comment]
because i use embed to bat + visual basic

**Comment by WoofHax** [comment]
this project can made by c++ ........

**Comment by GuckTubeYT** [comment]
> 
> 
> this project can made by c++ ........

yes, but im confused about c++ hehe

**Comment by GuckTubeYT** [comment]
btw @WoofHax do you have an idea for this app?

**Comment by kingawesomed2** [comment]
Its really amazing @gucktubeyt add Worlds/player data saver because when crash and restart data not saving

**Comment by WoofHax** [comment]
@GuckTubeYT idk too you is you app/project not my. I already quit this GrowtopiaServer Project since gtv3 cpp got leaked. No worth for me if i continue to coding GrowtopiaServer bcz outside there have alot of Growtopia Private Server.

**Comment by GuckTubeYT** [comment]
> Its really amazing @GuckTubeYT add Worlds/player data saver because when crash and restart data not saving

Hmmmmm.... lemme try?

**Comment by GuckTubeYT** [comment]
> 
> 
> Its really amazing @GuckTubeYT add Worlds/player data saver because when crash and restart data not saving

but, you must to create account bot for auto save

**Comment by GrowtopiaNoobs** [comment]
This had enough time to be noticed by people.
