### ISSUE TITLE
What should i add to GTPSController

### ISSUE THREAD

**Issue by GuckTubeYT** [GrowtopiaNoobs/GrowtopiaServer#1163]
What should i add to GTPSController

**Comment by kingawesomed2** [comment]
Bot checker

**Comment by kingawesomed2** [comment]
And bind auto crasher+ server restarter

**Comment by kingawesomed2** [comment]
Auto uptader

**Comment by GuckTubeYT** [comment]
> 
> 
> And bind auto crasher+ server restarter

Done

**Comment by GuckTubeYT** [comment]
W

> 
> 
> Bot checker

Bot checker?

**Comment by GuckTubeYT** [comment]
"Add Role" Good Idea?

**Comment by kingawesomed2** [comment]
Add subserver

**Comment by GuckTubeYT** [comment]
> 
> 
> Add subserver

lol subserver, btw subserver not supported, and then i dont know about subserver coding

**Comment by kingawesomed2** [comment]
add auto saver player/worlds when crash and restart

**Comment by GuckTubeYT** [comment]
> add auto saver player/worlds when crash

Hmmmmm good idea
