### ISSUE TITLE
How to make Sub-server

### ISSUE THREAD

**Issue by kingawesomed2** [GrowtopiaNoobs/GrowtopiaServer#1164]
How?

**Comment by Zlarex** [comment]
maybe this -> github.com/GrowtopiaNoobs/GrowtopiaServer2

**Comment by DrOreo002** [comment]
Buy another vps or just run another exe file but with different port ofc.

Then make a simple server that will handle the OnSendToServer packet or you can say the proxy. The proxy server should be the one who decided where to send the player, you can "copy" this function by looking at BungeeCord (Proxy server made for Minecraft)

Can't give you more explanation other than that since I havent tried to make one 😂

**Comment by Valkr1e** [comment]
> Buy another vps or just run another exe file but with different port ofc.
> 
> Then make a simple server that will handle the OnSendToServer packet or you can say the proxy. The proxy server should be the one who decided where to send the player, you can "copy" this function by looking at BungeeCord (Proxy server made for Minecraft)
> 
> Can't give you more explanation other than that since I havent tried to make one . But by looking at my Growtopia packet capturer I can safely say that is how Growtopia made "sub-server"

What ur discord ?

**Comment by DrOreo002** [comment]
Need help?, ask me here. I don't want to give private lesson for free

**Comment by WoofHax** [comment]
i am not sure why you guys want to make sub-server anyway.
https://github.com/GrowtopiaNoobs/Growtopia-Bot/blob/373d101e28870bdb3c9b47a8c5b24c2f24683af0/Growtopia_Bot/userfunc.h#L135 if you want make sub-server here link have exemple from gt bot.

**Comment by DEERUX** [comment]
subserver function was literally given in gtv3 publishment / open source code kingawesomed just asks unnecessary while not even knowing basics.

**Comment by GrowtopiaNoobs** [comment]
This is complicated stuff and there is no easy answer. You need to share worlds and messages between multiple enet servers. Implementation is up to you. Closing this, because it is old and there is not enough activity. If you still have this question, then please open new one with same content.
