### ISSUE TITLE
How to fix crash Many Netid packets

### ISSUE THREAD

**Issue by kingawesomed2** [GrowtopiaNoobs/GrowtopiaServer#1167]
How to fix worlds crasher server crash

**Comment by WoofHax** [comment]
i can't understand what are you talking about oof.

**Comment by Zlarex** [comment]
Cooldown?

**Comment by DrOreo002** [comment]
Proper connection handling for ur server. 

1. Don't ever do everything on the main thread
2. Multi threading
3. SQL Based database, json is shit
4. Brain

**Comment by DEERUX** [comment]
no 5. on the list is missing for him @DrOreo002 from where will we get a brain know huh??

**Comment by GrowtopiaNoobs** [comment]
Ideas were given and I don't think there is way to help more, because there isn't enough information.
