### ISSUE TITLE
[BUG] 3 Far When put Block

### ISSUE THREAD

**Issue by Valkr1e** [GrowtopiaNoobs/GrowtopiaServer#1168]
How To Fix BUG When Using Rayman Then Put Block 3 Far Like When we punch using Rayman. But other items not
Please Help

**Comment by WoofHax** [comment]
sendTileUpdate it was same with sendDrop

**Comment by InjectionZ** [comment]
Uhhh, Check for plantingTree == 18

**Comment by Valkr1e** [comment]
And then

**Comment by InjectionZ** [comment]
Check for rayman and then sendTileUpdate

**Comment by Valkr1e** [comment]
Nothing wrong with rayman
