### ISSUE TITLE
Error Connecting 

### ISSUE THREAD

**Issue by axnanyt** [GrowtopiaNoobs/GrowtopiaServer#1169]
I Have made a server with azure vps and added firewall and have setup xampp. But when i open growtopia it is showing error connecting can anyone help me i have been trying to fix this for a week

**Comment by DrOreo002** [comment]
Whats the error?

**Comment by axnanyt** [comment]
> Whats the error?

Showing error connecting when opening Growtopia

**Comment by DrOreo002** [comment]
1. Ur connection is shit
2. You forget to setup the web server containing server data

**Comment by NotDark** [comment]
> I Have made a server with azure vps and added firewall and have setup xampp. But when i open growtopia it is showing error connecting can anyone help me i have been trying to fix this for a week

firewall in the azure website panel

**Comment by axnanyt** [comment]
> 1. Ur connection is shit
> 2. You forget to setup the web server containing server data

I did setup web server and pasted server data in htdocs as well

**Comment by axnanyt** [comment]
> > I Have made a server with azure vps and added firewall and have setup xampp. But when i open growtopia it is showing error connecting can anyone help me i have been trying to fix this for a week
> 
> firewall in the azure website panel

Did still not working

**Comment by WoofHax** [comment]
For azure add firewall rules 

Inbound 17091 udp tcp 80 is already added
Outbound add tcp 80 port http
