### ISSUE TITLE
GNU Affero General Public License violation

### ISSUE THREAD

**Issue by AlePur** [GrowtopiaNoobs/GrowtopiaServer#117]
Bunch of people are using your server (tweaked by them) and refuse to share the source code. Asking for it got me banned from discord + the server. Discord: https://discordapp.com/invite/eDccfxK. Server address: http://145.239.149.135

**Comment by Mempler** [comment]
We're aware of that, Sadly we dont have the money to go against them nor wont they listen to us anyway.

But still, thank you for your report.

**Comment by ritzysw** [comment]
just a little note: this @AlePur kid was banned for trying to ddos server, spamming, ban evading like 6+ times.
we are in direct contact with Anybody/GTNoobs, you can ask him if you wish

**Comment by AlePur** [comment]
Just a little note: I was ban evading because you refused to communicate, but I never spammed or DDoSed your server.

**Comment by Mempler** [comment]
Both of you, stop. I dont care what you're doing on your server. But that what you're talking about is offtopic.

**Comment by Mempler** [comment]
Just a side note, if you need any help with something. You dont need to always contact Anybody, you can also contact me ^^


And no, i dont help you with community stuff like "I got banned for this reason, so i l'll ddos for that reason" or smth like that.

**Comment by AlePur** [comment]
And I never asked you anything about that

**Comment by Mempler** [comment]
It was an example.
