### ISSUE TITLE
Host server on ubuntu

### ISSUE THREAD

**Issue by kingawesomed2** [GrowtopiaNoobs/GrowtopiaServer#1170]
How to host server on ubuntu and how to host server on website example exampla.com/growtopia/server_data.php

**Comment by WoofHax** [comment]
sudo apt install apache2

**Comment by GuckTubeYT** [comment]
after you install apache, install wine and visual studio exe, or you can use build-essential

**Comment by herothedev** [comment]
vs wont work on linjx

**Comment by GrowtopiaNoobs** [comment]
Check `appveyor.yml` for build instructions. Also I guess this is solved, because there was no new activity.
