### ISSUE TITLE
GTPSController Code Source Has Been Public

### ISSUE THREAD

**Issue by GuckTubeYT** [GrowtopiaNoobs/GrowtopiaServer#1174]
Hello guys, if you want to know my GTPSController Code Source, now you can look my code source of GTPSController

Link: https://github.com/gucktubeyt/gtpscontroller

**Comment by JadlionHD** [comment]
hey @GuckTubeYT 
I recommend you to put some license in your repo to protect your work from people that saying "this source made by me" something like that.
ok that's what i wanted to say

**Comment by GuckTubeYT** [comment]
ok

**Comment by GrowtopiaNoobs** [comment]
This had enough time to get attention, so I am closing this now.
