### ISSUE TITLE
About Nginx (Alternative Apache)

### ISSUE THREAD

**Issue by GuckTubeYT** [GrowtopiaNoobs/GrowtopiaServer#1175]
Nginx make your server anti ddos (At Google :V), but I Have a Question

1. It Is auto down if you leave vps?

**Comment by DrOreo002** [comment]
nothing will be down if there's nothing wrong with your vps. Your hosting company will sure keep your vps active everytime

**Comment by GuckTubeYT** [comment]
@DrOreo002 ohhhh thanks for information

**Comment by GuckTubeYT** [comment]
I want to make Nginx Control panel and anti ddos (maybe it is work)

**Comment by DrOreo002** [comment]
what does that even do with cpp server that works with UDP packet?

**Comment by GuckTubeYT** [comment]
> what does that even do with cpp server that works with UDP packet?

Hmmmm.... at windows server = adding firewall
But at linux vps = no need to adding firewall? Maybe?

**Comment by MoanHawks** [comment]
> > what does that even do with cpp server that works with UDP packet?
> 
> Hmmmm.... at windows server = adding firewall
> But at linux vps = no need to adding firewall? Maybe?

all virtual machine have firewall

**Comment by GuckTubeYT** [comment]
> > > what does that even do with cpp server that works with UDP packet?
> > 
> > 
> > Hmmmm.... at windows server = adding firewall
> > But at linux vps = no need to adding firewall? Maybe?
> 
> all virtual machine have firewall

Ohhh

**Comment by GuckTubeYT** [comment]
But, when i make mcpe server at linux server, no need to add firewall

**Comment by Bexpg** [comment]
u have too add firewall and port so everyone can connect

**Comment by GuckTubeYT** [comment]
> u have too add firewall and port so everyone can connect

Yeah i know, and then works! Thanks

**Comment by GrowtopiaNoobs** [comment]
No server is anti-ddos as it is impossible. But you can google how to mitigate attacks such as slowloris.
