### ISSUE TITLE
How to setup mysql for gtserver?

### ISSUE THREAD

**Issue by Ipadtopia** [GrowtopiaNoobs/GrowtopiaServer#1176]

**Comment by MoanHawks** [comment]
Search on Google 

C++ MySQL connecter and MySQL visual studio

**Comment by kingawesomed2** [comment]
idk

**Comment by cmdocmd** [comment]
wym how to setup mysql samething instead of saving data to json save it in mysql....

**Comment by xXAbood** [comment]
https://github.com/mysql
