### ISSUE TITLE
[issue] 404 Error

### ISSUE THREAD

**Issue by triple14** [GrowtopiaNoobs/GrowtopiaServer#1177]
Everytime I connect to my server and logon it says

"Server gave a 404 : File Not Found. Bad Url?"

Anyway to fix this?

**Comment by Ipadtopia** [comment]
check ur cdncontent.

**Comment by GuckTubeYT** [comment]
Or make your own cdncontent

**Comment by DrKfir** [comment]
just make your own CDN it's easy @triple14

**Comment by Bexpg** [comment]
Uptade ur cdn content with newest one cdncontent47

**Comment by GrowtopiaNoobs** [comment]
Issue was answered. Closing.
