### ISSUE TITLE
[BUG] Can't find website, bad URL or no internet error

### ISSUE THREAD

**Issue by LinkTopia2** [GrowtopiaNoobs/GrowtopiaServer#1178]
![unknown](https://user-images.githubusercontent.com/60845093/74102271-b2580f00-4b4a-11ea-91e9-2556afe4ccaa.png)

**Comment by ardakurucim** [comment]
turn http server on u can use xampp/python/nginx

**Comment by LinkTopia2** [comment]
> turn http server on u can use xampp/python/nginx

Do you have discord? I need more help

**Comment by JadlionHD** [comment]
Try to login Growtopia Official then wait updating item until done, after that back to gtps.
Idk if this work or no just try it

**Comment by LinkTopia2** [comment]
> Try to login Growtopia Official then wait updating item until done, after that back to gtps.
> Idk if this work or no just try it

Not working

**Comment by MoanHawks** [comment]
check http is on or not
or
try go https://www.speedtest.net/ and check ur shit internet

**Comment by Bexpg** [comment]
Uotade cdn cache

**Comment by iProgramMC** [comment]
his gt doesnt even say "located server, connecting...". I think he isnt hosting the http server

**Comment by GrowtopiaNoobs** [comment]
As you created new issue, where you have this problem solved, I am closing this. Please close your solved issues. (And post answer how you solved them)
