### ISSUE TITLE
[BUG] Growtopia Crashes Upon Connection

### ISSUE THREAD

**Issue by WuXeR** [GrowtopiaNoobs/GrowtopiaServer#1179]
**Describe the bug**
Growtopia crashes upon connecting

**To Reproduce**
1. Open Server
2. Open Growtopia
3. Login without growid
4. Growtopia closes/crashes

**Expected behavior**
The server runs fine, however, when I connect with growtopia my game just closes.

**Server environment (please complete the following information):**
 - OS: Windows10
 - Experience: beginner
 - Modifications: none

**Client environment (please complete the following information):**
 - Growtopia version: V3.01

**Comment by kingawesomed2** [comment]
Ctrl+f register and send screenshoot here

**Comment by WuXeR** [comment]
I haven't changed anything about the code. I just realized I should have set Modifications: none

**Comment by WuXeR** [comment]
Is there anything I need to change about the code to make it work?

**Comment by WuXeR** [comment]
Hmmm... seems [this ](https://github.com/GrowtopiaNoobs/GrowtopiaServer/issues/1181)is actually my issue
