### ISSUE TITLE
Nginx

### ISSUE THREAD

**Issue by kingawesomed2** [GrowtopiaNoobs/GrowtopiaServer#1180]
How to use nginx ?

**Comment by WuXeR** [comment]
are u using ubuntu? if so it's very straightforward

**Comment by DEERUX** [comment]
funny thing why are people asking this here when its the growtopiaserver repo..

**Comment by kingawesomed2** [comment]
@DEERUX  retard im qsking how to run gtps with nginx its about issue gt

**Comment by DEERUX** [comment]
retard u literall just asked "How to use nginx" not about how to run gtps with nginx and thats such a stupid question nginx and gtps are hosted seperately and then you normally use the growtopia/server_data.php file for the redirection

**Comment by GrowtopiaNoobs** [comment]
This is already answered on wiki:

> You need to make HTTP server which contains file /growtopia/server_data.php. This file can be found on original growtopia site and minimal editing is needed.

Other setup should be usual for nginx. Please open new issue if you will have more specific information.
