### ISSUE TITLE
[BUG] Growtopia still crashes...

### ISSUE THREAD

**Issue by WuXeR** [GrowtopiaNoobs/GrowtopiaServer#1184]
I'm not gonna follow the format because I just want to ask if anyone has a working 3.01 server. If so could you tell me what you did to make it work or even send me the files. I know this isn't exactly what this is used for but my growtopia crashes upon entering a world.

**Comment by cmdocmd** [comment]
dude dont use leaked cpp just download this github files

**Comment by WuXeR** [comment]
That's what I've been doing -.- it doesn't work

**Comment by Bexpg** [comment]
Delete players/worlds folder and create new one

**Comment by WuXeR** [comment]
It's fine I figured it out. I didn't have the enet lib in the same folder as my .exe file.
