### ISSUE TITLE
[BUG] Can't start my private server on VPS

### ISSUE THREAD

**Issue by LinkTopia2** [GrowtopiaNoobs/GrowtopiaServer#1185]
![Screenshot_2020-02-11-08-47-49-1](https://user-images.githubusercontent.com/60845093/74225518-8ad88200-4cc3-11ea-955f-9d6672ec1053.png)
Anyone knows what is this? I'm new at all this.
![Screenshot_2020-02-09-22-38-10-1](https://user-images.githubusercontent.com/60845093/74225572-a2176f80-4cc3-11ea-9438-1d647683296e.png)

**Comment by JadlionHD** [comment]
use xampp instead of python if u have a vps.

**Comment by kingawesomed2** [comment]
Ur file not full

**Comment by kingawesomed2** [comment]
u missing some folder

**Comment by RajehTXD** [comment]
Oh i know. i had the same bug.. it was on 2.987 but the thing missing i think is the cdn get update files. and so you would have to have the same cache files as the specific vesion the seve is built for.
and yes use xampp it is better for http requests. Check you items.dat... Good Luck Buddy and i hope i help - RajehTXD, Returning to help on github XD

**Comment by RajehTXD** [comment]
If you could by anyway have you cpp then put it on some sort of repo and ill help diagnose it. I have coded my own in the summer and so i dont need any, I am lebaneese and Lebanon has no "Real IP" so im stuck using vps or local network. The Fact it is Logging on means it is an error. You Left your IP out so

Country Code | Location | Network | Postal Code | Approximate Coordinates* | Accuracy Radius (km) | ISP | 
Organization | Domain | Metro Code
44.224.22.196 | US | Boardman,Oregon,United States,North America | 44.224.0.0/17 | 97818 | 45.8491,-119.7143 | 1000 | Amazon.com | Amazon.com | amazonaws.com | 810

**Comment by Bexpg** [comment]
1. Dont use leaked cpp. 2. u missing some file

**Comment by DEERUX** [comment]
@Bexpg ur using one urself go get a mirror before saying anything thanks.
