### ISSUE TITLE
[BUG] Not the latest version

### ISSUE THREAD

**Issue by LinkTopia2** [GrowtopiaNoobs/GrowtopiaServer#1186]
I'm a new coder, so I'd appreciate if you'd describe me this error as clear as possible, and a solution to fix it.Also, mention your discord in the description, so if I don't understand you, I can contact you
![image](https://user-images.githubusercontent.com/60845093/74242981-8cb43c80-4ce7-11ea-9b91-0ffa60a933e4.png)

**Comment by LinkTopia2** [comment]
> dude cmon dont use leaked cpp... just download the cpp from the github

Where can I find the cpp?

**Comment by MoanHawks** [comment]
> > dude cmon dont use leaked cpp... just download the cpp from the github
> 
> Where can I find the cpp?

google it

**Comment by NotDark** [comment]
> > dude cmon dont use leaked cpp... just download the cpp from the github
> 
> Where can I find the cpp?

https://github.com/GrowtopiaNoobs/GrowtopiaServer/

**Comment by kingawesomed2** [comment]
Ctrl + f find 2.997 and change to 3.01

**Comment by RajehTXD** [comment]
it is in the Game version variable in the client. which cant be decoded and is hardcoded into the client itself. It is to stop hacks and whatnot (update items). and so more and more nulls will be the older's version case and more bugs etc..
you find a variable sent to the server by the client called game_version just change what it is equal to afterwards. and yup leaked cpp

**Comment by White-Scorp** [comment]
> I'm a new coder, so I'd appreciate if you'd describe me this error as clear as possible, and a solution to fix it.Also, mention your discord in the description, so if I don't understand you, I can contact you
> ![image](https://user-images.githubusercontent.com/60845093/74242981-8cb43c80-4ce7-11ea-9b91-0ffa60a933e4.png)

Ctrl+F find 2.997 change to 3.011

**Comment by Bexpg** [comment]
Open enet server test.sln go to enet server test.cpp press ctrl+f search  for 2.997 and change all too 3.011

**Comment by DevError** [comment]
I actually will kindly answer that, I probley recommend changing some things in the cpp file it self. Like example You said your new coder, thats great couse your in luck just try some of my methods 
1. Try changing config version, go to cpp file and search in finder "2.997" and change to the most present version, if dont work try next.
2. I'm 85% right on the first method is helpful but if you get a new error called "error connection" try a new hash file and data file from original GT Oath folder in "cach". Kinda rushed on this sorry for not deep explained.
More help ;)
https://discord.gg/KjvxjzK

**Comment by GrowtopiaNoobs** [comment]
Answer was given and there was no new activity, so I am closing this.
