### ISSUE TITLE
Get Help

### ISSUE THREAD

**Issue by hadiGTPS** [GrowtopiaNoobs/GrowtopiaServer#1189]
Here Is group i help you fully in anything 
https://discord.gg/GPqSPYz
Thanks
And no i aint making any server furthor soon

**Comment by xXAbood** [comment]
bruh

**Comment by kingawesomed2** [comment]
Go learn how to code first after open ur discord server and help people.

**Comment by BILLION-GT** [comment]
> Go learn how to code first after open ur discord server and help people.

Stfu u need to learn how to code.

**Comment by kingawesomed2** [comment]
> > Go learn how to code first after open ur discord server and help people.
> 
> Stfu u need to learn how to code.

 Ok turkid.

**Comment by DEERUX** [comment]
@kingawesomed2 before you criticize people make sure you got a mirror with you and you cant code at all or maybe you think using other's premade „enet server test.cpp“ (which already is worse than taking the original one’ from anybody) is coding.
and I believe you are less than 13 yourself.
clauwn.

**Comment by FortniteSyr** [comment]
@DEERUX bro i got problem with run ios on Project time crystal I want to run the Ios can u help if u can 
jobst#0164

**Comment by GrowtopiaNoobs** [comment]
This had enough time to get attention, so I am closing this.
