### ISSUE TITLE
Disconnectiong... Disconnecting... And again disconnecting...

### ISSUE THREAD

**Issue by ilyn1337** [GrowtopiaNoobs/GrowtopiaServer#119]
I did debug the code so i found something is interesting here:
https://github.com/ipr0gr4mipas2/growtopia_server/blob/master/enet%20server%20test/enet%20server%20test.cpp#L2897
how can i fix that???

**Comment by Mempler** [comment]
You need to change the items.dat hash to the latest one. but whatever. we dont provide support for forks if they're not making pull requests.

This fork you gave us is actually outdated.
