### ISSUE TITLE
[BUG] Not working

### ISSUE THREAD

**Issue by bestforums** [GrowtopiaNoobs/GrowtopiaServer#1190]
Hi. This source or others don't work for me. This source gives disconnected from server error. Other sources fail loading at updating items 1/78 . I have a vps and I will host forever for free if you find me a working source. My discord id gtpsftw#9213 . Thank you.

**Comment by Bexpg** [comment]
Change old items.dat with new items.dat u can find in growtopia folder cache/items.dat

**Comment by bestforums** [comment]
I can't find it. I can only see old items dat. How to find new one? At another source?

**Comment by Bexpg** [comment]
@bestforums windows + r appdata local growtopia cache items.dat
