### ISSUE TITLE
SendDrop

### ISSUE THREAD

**Issue by Bexpg** [GrowtopiaNoobs/GrowtopiaServer#1191]
How to make When Break Dirts, drop blue , red , purple Gems. And save They when reenter world

> ### ****

**Comment by InjectionZ** [comment]
Save with vector struct and get dropped info by uids

**Comment by Bexpg** [comment]
At yalanini sikim inani @InjectionZ  translate

**Comment by xXAbood** [comment]
injection is right

**Comment by BILLION-GT** [comment]
> At yalanini sikim inani @InjectionZ translate

He told u how to do.
And i think u wan't free code but no one give you free code

**Comment by Bexpg** [comment]
@BILLION-GT  mother fucker 9 years old kids i dont want free code but ur mom want suck ma dick

**Comment by SSebia** [comment]
> @BILLION-GT mother fucker 9 years old kids i dont want free code but ur mom want suck ma dick

Retarded Indog

**Comment by BILLION-GT** [comment]
> @BILLION-GT mother fucker 9 years old kids i dont want free code but ur mom want suck ma dick

Lol i know you ask for free code here.
If u know a little about code then why u saying @InjectionZ is lying.
@InjectionZ u right 👍

**Comment by BILLION-GT** [comment]
> > @BILLION-GT mother fucker 9 years old kids i dont want free code but ur mom want suck ma dick
> 
> Lol i know you ask for free code here.
> If u know a little about code.
Then why u saying @InjectionZ is lying.
> @InjectionZ u right

**Comment by BILLION-GT** [comment]
> > @BILLION-GT mother fucker 9 years old kids i dont want free code but ur mom want suck ma dick
> 
> Lol i know you ask for free code here.
> If u know a little about code.
Then why u saying @InjectionZ is lying.
> @InjectionZ u right

**Comment by DEERUX** [comment]
gtkid fight battle

**Comment by BILLION-GT** [comment]
> > @BILLION-GT mother fucker 9 years old kids i dont want free code but ur mom want suck ma dick

Lol i know you ask for free code here.
If u know a little about code.
Then why u saying @InjectionZ is lying.
@InjectionZ u right

**Comment by DEERUX** [comment]
gtkid fight battle winner gets the honor

**Comment by Bexpg** [comment]
@SSebia  u are fucking indog fucking skids

**Comment by BILLION-GT** [comment]
> @SSebia u are fucking indog fucking skids

STFU.

**Comment by DrOreo002** [comment]
Willi does have a sendDrop function implemented on his c# server. With a little bit of brain cells you should be able to translate it into c++

https://github.com/willi123yao/GrowtopiaServerCS/blob/master/GrowtopiaServer/GrowtopiaServer.cs#L1586
