### ISSUE TITLE
Auto Custom ID Maker 

### ISSUE THREAD

**Issue by hadiGTPS** [GrowtopiaNoobs/GrowtopiaServer#1192]
https://github.com/hadiGTPS/custome-item-maker
Make Your Own Custom Item ID. Useless App But Alot Don't Know How to Create New ID For Item. SOON i make rttex helper. if u wana add new items to app deompile it its c# easy decompile. if it ask u what item u wana make make sure answer is : eyes or shirt or pants or feets or hand or wing.
Hope You Like.

**Comment by DrOreo002** [comment]
Why don't you just upload the source?. Isn't that what github is used for?

**Comment by sadMotion** [comment]
bro use dnspy and export it
you can get easy project 
🥉

**Comment by sadMotion** [comment]
oh its c++ sorry
 Microsoft Visual C++ v14 - 2015 - ( x64 ) www.microsoft.com (exe 4883ec 28-48) [ Win Vista ]

**Comment by GrowtopiaNoobs** [comment]
Please release your app with source code.
Closing
