### ISSUE TITLE
Growtopia is currently running nginx

### ISSUE THREAD

**Issue by GorgonUK** [GrowtopiaNoobs/GrowtopiaServer#1195]
Server: nginx

**Comment by bykoi** [comment]
#useful

**Comment by Bexpg** [comment]
Thanks For Info.

**Comment by DrOreo002** [comment]
?????????

**Comment by gucktubeyt2** [comment]
now you can run server with nginx

**Comment by DEERUX** [comment]
yeah wow, as if no one knew its possible to host a webserver using nginx, the linux + nginx combo is most frequent anyway.

**Comment by GrowtopiaNoobs** [comment]
This issue doesn't tell us anything. Please create new one and describe more properly what you want to say.
Closing
