### ISSUE TITLE
Out Of World Crash | canWalkInBlocks causes Unlimited jump

### ISSUE THREAD

**Issue by SSebia** [GrowtopiaNoobs/GrowtopiaServer#1196]
Ok, so basically canWalkInBlocks somehow makes you unlimited jump, if i put candoublejump near it it still makes unlimited jump effect. The weird thing is that the unlimited jump effect disappears after using /warpto or /warp. Any suggestions?

**Comment by MoanHawks** [comment]
did you use invis?

**Comment by mar4ello6** [comment]
U placed smstate or mstate to 1. (In OnSpawn)

**Comment by SSebia** [comment]
> U placed smstate or mstate to 1. (In OnSpawn)

Issue fixed thanks!
