### ISSUE TITLE
Save World items

### ISSUE THREAD

**Issue by Bexpg** [GrowtopiaNoobs/GrowtopiaServer#1197]
so yeah i made wheb break blocks drop gems but when reenter its gone, and When take its not save in gemdb so can anyone help me how save 2 thoughts.

**Comment by bykoi** [comment]
save them in world with massive/vector

**Comment by DrOreo002** [comment]
You know that sendDrop also sends packet to the client right?, so whenever a drop packet is being sent save its item id, position or whatever to a vector or maybe a single class, up to you.

Then when users enter the world re send those packet back so the clients know that there's a dropped item on that location

**Comment by Bexpg** [comment]
@DrOreo002  how i can send packet back and when take gems its not save in gemdb how fix

**Comment by bykoi** [comment]
save it?

**Comment by Bexpg** [comment]
@DrOreo002  dm me in discord Bexpg#1234 if you want help me for money, or dl

**Comment by DEERUX** [comment]
-gemdb sounds very pasty
-learn how to load items properly with appending its certain bytes to worldp.
-balance memory usage and disk usage at best possibilites
-maybe look for something else than a vector
-and dont fucking offer people a diamond lock or some shit if you arent going to pay first anyway its the most retarded scam method in history since back then and still til today.

**Comment by Bexpg** [comment]
@DEERUX  fuck off im paying first and also im dont care dls i have a lot of dls  and im offerin dls to people because people why should help for free? i dont like free helping from people and you fucking shit retard go learn how to code marketplace first

**Comment by DrOreo002** [comment]
never actually tried this in cpp cus I do java mainly so I couldn't help you further

**Comment by White-Scorp** [comment]
> @DrOreo002 dm me in discord Bexpg#1234 if you want help me for money, or dl

White#9560 add me on discord.

**Comment by DEERUX** [comment]
@bexpg good lie
