### ISSUE TITLE
Discord Support server ;)

### ISSUE THREAD

**Issue by DevError** [GrowtopiaNoobs/GrowtopiaServer#1200]
If you need lots of support for making / Developing a GTPS Server then I suggest joining this server, i've been coding for long time and now taking My time to teach everyone to master the basics.

Link ;)
https://discord.gg/KjvxjzK

**Comment by DrOreo002** [comment]
Gtnoobs already has a discord channel on his GrowtopiaServer2 repo, the channel do have a "coding" text channel and other stuff related to asking for a question

**Comment by MoanHawks** [comment]
https://discord.gg/maTqER

**Comment by GrowtopiaNoobs** [comment]
This had enough time to get attention, so I am closing this.
