### ISSUE TITLE
Digger 1 hit

### ISSUE THREAD

**Issue by Bexpg** [GrowtopiaNoobs/GrowtopiaServer#1201]
How to make Digger 1 hit im think its about planting tree but not sure so i decised to ask

**Comment by cmdocmd** [comment]
you can do it in two way 
First way 
Check if player hand in digger if it is digger then 
either make when he punch block send it 4 times to be broken
or change block hit to 1 ...

**Comment by Bexpg** [comment]
@cmdocmd  ok send code if you are know what you doing

**Comment by InjectionZ** [comment]
โง่

**Comment by Bexpg** [comment]
Info : cmd doesnt know to code and scam my 3dls i just kidding dont serious 😉

**Comment by DEERUX** [comment]
@Bexpg you don't know how to code if you are asking such stupid questions in such loser-ish way.

**Comment by Bexpg** [comment]
Platingtree  i made 1hit done.

**Comment by DEERUX** [comment]
„plantingtree“
