### ISSUE TITLE
Save

### ISSUE THREAD

**Issue by Bexpg** [GrowtopiaNoobs/GrowtopiaServer#1203]
How to save items in inventory when drop and take

**Comment by MoanHawks** [comment]
![IMG_20200227_114612](https://user-images.githubusercontent.com/52075701/75410400-c8413e80-5956-11ea-8efb-9df4b3993248.jpg)

**Comment by gucktubeyt2** [comment]
vote for @MoanHawks

**Comment by SSebia** [comment]
> How to save items in inventory when drop and take

It's easy lol

**Comment by DEERUX** [comment]
literally track inventory, best would be to create inventory add and remove functions, you may use an array for that and pay attention for sizes, as inventories have given sizes anyway, to explicitly save or load then we deserialize/serialize them in a binary form, it can be done through mysql as well.

**Comment by Bexpg** [comment]
@SSebia  @MoanHawks  if you dont know How then dont comment my issues.

**Comment by Bexpg** [comment]
@DEERUX  dm me on discord Bexpg#1234 i need ask something (i dont ask for code or help)

**Comment by DEERUX** [comment]
no

**Comment by SSebia** [comment]
> @SSebia @MoanHawks if you dont know How then dont comment my issues.

Lmao you are using my CPP because you would never create inventory system that saves and loads. Anyways I wish you luck making take drop to save to your inventory :DDD

**Comment by Bexpg** [comment]
@SSebia  1. Im using ur cpp because my pc broken for now 2. Its not ur someone sayed its coded from wry

**Comment by MoanHawks** [comment]
> @SSebia @MoanHawks if you dont know How then dont comment my issues.

How dumb you are if you don't know how to coding c++ then don't become development  c++.

**Comment by SSebia** [comment]
> @SSebia 1. Im using ur cpp because my pc broken and my real file in pc 2. Its not ur someone sayed its coded by wry

:DDDD lmao retard, it's not even opened by wry.

**Comment by raiterjaki** [comment]
retardpg

**Comment by Bexpg** [comment]
@MoanHawks Say this who using copy paste? Say me how to code magplant + marketplace @SSebia  @MoanHawks

**Comment by MoanHawks** [comment]
> @SSebia 1. Im using ur cpp because my pc broken and my real file in pc 2. Its not ur someone sayed its coded by wry


> @MoanHawks Say this who using copy paste? Say me how to code magplant + marketplace @SSebia @MoanHawks

1. Using people cpp?????
2. if you pc broken then just quit don't continue coding.

**Comment by InjectionZ** [comment]
Pr0 Bexpg

**Comment by MoanHawks** [comment]
> Pr0 Bexpg

Pr0 us1ng p30pl3 cpp

**Comment by Bexpg** [comment]
Ur mom using my dicks to fuck self hahaahah nob ur mom noobbb
