### ISSUE TITLE
How To Create A Growtopia Discord Bot For Private Server?

### ISSUE THREAD

**Issue by lixorhaxz** [GrowtopiaNoobs/GrowtopiaServer#1205]

**Comment by GuckTubeYT** [comment]
Use discord js?

**Comment by lixorhaxz** [comment]
> Use discord js?

Iya Gmn tong gw mana pernah buat bot

**Comment by JadlionHD** [comment]
bot apanya?

**Comment by JadlionHD** [comment]
https://discord.js.org/

**Comment by DrOreo002** [comment]
Learn how to use socket at cpp first then use that socket to communicate with your bot via packet based

**Comment by MoanHawks** [comment]
> Learn how to use socket at cpp first then use that socket to communicate with your bot via packet based

https://github.com/zaphoyd/websocketpp

**Comment by herothedev** [comment]
sleepydiscord, discord.net, discord.js, discord.py. select one.

**Comment by JadlionHD** [comment]
most easy one is js and py

**Comment by MoanHawks** [comment]
> sleepydiscord, discord.net, discord.js, discord.py. select one.

sleepy discord better can include to enet cpp server + use while loop

**Comment by raiterjaki** [comment]
you can make discord bot to check ip/growtopia/server_data.php every 2-3 minutes and if it can't reach that link then it edits message and makes it say down but, if it reaches to that link then edits message and says that server is up.

**Comment by GrowtopiaNoobs** [comment]
Ideas were given and there was no new activity, so I am closing this.
