### ISSUE TITLE
how to fix enet crashing in new items.dat

### ISSUE THREAD

**Issue by googback** [GrowtopiaNoobs/GrowtopiaServer#1213]

**Comment by FortniteSyr** [comment]
اسمع لو ماتجيني عل دسكورد تعطيني سي بي بي بفقع وجهك 
=============
FortniteSyr#0164
=============

**Comment by FortniteSyr** [comment]
i need cpp ada ma tje bzg 3lek 
FortniteSyr#0164

**Comment by FortniteSyr** [comment]
ok come pls FortniteSyr#0164

**Comment by FortniteSyr** [comment]
pls come me need good cpp
 FortniteSyr#0164

**Comment by JadlionHD** [comment]
????? @FortniteSyr

**Comment by googback** [comment]
@D3c0d33 thanks man
