### ISSUE TITLE
Project Reborn V2 in c#

### ISSUE THREAD

**Issue by cmdocmd** [GrowtopiaNoobs/GrowtopiaServer#1214]
Project Reborn V2 in c#
https://github.com/cmdocmd/GrowtopiaServerCS
by Hadi And CMD

**Comment by D3c0d33** [comment]
With SQL

**Comment by cmdocmd** [comment]
mysql ye

**Comment by SecretSC** [comment]
XD

**Comment by GrowtopiaNoobs** [comment]
Closing this issue as it got enough attention.
