### ISSUE TITLE
how to remove seeds from /find

### ISSUE THREAD

**Issue by googback** [GrowtopiaNoobs/GrowtopiaServer#1218]
help..

**Comment by raiterjaki** [comment]
heard of odd and even numbers?

**Comment by herothedev** [comment]
for (itemDefs().size / 2) {
// use ur brain here
}

**Comment by cmdocmd** [comment]
dude to remove seeds from /find
you can check if the item name include 
seed
if it include nothing
else
add the name inside the loop
then loop all items easy....

**Comment by ImBusy1** [comment]
Thanks

**Comment by D3c0d33** [comment]
CLOSE THIS ISSUE.
