### ISSUE TITLE
How to make an database(mysql) 

### ISSUE THREAD

**Issue by ImBusy1** [GrowtopiaNoobs/GrowtopiaServer#1219]
Thx

**Comment by NotDark** [comment]
https://www.google.com/

**Comment by googback** [comment]
not funny @NotDark

**Comment by herothedev** [comment]
"not funny" bruh its the truth

**Comment by raiterjaki** [comment]
https://www.google.com/
credits to @NotDark for giving the solution to you.

**Comment by googback** [comment]
i can do the search myself but i need the help sfor the clothes,gems,eveything for player fp

**Comment by herothedev** [comment]
"fp", google is solution for you. you can use your brain to store the things. theres tons of tutorials on google, just search "c++ mysql connector"

**Comment by cmdocmd** [comment]
@NotDark is correct
you should search on google for help
and anyways i released a c# server with mysql already go use it ?
