### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by herothedev** [GrowtopiaNoobs/GrowtopiaServer#122]
Do anyone know how to fix that crash bug, so when you enter world in my private then it will be crashed, but if i replace cache with vyte server's then it let me in world without crashing.

I think this issue is in somewhere when the server updates items, but i didnt edit any item loading things.

if you know/think how to fix this please contact me on discord Hero#7865 or Reply here.

**Comment by jDoeanl** [comment]
Same here, it also says "an error occurred while trying to create ENet Server host.
That's probably the reason, i haven't found the fix yet.

**Comment by Mempler** [comment]
> Same here, it also says "an error occurred while trying to create ENet Server host.
> That's probably the reason, i haven't found the fix yet.

Check if your port is already in use!

**Comment by jDoeanl** [comment]
> > Same here, it also says "an error occurred while trying to create ENet Server host.
> > That's probably the reason, i haven't found the fix yet.
> 
> Check if your port is already in use!

I did that, still nothing

**Comment by jDoeanl** [comment]
> > Same here, it also says "an error occurred while trying to create ENet Server host.
> > That's probably the reason, i haven't found the fix yet.
> 
> Check if your port is already in use!

i fixed it, but now i get disconnected all the time, version 2.981

**Comment by Mempler** [comment]
should be fixed.
