### ISSUE TITLE
GTPSLauncherCSharp

### ISSUE THREAD

**Issue by GuckTubeYT** [GrowtopiaNoobs/GrowtopiaServer#1222]
Hello guys, i just published GTPSLauncherCSharp, because i dont know why, when i using GTPSLauncher Visual basic, it detected virus.

Please dont Change Owner to your name
and please dont sell this app, this app is for free for all
btw dont forget to star my project hehe

Source Code: https://github.com/GuckTubeYT/GTPSLauncherCSharp

**Comment by D3c0d33** [comment]
**good job**

**Comment by GuckTubeYT** [comment]
> **good job**

Thanks bro :)

**Comment by arshizx** [comment]
> Please dont Change Owner to your name
You mean give credit?

**Comment by GuckTubeYT** [comment]
> > Please dont Change Owner to your name
> 
> You mean give credit?

If you dont want give credit, its okay, but dont sell this app or change name owner okay

**Comment by arshizx** [comment]
ok ty

**Comment by GuckTubeYT** [comment]
youre welcome

**Comment by GrowtopiaNoobs** [comment]
Closing this issue as it got enough attention.
