### ISSUE TITLE
[HELP] How to convert an exe to apk

### ISSUE THREAD

**Issue by D3c0d33** [GrowtopiaNoobs/GrowtopiaServer#1223]
HOW TO DO, i already know growtopia1.com to ip own vps, there i'm asking how to convert the exe to apk.

**Comment by Unknow532** [comment]
Just change type file name behind 

idk.exe to idk.apk

**Comment by MoanHawks** [comment]
just change type file exe to apk

**Comment by D3c0d33** [comment]
> just change type file exe to apk

Huh? android user's can use it?

**Comment by MoanHawks** [comment]
> > just change type file exe to apk
> 
> Huh? android user's can use it?
How to (convert an exe to apk)

**Comment by FortniteSyr** [comment]
SureKing i want you come talk fast ...

discord :     jobst#0164

come fast... :+1:

**Comment by MoanHawks** [comment]
😳

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MoanHawks** [comment]
😳

**Comment by icantspellmyname** [comment]
😳

**Comment by FortniteSyr** [comment]
guys what cdn content__ I put? i don't know make own cdncontent

**Comment by D3c0d33** [comment]
NVM, WORK.
