### ISSUE TITLE
[BUG] Uh, what does this mean?

### ISSUE THREAD

**Issue by LinkTopia2** [GrowtopiaNoobs/GrowtopiaServer#1224]
![image](https://user-images.githubusercontent.com/60845093/75992521-c3552f80-5f00-11ea-9b79-da93c36f50dc.png)

**Comment by MoanHawks** [comment]
File missing fp

**Comment by LinkTopia2** [comment]
> That mean file missing fp

what file?

**Comment by MoanHawks** [comment]
rttex file you idiot

**Comment by LinkTopia2** [comment]
> rttex file you idiot
And where can I find the file and where do I have to add it

**Comment by MoanHawks** [comment]
![IMG-20200303-WA0009](https://user-images.githubusercontent.com/52075701/75999377-1351e780-5f3d-11ea-94f6-5eeb414a855a.jpg)

**Comment by arshizx** [comment]
update ur items.dat & cdn #1221

**Comment by LinkTopia2** [comment]
> ![IMG-20200303-WA0009](https://user-images.githubusercontent.com/52075701/75999377-1351e780-5f3d-11ea-94f6-5eeb414a855a.jpg)
> 
> Just updating you items.dat fp

I used the items.dat zip, its the latest one, posted on github

**Comment by LinkTopia2** [comment]
> update ur items.dat & cdn #1221

Please tell me what is cdn

**Comment by DrKfir** [comment]
@LinkTopia2 Put the latest CDN
`0098/CDNContent52/cache/`
If you don't know then let me help you in discord.

**Comment by GrowtopiaNoobs** [comment]
Answer was given and there was no new activity in this issue, I take this as solved.
