### ISSUE TITLE
[HELP] How to convert an exe to apk

### ISSUE THREAD

**Issue by raiterjaki** [GrowtopiaNoobs/GrowtopiaServer#1225]
HOW TO DO, i already know growtopia1.com to ip own vps, there i'm asking how to convert the exe to apk.

HOw to do???? I alraedy code vps good 59,183 line not enough ;;;:9((((( 
I coded weatheer stuff machin to vps server but i want hOstT servEr termux?????
HELP ME! vPs expire sO i hOsT para gratiS termux. HELP PLASESE!

**Comment by MoanHawks** [comment]
G0 r00t y0u ph0n3 th3n run s3rv3r 0n t3rmux

**Comment by raiterjaki** [comment]
> G0 r00t y0u ph0n3 th3n run s3rv3r 0n t3rmux l4 s0h4i

didn't work u indog

**Comment by MoanHawks** [comment]
> > G0 r00t y0u ph0n3 th3n run s3rv3r 0n t3rmux l4 s0h4i
> 
> didn't work u indog

only for sohai 人 no work

**Comment by GuckTubeYT** [comment]
> > G0 r00t y0u ph0n3 th3n run s3rv3r 0n t3rmux l4 s0h4i
> 
> didn't work u indog

wtf

**Comment by GuckTubeYT** [comment]
is insane to convert exe to apk

**Comment by herothedev** [comment]
it works, if you ROOT.

**Comment by MoanHawks** [comment]
talking with shit man 😂

**Comment by GuckTubeYT** [comment]
> it works, if you ROOT.

Lol no bro, root just edit hosts without virtual host

**Comment by MoanHawks** [comment]
@GuckTubeYT wow how stupid you are

**Comment by GuckTubeYT** [comment]
> @GuckTubeYT wow how stupid you are wait i think i am stupid how to use ./a.out in termux :/ ???
Ohhhhh

**Comment by GuckTubeYT** [comment]
sorry, I did not read further

**Comment by GuckTubeYT** [comment]
You can use Userland or Termux

**Comment by GrowtopiaNoobs** [comment]
Please stop trolling
If anyone means this really, then you can try it using wine, but best way is to compile this server for android
