### ISSUE TITLE
[BUG] UPDATE REQUIRED ERROR

### ISSUE THREAD

**Issue by LinkTopia2** [GrowtopiaNoobs/GrowtopiaServer#1233]
Please tell me what I'm doing wrong - My discord is LinkTopia#6262
![image](https://user-images.githubusercontent.com/60845093/76144812-93d32e00-608c-11ea-9605-76da4147b597.png)

**Comment by MoanHawks** [comment]
????????? Stupid?????

**Comment by LinkTopia2** [comment]
> ????????? Stupid?????

Not expirienced enough.Tell me what should I do

**Comment by MoanHawks** [comment]
string gameversion = "3.021";

**Comment by sadMotion** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/issues/1232 
help pls

**Comment by MoanHawks** [comment]
@sadMotion go fix ur self la you sohai

**Comment by LinkTopia2** [comment]
> string gameversion = "3.021";

Tried, still shows that update is needed
![image](https://user-images.githubusercontent.com/60845093/76147826-e9b5cf00-60a8-11ea-962d-4ef9b63843c8.png)

**Comment by atomiclucky** [comment]
Check the if statement, not just change the string

**Comment by MoanHawks** [comment]
using leak cpp like stupid

**Comment by icantspellmyname** [comment]
😳

**Comment by LinkTopia2** [comment]
> "I know how to code, For a fact I can make my own game, But that's too time consuming. 2nd of all, i use my own CPP, my friend gave it to me as he is quitting GTPS in general" -Linktopia
This is a brand new CPP for fucks sake i stopped using the last one

**Comment by icantspellmyname** [comment]
> 
> 
> > "I know how to code, For a fact I can make my own game, But that's too time consuming. 2nd of all, i use my own CPP, my friend gave it to me as he is quitting GTPS in general" -Linktopia
> > This is a brand new CPP for fucks sake i stopped using the last one

"I know how to code, For a fact I can make my own game".
then why cant you just fix this simple problem

**Comment by LinkTopia2** [comment]
> > > "I know how to code, For a fact I can make my own game, But that's too time consuming. 2nd of all, i use my own CPP, my friend gave it to me as he is quitting GTPS in general" -Linktopia
> > > This is a brand new CPP for fucks sake i stopped using the last one
> 
> "I know how to code, For a fact I can make my own game".
> then why cant you just fix this simple problem

zzzzzzzzzzzzzzz
I said I'm new to GTPS coding, i'm not used to codes like this pls learn to read

**Comment by icantspellmyname** [comment]
> 
> 
> > > > "I know how to code, For a fact I can make my own game, But that's too time consuming. 2nd of all, i use my own CPP, my friend gave it to me as he is quitting GTPS in general" -Linktopia
> > > > This is a brand new CPP for fucks sake i stopped using the last one
> > 
> > 
> > "I know how to code, For a fact I can make my own game".
> > then why cant you just fix this simple problem
> 
> zzzzzzzzzzzzzzz
> I said I'm new to GTPS coding, i'm not used to codes like this pls learn to read

but its a simple fix 😔

**Comment by LinkTopia2** [comment]
> > > > > "I know how to code, For a fact I can make my own game, But that's too time consuming. 2nd of all, i use my own CPP, my friend gave it to me as he is quitting GTPS in general" -Linktopia
> > > > > This is a brand new CPP for fucks sake i stopped using the last one
> > > 
> > > 
> > > "I know how to code, For a fact I can make my own game".
> > > then why cant you just fix this simple problem
> > 
> > 
> > zzzzzzzzzzzzzzz
> > I said I'm new to GTPS coding, i'm not used to codes like this pls learn to read
> 
> but its a simple fix

If its so simple then help, rather then keeping posting shit commencts that make no sense

**Comment by MoanHawks** [comment]
@LinkTopia2 pls stop coding c++

**Comment by icantspellmyname** [comment]
> 
> 
> @LinkTopia2 pls stop coding c++

agreed




> 
> 
> > > > > > "I know how to code, For a fact I can make my own game, But that's too time consuming. 2nd of all, i use my own CPP, my friend gave it to me as he is quitting GTPS in general" -Linktopia
> > > > > > This is a brand new CPP for fucks sake i stopped using the last one
> > > > 
> > > > 
> > > > "I know how to code, For a fact I can make my own game".
> > > > then why cant you just fix this simple problem
> > > 
> > > 
> > > zzzzzzzzzzzzzzz
> > > I said I'm new to GTPS coding, i'm not used to codes like this pls learn to read
> > 
> > 
> > but its a simple fix
> 
> If its so simple then help, rather then keeping posting shit commencts that make no sense

ok what gt version are you using please confirm it. did you put it after login packet is sent or not
😳

**Comment by LinkTopia2** [comment]
> > @LinkTopia2 pls stop coding c++
> 
> agreed
> 
> > > > > > > "I know how to code, For a fact I can make my own game, But that's too time consuming. 2nd of all, i use my own CPP, my friend gave it to me as he is quitting GTPS in general" -Linktopia
> > > > > > > This is a brand new CPP for fucks sake i stopped using the last one
> > > > > 
> > > > > 
> > > > > "I know how to code, For a fact I can make my own game".
> > > > > then why cant you just fix this simple problem
> > > > 
> > > > 
> > > > zzzzzzzzzzzzzzz
> > > > I said I'm new to GTPS coding, i'm not used to codes like this pls learn to read
> > > 
> > > 
> > > but its a simple fix
> > 
> > 
> > If its so simple then help, rather then keeping posting shit commencts that make no sense
> 
> ok what gt version are you using please confirm it. did you put it after login packet is sent or not

I am using 3.021 but when i try to log in it shows that i need to update it to 2.997

**Comment by icantspellmyname** [comment]
> 
> 
> > > @LinkTopia2 pls stop coding c++
> > 
> > 
> > agreed
> > > > > > > > "I know how to code, For a fact I can make my own game, But that's too time consuming. 2nd of all, i use my own CPP, my friend gave it to me as he is quitting GTPS in general" -Linktopia
> > > > > > > > This is a brand new CPP for fucks sake i stopped using the last one
> > > > > > 
> > > > > > 
> > > > > > "I know how to code, For a fact I can make my own game".
> > > > > > then why cant you just fix this simple problem
> > > > > 
> > > > > 
> > > > > zzzzzzzzzzzzzzz
> > > > > I said I'm new to GTPS coding, i'm not used to codes like this pls learn to read
> > > > 
> > > > 
> > > > but its a simple fix
> > > 
> > > 
> > > If its so simple then help, rather then keeping posting shit commencts that make no sense
> > 
> > 
> > ok what gt version are you using please confirm it. did you put it after login packet is sent or not
> 
> I am using 3.021 but when i try to log in it shows that i need to update it to 2.997

but in the pic you showed you changing the text that you need to update it to 3.021
why dont you find 2.997 🤡

**Comment by LinkTopia2** [comment]
> > > > @LinkTopia2 pls stop coding c++
> > > 
> > > 
> > > agreed
> > > > > > > > > "I know how to code, For a fact I can make my own game, But that's too time consuming. 2nd of all, i use my own CPP, my friend gave it to me as he is quitting GTPS in general" -Linktopia
> > > > > > > > > This is a brand new CPP for fucks sake i stopped using the last one
> > > > > > > 
> > > > > > > 
> > > > > > > "I know how to code, For a fact I can make my own game".
> > > > > > > then why cant you just fix this simple problem
> > > > > > 
> > > > > > 
> > > > > > zzzzzzzzzzzzzzz
> > > > > > I said I'm new to GTPS coding, i'm not used to codes like this pls learn to read
> > > > > 
> > > > > 
> > > > > but its a simple fix
> > > > 
> > > > 
> > > > If its so simple then help, rather then keeping posting shit commencts that make no sense
> > > 
> > > 
> > > ok what gt version are you using please confirm it. did you put it after login packet is sent or not
> > 
> > 
> > I am using 3.021 but when i try to log in it shows that i need to update it to 2.997
> 
> but in the pic you showed you changing the text that you need to update it to 3.021
> why dont you find 2.997

Thats why i posted this cause I cant find 2.997 in the CPP

**Comment by MoanHawks** [comment]
> > > > > @LinkTopia2 pls stop coding c++
> > > > 
> > > > 
> > > > agreed
> > > > > > > > > > "I know how to code, For a fact I can make my own game, But that's too time consuming. 2nd of all, i use my own CPP, my friend gave it to me as he is quitting GTPS in general" -Linktopia
> > > > > > > > > > This is a brand new CPP for fucks sake i stopped using the last one
> > > > > > > > 
> > > > > > > > 
> > > > > > > > "I know how to code, For a fact I can make my own game".
> > > > > > > > then why cant you just fix this simple problem
> > > > > > > 
> > > > > > > 
> > > > > > > zzzzzzzzzzzzzzz
> > > > > > > I said I'm new to GTPS coding, i'm not used to codes like this pls learn to read
> > > > > > 
> > > > > > 
> > > > > > but its a simple fix
> > > > > 
> > > > > 
> > > > > If its so simple then help, rather then keeping posting shit commencts that make no sense
> > > > 
> > > > 
> > > > ok what gt version are you using please confirm it. did you put it after login packet is sent or not
> > > 
> > > 
> > > I am using 3.021 but when i try to log in it shows that i need to update it to 2.997
> > 
> > 
> > but in the pic you showed you changing the text that you need to update it to 3.021
> > why dont you find 2.997
> 
> Thats why i posted this cause I cant find 2.997 in the CPP

You need to knowledge about  c++

**Comment by LinkTopia2** [comment]
> > > > > > @LinkTopia2 pls stop coding c++
> > > > > 
> > > > > 
> > > > > agreed
> > > > > > > > > > > "I know how to code, For a fact I can make my own game, But that's too time consuming. 2nd of all, i use my own CPP, my friend gave it to me as he is quitting GTPS in general" -Linktopia
> > > > > > > > > > > This is a brand new CPP for fucks sake i stopped using the last one
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > "I know how to code, For a fact I can make my own game".
> > > > > > > > > then why cant you just fix this simple problem
> > > > > > > > 
> > > > > > > > 
> > > > > > > > zzzzzzzzzzzzzzz
> > > > > > > > I said I'm new to GTPS coding, i'm not used to codes like this pls learn to read
> > > > > > > 
> > > > > > > 
> > > > > > > but its a simple fix
> > > > > > 
> > > > > > 
> > > > > > If its so simple then help, rather then keeping posting shit commencts that make no sense
> > > > > 
> > > > > 
> > > > > ok what gt version are you using please confirm it. did you put it after login packet is sent or not
> > > > 
> > > > 
> > > > I am using 3.021 but when i try to log in it shows that i need to update it to 2.997
> > > 
> > > 
> > > but in the pic you showed you changing the text that you need to update it to 3.021
> > > why dont you find 2.997
> > 
> > 
> > Thats why i posted this cause I cant find 2.997 in the CPP
> 
> You need to knowledge abo

**Comment by LinkTopia2** [comment]
> > > > > > @LinkTopia2 pls stop coding c++
> > > > > 
> > > > > 
> > > > > agreed
> > > > > > > > > > > "I know how to code, For a fact I can make my own game, But that's too time consuming. 2nd of all, i use my own CPP, my friend gave it to me as he is quitting GTPS in general" -Linktopia
> > > > > > > > > > > This is a brand new CPP for fucks sake i stopped using the last one
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > "I know how to code, For a fact I can make my own game".
> > > > > > > > > then why cant you just fix this simple problem
> > > > > > > > 
> > > > > > > > 
> > > > > > > > zzzzzzzzzzzzzzz
> > > > > > > > I said I'm new to GTPS coding, i'm not used to codes like this pls learn to read
> > > > > > > 
> > > > > > > 
> > > > > > > but its a simple fix
> > > > > > 
> > > > > > 
> > > > > > If its so simple then help, rather then keeping posting shit commencts that make no sense
> > > > > 
> > > > > 
> > > > > ok what gt version are you using please confirm it. did you put it after login packet is sent or not
> > > > 
> > > > 
> > > > I am using 3.021 but when i try to log in it shows that i need to update it to 2.997
> > > 
> > > 
> > > but in the pic you showed you changing the text that you need to update it to 3.021
> > > why dont you find 2.997
> > 
> > 
> > Thats why i posted this cause I cant find 2.997 in the CPP
> 
> You need to knowledge about c++

bruh, just stop with this and if you cant help then dont even bother reading this thread

**Comment by MoanHawks** [comment]
I already help you 

string gameversion = "3.021";
 
here

**Comment by LinkTopia2** [comment]
> I already help you
> 
> string gameversion = "3.021";
> 
> here

OMGGGGG i tried it and it didnt work for fucks sake pls swipe up and read

**Comment by MoanHawks** [comment]
That why me say you need to knowledge about c++ you dumb

**Comment by LinkTopia2** [comment]
> That why me say you need to knowledge about c++ you dumb

just shut the fuck up and leave this thread if you dont have anything good to say

**Comment by LinkTopia2** [comment]
> That why me say you need to knowledge about c++ you dumb

you do this type of shit in every thread - Comment how stupid people are and so on

**Comment by MoanHawks** [comment]
???????? you using leak cpp?????

**Comment by LinkTopia2** [comment]
> ???????? you using leak cpp?????

for fucks sake so what if i do?

**Comment by LinkTopia2** [comment]
> ???????? you using leak cpp?????

Many people use leaked cpps and then recode the cpps as their own

**Comment by MoanHawks** [comment]
Oh copy paste nice jobs

**Comment by LinkTopia2** [comment]
> Oh copy paste nice jobs

zz pls learn english

**Comment by MoanHawks** [comment]
> > Oh copy paste nice jobs
> 
> zz pls learn english

????? True or not you just copy the code paste to you cpp????

**Comment by LinkTopia2** [comment]
> > > Oh copy paste nice jobs
> > 
> > 
> > zz pls learn english
> 
> ????? True or not you just copy the code paste to you cpp????
> 
> Yes true

I didnt copy it -_-

**Comment by MoanHawks** [comment]
Omg then why use people cpp?????

**Comment by icantspellmyname** [comment]
> 
> 
> > Oh copy paste nice jobs
> 
> zz pls learn english

"This is a brand new CPP for fucks sake i stopped using the last one"
"I didnt copy it -_-"
if you use a brand new "cpp" that u claimed didnt copy then why dont you know where do you put game version checking

**Comment by LinkTopia2** [comment]
> Omg then why use people cpp?????

cuz I want to run my server for a little bit and then make my own but this error is in the way

**Comment by icantspellmyname** [comment]
> 
> 
> > Omg then why use people cpp?????
> 
> cuz I want to run my server for a little bit and then make my own but this error is in the way

"I know how to code, For a fact I can make my own game, But that's too time consuming. 2nd of all, i use my own CPP, my friend gave it to me as he is quitting GTPS in general"
"I didnt copy it -_-"

**Comment by Bexpg** [comment]
Just delete line uptade required and done lol

**Comment by LinkTopia2** [comment]
> > > Omg then why use people cpp?????
> > 
> > 
> > cuz I want to run my server for a little bit and then make my own but this error is in the way
> 
> "I know how to code, For a fact I can make my own game, But that's too time consuming. 2nd of all, i use my own CPP, my friend gave it to me as he is quitting GTPS in general"
> "I didnt copy it -_-"

Pls swipe up and read

**Comment by LinkTopia2** [comment]
> Just delete line update required and done lol

you sure?

**Comment by icantspellmyname** [comment]
> 
> 
> > Just delete line update required and done lol
> 
> you sure?

but you lied saying "i use my own 'cpp'". why do i need to swipe up?

**Comment by LinkTopia2** [comment]
> > > Just delete line update required and done lol
> > 
> > 
> > you sure?
> 
> but you lied saying "i use my own 'cpp'". why do i need to swipe up?

I used the cpp that my friend gave it to me and said I can have it as my own cause he was quitting GTPS but the CPP had an error and my friend was too lazy to fix it smh so I switched

**Comment by LinkTopia2** [comment]
> "Pls swipe up and read"
> 
> but you lied saying "i use my own 'cpp'". why do i need to swipe up?

And why r u so mad that I use leaked CPPs?

**Comment by MoanHawks** [comment]
![IMG_20200308_161902](https://user-images.githubusercontent.com/52075701/76159177-aa46bb80-6158-11ea-8588-3dd2cfed2aea.jpg)

**Comment by icantspellmyname** [comment]
> 
> 
> > > > Just delete line update required and done lol
> > > 
> > > 
> > > you sure?
> > 
> > 
> > but you lied saying "i use my own 'cpp'". why do i need to swipe up?
> 
> I used the cpp that my friend gave it to me and said I can have it as my own cause he was quitting GTPS but the CPP had an error and my friend was too lazy to fix it smh so I switched

BUT WHY ARE YOU SAYING "UPDATE REQUIRED ERROR"??????? 
YOU SWITCHED BUT STILL HAVE THE "ERROR"?
ALSO I SEE A FUCKING STOLEN CODE THERE

**Comment by MoanHawks** [comment]
We got a memes 
![IMG_20200308_161902](https://user-images.githubusercontent.com/52075701/76159189-c0ed1280-6158-11ea-9cec-70e9a699690e.jpg)

**Comment by LinkTopia2** [comment]
> Just delete line update required and done lol



> > > > > Just delete line update required and done lol
> > > > 
> > > > 
> > > > you sure?
> > > 
> > > 
> > > but you lied saying "i use my own 'cpp'". why do i need to swipe up?
> > 
> > 
> > I used the cpp that my friend gave it to me and said I can have it as my own cause he was quitting GTPS but the CPP had an error and my friend was too lazy to fix it smh so I switched
> 
> BUT WHY ARE YOU SAYING "UPDATE REQUIRED ERROR"???????
> YOU SWITCHED BUT STILL HAVE THE "ERROR"?
> ALSO I SEE A FUCKING STOLEN CODE THERE

bruhh,l the last cpp i used had a diffrient error zzzzzzzzzzzzzzz

**Comment by LinkTopia2** [comment]
> > > > > Just delete line update required and done lol
> > > > 
> > > > 
> > > > you sure?
> > > 
> > > 
> > > but you lied saying "i use my own 'cpp'". why do i need to swipe up?
> > 
> > 
> > I used the cpp that my friend gave it to me and said I can have it as my own cause he was quitting GTPS but the CPP had an error and my friend was too lazy to fix it smh so I switched
> 
> BUT WHY ARE YOU SAYING "UPDATE REQUIRED ERROR"???????
> YOU SWITCHED BUT STILL HAVE THE "ERROR"?
> ALSO I SEE A FUCKING STOLEN CODE THERE

damn dawg u hella mad xDDDDDDD

**Comment by icantspellmyname** [comment]
> 
> 
> > > > > > Just delete line update required and done lol
> > > > > 
> > > > > 
> > > > > you sure?
> > > > 
> > > > 
> > > > but you lied saying "i use my own 'cpp'". why do i need to swipe up?
> > > 
> > > 
> > > I used the cpp that my friend gave it to me and said I can have it as my own cause he was quitting GTPS but the CPP had an error and my friend was too lazy to fix it smh so I switched
> > 
> > 
> > BUT WHY ARE YOU SAYING "UPDATE REQUIRED ERROR"???????
> > YOU SWITCHED BUT STILL HAVE THE "ERROR"?
> > ALSO I SEE A FUCKING STOLEN CODE THERE
> 
> damn dawg u hella mad xDDDDDDD

yes im mad because i see tons private server using my friend's hard work

**Comment by LinkTopia2** [comment]
> > > > > Just delete line update required and done lol
> > > > 
> > > > 
> > > > you sure?
> > > 
> > > 
> > > but you lied saying "i use my own 'cpp'". why do i need to swipe up?
> > 
> > 
> > I used the cpp that my friend gave it to me and said I can have it as my own cause he was quitting GTPS but the CPP had an error and my friend was too lazy to fix it smh so I switched
> 
> BUT WHY ARE YOU SAYING "UPDATE REQUIRED ERROR"???????
> YOU SWITCHED BUT STILL HAVE THE "ERROR"?
> ALSO I SEE A FUCKING STOLEN CODE THERE

zz ur friend, Im using a super old cpp that was made a long time ago

**Comment by MoanHawks** [comment]
@LinkTopia2 dark cpp??????

**Comment by LinkTopia2** [comment]
> > > > > > > Just delete line update required and done lol
> > > > > > 
> > > > > > 
> > > > > > you sure?
> > > > > 
> > > > > 
> > > > > but you lied saying "i use my own 'cpp'". why do i need to swipe up?
> > > > 
> > > > 
> > > > I used the cpp that my friend gave it to me and said I can have it as my own cause he was quitting GTPS but the CPP had an error and my friend was too lazy to fix it smh so I switched
> > > 
> > > 
> > > BUT WHY ARE YOU SAYING "UPDATE REQUIRED ERROR"???????
> > > YOU SWITCHED BUT STILL HAVE THE "ERROR"?
> > > ALSO I SEE A FUCKING STOLEN CODE THERE
> > 
> > 
> > damn dawg u hella mad xDDDDDDD
> 
> yes im mad because i see tons private server using my friend's hard work

who

> @LinkTopia2 dark cpp??????

nop

**Comment by MoanHawks** [comment]
old cpp

**Comment by LinkTopia2** [comment]
> old cpp. Wait playingo cpp??? :/

Nop :D i cant tell you cause that bastard will scream his lungs out again, that im using a leaked cpp

**Comment by MoanHawks** [comment]
and you still copy paste right?

**Comment by icantspellmyname** [comment]
😳

**Comment by LinkTopia2** [comment]
> and you still copy paste right?

![image](https://user-images.githubusercontent.com/60845093/76159303-ac445680-6127-11ea-98df-7e8bb39dc9d2.png)
one dude said I should delete the whole update required thing and the error will be gone

**Comment by LinkTopia2** [comment]
![image](https://user-images.githubusercontent.com/60845093/76159310-cc741580-6127-11ea-9434-c4f76c08ca7b.png)
One dude said I should delete the whole update required and that would fix the error but idk

**Comment by NotDark** [comment]
> I am using 3.021 but when i try to log in it shows that i need to update it to 2.997

did u even rebuild after u change to 3.021

**Comment by LinkTopia2** [comment]
> > I am using 3.021 but when i try to log in it shows that i need to update it to 2.997
> 
> did u even rebuild after u change to 3.021

You mean save? Yes I saved the CPP, but Idk what rebuild means specificlly, tell me

**Comment by arshizx** [comment]
Click Build Then Click Rebuild Paste the enet server test.exe to ur server folder

**Comment by LinkTopia2** [comment]
> Click Build Then Click Rebuild Paste the enet server test.exe to ur server folder

Give me your discord

**Comment by MoanHawks** [comment]
![FB_IMG_1582039302089](https://user-images.githubusercontent.com/52075701/76160764-e03f6c00-6167-11ea-976a-0418012c5a27.png)

**Comment by LinkTopia2** [comment]
God, why you put me on a planet where people complain about shit and can't help?

**Comment by InjectionZ** [comment]
W0w prossssss, cpp != source :')

**Comment by noobsteak** [comment]
hmm maybe try to actually build the source? wow me big brain you're welcome ;)

**Comment by LustsPS** [comment]
Imagine a "gAmE dEvElOpEr" don't know the C++ language 😂🤭

**Comment by JadlionHD** [comment]
> Imagine a "gAmE dEvElOpEr" don't know the C++ language 🤭

Lol

**Comment by MoanHawks** [comment]
Imagine make a game using push button 😳

**Comment by LustsPS** [comment]
How a "gAmE dEvElOpEr" don't know the C++ language? I thought C++ is the basic things that you need to learn before learning other languages 🤔

**Comment by MoanHawks** [comment]
Imagine Make a game using visual basic 😳

**Comment by Valkr1e** [comment]
@LinkTopia2 Bro can you just stop making a GTPS. And go learn about C++ Language.

You dont even know how to fix this simple problem

**Comment by JadlionHD** [comment]
Just close this issue already @LinkTopia2 , most of those people are helping you, but you are literally stubborn that because you didnt know how to fix that simple error.



> @LinkTopia2 Bro can you just stop making a GTPS. And go learn about C++ Language.
> 
> You dont even know how to fix this simple problem

like valkr1e said, if you dont know about c++, just dont make an gtps

**Comment by JadlionHD** [comment]
![1](https://user-images.githubusercontent.com/48410066/76919423-70fe1080-68fb-11ea-8b79-7a6d7847c670.PNG)
i see your problem there, go change it into latest version and close this issue.

**Comment by LinkTopia2** [comment]
> ![1](https://user-images.githubusercontent.com/48410066/76919423-70fe1080-68fb-11ea-8b79-7a6d7847c670.PNG)
> i see your problem there, go change it into latest version and close this issue.

Doesn't work, tried it
