### ISSUE TITLE
[QUESTION/REQUEST] Is there no other way to get CoreData other than using an items.dat to CoreData builder?

### ISSUE THREAD

**Issue by noobsteak** [GrowtopiaNoobs/GrowtopiaServer#1235]
I'm looking for the latest CoreData.

**Comment by bykoi** [comment]
the coredata builder which is on my github repo works, but you have to use decompressed items.dat (use zlib)

**Comment by noobsteak** [comment]
I've already tried using it and adding changes based off it. It still doesn't work.

**Comment by NotDark** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/master/enet%20server%20test/enet%20server%20test.cpp#L1091 replace to items.dat decoder https://github.com/GrowtopiaNoobs/Growtopia_ItemsDecoder

**Comment by D3c0d33** [comment]
> I've already tried using it and adding changes based off it. It still doesn't work.

It's still working fine for me.
