### ISSUE TITLE
about index_of_dropped_item on official server?

### ISSUE THREAD

**Issue by rwdkor** [GrowtopiaNoobs/GrowtopiaServer#1237]
about index_of_dropped_item(**uid**) on official server?

when any client pick up the item, he sends packet like below
`itemactivateobject(indexofdroppeditem, (float)item_pos_x * 32.0, (float)item_pos_y * 32.0);
movement::state((float)item_pos_x * 32.0, (float)item_pos_x * 32.0, 16400+movement, -1, -1);`

i captured all received packets from official server and could find index_of_dropped_item from `*(int*)ITEM_CHANGE_OBJECT` + 8` and not every index comes in. (like 0, 1, 3, 4, 6 ... / missing some in middle)

am i doing something wrong?

**Comment by iProgramMC** [comment]
yes, you may need to extend the world packet and add some 0s at the end so that the indexes are not garbage data

**Comment by rwdkor** [comment]
> yes, you may need to extend the world packet and add some 0s at the end so that the indexes are not garbage data

thanks! i found init uid packet from extended part of world packet :)
