### ISSUE TITLE
CLOSE THIS REPOSITORY PLEASE

### ISSUE THREAD

**Issue by loanselot** [GrowtopiaNoobs/GrowtopiaServer#1239]
END THIS CANCER @GrowtopiaNoobs END THIS CANCER @GrowtopiaNoobs 
YOU DONT FUCKING HELP TO ANYONE UNDERSTAND CODING JUST CLOSE THIS BS ALREADY 
PLEASEE

**Comment by Bexpg** [comment]
Retard

**Comment by loanselot** [comment]
fuck off cockroach

**Comment by DEERUX** [comment]
@Bexpg shut the fuck up

**Comment by Bexpg** [comment]
Ban this  retard from this repo @growtopiapro

**Comment by Bexpg** [comment]
Go learn code from google dont ask growtopiapro for help you his not ur dad or teacher retarded kids

**Comment by DEERUX** [comment]
just shut up loser

**Comment by Bexpg** [comment]
Loool  pr0hx0r sp4king

**Comment by GuckTubeYT** [comment]
> END THIS CANCER @GrowtopiaNoobs END THIS CANCER @GrowtopiaNoobs
> YOU DONT FUCKING HELP TO ANYONE UNDERSTAND CODING JUST CLOSE THIS BS ALREADY
> PLEASEE

bruh retard kid dont know making GTPS Server

**Comment by DrOreo002** [comment]
> > END THIS CANCER @GrowtopiaNoobs END THIS CANCER @GrowtopiaNoobs
> > YOU DONT FUCKING HELP TO ANYONE UNDERSTAND CODING JUST CLOSE THIS BS ALREADY
> > PLEASEE
> 
> bruh retard kid dont know making GTPS Server

get ur self a mirror

**Comment by MoanHawks** [comment]
> END THIS CANCER @GrowtopiaNoobs END THIS CANCER @GrowtopiaNoobs
> YOU DONT FUCKING HELP TO ANYONE UNDERSTAND CODING JUST CLOSE THIS BS ALREADY
> PLEASEE

True 
please @GrowtopiaNoobs just close this bs

**Comment by cmdocmd** [comment]
First time i agree with you @GrowtopiaNoobs you should close this for real

**Comment by DEERUX** [comment]
stop the war. close the issues tab! - a poem.

**Comment by Bexpg** [comment]
@DEERUX  "a retard" -poem`

**Comment by DEERUX** [comment]
@Bexpg more like u lol

**Comment by arshizx** [comment]
> @Bexpg more like u lol

he doesn't accept the fact, that he is retard lol

**Comment by Bexpg** [comment]
@arshizx  ye xddddddddddddddddddddddd  u doesnt accept that u kids who want be famaous

**Comment by arshizx** [comment]
> 
> 
> @arshizx ye xddddddddddddddddddddddd u doesnt accept that u kids who want be famaous

you mean yourself is kids and who want be fam0us lmao xDDDDDDDDDD

**Comment by DEERUX** [comment]
vote poll:
bexpg is < 14
bexpg is > 16
my vote: < 14

**Comment by Bexpg** [comment]
vote poll:
Pr0hx0rgeDeerux is < 12
Pr0hx0rgeDeerux is > 10
my vote: < -9

**Comment by raiterjaki** [comment]
> vote poll:
> Pr0hx0rgeDeerux is < 12
> Pr0hx0rgeDeerux is > 10
> my vote: < -9

Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by xXAbood** [comment]
> vote poll:
> Pr0hx0rgeDeerux is < 12
> Pr0hx0rgeDeerux is > 10
> my vote: < -9

Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by Bexpg** [comment]
> coding

Hello im from syria turkish soldiers kill my family because they are terrorist!! And im hating from turkey

**Comment by GrowtopiaNoobs** [comment]
This repo won't be closed
To help a bit you can start to post usefull answers and report trolling answers
