### ISSUE TITLE
beta server bug

### ISSUE THREAD

**Issue by Bexpg** [GrowtopiaNoobs/GrowtopiaServer#1241]
I logged beta server 1-2 days ago in my vps and i forget too close growtopia now beta server cant accesible and i get this error how i can fix this error and can login into beta server
![20200313_184116](https://user-images.githubusercontent.com/61095632/76636607-67bb1f80-655a-11ea-839b-9af43018b641.jpg)

**Comment by Bexpg** [comment]
What this error mean?

**Comment by Bexpg** [comment]
When i search logon packet text 33 in google , google showed me wireshark videos

**Comment by xXAbood** [comment]
can u disappear from existence u dumb mother fucker oh my god just go fucking die u little cunt

**Comment by MoanHawks** [comment]
Idiot not GrowtopiaServer issues

**Comment by noobes1337** [comment]
retard

**Comment by Bexpg** [comment]
i just asked questions why so many retard in here. wtf...

**Comment by Bexpg** [comment]
@MoanHawks  u idiot niggerrrrrrrrrrrrrrrrr go fix ur english wtf is ``idiot not growtopiaserver``

**Comment by Bexpg** [comment]
@noobes1337 u retard nob

**Comment by Bexpg** [comment]
@xXAbood  stfu nigaaa  we kill syria soldier ahhahahaha noobssssssssss

**Comment by MoanHawks** [comment]
Don't have brain?????

**Comment by Bexpg** [comment]
@MoanHawks  u dont have brain if u cant speak english go use google translate

**Comment by MoanHawks** [comment]
![IMG_20200314_160820](https://user-images.githubusercontent.com/52075701/76677849-0d7b9680-660e-11ea-8d77-df0486d6e50e.jpg)

**Comment by DEERUX** [comment]
this is the gt server issues tab, go ask this somewhere else if u are dumb enough to join beta, cuz I have achieved it already with ease.

**Comment by Bexpg** [comment]
@deerux no one askedddddd stfu

**Comment by DEERUX** [comment]
cerebralparese

**Comment by xXAbood** [comment]
BEX LITERALLY NO ONE WANTS U IN THIS LIFE OH MY FUCKING GOD JUST KILL URSELF ALREADY U LITERAL SADDISTIC COCK FAGGOT

**Comment by xXAbood** [comment]
turkhackteam dude on god allah islam power strong dude fuck ur mom u literal fag get out literally no one wants u even ur family doesnt want u

**Comment by Bexpg** [comment]
i fixed error.;
