### ISSUE TITLE
How to get gt packets

### ISSUE THREAD

**Issue by Bexpg** [GrowtopiaNoobs/GrowtopiaServer#1243]
How to get gt packets

**Comment by Bexpg** [comment]
i know but what best programs for it

**Comment by DrOreo002** [comment]
ama's enetproxy https://github.com/ama6nen/enetproxy/tree/master/proxy

**Comment by Bexpg** [comment]
I dont think amas enetproxy best for it

**Comment by MoanHawks** [comment]
> I dont think amas enetproxy best for it

Then make you self idiot

**Comment by Bexpg** [comment]
@MoanHawks  ``then make you self idiot`` fix ur grammar first retard

**Comment by Bexpg** [comment]
indog no one asked you  niger

**Comment by MoanHawks** [comment]
> indog no one asked you niger

oh I am Indo? 😳

**Comment by DrOreo002** [comment]
bacot lo semua anjing

**Comment by GuckTubeYT** [comment]
> 
> 
> bacot lo semua anjing

nah gitu kek dari tadi keluarin bahasa kesayangan kita :V

**Comment by Bexpg** [comment]
apa kontol anjir memek goblok

**Comment by raiterjaki** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by Bexpg** [comment]
@retardjaki u didnt see tittle? i ask questions this gt private server issue why u commenting ur other shit memes retard nobs

**Comment by Bexpg** [comment]
if you want war  dm me in discord last time i call you in discord and you  scared open ur voice forget ???! @retardjaki
