### ISSUE TITLE
GROWTOPIA DEVELOPER server

### ISSUE THREAD

**Issue by Bexpg** [GrowtopiaNoobs/GrowtopiaServer#1244]
guys so yeah i found waY To  login growtopia developer server i need one program thats can see gt packets

**Comment by MoanHawks** [comment]
![IMG_20200311_053620](https://user-images.githubusercontent.com/52075701/76681246-05325400-662c-11ea-9d6e-1f4d314ff9a4.jpg)

**Comment by Bexpg** [comment]
yes im coding c# c++ other people too but they cant found developer server but im found.
