### ISSUE TITLE
Items.dat

### ISSUE THREAD

**Issue by Bexpg** [GrowtopiaNoobs/GrowtopiaServer#1245]
How to make new items.dat work when im adding new items.dat gt auto closing

**Comment by DEERUX** [comment]
"coder" > if u would have any knowledge of anything you would know it is zlib compressed due to the 78 9C default zlib compression header in the file itself and perhaps with pure logic as file size shrunk??
you just dont know about anything, and I bet you would still beg for code and ask how to decompress.
>now I bet u will beg for code again on „how to decompress pls“ cuz u dont know how to code a zlib decompression lmao

**Comment by Bexpg** [comment]
Im no beg but i want to know how give me more info

**Comment by Bexpg** [comment]
Stop shit talk sooo what i do with zlib i added zlib code in python now i what do

**Comment by Bexpg** [comment]
import zlib
import os

Retarddr = open('gtbp.dat', 'rb')
decompressed_data = zlib.decompress(f.read())

Retarddr = None
if os.path.exists('u-items.dat'):
    Retarddr = open('u-items.dat', 'r+')
else:
    Retarddr = open('u-items.dat','w')

Retarddr = open('u-items.dat', 'wb')
Retarddr.write(decompressed_data)
Retarddr.flush()
Retarddr.close()

**Comment by xXAbood** [comment]
can u stop trying to be as an "active user" as if ur acting like ur pro just dont ever exist dumbass

**Comment by Bexpg** [comment]
> can u stop trying to be as an "active user" as if ur acting like ur pro just dont ever exist dumbass

Im dont know and asking what wrong niger its gt privTe server issues i can ask everything about g tpriv server

**Comment by DEERUX** [comment]
yeah see? why are u even asking if u got some code?
also .flush()
.close()
lmao unnecessary, close flushes already.

**Comment by Bexpg** [comment]
@deerux i need drag items dat to python or what

**Comment by DEERUX** [comment]
the fact that u now dont know what to do confuses me, this can only mean u pasted the code otherwise u would perfectly know what to do with the items.dat file

**Comment by Bexpg** [comment]
'I dont know want help me or no

**Comment by ama6nen** [comment]
> "coder" > if u would have any knowledge of anything you would know it is zlib compressed due to the 78 9C default zlib compression header in the file itself and perhaps with pure logic as file size shrunk??
> you just dont know about anything, and I bet you would still beg for code and ask how to decompress.
> 
> > now I bet u will beg for code again on „how to decompress pls“ cuz u dont know how to code a zlib decompression lmao

yeah all programmers know from memory that 78 9C bytes is zlib compression header because you need to know it am i right
spoiler: not related to coding at all

**Comment by Bexpg** [comment]
im found the way closing.......
