### ISSUE TITLE
How to long place/punch

### ISSUE THREAD

**Issue by Bexpg** [GrowtopiaNoobs/GrowtopiaServer#1246]
How to long place/punch i can do copy paste but i dont want can anyone say me how to do long punch/place

**Comment by noobsteak** [comment]
ok so u need to doing find in code and then cope and pasta and u is can long placing and punchings.
i trying best to helped u

**Comment by xXAbood** [comment]
me when state change

**Comment by iProgramMC** [comment]
sendState contains some info about that

**Comment by Bexpg** [comment]
@iProgramMC  thanks pro
