### ISSUE TITLE
[BUG] "action|refresh_item_data"

### ISSUE THREAD

**Issue by noobsteak** [GrowtopiaNoobs/GrowtopiaServer#1247]
For some reason "action|refresh_item_data" gets sent 2 times when a client connects to the server and it's lowkey annoying. Seeing if anyone would know a potential fix to this problem.

**Comment by Bexpg** [comment]
@ama6nen help ur fanboy Bro

**Comment by DEERUX** [comment]
Stop. please. (warning) this is autism at its maximum level also bexpg ur literally his fanboy right here :)

**Comment by Bexpg** [comment]
u warning me ? @DEERUX

**Comment by Bexpg** [comment]
And im not fucking fanboy of this retard

**Comment by DEERUX** [comment]
@Bexpg yeah amateurz is a retard and a skid ur the greatest keep going!!

**Comment by Bexpg** [comment]
Its reality...

**Comment by Bexpg** [comment]
u cant change reality.mss

**Comment by DEERUX** [comment]
ya very true

**Comment by DEERUX** [comment]
@bexpg bexpg keep behaving like that ur a good boy, stay strong!!

**Comment by Bexpg** [comment]
He dont have hiis own game he dont know code just copying gt packet

**Comment by Bexpg** [comment]
Imagine copying 7/24 gt packets and make video about it.... cringe level maximum  right? Bro @DEERUX

**Comment by DEERUX** [comment]
YES EXACTLY AND EVEROYNE KNOWS BEXPG THE BIGGEST GUY, THE GREATEST, AND THE BEST GUY ON EARTH EVERYONE KNOWS BEXPG HAS HIS OWN GAME AND THIS AMA LIL' RETARD ONLY „COPYING“ GT PACKETS
BEXPG UR SO RIGHT...

**Comment by DEERUX** [comment]
sooooo trueee broo

**Comment by Bexpg** [comment]
Yee brooo im righttt

**Comment by Bexpg** [comment]
He not ignoring his fanboy he dont know code thats why he didnt answering any issues... bro!!!!!

**Comment by DEERUX** [comment]
Yeeeee ikr,,, now everyone fucking sub bexpg *ON FUCKING YOUTUBE* or he will ultimately hack u in less than 2 days I SUBBED ALREADY GUYS!

**Comment by Bexpg** [comment]
He not ignoring his fanboy he dont know code thats why he didnt answering any issues... bro!!!!!

**Comment by DEERUX** [comment]
YES EXACTLY

**Comment by Bexpg** [comment]
Or maybe he busy with copy paste gt packets?

**Comment by DEERUX** [comment]
OOOOOO U DISSED HIM SO HARD MAN WE HAVE TO CELEBRATE THIS

**Comment by Bexpg** [comment]
Yeaaa im bleck niger im live in germany im 13 yrs old and im saying im 16 yrs olddddd broaa!!!!!

**Comment by DEERUX** [comment]
oh wtf u live in germany? never knew. So you are 13 years old? Cool I am 16.

**Comment by DEERUX** [comment]
@Bexpg show ama this retard how good u are spam ping him and battle with him here i will be out now

**Comment by Bexpg** [comment]
Let's take the kids out

**Comment by Bexpg** [comment]
Aka deerux

**Comment by DEERUX** [comment]
@Bexpg show ama ur very secret good tricks flex on him master

**Comment by Bexpg** [comment]
![Screenshot_20200317-031622_Discord](https://user-images.githubusercontent.com/61095632/76810017-b89e7280-67fd-11ea-8034-34376a5939ea.jpg)
@DEERUX  he didnt accept my friend request wtf bro!!!!

**Comment by DEERUX** [comment]
OOOOOOOOO is he scared maybe???!!

**Comment by Bexpg** [comment]
Yes absolutely!!

**Comment by Bexpg** [comment]
Im ignored this kids lel

**Comment by DEERUX** [comment]
OH MY GOD YOU IGNORED AMATEURZ? THATS +100 HIT GG GOOD GAME FOR BEXPG
winner: bexpg (score: 100)

**Comment by Bexpg** [comment]
![Screenshot_20200317-031945_Discord](https://user-images.githubusercontent.com/61095632/76810161-2f3b7000-67fe-11ea-91dd-1f4e7a6c28f7.jpg)
Yesss bro im ignored this retard kids!!!

**Comment by DEERUX** [comment]
OMG YOU IGNORED ME TOO? THATS DOUBLE KILL FOR BEXPG!!!!

**Comment by Bexpg** [comment]
Wtff its you?!!!

**Comment by Bexpg** [comment]
Wtfff wrong picssss!!

**Comment by noobsteak** [comment]
Bex shut the fuck up. You don't fucking know shit and probably the most useless piece of crap alive.

"Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing."

**Comment by Bexpg** [comment]
@ama6nen bro ur fanboy bullying me Help wtf!!?!?!! Say to ur fanboy stop bullying me wtffffagsmKekfjeidigie

**Comment by atomiclucky** [comment]
This is honestly stupid. Don't you have anything else better do? Close this issue, please..

**Comment by Bexpg** [comment]
Will you say or im heck you bro!!!!

**Comment by atomiclucky** [comment]
> Will you say or im heck you bro!!!!

lol haha funny hacker

**Comment by Bexpg** [comment]
Im biggestt haxor in world 1331!!!!!!!

**Comment by iProgramMC** [comment]
Bexpg should just shut up.

**Comment by iProgramMC** [comment]
Nobody is helping OP with this issue. I am not sure why action|refresh_item_data is sent twice, but it could be because you don't send the items.dat in time?

**Comment by NotDark** [comment]
> For some reason "action|refresh_item_data" gets sent 2 times when a client connects to the server and it's lowkey annoying. Seeing if anyone would know a potential fix to this problem.

just ignore the action when get sent 2time

**Comment by iProgramMC** [comment]
I think that is a good way to solve the problem. Anybody already does this
iirc.

**Comment by noobsteak** [comment]
I just don't like when player joins the server it shows "Welcome to *server name*" 2 times.

**Comment by arshizx** [comment]
> I just don't like when player joins the server it shows "Welcome to _server name_" 2 times.

put the "Welcome to server name" to action|enter_game

**Comment by noobsteak** [comment]
My ocd reeeeeeeeeee

**Comment by herothedev** [comment]
or ignore the second packet, like add in playerinfo struct hasRecievedAndSentitemsDat = false; and make it true when first time recieving the packet ez pez.

**Comment by noobsteak** [comment]
Aight I'll try to do something like that or maybe reformat the code.

**Comment by arshizx** [comment]
wow bexpg king of coder (not skided gtos source) reacted my message

**Comment by xXAbood** [comment]
ignore the action when its sent twice steak
