### ISSUE TITLE
Fake aap bypass

### ISSUE THREAD

**Issue by ImBusy1** [GrowtopiaNoobs/GrowtopiaServer#1249]
![IMG-20200317-WA0040](https://user-images.githubusercontent.com/57601845/76875711-98ac9480-6879-11ea-9dd1-37370c140b0f.jpeg)
Its a stealer what about it ama?

**Comment by Tron-GT** [comment]
its not stealer

**Comment by Bexpg** [comment]
ye its trash virus dont download and reset ur pc

**Comment by noobsteak** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by Bexpg** [comment]
@ama6nen wtf get out here ur fan mennn

**Comment by loanselot** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by ama6nen** [comment]
Feel free to show at what exact line supposed stealer code is cuz its open-source
clearly says "proxy edited" btw

**Comment by D3c0d33** [comment]
Retard, it's not stealer lmao.

**Comment by ImBusy1** [comment]
Its a stealer

**Comment by ImBusy1** [comment]
> Feel free to show at what exact line supposed stealer code is cuz its open-source
> clearly says "proxy edited" btw

I just have the exe

**Comment by D3c0d33** [comment]
> Its a stealer

https://www.virustotal.com/gui/file/8b3f9d2b38baf60e42f2a12a424150d61e482c39c0baccdd1215267f5d13aedd/detection

**Comment by GuckTubeYT** [comment]
> 
> 
> ye its trash virus dont download and reset ur pc

Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by GrowtopiaNoobs** [comment]
If it is opensource, then check source code and decide yourself if you want to trust it
Also this is wrong repository to ask this question
