### ISSUE TITLE
[QUESTION] Guild flag

### ISSUE THREAD

**Issue by ilyn1337** [GrowtopiaNoobs/GrowtopiaServer#125]
How do i set 2 items to country flag? Is it similar as peer country? Or with which packet can i send to player to apply that?

**Comment by ritzysw** [comment]
use OnGuildDataChanged (args are 5 intx's)

**Comment by Mempler** [comment]
This pretty much answers that question. Thanks :+1:

**Comment by WarXYZ** [comment]
can explain how to use OnGuildDataChanged
