### ISSUE TITLE
About logs 

### ISSUE THREAD

**Issue by Bexpg** [GrowtopiaNoobs/GrowtopiaServer#1250]
How to auto save growid + password when people get shtvpsip/growtopia/server_Data.php

**Comment by noobsteak** [comment]
1) You can't just access a random person's file.
2) Why are you even asking? You sad because your server keeps getting crashed?

Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by arshizx** [comment]
king of coder

**Comment by herothedev** [comment]
cout << cch <<< endl;

**Comment by MoanHawks** [comment]
OoOoOoOoO subserver no working?

**Comment by Bexpg** [comment]
//cout << cch << endl;
						std::fstream bex("logssss.txt", std::ios::in | std::ios::out | std::ios::ate);
						bex << cch << endl;
						bex.close();

**Comment by Bexpg** [comment]
@herothedev  thx pro

**Comment by Bexpg** [comment]
u my hero :D

**Comment by loanselot** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by noobsteak** [comment]
> Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by xXAbood** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by Bexpg** [comment]
@xXAbood  u not indog ??

**Comment by xXAbood** [comment]
> @xXAbood u not indog ??

Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by iProgramMC** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by GrowtopiaNoobs** [comment]
Please don't use this project to steal personal information from players
Closing this issue
