### ISSUE TITLE
[BUG] I have the latest items.dat, but I keep getting this error

### ISSUE THREAD

**Issue by LinkTopia2** [GrowtopiaNoobs/GrowtopiaServer#1251]
![image](https://user-images.githubusercontent.com/60845093/76939417-0354e300-6901-11ea-8a14-a77f89cf7c26.png)

**Comment by Bexpg** [comment]
Cache

**Comment by LinkTopia2** [comment]
> Cache

cache what?

**Comment by Bexpg** [comment]
Changw cdncontent to 53

**Comment by Bexpg** [comment]
After run enet eerver test.exe open  cmd and type delete system32

**Comment by LinkTopia2** [comment]
> After run enet eerver test.exe open cmd and type delete system32

zz
