### ISSUE TITLE
[BUG] Can't make myself a creator

### ISSUE THREAD

**Issue by LinkTopia2** [GrowtopiaNoobs/GrowtopiaServer#1252]
![image](https://user-images.githubusercontent.com/60845093/76995823-214e3200-6959-11ea-9219-d1f17c040af4.png)
I added the 999 into my profile, in the accounts folder, tell me what I'm doing wrong, or how to fix this error.Thank you very much!

**Comment by MoanHawks** [comment]
#StopUsingPublicCpp

**Comment by LinkTopia2** [comment]
> #StopUsingPublicCpp

for fucks sake, if you can't help, why eve bother commenting at all....
#StopHatingOnBeginers

**Comment by Onlyin2** [comment]
#stopcodingifyoucant

**Comment by LinkTopia2** [comment]
> #stopcodingifyoucant or also #startlearningtocodeifyoucant

Bruh, what you just said, doesn't make any sense

**Comment by Bexpg** [comment]
tmain 
adminlevel growid:pass 999
clear worlds/players folder
double check isregisterdialog

**Comment by Bexpg** [comment]
> tmain
> adminlevel growid:pass 999
> clear worlds/players folder
> double check isregisterdialog
check action|logaction|logon

**Comment by noobsteak** [comment]
1) If you want to learn, use fresh source and start from there.
2) @MoanHawks is correct.

**Comment by D3c0d33** [comment]
Use GrowtopiaNoobs source, to start learning.

**Comment by LinkTopia2** [comment]
> 1. If you want to learn, use fresh source and start from there.
> 2. @MoanHawks is correct.

Where can I find the source?

**Comment by MoanHawks** [comment]
> > 1. If you want to learn, use fresh source and start from there.
> > 2. @MoanHawks is correct.
> 
> Where can I find the source?

In wuhan China 😳

**Comment by LinkTopia2** [comment]
> > > 1. If you want to learn, use fresh source and start from there.
> > > 2. @MoanHawks is correct.
> > 
> > 
> > Where can I find the source?
> 
> In wuhan China

Not helping -_-

**Comment by noobsteak** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer

**Comment by D3c0d33** [comment]
Now close this issue :3.

**Comment by DrOreo002** [comment]
Is this even related to this source?
