### ISSUE TITLE
How to give gems to news player when register

### ISSUE THREAD

**Issue by Bexpg** [GrowtopiaNoobs/GrowtopiaServer#1256]
How to give gems to news player when register

**Comment by MoanHawks** [comment]
![IMG_20200314_204004](https://user-images.githubusercontent.com/52075701/77204648-287a6900-6b2e-11ea-8a08-85e229fbc354.jpg)

**Comment by xXAbood** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by kuteshiki** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by kuteshiki** [comment]
@Bexpg 
176.217.16.44
client: pernado low
adress: Istanbul
city: diyarbakur
tele: vodafone

**Comment by kuteshiki** [comment]
![https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png]

**Comment by loanselot** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by xXAbood** [comment]
> Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by ardakurucim** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by noobes1337** [comment]
turkey 17 years old gang

**Comment by N-a-h** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by noobes1337** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by kuteshiki** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.
![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)

**Comment by noobsteak** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by kuteshiki** [comment]
`![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)`

**Comment by kuteshiki** [comment]
copy paste that shit

**Comment by kuteshiki** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by kuteshiki** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by kuteshiki** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by kuteshiki** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by kuteshiki** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by kuteshiki** [comment]
![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)

**Comment by kuteshiki** [comment]
![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)

**Comment by noobes1337** [comment]
https://i.imgur.com/rCjpIbT.png

**Comment by noobes1337** [comment]
https://i.imgur.com/rCjpIbT.png

**Comment by noobsteak** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by kuteshiki** [comment]
![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)
![yesimretard](https://i.imgur.com/rCjpIbT.png)

**Comment by noobsteak** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by noobsteak** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by kuteshiki** [comment]
![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)
![yesimretard](https://i.imgur.com/rCjpIbT.png)

**Comment by kuteshiki** [comment]
![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)
![yesimretard](https://i.imgur.com/rCjpIbT.png)

**Comment by noobsteak** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by noobsteak** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by kuteshiki** [comment]
![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)
![yesimretard](https://i.imgur.com/rCjpIbT.png)

**Comment by kuteshiki** [comment]
![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)
![yesimretard](https://i.imgur.com/rCjpIbT.png)

**Comment by noobsteak** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by kuteshiki** [comment]
![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)
![yesimretard](https://i.imgur.com/rCjpIbT.png)

**Comment by kuteshiki** [comment]
![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)
![yesimretard](https://i.imgur.com/rCjpIbT.png)

**Comment by kuteshiki** [comment]
![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)
![yesimretard](https://i.imgur.com/rCjpIbT.png)

**Comment by noobes1337** [comment]
![rCjpIbT](https://user-images.githubusercontent.com/56735791/77205504-ad995a00-6afd-11ea-8495-6ea2d00d904a.png)

**Comment by noobes1337** [comment]
![rCjpIbT](https://user-images.githubusercontent.com/56735791/77205509-b0944a80-6afd-11ea-93d4-416c4bf152ac.png)

**Comment by noobes1337** [comment]
![rCjpIbT](https://user-images.githubusercontent.com/56735791/77205516-b38f3b00-6afd-11ea-996b-ca2a4645a438.png)

**Comment by kuteshiki** [comment]
![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)
![yesimretard](https://i.imgur.com/rCjpIbT.png)

**Comment by kuteshiki** [comment]
![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)
![yesimretard](https://i.imgur.com/rCjpIbT.png)

**Comment by kuteshiki** [comment]
![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)
![yesimretard](https://i.imgur.com/rCjpIbT.png)

**Comment by noobsteak** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by loanselot** [comment]
unwatched

**Comment by noobes1337** [comment]
![D7sGWWh](https://user-images.githubusercontent.com/56735791/77205566-cc97ec00-6afd-11ea-9dad-883310c45fd8.png)

**Comment by kuteshiki** [comment]
![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)
![yesimretard](https://i.imgur.com/rCjpIbT.png)
![imurdad](https://user-images.githubusercontent.com/56735791/77205566-cc97ec00-6afd-11ea-9dad-883310c45fd8.png)

**Comment by noobes1337** [comment]
![s9n44A0](https://user-images.githubusercontent.com/56735791/77205636-f224f580-6afd-11ea-9bf2-cf09fb1fd732.png)

**Comment by noobes1337** [comment]
![Screenshot_225](https://user-images.githubusercontent.com/56735791/77205673-023cd500-6afe-11ea-9dcd-e4754cde2a6e.png)
retard moment

**Comment by noobsteak** [comment]
![LOLLL~2](https://user-images.githubusercontent.com/49786970/77205709-cee15280-6acb-11ea-8d22-6c9b106fac6f.png)

**Comment by kuteshiki** [comment]
![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)
![yesimretard](https://i.imgur.com/rCjpIbT.png)
![imurdad](https://user-images.githubusercontent.com/56735791/77205566-cc97ec00-6afd-11ea-9dad-883310c45fd8.png)
![racist](https://cdn.discordapp.com/attachments/654930012163801088/667291409505583144/Screenshot_225.png)
![speed](https://user-images.githubusercontent.com/56735791/77205636-f224f580-6afd-11ea-9bf2-cf09fb1fd732.png)
![notracist](https://cdn.discordapp.com/attachments/654930012163801088/667291470872707072/Screenshot_220.png)

**Comment by noobes1337** [comment]
![8nHXBwz](https://user-images.githubusercontent.com/56735791/77205736-24ceee00-6afe-11ea-9435-2fb3fa7dabc0.png)

**Comment by kuteshiki** [comment]
![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)
![yesimretard](https://i.imgur.com/rCjpIbT.png)
![imurdad](https://user-images.githubusercontent.com/56735791/77205566-cc97ec00-6afd-11ea-9dad-883310c45fd8.png)
![racist](https://cdn.discordapp.com/attachments/654930012163801088/667291409505583144/Screenshot_225.png)
![speed](https://user-images.githubusercontent.com/56735791/77205636-f224f580-6afd-11ea-9bf2-cf09fb1fd732.png)
![notracist](https://cdn.discordapp.com/attachments/654930012163801088/667291470872707072/Screenshot_220.png)
![indog](https://user-images.githubusercontent.com/56735791/77205736-24ceee00-6afe-11ea-9435-2fb3fa7dabc0.png)

**Comment by noobes1337** [comment]
https://i.imgur.com/sEJBlVB.png

**Comment by kuteshiki** [comment]
![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)
![yesimretard](https://i.imgur.com/rCjpIbT.png)
![imurdad](https://user-images.githubusercontent.com/56735791/77205566-cc97ec00-6afd-11ea-9dad-883310c45fd8.png)
![racist](https://cdn.discordapp.com/attachments/654930012163801088/667291409505583144/Screenshot_225.png)
![speed](https://user-images.githubusercontent.com/56735791/77205636-f224f580-6afd-11ea-9bf2-cf09fb1fd732.png)
![notracist](https://cdn.discordapp.com/attachments/654930012163801088/667291470872707072/Screenshot_220.png)
![indog](https://user-images.githubusercontent.com/56735791/77205736-24ceee00-6afe-11ea-9435-2fb3fa7dabc0.png)
![icantthinkofmoreofthesepleasehelp](https://i.imgur.com/sEJBlVB.png)

**Comment by noobes1337** [comment]
![Jw1dOME](https://user-images.githubusercontent.com/56735791/77205839-5ba50400-6afe-11ea-93cf-d412aa1e4f1c.png)

**Comment by xXAbood** [comment]
no one wants him to exist wtf

**Comment by kuteshiki** [comment]
duhh

**Comment by kuteshiki** [comment]
`
![helloimfromturkeyim17yearsoldandimcodingcsharpcppimlikekiddingwithotherskidstheythinkimkidsbutimjustkiddingandtheylaughing](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)
![yesimretard](https://i.imgur.com/rCjpIbT.png)
![imurdad](https://user-images.githubusercontent.com/56735791/77205566-cc97ec00-6afd-11ea-9dad-883310c45fd8.png)
![racist](https://cdn.discordapp.com/attachments/654930012163801088/667291409505583144/Screenshot_225.png)
![speed](https://user-images.githubusercontent.com/56735791/77205636-f224f580-6afd-11ea-9bf2-cf09fb1fd732.png)
![notracist](https://cdn.discordapp.com/attachments/654930012163801088/667291470872707072/Screenshot_220.png)
![indog](https://user-images.githubusercontent.com/56735791/77205736-24ceee00-6afe-11ea-9435-2fb3fa7dabc0.png)
![icantthinkofmoreofthesepleasehelp](https://i.imgur.com/sEJBlVB.png)
![smartass](https://user-images.githubusercontent.com/56735791/77205839-5ba50400-6afe-11ea-93cf-d412aa1e4f1c.png)
`

**Comment by noobes1337** [comment]
![image](https://user-images.githubusercontent.com/56735791/77205918-8a22df00-6afe-11ea-9384-edb1bceb78d2.png)

**Comment by kuteshiki** [comment]
``

**Comment by noobes1337** [comment]
![image](https://user-images.githubusercontent.com/56735791/77205979-aa529e00-6afe-11ea-9576-f02c46c42a6f.png)

**Comment by kuteshiki** [comment]
cya

**Comment by noobes1337** [comment]
![image](https://user-images.githubusercontent.com/56735791/77206016-bc344100-6afe-11ea-80b3-ba3c9864daf9.png)

**Comment by noobes1337** [comment]
![image](https://user-images.githubusercontent.com/56735791/77206065-cf471100-6afe-11ea-9e80-42dc2c60e74c.png)

**Comment by noobes1337** [comment]
![image](https://user-images.githubusercontent.com/56735791/77206077-d5d58880-6afe-11ea-88e1-58b545a2e35c.png)

**Comment by noobes1337** [comment]
![image](https://user-images.githubusercontent.com/56735791/77206106-e423a480-6afe-11ea-8194-b70734306935.png)

**Comment by kuteshiki** [comment]
`
Doxxing and invasion of privacy - Don't post other people's personal information, such as phone numbers, private email addresses, physical addresses, credit card numbers, Social Security/National Identity numbers, or passwords. Depending on the context, such as in the case of intimidation or harassment, we may consider other information, such as photos or videos that were taken or distributed without the subject's consent, to be an invasion of privacy, especially when such material presents a safety risk to the subject.
`

`
Actions we may take in response to an abuse report include but are not limited to:

    Content Removal
    Content Blocking
    Account Suspension
    Account Termination
`

**Comment by noobes1337** [comment]
friends group eyy
![image](https://user-images.githubusercontent.com/56735791/77206130-f0a7fd00-6afe-11ea-8c76-b164e728fca1.png)

**Comment by kuteshiki** [comment]
yeah cya

**Comment by xXAbood** [comment]
https://cdn.discordapp.com/attachments/690655797113258044/690670844027863110/unknown.png

**Comment by xXAbood** [comment]
(https://cdn.discordapp.com/attachments/690655797113258044/690670844027863110/unknown.png)

**Comment by Bexpg** [comment]
@
![21321](https://user-images.githubusercontent.com/61095632/77209847-75e7dd80-6b10-11ea-9d27-d6bbbec7f9bb.PNG)
@kuteshiki  U  playing with cat 2 minute ??? i will play with ur life unlimited  : )

**Comment by Bexpg** [comment]
![qwdwqd](https://user-images.githubusercontent.com/61095632/77209937-b6dff200-6b10-11ea-9d96-744797e4352b.PNG)

**Comment by Bexpg** [comment]
@kuteshiki Realllyy u getted 7k gems ? Omg!!

**Comment by Bexpg** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/61095632/77210058-10e0b780-6b11-11ea-8fae-5241ffd088ee.PNG)

@noobes1337  PLaying bigeest retard????????????? : ) uur the biggest retard

**Comment by Bexpg** [comment]
![f0c79a9be66615df2c40be48c76aafc5](https://user-images.githubusercontent.com/61095632/77210206-73d24e80-6b11-11ea-8086-deb66ed77a60.jpg)
@loanselot  okay ur mom look stupid and  pusher if you keep doing this shit you know what will be :  )

**Comment by niko1802** [comment]
> ![f0c79a9be66615df2c40be48c76aafc5](https://user-images.githubusercontent.com/61095632/77210206-73d24e80-6b11-11ea-8086-deb66ed77a60.jpg)
> @loanselot okay ur mom look stupid and pusher if you keep doing this shit you know what will be : )

i literally have no idea what youre trying to say

**Comment by loanselot** [comment]
you just deleted all of your dms because of unsecurity of your mom and yourself lol hopefully i got all of chat archived

**Comment by Bexpg** [comment]
![213213](https://user-images.githubusercontent.com/61095632/77210411-0246d000-6b12-11ea-8abb-646f5b55165f.PNG)
@MoanHawks  who striked you retardd why you crying?

**Comment by Bexpg** [comment]
wait , u mod ? [UR MODS ????? :)

**Comment by Bexpg** [comment]
@xXAbood  and you stupid i wont say anything about you because im not respecting who putted anime charecters in pp you must be 10 or 12 years old

**Comment by Bexpg** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/61095632/77210695-b0527a00-6b12-11ea-9503-2d830616e98e.PNG)
@noobsteak  i only want say this to you.... @ama6ten  get out ur 10-12 years old fanboy

**Comment by Bexpg** [comment]
> > ![f0c79a9be66615df2c40be48c76aafc5](https://user-images.githubusercontent.com/61095632/77210206-73d24e80-6b11-11ea-8086-deb66ed77a60.jpg)
> > @loanselot okay ur mom look stupid and pusher if you keep doing this shit you know what will be : )
> 
> i literally have no idea what youre trying to say

AS,LDDFSJIKODADADOAKDAODSKADOSADJGF OSAKDKAOSK APA KONTOL ANJIGNGNG INDOGHFJI OSAJF ASODKDAOD now you understand ? its indog language my friends learned to me

**Comment by niko1802** [comment]
> > > ![f0c79a9be66615df2c40be48c76aafc5](https://user-images.githubusercontent.com/61095632/77210206-73d24e80-6b11-11ea-8086-deb66ed77a60.jpg)
> > > @loanselot okay ur mom look stupid and pusher if you keep doing this shit you know what will be : )
> > 
> > 
> > i literally have no idea what youre trying to say
> 
> AS,LDDFSJIKODADADOAKDAODSKADOSADJGF OSAKDKAOSK APA KONTOL ANJIGNGNG INDOGHFJI OSAJF ASODKDAOD now you understand ? its indog language my friends learned to me

Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by loanselot** [comment]
> Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by Bexpg** [comment]
![f0c79a9be66615df2c40be48c76aafc5](https://user-images.githubusercontent.com/61095632/77211016-92d1e000-6b13-11ea-9e32-43d0df4c0661.jpg)
ok im calling ur mom @loanselot

**Comment by Bexpg** [comment]
![Ekran Alıntısıasd](https://user-images.githubusercontent.com/61095632/77211100-e04e4d00-6b13-11ea-8716-160b21592ece.PNG)
@xXAbood  KASDOSGDJDOASJFOADSAKOSQWDIWQDQWDQWDWQDQWD

**Comment by Bexpg** [comment]
@noobes1337  Why u made private ur  video about me SCAREd????????????????

**Comment by niko1802** [comment]
How to fix place block to wl and gone (if you dont know keep yourself ur shit comment)

**Comment by Bexpg** [comment]
![Ekran sadsd](https://user-images.githubusercontent.com/61095632/77211199-43d87a80-6b14-11ea-8d05-42fb25aa1839.PNG)
@noobes1337  face reveal download it before deleted!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Bexpg** [comment]
![12321](https://user-images.githubusercontent.com/61095632/77211253-6ff3fb80-6b14-11ea-8f08-199acd749c0c.PNG)
@kuteshiki  face reveal!!!!!!!!!

**Comment by Bexpg** [comment]
I CAN SAY THAT NO ONE FACE REVEAL IS FAKE IF YOU THINK ITS FAKE OR SOMETHING UR GAY!

**Comment by niko1802** [comment]
![image](https://user-images.githubusercontent.com/48137608/77211464-b9404d00-6b0c-11ea-8518-0b23f5b077d4.png)

bexpg face reveal

haha so funny

**Comment by Bexpg** [comment]
bastard kids who envy my success

**Comment by niko1802** [comment]
me when growtopia private server success

**Comment by Bexpg** [comment]
@niko1802  Did i asked???????????

**Comment by Bexpg** [comment]
@niko1802  Did i asked???????????   ANSWER DID I ASKED?

**Comment by Bexpg** [comment]
NO

**Comment by Bexpg** [comment]
SO SHUT THE FUCK UP

**Comment by niko1802** [comment]
did i ask

**Comment by Bexpg** [comment]
@niko1802   did i give permission to you for talk ??

**Comment by Bexpg** [comment]
NO

**Comment by niko1802** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by Bexpg** [comment]
YOU CANT SPEAK WITHOUT GET PERMISSIONS FROM ME

**Comment by Bexpg** [comment]
SHUT UP NIGGERRSS

**Comment by Bexpg** [comment]
HELLO IM FROM INDOGNESIAAAA IM SCAMMING PEOPLEEEEEEEEEEEE AND THINK IM BEST HACKER, SCAMMER LELLLLLLLLLLLLL

**Comment by Bexpg** [comment]
@niko1802  well you learning so fast don't speak again without get permissions from me

**Comment by niko1802** [comment]
Take me serious because I will not joke again 🃏

**Comment by Bexpg** [comment]
you again speaked without get permissions from me ?

**Comment by Bexpg** [comment]
WTFFFFFFFFFFFFFFFFFFFFFF

**Comment by Bexpg** [comment]
@niko1802  i give you permission go speak  i good king bastard

**Comment by niko1802** [comment]
youre worse at english than most indonesian people ive talked to

**Comment by Bexpg** [comment]
@niko1802  did i asked ??????????? YES i did asked ur mom address i need celebrate he for make idiot kids like you

**Comment by Bexpg** [comment]
CLOSING THANKS FOR SS @noobes1337  I WILL SEND DISCORD SECURITY TEAM FOR  CHECK + SPAMMING IN GITHUB  DISCORD IS ILLEGAL THINGS ALRIGHT THANKS FOR THE ALL SS

**Comment by xXAbood** [comment]
> ![Ekran Alıntısıasd](https://user-images.githubusercontent.com/61095632/77211100-e04e4d00-6b13-11ea-8716-160b21592ece.PNG)
> @xXAbood KASDOSGDJDOASJFOADSAKOSQWDIWQDQWDQWDWQDQWD

can u atleast make a winform u literal saddistic faggot

**Comment by xXAbood** [comment]
![image](https://user-images.githubusercontent.com/59313717/77219621-13fb9800-6b51-11ea-8b76-715875a07a31.png)

**Comment by xXAbood** [comment]
![image](https://cdn.discordapp.com/attachments/690655797113258044/690670844027863110/unknown.png)

**Comment by noobes1337** [comment]
ok u got me
