### ISSUE TITLE
I AM ARE 17 ( """SEVEN""" ) YEARS OLDS FROM C# CPP CODER TURKEY

### ISSUE THREAD

**Issue by loanselot** [GrowtopiaNoobs/GrowtopiaServer#1257]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by noobes1337** [comment]
BEXPG LEADER!

**Comment by niko1802** [comment]
hahaha im too kidding with skidding skid kids but they think im skidding im just really kidding with them skidding not me im kidding skids but they laughing thinking i skidding but i kidding them laugh!!! im 17 too and coding c# c++ and skidding with other kidding ki

**Comment by Bexpg** [comment]
its not growtopiaserver issue.

**Comment by Bexpg** [comment]
https://user-images.githubusercontent.com/61095632/77210206-73d24e80-6b11-11ea-8086-deb66ed77a60.jpg
@loanselot  ur mom called me do you know why he called me????????

**Comment by Bexpg** [comment]
https://www.youtube.com/watch?v=_RXF07aBRg8
loanselot face reveal i f you dont believe its ok but google dorks recommend me this when i type loanselot in google.

**Comment by Bexpg** [comment]
![qwdw](https://user-images.githubusercontent.com/61095632/77212443-29a09b80-6b18-11ea-8ba8-e0270347c228.PNG)

He like!!!

**Comment by Bexpg** [comment]
i dont lik e ur mom ur mom fucking fat + im sure u dont have dad must he kill his self for make idiot kids like you

**Comment by Bexpg** [comment]
NOKTA HADI EYWALLAH YEGENIM :   )

**Comment by Bexpg** [comment]
@xxabood  
Hello im from syria turkish soldiers kill my family because they are terrorist!! And im hating from turkey

**Comment by Bexpg** [comment]
@loanselot  Hello my name is leaonslot im from turkey im 12 years old im dont belive god

**Comment by Bexpg** [comment]
@noobesgt hello im 13 years old im live in indognesia my family are dog!!!!  Im 7/24 doing copy paste  im beg bexpg for dont strike me

**Comment by Bexpg** [comment]
@niko1802  Hello im from indognesia noobesgt my best friends me want be famaous and get some retard friends thats why im trying war with my dad(bexpg)

**Comment by Bexpg** [comment]
@ardakurucim  hello im from turkey im 14 years old bexpg ignored me on discord  idk why he so pro im want be like he

**Comment by Bexpg** [comment]
@kuteshiki hello im 12 years old ( im really 12 years old im scared people judge me and deleted from my bio only bexpg see)  im living in indognesia im trying learn java from youtubeeeee im like watching anime im think anime is really good my mom name is hentai

**Comment by Bexpg** [comment]
@Bexpg  Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing. (YOU ARE BEST AND OTHER BASHED JEOLOUS YOU DONT CARE THEY AND KEEP BE BEST!!!!)

**Comment by Bexpg** [comment]
While im writing this comment other skids,retard sleeping. :) IM KNOW UR MOM DONT ALLOW YOU PLAY PC IN NIGHT  IM LIVING ALONE SO I CAN DO IT WHATEVER I WANT BUT YOU CANT DO IT BEFORE JUDGE OTHER PEOPLES BIO STOP BEING RETARD)

**Comment by Bexpg** [comment]
While im writing this comment other skids,retard sleeping. :) IM KNOW UR MOM DONT ALLOW YOU PLAY PC IN NIGHT IM LIVING ALONE SO I CAN DO IT WHATEVER I CAN BUT YOU CANT DO IT BEFORE JUDGE OTHER PEOPLES BIO STOP BEING RETARD

**Comment by Bexpg** [comment]
IM DONE I DONT NEED COMMENT ANYMORE ;)))))) ALL OF THEM ROASTEDDDD

**Comment by niko1802** [comment]
ok indog

**Comment by niko1802** [comment]
staying in a good sleep cycle is important for your health.
you should do your best to get a proper sleep cycle that fits with the activities you have to do during the time youre awake, for example im trash at waking up so i try to go to sleep early and wake up hours before i start my morning activities

**Comment by niko1802** [comment]
im 90% sure youre just trolling by parodying the 9 year old indogs that come through this github repository, if not that you probably have a mental disability or something
but fr youre funny and theres just something so amusing about getting a reaction out of this character youre playing and i love it, keep this going bro its funny

**Comment by kuteshiki** [comment]
faggot i'm 19 burn in hell nigga @Bexpg 
here's your ip & other things:
![useless](https://media.discordapp.net/attachments/623772420838522880/690661495792599050/unknown.png)

**Comment by Bexpg** [comment]
Im Cant stop laugh JDFJQIDJKAKWJEUFUW

**Comment by Bexpg** [comment]
ITS MY OLD WIFI IP ADDRESS 🤣

**Comment by Bexpg** [comment]
+ my name not pernando low :) its my facebook name

**Comment by Bexpg** [comment]
City istqnbul telo: TURKCELL (TURK)CELL ;)))

**Comment by Bexpg** [comment]
@niko1802 Hello im from indognesia noobesgt my best friends me want be famaous and get some retard friends thats why im trying war with my dad(bexpg)

**Comment by Bexpg** [comment]
@niko1802 Hello im from indognesia noobesgt my best friends me want be famaous and get some retard friends thats why im trying war with my dad(bexpg)

**Comment by Onlyin2** [comment]
Hey bex, are you sure you're 17? You sound like 9 to me. I like your bio "take me seriously" bruh you're a fucking joke how do you excpect people to actually take you seriously. I've seen some dumbass hoes but you're on a whole other level. Get the fuck out of here before you actually get placed back in your rat hole.

**Comment by loanselot** [comment]
Take me serious because I will not joke again 🃏

**Comment by Luc1Fer-LTPS** [comment]
i can track you down i can do that shit

**Comment by noobes1337** [comment]
suicide retard

**Comment by Luc1Fer-LTPS** [comment]
why bex use gtos source? didnt sebia skid wry source

**Comment by xXAbood** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by noobes1337** [comment]
me when bexpg my friend

**Comment by Luc1Fer-LTPS** [comment]
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by noobes1337** [comment]
https://media.discordapp.net/attachments/690655797113258044/690870358617620480/unknown.png

**Comment by xXAbood** [comment]
indawg indawg wtf

**Comment by Luc1Fer-LTPS** [comment]
![unknown](https://user-images.githubusercontent.com/58911008/77224624-f9411780-6b80-11ea-99cb-614da213bce3.png)
 im cant speak english

**Comment by noobes1337** [comment]
@Bexpg 
![image](https://user-images.githubusercontent.com/56735791/77224626-36e97480-6b70-11ea-946f-ec1382116f9f.png) ok bro u got me..

**Comment by Luc1Fer-LTPS** [comment]
bexleetpro

**Comment by xXAbood** [comment]
![image](https://user-images.githubusercontent.com/59313717/77224646-17a71300-6b81-11ea-879c-6140c091a467.png)
wtf

**Comment by Luc1Fer-LTPS** [comment]
https://cdn.discordapp.com/attachments/654930012163801088/667291843964436530/Screenshot_306.png

**Comment by xXAbood** [comment]
!(https://cdn.discordapp.com/attachments/654930012163801088/667291843964436530/Screenshot_306.png)

**Comment by xXAbood** [comment]
![11-111776_mangekyou-sharingan-itachi-mangekyou-sharingan](https://cdn.discordapp.com/attachments/654930012163801088/667291843964436530/Screenshot_306.png)

**Comment by Luc1Fer-LTPS** [comment]
**i got from his pc**

**Comment by niko1802** [comment]
atleast whe didnt have to make this up

Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by Bexpg** [comment]
atleast we didnt have to make this up

Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by GrowtopiaNoobs** [comment]
Offtopic, this haven't got any real purpose, closing this
Please if you see any offtopic/trolling threads, then dont engage in them
