### ISSUE TITLE
Succes Login on PC but Updating Item in Android

### ISSUE THREAD

**Issue by vonsogt** [GrowtopiaNoobs/GrowtopiaServer#126]
PC Version : 2.987
![image](https://user-images.githubusercontent.com/35516476/53290978-6a779500-37de-11e9-8d87-cedc4c7b1717.png)

Android : 2.987

I using new hash 7xxxxxxxxx and login 

Please help, i wasted so many time maybe and i need your help
please dont say in growtopia-bot already outdated hash

**Comment by mar4ello6** [comment]
Try firstly connect to normal server, then to your.
