### ISSUE TITLE
[BUG] event starter by bexpg literally no joke enjoy bruhhhhhh

### ISSUE THREAD

**Issue by xXAbood** [GrowtopiaNoobs/GrowtopiaServer#1260]
else if (str == "/startevent") {
							if (!isSuperAdmin(((PlayerInfo*)(peer->data))->rawName, ((PlayerInfo*)(peer->data))->tankIDPass)) continue;

						}

**Comment by Bexpg** [comment]
else if (str.substr(0, 10) == "/startevent ") {
							if (adminlevel(((PlayerInfo*)(peer->data))->rawName) == 999) {
								ENetPeer* currentPeer;
								string imie = str.substr(5, cch.length() - 5 - 1);
								GamePacket p = packetEnd(appendInt(appendString(appendString(appendString(appendString(createPacket(), "OnAddNotification"), "interface/large/anni_sta.rttex"), "`2Gems event for noobs!"), "audio/pinata_lasso.wav"), 0));
								ENetPacket* packet = enet_packet_create(p.data,
									p.len,
									ENET_PACKET_FLAG_RELIABLE);
								GamePacket p2 = packetEnd(appendInt(appendString(appendString(appendString(appendString(createPacket(), "OnAddNotification"), "interface/large/anni_sta.rttex"), "`2Giveaway gems for `3EVERYONE!"), "audio/pinata_lasso.wav"), 0));
								ENetPacket* packet2 = enet_packet_create(p2.data,
									p2.len,
									ENET_PACKET_FLAG_RELIABLE);
								enet_peer_send(peer, 0, packet2);
								for (currentPeer = server->peers;
									currentPeer < &server->peers[server->peerCount];
									++currentPeer)
								{
									if (currentPeer->state != ENET_PEER_STATE_CONNECTED)
										continue;

									std::ifstream ifsz("gemdb/" + ((PlayerInfo*)(currentPeer->data))->rawName + ".txt");
									std::string content((std::istreambuf_iterator<char>(ifsz)),
										(std::istreambuf_iterator<char>()));

									int b = atoi(content.c_str());

									if (b > 0)
									{

										int gemcalc1000000k = b + atoi(str.substr(10, cch.length() - 10 - 1).c_str());


										ofstream myfile2;
										myfile2.open("gemdb/" + ((PlayerInfo*)(currentPeer->data))->rawName + ".txt");
										myfile2 << std::to_string(gemcalc10k);
										myfile2.close();

										std::ifstream ifszi("gemdb/" + ((PlayerInfo*)(currentPeer->data))->rawName + ".txt");
										std::string contentx((std::istreambuf_iterator<char>(ifszi)),
											(std::istreambuf_iterator<char>()));


										int updgem = atoi(contentx.c_str());
										GamePacket pp = packetEnd(appendInt(appendString(createPacket(), "OnSetBux"), updgem));
										ENetPacket* packetpp = enet_packet_create(pp.data,
											pp.len,
											ENET_PACKET_FLAG_RELIABLE);

										enet_peer_send(currentPeer, 0, packetpp);
										delete pp.data;

**Comment by Bexpg** [comment]
else if (str == "/startevent") {
if (!isSuperAdmin(((PlayerInfo*)(peer->data))->rawName, ((PlayerInfo*)(peer->data))->tankIDPass)) continue;
					}
			gemeventfornoobs();
		}
	}

}

**Comment by Bexpg** [comment]
@xXAbood  share my void gemevenfornoobs code too

**Comment by xXAbood** [comment]
but u dont exist how

**Comment by Bexpg** [comment]
> exist

ok just say mission failed u dont know how to code :)

**Comment by xXAbood** [comment]
> > exist
> 
> ok just say mission failed u dont know how to code :)

it just works like AppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendString OnDialogRequest memcpy,v3 CRT_SECURE_NO_WARNINGS literally

**Comment by raiterjaki** [comment]
> > > exist
> > 
> > 
> > ok just say mission failed u dont know how to code :)
> 
> it just works like AppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendStringAppendString OnDialogRequest memcpy,v3 CRT_SECURE_NO_WARNINGS literally

more like _CRT_SECURE_NO_WARNINGS instead of CRT_SECURE_NO_WARNINGS

**Comment by GrowtopiaNoobs** [comment]
Please add only issues that contribute to something
