### ISSUE TITLE
[???] Requesting help on custom items.

### ISSUE THREAD

**Issue by noobsteak** [GrowtopiaNoobs/GrowtopiaServer#1261]
When using dark's itemsdat tool, I sucessfully created my own item with it's own texture.
![nw](https://user-images.githubusercontent.com/49786970/77260696-084ac700-6c60-11ea-8bf0-c1d02b39462c.png)
As you can see in this image, there is a part that looks glitchy. I don't know why it's doing this and I've checked the rttex file which is all good. If anyone knows what might be causing this, please help. Highly appreciated :)

**Comment by Bexpg** [comment]
Its growtopia server issue  go ask to dark lel

**Comment by DrOreo002** [comment]
probably a problem with your texture. I'd suggest checking the growtoken texture first and see if the size is the same as yours

**Comment by noobsteak** [comment]
Nope. As stated above, "I've checked the rttex file which is all good." The texture size is 32x32. Is there any other problems why?

**Comment by iProgramMC** [comment]
@noobsteak don't use cernodile's rttex tools, use RTPack (https://github.com/sethrobinson/proton). Usage is as follows: `RTPack -8888 -force_alpha <your_texture_file>.png`.

I've used this script which can be put in a .bat file and you can drag and drop the png onto:
```batch
rem @echo off
set arg1=%1
"RTPack/RTPack.exe" -8888 -force_alpha %arg1%
```

**Comment by noobsteak** [comment]
okay thanks :D
