### ISSUE TITLE
Vytepr0dd0rser

### ISSUE THREAD

**Issue by Bexpg2** [GrowtopiaNoobs/GrowtopiaServer#1265]
Vytehas50kbgl

**Comment by Bexpg2** [comment]
if you shy create fake discord accounts and dm me

**Comment by Alexander9673** [comment]
you need to code it, setting up mysql server is easy.
https://dev.mysql.com/doc/connector-cpp/8.0/en/ you can refer here for the docs

**Comment by noobes1337** [comment]
bexpg's wallet: 0$

**Comment by Bexpg2** [comment]
> bexpg's wallet: 0$

Bexpg living in village and bexpg's wallet 0?

**Comment by Alexander9673** [comment]
@Bexpg2 i also pmed you on discord

**Comment by noobes1337** [comment]
> > bexpg's wallet: 0$
> 
> Bexpg living in village and bexpg's wallet 0?
> if i am sell 1 dls for 2$ i have 400dls 400x2 = 800$
> Bexpg's wallet 800$

Sorry my bad ur that poor, can't afford a wallet also ur having fantasy u don't have any dls or even a village

**Comment by playingoDEERUX** [comment]
ur literally not better noobes

**Comment by Bexpg2** [comment]
> > > bexpg's wallet: 0$
> > 
> > 
> > Bexpg living in village and bexpg's wallet 0?
> > if i am sell 1 dls for 2$ i have 400dls 400x2 = 800$
> > Bexpg's wallet 800$
> 
> Sorry my bad ur that poor, can't afford a wallet also ur having fantasy u don't have any dls or even a village

Check my first video on youtube parkour with davinci wings 6 month before gt priv has no paint/res effect/door
