### ISSUE TITLE
How to hide growtopia/server_data.php?

### ISSUE THREAD

**Issue by pytuz** [GrowtopiaNoobs/GrowtopiaServer#1270]
How to hide server_data.php on windows server? I tried to hide it, but when I log in, its down

**Comment by NotDark** [comment]
you cant hide it

**Comment by playingoDEERUX** [comment]
@pytuz impossible, if you do that, its even easily obtainable by using cheat engine.

**Comment by Tron-GT** [comment]
https://github.com/Tron-GT/growtopia-server_data.php

**Comment by playingoDEERUX** [comment]
@Tron-GT this does not fully "hide" the server_data.php tho
all this script does is block GET requests but you can still use cheat engine on growtopia to find out the address of the server or just fake a POST request.

**Comment by MoanHawks** [comment]
2 time create enet 😳

**Comment by pytuz** [comment]
ok nvm, thanks.
