### ISSUE TITLE
[QUESTION] How do you stop players from leaving world?

### ISSUE THREAD

**Issue by noobsteak** [GrowtopiaNoobs/GrowtopiaServer#1273]
So basically in real GT when you join as guest, you automatically get sent to TUTORIAL and when you click the menu button, "Exit World" is not available. Then when you try to leave the world, it asks you to finish the tutorial. How do you implement this into private servers?

**Comment by Onlyin2** [comment]
> So basically in real GT when you join as guest, you automatically get sent to TUTORIAL and when you click the menu button, "Exit World" is not available. Then when you try to leave the world, it asks you to finish the tutorial. How do you implement this into private servers?

Alt+F4, *a simple spell but quite unbreakable*

**Comment by ardakurucim** [comment]
@Onlyin2 did u even read the issue?

**Comment by Onlyin2** [comment]
> @Onlyin2 did u even read the issue?

It's a joke not a dick, don't take it so hard.

**Comment by ardakurucim** [comment]
It wasn't funny actually

**Comment by Onlyin2** [comment]
> It wasn't funny actually



> It wasn't funny actually

There's a minimum coprehension level for that joke, and it's clear you're way too low to understand.

**Comment by MoanHawks** [comment]
packetType is 14
characterState = find it you self using cheat engines

**Comment by xXAbood** [comment]
its depended on the characterState if im not wrong steak.

**Comment by xXAbood** [comment]
> > It wasn't funny actually
> 
> > It wasn't funny actually
> 
> There's a minimum comprehension level for that joke, and it's clear you're way too low to understand.

no one even asked

**Comment by noobsteak** [comment]
Bruh that kid freaking trolling -_- probably didn't understand anything I've just asked.

**Comment by noobsteak** [comment]
Thanks @MoanHawks
