### ISSUE TITLE
How to use nginx

### ISSUE THREAD

**Issue by Bexpg2** [GrowtopiaNoobs/GrowtopiaServer#1275]
How to setup fucking nginx for private server(windows) when i changed index.html nothing changed also when i put server data php and go to serverip/griwtopia/serverdataphp its auto download serverdataphp and i cant connect

**Comment by noobsteak** [comment]
dont use nginx then -_-"

**Comment by D3c0d33** [comment]
if don't work, try click reload till a notification/alert popped out "Nginx reloaded!".

**Comment by Bexpg2** [comment]
Nginx antiddos xampp trash

**Comment by Bexpg2** [comment]
> if don't work, try click reload till a notification/alert popped out "Nginx reloaded!".

Funny

**Comment by D3c0d33** [comment]
> > if don't work, try click reload till a notification/alert popped out "Nginx reloaded!".
> 
> Funny

?

**Comment by Bexpg2** [comment]
Nginx has no php and cant read php files thats why no work how use php with nginx

**Comment by herothedev** [comment]
it works with php too, its same as xampp, but better.

**Comment by GuckTubeYT** [comment]
use fpm @Bexpg2

**Comment by Bexpg2** [comment]
i found way
