### ISSUE TITLE
[BUG] Visual studio error, not sure if it is linked to GTPS

### ISSUE THREAD

**Issue by LinkTopia2** [GrowtopiaNoobs/GrowtopiaServer#1276]
![unknown](https://user-images.githubusercontent.com/60845093/77953240-a0d2ee00-72d5-11ea-9b66-87679673050f.png)

**Comment by YourBoiBusy** [comment]
open the file system in notepad++ then  remove the error
its already #error in file system

**Comment by FocusedSG** [comment]
The solution is literally written within the error code. They asked you to define _SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNINGS in your code to ignore the deprecation warning so that the compiler proceed.

**Comment by xXAbood** [comment]
arent u the guy that claims he made rollback 4
