### ISSUE TITLE
[BUG] 'Operation =' is ambiguous

### ISSUE THREAD

**Issue by CuekGaming** [GrowtopiaNoobs/GrowtopiaServer#1277]
![dsad](https://user-images.githubusercontent.com/62921987/77983803-6da55480-72ff-11ea-95cc-1eb75f9a6a45.PNG)

**Comment by herothedev** [comment]
maybe try not to use stolen cpp(s)

**Comment by CuekGaming** [comment]
> 
> 
> maybe try not to use stolen cpp(s)

hmm i just use my old cpp

**Comment by CuekGaming** [comment]
Fixed 
using this code : .get<string>();

**Comment by CuekGaming** [comment]
Fixed
