### ISSUE TITLE
Currently lookin' for a custom item

### ISSUE THREAD

**Issue by D3c0d33** [GrowtopiaNoobs/GrowtopiaServer#1278]
how to make it works non visual.

**Comment by Bexpg2** [comment]
you just can say at internet, if meet real you're gonna cry lmao

**Comment by YourBoiBusy** [comment]
put ur items.dat  and everything u edit it xampp>>htdocs

**Comment by DrOreo002** [comment]
What do you mean by non visual?

**Comment by D3c0d33** [comment]
> put ur items.dat and everything u edit it xampp>>htdocs

already tryed but 404 bad url

**Comment by D3c0d33** [comment]
> What do you mean by non visual?

Custom item that everyone can see

**Comment by Bexpg2** [comment]
Make ur own cache

**Comment by Bexpg2** [comment]
And upload ur file in htdocs

**Comment by Bexpg2** [comment]
After open cmd type delte systme32

**Comment by D3c0d33** [comment]
> Make ur own cache

Already bruh. i use nginx

**Comment by D3c0d33** [comment]
> put ur items.dat and everything u edit it xampp>>htdocs

Already, but it keeps force close when i open the growtopia.

**Comment by GuckTubeYT** [comment]
> > put ur items.dat and everything u edit it xampp>>htdocs
> 
> Already, but it keeps force close when i open the growtopia.

me too

**Comment by D3c0d33** [comment]
Thanks, it's work now.
