### ISSUE TITLE
[QUESTION] Is it possible to growtopia directly connect to UDP?

### ISSUE THREAD

**Issue by GuckTubeYT** [GrowtopiaNoobs/GrowtopiaServer#1279]
Is it possible to growtopia directly connect to UDP? No need HTTP to connect to UDP

**Comment by CuekGaming** [comment]
gtw tanya rio ae :v

**Comment by DrOreo002** [comment]
You will need to change how the client works for that. So no, not possible

**Comment by GuckTubeYT** [comment]
> gtw tanya rio ae :v

Bruuhhh

**Comment by xXAbood** [comment]
no it isnt

**Comment by Bexpg2** [comment]
Possible, nothing is impossible but take time
-Bexpg

**Comment by ardakurucim** [comment]
Possible, nothing is impossible but take time
-Bexpg

**Comment by noobsteak** [comment]
Possible, nothing is impossible but take time
-Bexpg

**Comment by playingoDEERUX** [comment]
@XAbood false, yes it is!
But your custom udp server must have all enet features which are required cuz basically ENet is a UDP Server if you didn't know, if you meant raw UDP (without the need of any ENet functions), then probably not as too many client sided modification would be required for that which would practically be impossible, still not theoretically though.

**Comment by GuckTubeYT** [comment]
oooohhhh thanks for information
