### ISSUE TITLE
How to make Discord bot reads live status embed

### ISSUE THREAD

**Issue by MarioBITs** [GrowtopiaNoobs/GrowtopiaServer#1282]
How to make discord bot that can read the exe, an example if your  enet server test.exe its crash/closed the discord bot should say DOWN and 0 players playing

And if the enet server test.exe is opened, its should say Server is up and [current player online] players playing.

**Comment by cmdocmd** [comment]
make the server make a text file inside the text file players count and make the discord bot read from the file

**Comment by MoanHawks** [comment]
1. https://github.com/yourWaifu/sleepy-discord
2. install websocket++ or openSSL
3. include it to you enet server test.cpp

**Comment by MarioBITs** [comment]
> 1. https://github.com/yourWaifu/sleepy-discord
> 2. install websocket++ or openSSL
> 3. include it to you enet server test.cpp
> 
> is simple things if you cant do then that you problem not me

**#include** "sleepy_discord/websocketpp_websocket.h"

class MyClientClass : public SleepyDiscord::DiscordClient {
public:
	using SleepyDiscord::DiscordClient::DiscordClient;
	void onMessage(SleepyDiscord::Message message) override {
		if (message.startsWith("whcg setup"))
			sendMessage(message.channelID, "Server is up" + to_string(counts));
	}
};

int main() {
	MyClientClass client("token bot discord", 2);
	client.run();
}****

**Comment by MarioBITs** [comment]
@MoanHawks  Can you give me, your discord i'd want to ask for more easy ways.

**Comment by MarioBITs** [comment]
Thanks
