### ISSUE TITLE
Blocking a bot in our server

### ISSUE THREAD

**Issue by pytuz** [GrowtopiaNoobs/GrowtopiaServer#1283]
How to block a Growtopia bot in our server?

**Comment by MarioBITs** [comment]
> How to block a Growtopia bot in our server?

Well this issue, i think no one can fix right now, but i know some one maybe knows.

**Comment by NotDark** [comment]
![image](https://user-images.githubusercontent.com/44568476/78528254-89ce5780-7811-11ea-82ab-06719b3f9b6b.png)

**Comment by MarioBITs** [comment]
![image](https://user-images.githubusercontent.com/49722651/78536673-6955cb80-7818-11ea-913b-4688d7f8a0d3.png)
Awesome, and great! , its should be complicated 😳

**Comment by MoanHawks** [comment]
Just create 3 time enet

**Comment by pytuz** [comment]
ok nvm
