### ISSUE TITLE
How To Update Growtopia Private Server Version 3.021 To 3.22

### ISSUE THREAD

**Issue by xeonu-droid** [GrowtopiaNoobs/GrowtopiaServer#1284]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MarioBITs** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

😳 , Gameversion. if you're using leaks cpp ok then 😳

**Comment by MarioBITs** [comment]
@GrowtopiaNoobs Close this issue, no respond looks its has been fixed.

**Comment by GrowtopiaNoobs** [comment]
Closing this issue as it is unedited template and there has been no new activity.
