### ISSUE TITLE
[Q] What a better software converter rttex?

### ISSUE THREAD

**Issue by MarioBITs** [GrowtopiaNoobs/GrowtopiaServer#1285]
Don't say cornodile is better one, I'd try it but its corrupt.

**Comment by MarioBITs** [comment]
![image](https://user-images.githubusercontent.com/49722651/78519162-a4420a00-77ec-11ea-816d-1c4e41681cc5.png)
When i use protonSDK, Its .rtpak type, why not rttex?

**Comment by GuckTubeYT** [comment]
https://github.com/GuckTubeYT/RTPack Use this

**Comment by GuckTubeYT** [comment]
btw i didnt make this app, i just publish

**Comment by MarioBITs** [comment]
@GuckTubeYT Kontol, mantap2 sip ✌️

**Comment by GuckTubeYT** [comment]
anjay, ngomong nya :V
