### ISSUE TITLE
how to add a new cpp? in gtnoobs cpp

### ISSUE THREAD

**Issue by FeryN77** [GrowtopiaNoobs/GrowtopiaServer#1286]
How i can put new cpp

**Comment by mar4ello6** [comment]
Wdym?

**Comment by MarioBITs** [comment]
> How i can put new cpp

Do you mean put new cpp in gtnoobs source? just go trough enet server test folder. **IF U HAVE**

**Comment by FeryN77** [comment]
U have discord?

**Comment by FeryN77** [comment]
> > How i can put new cpp
> 
> Do you mean put new cpp in gtnoobs source? just go trough enet server test folder. **IF U HAVE**

How?

**Comment by MarioBITs** [comment]
> U have discord?

yea i have.

**Comment by FeryN77** [comment]
what is your discord name

**Comment by FeryN77** [comment]
I want ask something

**Comment by FeryN77** [comment]
My discord FERY#2769

**Comment by GrowtopiaNoobs** [comment]
You need to check for differences in source and combine them together. You should learn coding to do this as there can be some bigger changes and original source can be ahead of the one you want to add new features from.
