### ISSUE TITLE
[BUG] Cant place block or break(Breaking=dc)

### ISSUE THREAD

**Issue by GramingFoxTeam** [GrowtopiaNoobs/GrowtopiaServer#1289]
I just maked turkish and i fixed some issues(not touched codes)and didnt do much too but i cant place or break block
And can you say how do i add admin?

**Comment by GramingFoxTeam** [comment]
Note;when i try old one still same.

**Comment by cmdocmd** [comment]
maybe you have dont have coredata

**Comment by GramingFoxTeam** [comment]
hmm where do get it?

**Comment by GramingFoxTeam** [comment]
im sorry for opening tons of issues bcz im new xd

**Comment by GramingFoxTeam** [comment]
> maybe you have dont have coredata

Where do i find it?

**Comment by GramingFoxTeam** [comment]
Ok.I got one from https://github.com/NotDark/GrowtopiaServer and deleted worlds.Now its working correctly
