### ISSUE TITLE
[BUG] When i try to join my private server the game crash.

### ISSUE THREAD

**Issue by Furkan125** [GrowtopiaNoobs/GrowtopiaServer#1290]

**Comment by GramingFoxTeam** [comment]
Merhaba,ilk öncelikle gt sürümün ne?Onu söylersen sana dosya verebilirim!

**Comment by GramingFoxTeam** [comment]
Çünkü bende bunu yaşadım:D

**Comment by GramingFoxTeam** [comment]
Hello,What is your gt version?
BTW if you know fix for cant place/break block say me
Thanks!

**Comment by MoanHawks** [comment]
😳

**Comment by GramingFoxTeam** [comment]
> 😳

?

**Comment by Furkan125** [comment]
> Hello,What is your gt version?
> BTW if you know fix for cant place/break block say me
> Thanks!

My gt version is latest version (v3.32)

**Comment by GramingFoxTeam** [comment]
> > Hello,What is your gt version?
> > BTW if you know fix for cant place/break block say me
> > Thanks!
> 
> My gt version is latest version (v3.32)

Hello,i am busy rn
But if you have dc can you say?(i will help you)

**Comment by GramingFoxTeam** [comment]
> > Hello,What is your gt version?
> > BTW if you know fix for cant place/break block say me
> > Thanks!
> 
> My gt version is latest version (v3.32)

fist of all get coredata file (https://github.com/NotDark/GrowtopiaItemDatabase)
Then go GrowtopiaItemDatabase folder and put these into the Your server folder.
I will give you items.dat download it and then put into the your server folder then delete the Growtopia cache folder (its at AppData/Local/)
Still have problem?Write your dc.

**Comment by Furkan125** [comment]
Guys thanks for helping i fix the problem. Now i can close this issue
