### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by GramingFoxTeam** [GrowtopiaNoobs/GrowtopiaServer#1293]
Hello again,
so when i play GTPS on pc no prob logging etc.
But if i play on my phone It gets to Updating items and then it gives 404 error.
Can someone help me? 
(Note : im running on python not xampp)

**Comment by FeryN77** [comment]
CDNContent57

**Comment by GramingFoxTeam** [comment]
> CDNContent57

how do i do that?

**Comment by FeryN77** [comment]
Wht ur discord

**Comment by GramingFoxTeam** [comment]
,,#1696

**Comment by GramingFoxTeam** [comment]
> Wht ur discord

,,#1696

**Comment by GramingFoxTeam** [comment]
> Wht ur discord

What is ur dc too?

**Comment by GramingFoxTeam** [comment]
Ok.Just fixed the issue.
If you have this problem : 
Go find CDNContent(there are 3 of them)and edit every single to CDNContent57
Then go start.py edit it
There are 127.0.0.1 ips.
Change them to your ipv4 adress(open cmd and then type "ipconfig")
Still have problem ?
Type your dc here.
