### ISSUE TITLE
Cant add admin.

### ISSUE THREAD

**Issue by GramingFoxTeam** [GrowtopiaNoobs/GrowtopiaServer#1298]
Hello,i want to add admin but i cant.
If anyone knows it can say it
![image](https://user-images.githubusercontent.com/29177546/78832679-57308480-79f4-11ea-8596-15e071510943.png)

**Comment by pytuz** [comment]
wtf...

**Comment by LaYellow** [comment]
can you atleast change your vs to english

**Comment by NotDark** [comment]
![image](https://user-images.githubusercontent.com/44568476/78857759-deb1de00-7a5c-11ea-8d16-0ce9740490e4.png)

**Comment by Zlarex** [comment]
Yes, because you put it on the wrong line

**Comment by MoanHawks** [comment]
why you add addAdmin outside int main() o.O

**Comment by GramingFoxTeam** [comment]
> why you add addAdmin outside int main() o.O

Do i need to add in there?

**Comment by GramingFoxTeam** [comment]
Guys.Someone can post an ss of it?Im confused.

**Comment by ardakurucim** [comment]
fonksiyonu yanlış yere koymuşsun

**Comment by ardakurucim** [comment]
discord ver yardım edeyim

**Comment by GramingFoxTeam** [comment]
> discord ver yardım edeyim

,,#1696 pnp

**Comment by GramingFoxTeam** [comment]
> discord ver yardım edeyim

Seninki ne?

**Comment by GrowtopiaNoobs** [comment]
Move that line slowly down, till it starts working for you, or if you want to work more effective, then learn C++.

**Comment by GramingFoxTeam** [comment]
> Move that line slowly down, till it starts working for you, or if you want to work more effective, then learn C++.

well i fixed rn by help of arda im closing.
