### ISSUE TITLE
[BUG] player_tribbutes.dat  NEW PATCH!??!

### ISSUE THREAD

**Issue by MarioBITs** [GrowtopiaNoobs/GrowtopiaServer#1300]
**Growtopia easter week update**

_When i put newest items.dat with compressed items.dat it's not working anymore stuck at 1/1 of updating items data....._
![image](https://user-images.githubusercontent.com/49722651/78904128-50624a00-7aa6-11ea-879a-dbcc64a0898d.png)

### if you have same issue of this don't make the issue again.

**Comment by Valkr1e** [comment]
wow pro bug 😳

**Comment by MarioBITs** [comment]
Closed, usual mistake
