### ISSUE TITLE
stuck on Located server, connecting... with AZURE VPS

### ISSUE THREAD

**Issue by Farhan1907s** [GrowtopiaNoobs/GrowtopiaServer#1305]
Hello Please help me it's my server using Vps from Azure, If you want to answer please detailed Thank you....

**Comment by MoanHawks** [comment]
Firewall rules azure

**Comment by Farhan1907s** [comment]
> Firewall rules azure

How to add them because there you need a lot, do you have discord? can you help me on discord?

**Comment by FeryN77** [comment]
Ez

**Comment by GuckTubeYT** [comment]
Firewall Rules Portal Azure

**Comment by GrowtopiaNoobs** [comment]
Closing this issue as it was answered and author created #1306
