### ISSUE TITLE
[ISSUE] Server 404

### ISSUE THREAD

**Issue by noobgt** [GrowtopiaNoobs/GrowtopiaServer#1313]
Ive been getting an issue where i would get Server gave a 404 bad file etc. Ive checked the CDNContent value its set to its val just still getting 404. Please help i need help ASAP!

**Comment by playingo2006** [comment]
You have to implement a fix for it. GrowtopiaNoobs didn't implement fix for it. You can get CDNContent with the way I've implemented just download growtopia and get it's download address and you will see CDNContent. (NOTE: This is fully implemented by me don't act like pro and pretend that it is your code or you will get DMCA striked.)

**Comment by Luc1Fer-LTPS** [comment]
playingo have discord?

**Comment by Luc1Fer-LTPS** [comment]
i dont understand

**Comment by xXAbood** [comment]
> You have to implement a fix for it. GrowtopiaNoobs didn't implement fix for it. You can get CDNContent with the way I've implemented just download growtopia and get it's download address and you will see CDNContent. (NOTE: This is fully implemented by me don't act like pro and pretend that it is your code or you will get DMCA striked.)

DMCA STRIKE YO

**Comment by xXAbood** [comment]
> i dont understand

khalifa ill tell u in discord

**Comment by Luc1Fer-LTPS** [comment]
ok delete ^

**Comment by GrowtopiaNoobs** [comment]
If `CDNContent` is outdated, then please create PR so I can merge it.

**Comment by playingo2006** [comment]
https://imgur.com/a/vVExFDs

**Comment by playingo2006** [comment]
> i dont understand

send me your discord I will teach you how to implement stuff.

**Comment by noobgt** [comment]
@playingo2006 whats ur disc

**Comment by playingo2006** [comment]
> @playingo2006 whats ur disc

give me yours.

**Comment by noobgt** [comment]
noоb#0947

**Comment by playingo2006** [comment]
> noоb#0947

Thank you. Added you to list of students who are trying to learn how to implement stuff. I will reach out to you soon as possible. Thanks for understanding. GTv3/growmmfi support. Best Regards.

**Comment by noobgt** [comment]
nty

**Comment by GrowtopiaNoobs** [comment]
Closing this issue, as problem was identified and there was created issue #1316 to solve it.
