### ISSUE TITLE
[QUESTION] Sign popup bubble, Door popup bubble.

### ISSUE THREAD

**Issue by ilyn1337** [GrowtopiaNoobs/GrowtopiaServer#132]
After spending times on it, I realize something... Its not from packets. Did anyone find that or do you have any ideas for Sign popup bubble?

**Comment by ritzysw** [comment]
You need to experiment with tile pointers(something like worldPtr in code),
or check gt bot to get data needed from real server

**Comment by Tryp0** [comment]
Once you do debug and compile bot, download the bot gui, and copy all dlls from there, and paste them in the folder where you compiled gt bot, then use it from qt creator.

**Comment by FKSP** [comment]
ok, but what compiler to use and how I can setup it?

**Comment by ilyn1337** [comment]
thanks @ritzysw
