### ISSUE TITLE
[BUG] breakHits are messed up.

### ISSUE THREAD

**Issue by noobsteak** [GrowtopiaNoobs/GrowtopiaServer#1324]
Block breaking is broken...
Public lava takes 22 hits to break.

**Comment by noobgt** [comment]
check breakHits maybe ((PlayerInfo*)(peer->data))->breakHits

**Comment by MoanHawks** [comment]
i am not programming C++ but I know the bug is in this line only 😳 https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/0d5117e60606c5b1aaf03d171dbc10a59dfc41e4/enet%20server%20test/enet%20server%20test.cpp#L1263

**Comment by GrowtopiaNoobs** [comment]
It should be solved by #1327, please let us know if everything works as excepted.

**Comment by noobsteak** [comment]
Thanks
