### ISSUE TITLE
[QUESTION] How to wrench other players?

### ISSUE THREAD

**Issue by mar4ello6** [GrowtopiaNoobs/GrowtopiaServer#133]

**Comment by WarXYZ** [comment]
Ye i want this too, How to wrench other players

**Comment by DarkTitanMC** [comment]
You need to code it

**Comment by niko1802** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/commit/1fd1823ee796f197958d74b07e441267afd44db7

**Comment by mar4ello6** [comment]
Thanks @niko1802 !
