### ISSUE TITLE
Who is working with CoreData for Private Server right now?

### ISSUE THREAD

**Issue by WarXYZ** [GrowtopiaNoobs/GrowtopiaServer#134]

**Comment by NotDark** [comment]
you can check my fork for coredata but me no updated newest item yet

**Comment by WarXYZ** [comment]
> you can check my fork for coredata but me no updated newest item yet

thanks sm

**Comment by vonsogt** [comment]
> you can check my fork for coredata but me no updated newest item yet

your discord name?
