### ISSUE TITLE
[BUG] Worlds selection issue

### ISSUE THREAD

**Issue by failanas** [GrowtopiaNoobs/GrowtopiaServer#1340]
Doesn't let to create or select the world. Blue rectangular in the center of the screen. Any ideas?

Screenshot:
https://ibb.co/n7GSfCJ

**Comment by noobsteak** [comment]
Issue with news dialog.

**Comment by failanas** [comment]
> Issue with news dialog.

is any solution to solve that issue?

**Comment by GrowtopiaNoobs** [comment]
I have added patch into source, please download source again and try out if everything works now.

**Comment by failanas** [comment]
SOLVED: you are the star!
