### ISSUE TITLE
[BUG] Can't create GrowID and commands don't work.

### ISSUE THREAD

**Issue by failanas** [GrowtopiaNoobs/GrowtopiaServer#1342]
Can't create GrowID and commands don't work.

**Comment by DrOreo002** [comment]
We're not a wizard.. at least provide us with error logs (if there's any) or a video or anything that will explain your problem further instead of just typing 1 sentence here

**Comment by GrowtopiaNoobs** [comment]
The bug with GrowID should be fixed now, try to download new source. And what issue with commands do you have?

**Comment by failanas** [comment]
GrowID is okay now. Thank you!
Regarding the commands, for instance /find should show dialog box https://ibb.co/60pF2RM 
also would be nice to have commands:
/freeze
/invisible
/addmod
/ipban

**Comment by GrowtopiaNoobs** [comment]
I am not adding new features myself and keeping it up to community, so if you want those features then please create issue and kindly ask for PR. And that stuff with find isn't actually bug. It works like this `/find Dirt` and doesn't show any dialog.

**Comment by failanas** [comment]
Thanks!
