### ISSUE TITLE
[QUESTION] What tutorial to watch?

### ISSUE THREAD

**Issue by awsumturtle** [GrowtopiaNoobs/GrowtopiaServer#1348]
What tutorial should i watch so i know what to do in the project? I have no idea.

**Comment by awsumturtle** [comment]
Like, what am i supposed to watch to know what to do what i want? I am clueless as to what i should watch

**Comment by noobsteak** [comment]
Learn basics of c++ here
http://cplusplus.org

**Comment by awsumturtle** [comment]
Ok. Is there something i should do after that or will i be okay with that?

**Comment by noobsteak** [comment]
You should be okay after that. Good luck

**Comment by awsumturtle** [comment]
Thank you alot!
