### ISSUE TITLE
Custom Cache File [QUESTION] 

### ISSUE THREAD

**Issue by Furkan125** [GrowtopiaNoobs/GrowtopiaServer#1352]
Guys how can i make custom cache file for my server ?

**Comment by DrOreo002** [comment]
what do you mean by custom cache?

**Comment by Surekings** [comment]
> Guys how can i make custom cache file for my server ?

#1304

**Comment by Furkan125** [comment]
> what do you mean by custom cache?

i need to change textures of items for my private server

**Comment by Furkan125** [comment]
> > Guys how can i make custom cache file for my server ?
> 
> #1304

I download Custom item pack release (#1304) but idk how can i use ?
