### ISSUE TITLE
[QUESTION] Mod added and mod removed.

### ISSUE THREAD

**Issue by pytuz** [GrowtopiaNoobs/GrowtopiaServer#1354]
Does someone know how to make like if we equip items, it will show mod added
And if we unequip the items, it will show mod removed

**Comment by luc1fer-1337** [comment]
use pMov->plantingTree

**Comment by luc1fer-1337** [comment]
add a gamepacket of onconsolemessage and add ur text

**Comment by luc1fer-1337** [comment]
example:

if (pMov->plantingTree == itemid)
									{
										sendConsoleMsg(peer, "your effect");
										break;
									}

**Comment by pytuz** [comment]
yea ik but how about the mod removed?

**Comment by luc1fer-1337** [comment]
make a new .txt for ur effects like void UpdateClothingEffect(ENetPeer* peer, pMov->plantingTree) and make a txt file with all effects like (ClothEffects.txt)

**Comment by luc1fer-1337** [comment]
then add like

<itemid>|<item effect text>
<itemid>|<item effect text>

**Comment by luc1fer-1337** [comment]
id|effect text
id|effect text

**Comment by luc1fer-1337** [comment]
@pytuz check #1355

**Comment by pytuz** [comment]
nvm found it.
