### ISSUE TITLE
Clothingeffects builder based off anybody's decoder

### ISSUE THREAD

**Issue by xXAbood** [GrowtopiaNoobs/GrowtopiaServer#1359]
https://github.com/xXAbood/ClothingeffectsBuilder
you need the items.dat in the same path but enjoy.
Contribute to #1355

**Comment by bykoi** [comment]
epic ctrl c ctrl v from my repo

**Comment by Surekings** [comment]
> https://github.com/xXAbood/ClothingeffectsBuilder
> you need the items.dat in the same path but enjoy.

Thanks, helped so much 👍

**Comment by cmdocmdd** [comment]
Wow even the title name is copied from byko

**Comment by xXAbood** [comment]
> Wow even the title name is copied from byko
feels bad u got banned :(

**Comment by xXAbood** [comment]
![image](https://user-images.githubusercontent.com/59313717/80341846-354c5400-8874-11ea-9dd2-1824f603cf54.png)
i wouldnt like to be annoying as you are, so instead im just going to ignore you after this message

**Comment by cmdocmdd** [comment]
This source is made by Byko
https://github.com/bykoi/CoreDataBuilder/issues/1
Abood just taking byko’s work and pretend that it is his work

**Comment by xXAbood** [comment]
pretend sure

**Comment by xXAbood** [comment]
> This source is made by Byko
> 
> https://github.com/bykoi/CoreDataBuilder
> 
> Abood just taking byko’s work and pretend that it is his work

i mean just so you know. 
![image](https://user-images.githubusercontent.com/59313717/80368866-735e6d80-889e-11ea-959a-6ad0ccab75bb.png)

**Comment by cmdocmdd** [comment]
![d2](https://user-images.githubusercontent.com/64281837/80375997-3a2bfa80-88aa-11ea-9211-73933fa638b0.PNG)
yeah sure

**Comment by xXAbood** [comment]
> ![d2](https://user-images.githubusercontent.com/64281837/80375997-3a2bfa80-88aa-11ea-9211-73933fa638b0.PNG)
> yeah sure

![image](https://user-images.githubusercontent.com/59313717/80392168-d90f2180-88bf-11ea-8954-40764f08d62b.png)
bro

**Comment by cmdocmdd** [comment]
yes he meant to use items.dat decoder that dark made pull request based on Anybody decoder not to steal bykos codes and saying its urs

**Comment by xXAbood** [comment]
when i try to change the topic

**Comment by Bexpg1337** [comment]
L0L
