### ISSUE TITLE
Growtale CPP

### ISSUE THREAD

**Issue by pytuz** [GrowtopiaNoobs/GrowtopiaServer#1360]
https://github.com/pytuz/growtale

enjoy :) don't forget to credit me 

this what you want right @timetopia

**Comment by GuckTubeYT** [comment]
yey

**Comment by MoanHawks** [comment]
if 
else if 
else if 
else if

**Comment by TimeTopia** [comment]
1st of all u guys think i leaked but didnt knew my discord was hacked secondly u are the one leaked it so whatever

**Comment by Alexander9673** [comment]
damn, so many leaks happened, yet still none of them use a proper database.

**Comment by xXAbood** [comment]
for some reason people think that theyre called "leaks" but k

**Comment by Alexander9673** [comment]
:shrug:

**Comment by finland1337** [comment]
Wheres credits for using Project Cold?

**Comment by pppzk** [comment]
Damn

**Comment by Granger-spec** [comment]
why it dont have setconsole?

**Comment by InjectionZ** [comment]
> Wheres credits for using Project Cold?

yes

**Comment by MoanHawks** [comment]
but I see only
if
else if
else if
else if
else

**Comment by freestylehero** [comment]
> only i see is
> if
> else if
> else if
> else if
> else

well, its leaked or yeah... like thats why its "leaked".

**Comment by Granger-spec** [comment]
why the cpp only?

**Comment by TimeTopia** [comment]
Lmao who wants the full folder dm me in discord TimeTopia#0001

**Comment by Orbit4682** [comment]
Lmao this is so fake

**Comment by raiterjaki** [comment]
fp! where sln 😡

**Comment by raiterjaki** [comment]
You forgot to credit Growtopia Noobs (Anybody) the guy who deserves the most credit.
