### ISSUE TITLE
Packet drop

### ISSUE THREAD

**Issue by xXAbood** [GrowtopiaNoobs/GrowtopiaServer#1361]
Packet drops whenever a player is logging in to update the item data, any solutions

**Comment by cmdocmdd** [comment]
Retard because you steal other’s works and saying its yours while you dont even know how to read from a txt file im not going to help you

**Comment by NotDark** [comment]
![image](https://user-images.githubusercontent.com/44568476/80360731-59c72100-88b2-11ea-8e6a-72ea2f921603.png) 
![image](https://user-images.githubusercontent.com/44568476/80360755-651a4c80-88b2-11ea-877e-fc095a129bbd.png) set to false

**Comment by MoanHawks** [comment]
I hope someone create the PR 😳

**Comment by xXAbood** [comment]
thanks alot
