### ISSUE TITLE
Config.json

### ISSUE THREAD

**Issue by JokerST1337** [GrowtopiaNoobs/GrowtopiaServer#1365]
void loadConfig()
{

	cout << "[!] loading config" << endl;
	std::ifstream ifs("config.json");
	if (ifs.is_open()) {

		json j;
		ifs >> j;

		configPort = j["Port"];
		music = j["Music"].get<string>();

		cout << "[~] Config loaded." << endl;
		cout << "[-] Hosting on Port: " << configPort << endl;
		cout << "[!] Music theme: " << music << endl;

	}

How i can convert this as config.json Help me please

**Comment by JadlionHD** [comment]
there's something wrong with the port
`configPort = j["Port"].get<int>();`

also for your json file its something like this
```
{
	"Port": 17091,
	"Music": "Your music goes here"
}
```

**Comment by JokerST1337** [comment]
> there's something wrong with the port
> `configPort = j["Port"].get<int>();`
> 
> also for your json file its something like this
> 
> ```
> {
> 	"Port": 17091,
> 	"Music": "Your music goes here"
> }
> ```

THank you so much it helped me alot
