### ISSUE TITLE
[QUESTION] Updating to 14/16 items and after get 404 error

### ISSUE THREAD

**Issue by Denis3947** [GrowtopiaNoobs/GrowtopiaServer#1367]
ok so basically when i try to join my private server i update 14/16 items and after i got a 404 error....
![Growtopia_qfQCVFfk1P](https://user-images.githubusercontent.com/64543722/80612526-5f507280-8a3c-11ea-9d0a-770203df9fcf.png)
Can someone help me pls?

**Comment by MoanHawks** [comment]
change you CDN

**Comment by Denis3947** [comment]
> change you CDN

I already changed it

**Comment by MoanHawks** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/pull/1362

read this before I kill you

**Comment by Denis3947** [comment]
> #1362
> 
> read this PR before I kill you :)

This #1362 PR isn't working ;3
![devenv_pZj7ysjhve](https://user-images.githubusercontent.com/64543722/80618559-d2111c00-8a43-11ea-85f1-67b19482df77.png)

**Comment by Granger-spec** [comment]
> ok so basically when i try to join my private server i update 14/16 items and after i got a 404 error....
> ![Growtopia_qfQCVFfk1P](https://user-images.githubusercontent.com/64543722/80612526-5f507280-8a3c-11ea-9d0a-770203df9fcf.png)
> Can someone help me pls?

I have the prob too Login in real gt then get thr items.dat then put it in ur private server file

**Comment by cmdocmd** [comment]
just get items.dat for real gt

**Comment by Denis3947** [comment]
Ok Thanks Guys You're all awsome!

Thanks for support
