### ISSUE TITLE
Question Getting address

### ISSUE THREAD

**Issue by Bexpg1337** [GrowtopiaNoobs/GrowtopiaServer#1368]
How to add When people getting address if many time spam auto crash gt or auto ban player

**Comment by DrOreo002** [comment]
What do you mean by getting address?

**Comment by Bexpg1337** [comment]
@DrOreo002  Http Get/post server.data.php and this 
![Screenshot_20200430-061041_Growtopia](https://user-images.githubusercontent.com/64568184/80668029-68c3f400-8aa9-11ea-9dc5-1859c1d7103e.jpg)

**Comment by Bexpg1337** [comment]
How i can make if people 2 time Post or Get server.data.php Auto ban or auto crash gt

**Comment by DrOreo002** [comment]
Not sure why you think that its a good idea tho but well it you would need to edit the http server's code, its at python I believe. Then you will have to know how to deal with database, so you can mark that IP as a banned IP into your 'banned ip' database.

**Comment by Bexpg1337** [comment]
> Not sure why you think that its a good idea tho but well.., so you would need to edit the http server's code, to check if there's a same IP address requesting to get the server_data.php between your specified time, 2 second for example. Then you will have to know how to deal with database, so you can mark that IP as a banned IP into your 'banned ip' database.
> 
> That's the simplest explanation that I can give, if you really know how to code this should be easy for ya

Thanks, i think Buying Layer 7 protect will help me i have one more questions how i can Block people login if there 50 players online "Example 50 players online please try again later"

**Comment by freestylehero** [comment]
if (peer.count > 50) consolemsg("hey, 50 plrs alr online")

**Comment by Bexpg1337** [comment]
> if (peer.count > 50) consolemsg("hey, 50 plrs alr online")

Thanks
