### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by yua1133** [GrowtopiaNoobs/GrowtopiaServer#1374]
server crashed when using aux guest name

**Comment by DrOreo002** [comment]
Need more information, you can't just said something is not working without providing extra information. We're not going to search through your problem with 0 extra information.

**Comment by yua1133** [comment]
> Need more information, you can't just said something is not working without providing extra information. We're not going to search through your problem with 0 extra information.

**Comment by yua1133** [comment]
without regiser using name LPT0 , LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9
COM0, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9
AUX, PRN, NUL, CON will crash the server

**Comment by yua1133** [comment]
i found a bug on my server, when i use guest and make name like "LPT0 , LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9
COM0, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9
AUX, PRN, NUL, CON" and enter server,the server will auto crash.

**Comment by Bexpg1337** [comment]
Then add ur server if someone enter name aux,prn etc. Auto disconnect

**Comment by Bexpg1337** [comment]
Also i think if u enter aux prn etc. Server will be crash too

**Comment by MoanHawks** [comment]
imagine load json file with name LPT0 , LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9
COM0, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9
AUX, PRN, NUL, CON 😳

**Comment by atomiclucky** [comment]
use linux, so hard to make a fix

**Comment by DrOreo002** [comment]
> when i use guest and put name like "LPT0 , LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9
> COM0, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9
> AUX, PRN, NUL, CON" and enter server,the server will auto crash.

Don't allow it then?. You can easily do so by checking the string, if it exactly equals to that then disconnect the player

**Comment by herothedev** [comment]
on this repo they're alr fixed.

**Comment by yua1133** [comment]
fixed closing this issue

**Comment by yua1133** [comment]
see
