### ISSUE TITLE
[QUESTION] How to Block /Proxy/Bot From server

### ISSUE THREAD

**Issue by Bexpg1337** [GrowtopiaNoobs/GrowtopiaServer#1379]
How to block proxy/bot from server i know no one will say because everyone using but anyway maybe any pro coder not will scare and say?

**Comment by MoanHawks** [comment]
https://github.com/GrowtopiaNoobs/Growtopia-Bot/blob/373d101e28870bdb3c9b47a8c5b24c2f24683af0/Growtopia_Bot/corefunc.h#L183

**Comment by Bexpg1337** [comment]
@MoanHawks  Not work

**Comment by Bexpg1337** [comment]
Deerux proxy can connect if i use this

**Comment by Bexpg1337** [comment]
void connectClient(string hostName, int port)
{
	client = enet_host_create(NULL /* create a client host */,
		1 /* only allow 1 outgoing connection */,
		2 /* allow up 2 channels to be used, 0 and 1 */,
		0 /* 56K modem with 56 Kbps downstream bandwidth */,
		0 /* 56K modem with 14 Kbps upstream bandwidth */);
	if (client == NULL)
	{
		cout << "An error occurred while trying to create an ENet client host.\n";
		_getch();
		exit(EXIT_FAILURE);
	}

	//enet_crc32(0, 0);



	ENetAddress address;
	
	client->checksum = enet_crc32;
	enet_host_compress_with_range_coder(client);
	enet_address_set_host(&address, hostName.c_str());
	address.port = port;
	/* Initiate the connection, allocating the two channels 0 and 1. */
	peer = enet_host_connect(client, &address, 2, 0);
	if (peer == NULL)
	{
		cout << "No available peers for initiating an ENet connection.\n";
		_getch();
		exit(EXIT_FAILURE);
	}

	enet_host_flush(client);
}

**Comment by Bexpg1337** [comment]
@MoanHawks  i need paste this right?

**Comment by MoanHawks** [comment]
no

**Comment by Bexpg1337** [comment]
What i need do please give me more information

**Comment by Bexpg1337** [comment]
@GrowtopiaNoobs  u made this sh*t gt bot help we to solve problem wtf also ur code crash to with deerux send collect packet

**Comment by Surekings** [comment]
> @GrowtopiaNoobs u made this sh*t gt bot help we to solve problem wtf also i builded this code and ur exe crash too with deerux send collect packet

Hey chill,if GrowtopiaNoobs didnt release the source ENet, you will not here fool

**Comment by DrOreo002** [comment]
> @GrowtopiaNoobs u made this sh*t gt bot help we to solve problem wtf also i builded this code and ur exe crash too with deerux send collect packet

Wowowow chill bro, whats wrong with you?, he gave bot, and private server to this community for free and you're blaming him?. Even actual server of Growtopia didn't manage to block bots...

**Comment by MoanHawks** [comment]
😳

**Comment by Bexpg1337** [comment]
> > @GrowtopiaNoobs u made this sh*t gt bot help we to solve problem wtf also i builded this code and ur exe crash too with deerux send collect packet
> 
> Hey chill,if GrowtopiaNoobs didnt release the source ENet, you will not here fool
I dont using growtipia noobs server i made my own server with c#

**Comment by Bexpg1337** [comment]
I would use capslock if I wasn't already calm. and I can say that a really garbage project nothing works, even the most crappy game runs better than this  If this project was sold for money, I can be sure that no one would buy it, because this is really a garbage project and no effort was made.

**Comment by Bexpg1337** [comment]
Perhaps the only problem is that it is free, if you did not give it for free, and maybe you would be more interested because you would be making money

**Comment by DrOreo002** [comment]
> I would use capslock if I wasn't already calm. and I can say that a really garbage project nothing works, even the most crappy game runs better than this If this project was sold for money, I can be sure that no one would buy it, because this is really a garbage project and no effort was made.

lol?, what's your problem?, there's no way this project is garbage when you still here asking for help then use this project's code as your references.

Anyway, no. There's no way you can block "bots" that just how the GT supposed to work, no "bots" blocking built in. Or maybe you can make your player base takes more time to go to your server by forcing them to register through a website

**Comment by MoanHawks** [comment]
> > I would use capslock if I wasn't already calm. and I can say that a really garbage project nothing works, even the most crappy game runs better than this If this project was sold for money, I can be sure that no one would buy it, because this is really a garbage project and no effort was made.
> 
> lol?, what's your problem?, there's no way this project is garbage when you still here asking for help then use this project's code as your references.
> 
> Anyway, no. There's no way you can block "bots" that just how GT supposed to work, no "bots" blocking built in. Or maybe you can make your player base takes more time to go to your server by forcing them to register through a website then they can log in into your server.
> 
> Like literally real Growtopia server couldn't even handle the bots because it does exactly the same as the client does

Imagine ubisoft made Growtopia using enet  :flushed: 

https://github.com/GrowtopiaNoobs/Growtopia-Bot/blob/373d101e28870bdb3c9b47a8c5b24c2f24683af0/Growtopia_Bot/corefunc.h#L183

Already give you some hint if you can't do it please stop coding ty👌

**Comment by DrOreo002** [comment]
@MoanHawks okay?. Its already built using enet right?

**Comment by MoanHawks** [comment]
> @MoanHawks okay?. Its already built using enet right?

Excuse me not for ubisoft

**Comment by Bexpg1337** [comment]
@DrOreo002 

If its not possible vyte how blocked? When i enter vyte server with bot i stuck located server connecting

**Comment by DrOreo002** [comment]
> > @MoanHawks okay?. Its already built using enet right?
> 
> Excuse me not for ubisoft
> 
> If ubisoft made growtopia using enet the Growtopia bot/proxy will no work anymore

Interesting, proof me then.



> @DrOreo002
> 
> If its not possible vyte how blocked? When i enter vyte server with bot i stuck located server connecting

Hm?, alright then. Might take a look at that later on

**Comment by MoanHawks** [comment]
bot Connect to -> IP 127.0.0.1 port 17091 (client) -> IP 127.0.0.1 port 17093 Create it you self client like proxy Same like OnSendToServer but https://github.com/GrowtopiaNoobs/Growtopia-Bot/blob/373d101e28870bdb3c9b47a8c5b24c2f24683af0/Growtopia_Bot/corefunc.h#L183
-> Connet another Server with port 17098 IP 127.0.0.1

**Comment by DrOreo002** [comment]
> bot Connect to -> IP 127.0.0.1 port 17091 (client) -> IP 127.0.0.1 port 17093 Create it you self client like proxy Same like OnSendToServer but https://github.com/GrowtopiaNoobs/Growtopia-Bot/blob/373d101e28870bdb3c9b47a8c5b24c2f24683af0/Growtopia_Bot/corefunc.h#L183
> -> Connet another Server with port 17098 IP 127.0.0.1
> 
> Understand?

Not really sure what you're talking about there..., ubisoft or vyte's server?

also

**Excuse me not for ubisoft**

You sure told me that ubisoft doesn't use enet right?. Where you clearly shows me a "connection" log and then **Create it you self client like proxy Same like OnSendToServer** that **create it yourself** should implement implement enet right?

**Comment by Bexpg1337** [comment]
u explain subserver bruh

**Comment by DrOreo002** [comment]
> u explain subserver bruh

xD, yeah I think so. Sub server are clearly made with enet, already implemented it to work for my bot tho. Pretty strange that he said **Excuse me not for ubisoft**

**Comment by MoanHawks** [comment]
> > Like literally real Growtopia server couldn't even handle the bots because it does exactly the same as the client does
>

**Comment by Bexpg1337** [comment]
i still dont understand how to block bot i need redirects bot to other ports?

**Comment by DrOreo002** [comment]
> > > Like literally real Growtopia server couldn't even handle the bots because it does exactly the same as the client does

Okay?, what exactly you're telling me here?. I'm confused so bad

Or maybe you misunderstand **couldn't even handle the bots**?. That revers to many bot that growtopia fails to block.

**Comment by MoanHawks** [comment]
> bot Connect to -> IP 127.0.0.1 port 17091 (client) -> IP 127.0.0.1 port 17093 Create it you self client like proxy Same like OnSendToServer but https://github.com/GrowtopiaNoobs/Growtopia-Bot/blob/373d101e28870bdb3c9b47a8c5b24c2f24683af0/Growtopia_Bot/corefunc.h#L183
> -> Connet another Server with port 17098 IP 127.0.0.1
> 
> Understand?
> 
> The bot stuck at 17093 port is very simple

@Bexpg1337 very simple if can't do it you self please stop coding ty

**Comment by Bexpg1337** [comment]
i still dont understand how to block bot i need redirects bot to other ports?

**Comment by MoanHawks** [comment]
> i still dont understand how to block bot i need redirects bot to other ports?

That you self already give you hint

**Comment by Bexpg1337** [comment]
u very bad at explain

**Comment by DrOreo002** [comment]
> i still dont understand how to block bot i need redirects bot to other ports?

Its no use, actual gt server already made one. They have `OnSendToServer` packet that told your "client" to connect into the ip and port that the packet provided. Basically "forwarding" your bot into other server

**Comment by MoanHawks** [comment]
Yes because my English bad 

https://github.com/GrowtopiaNoobs/Growtopia-Bot/blob/373d101e28870bdb3c9b47a8c5b24c2f24683af0/Growtopia_Bot/corefunc.h#L183

^^^^^^^^

**Comment by DrOreo002** [comment]
What other private server uses to "block" bot prolly a different channel at enet. I'll try to check if that's what causing it later

**Comment by Bexpg1337** [comment]
How i can catch if its bot/proxy?

**Comment by MoanHawks** [comment]
> > i still dont understand how to block bot i need redirects bot to other ports?
> 
> Its no use, actual gt server already made one. They have `OnSendToServer` packet that told your "client" to connect into the ip and port that the packet provided. Basically "forwarding" your bot into other server

Then you don't think bot can create packet OnSendToServer?

**Comment by Bexpg1337** [comment]
How i can catch if its bot/proxy?

**Comment by DrOreo002** [comment]
> > > i still dont understand how to block bot i need redirects bot to other ports?
> > 
> > 
> > Its no use, actual gt server already made one. They have `OnSendToServer` packet that told your "client" to connect into the ip and port that the packet provided. Basically "forwarding" your bot into other server
> 
> Then you don't think The bot can create packet OnSendToServer?

Hmm yes?. What I know is that the server send that packet into my bot. Then I accept it and connect to the IP and port that packet provided me with.

**Comment by xXAbood** [comment]
> @DrOreo002
> 
> If its not possible vyte how blocked? When i enter vyte server with bot i stuck located server connecting

when was it even blocked?

**Comment by DrOreo002** [comment]
> > @DrOreo002
> > If its not possible vyte how blocked? When i enter vyte server with bot i stuck located server connecting
> 
> when was it even blocked?

Its blocked apparently, for some reason 😂 I'm taking a look at this now. And it seems like it doesn't send any other information after I successfully connected using my proxy's enet client

But by using Wireshark there's no packet being sent from the private server into my client

**Comment by Bexpg1337** [comment]
Im so confused so what i need do to block proxy/bot in my server

**Comment by Surekings** [comment]
@GrowtopiaNoobs Please take care of this issue? bullying Your reposity

**Comment by Bexpg1337** [comment]
> @GrowtopiaNoobs Please take care of this issue? bullying Your reposity.
> Ban @Bexpg1337 at this repo

@Surekings  H3 hav3 brain niga you cant judge @GrowtopiaNoobs

**Comment by GrowtopiaNoobs** [comment]
@Bexpg1337 You are banned as of #1258
