### ISSUE TITLE
Bug with updating items on IOS

### ISSUE THREAD

**Issue by SecretHax** [GrowtopiaNoobs/GrowtopiaServer#138]
Bug with updating items on IOS, whats the cache folder that IOS client use?

**Comment by Mempler** [comment]
Should be the same as every other GT

**Comment by SecretHax** [comment]
> Should be the same as every other GT

Habe /cache auf meinen Server, auf pc und android geht es, auf IOS kriege ich 404 Fehler

**Comment by Mempler** [comment]
Hmm, das ist seltsam. Ich hab keine Ahnung tbh.
Hab halt kein IOS Device xD

**Comment by SecretHax** [comment]
>Hmm, das ist seltsam. Ich hab keine Ahnung tbh. ...

@Mempler Hm, aber server code hat doch /cache und IP drin, so das kann nicht folder name sein. Vielleicht IOS benutzt anderen photo format, oder so? Und darum gibt er 404 raus?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SecretHax** [comment]
>Hmm, das ist seltsam. Ich hab keine Ahnung tbh. ...

@Mempler btw, habe paar Tage her entdeckt das du auch Deutscher bist 😂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ilyn1337** [comment]
OnSuperMainStartAcceptLogonHrdxs47254722215a"), HASH), "ubistatic-a.akamaihd.net"), "0098/CDNContent3/cache/") ...

I think
