### ISSUE TITLE
[QUESTION] How to change Apk ip

### ISSUE THREAD

**Issue by Bexpg1337** [GrowtopiaNoobs/GrowtopiaServer#1380]
How to change apk ip

**Comment by GramingFoxTeam** [comment]
You can look this https://github.com/MarmoriPelaa/GTPatcher-Android

**Comment by Surekings** [comment]
or you can use apk easy tool

**Comment by Bexpg1337** [comment]
> You can look this https://github.com/MarmoriPelaa/GTPatcher-Android

i tryed use but i have problem with java

**Comment by GramingFoxTeam** [comment]
> > You can look this https://github.com/MarmoriPelaa/GTPatcher-Android
> 
> i tryed use but i have problem with java
get on here https://github.com/MarmoriPelaa/GTPatcher-Android/releases

**Comment by Bexpg1337** [comment]
> > > You can look this https://github.com/MarmoriPelaa/GTPatcher-Android
> > 
> > 
> > i tryed use but i have problem with java
> > get on here https://github.com/MarmoriPelaa/GTPatcher-Android/releases


How to use? I need drag gt.apk file in where

**Comment by GramingFoxTeam** [comment]
> > > > You can look this https://github.com/MarmoriPelaa/GTPatcher-Android
> > > 
> > > 
> > > i tryed use but i have problem with java
> > > get on here https://github.com/MarmoriPelaa/GTPatcher-Android/releases
> 
> How to use? I need drag gt.apk file in where

Didnt you used any cmd?
First of drag to your Desktop, then type this:
cd C:\Users\Your username here\Desktop

**Comment by Bexpg1337** [comment]
> > > > > You can look this https://github.com/MarmoriPelaa/GTPatcher-Android
> > > > 
> > > > 
> > > > i tryed use but i have problem with java
> > > > get on here https://github.com/MarmoriPelaa/GTPatcher-Android/releases
> > 
> > 
> > How to use? I need drag gt.apk file in where
> 
> Didnt you used any cmd?
> First of drag to your Desktop, then type this:
> cd C:\Users\Your username here\Desktop
> Then type :
> java -jar GrowtopiaPatcher.jar [alternative ip address]
> Note:drag GrowtopiaPatcher.jar to the desktop too.

Me no used me nab btw what is cmd?

**Comment by Bexpg1337** [comment]
@GramingFoxTeam what is alternstive address

**Comment by GrowtopiaNoobs** [comment]
@Bexpg1337 You are banned as of #1258

**Comment by GramingFoxTeam** [comment]
f
