### ISSUE TITLE
[QUESTION] how to change apk app name

### ISSUE THREAD

**Issue by Bexpg1337** [GrowtopiaNoobs/GrowtopiaServer#1385]
![Screenshot_20200504-231820_Package installer](https://user-images.githubusercontent.com/64568184/81009579-96b88800-8e5d-11ea-896a-3f62b1231ce7.png)
I changed my gt apk ip address but how  i can change apk name?

**Comment by GramingFoxTeam** [comment]
Apk editor.You can download on internet.

**Comment by GramingFoxTeam** [comment]
Btw im Turkish too:D

**Comment by Bexpg1337** [comment]
> Btw im Turkish too:D

Selamun aleyküm reizzz

**Comment by Bexpg1337** [comment]
@GramingFoxTeam  hangi kısımdan değiştiriliyor ? Bu sürü kısım var

**Comment by GramingFoxTeam** [comment]
> @GramingFoxTeam  hangi kısımdan değiştiriliyor ? Bu sürü kısım var

Senin apk editor apk yı indirmen lazım sonra düzenle ye tıkla apk yı seçip

**Comment by Bexpg1337** [comment]
> > @GramingFoxTeam  hangi kısımdan değiştiriliyor ? Bu sürü kısım var
> 
> Senin apk editor apk yı indirmen lazım sonra düzenle ye tıkla apk yı seçip

Tamamda hangi kısımdan adı degistirecem

**Comment by Bexpg1337** [comment]
![Screenshot_20200504-234215_APK Parser](https://user-images.githubusercontent.com/64568184/81011606-e9e00a00-8e60-11ea-8bca-997cb825126b.png)
Bunların hangisinden?

**Comment by Bexpg1337** [comment]
@GramingFoxTeam

**Comment by Bexpg1337** [comment]
i found way no need help.

**Comment by Bexpg1337** [comment]
i found way no need help.
