### ISSUE TITLE
[QUESTION] how to block everyone from using an item

### ISSUE THREAD

**Issue by manksetip** [GrowtopiaNoobs/GrowtopiaServer#1388]

**Comment by raiterjaki** [comment]
If you have store in your server then you can look at its code and make one that no one will be able to wear.

**Comment by cmdocmd** [comment]
check packettype == 10

**Comment by iProgramMC** [comment]
If you mean placing an item, check the `item` variable in `sendTileUpdate` and return if `item` is the ID you wanna block.
If you mean wearing a clothing item, just `break` when you wear the blocked item (packet type == 10)
