### ISSUE TITLE
[QUESTION] "Subserver"

### ISSUE THREAD

**Issue by bexpg1377** [GrowtopiaNoobs/GrowtopiaServer#1389]
What logic does the sub-server run? Is it possible to open more than 1 application on a single computer or redirect to other threads if 1 sub server crashes on different threads?  growtopia using  1 ip address or have more than 1 ip address why i am asking here because i want to add my private server i already added mysql and i want add subserver too i would be glad if you help about subserver

**Comment by cmdocmd** [comment]
do you even know what subserver mean ?

**Comment by bexpg1377** [comment]
> do you even know what subserver mean ?

Yea alt server

**Comment by bexpg1377** [comment]
> do you even know what subserver mean ?

i want to know what is subserver that why i open this issue. And i want to know subserver work method.

**Comment by bexpg1377** [comment]
If i am right i think if 127.0.0.1 ip crash server redirect 127.0.0.2 and i want know i can make subserver with single ip or no

**Comment by cmdocmd** [comment]
1- yes you can make for same ip
2- subserver is just for send u to other server 
and if first server crashed it will not send you to the second server...

**Comment by bexpg1377** [comment]
> 1- yes you can make for same ip
> 2- subserver is just for send u to other server
> and if first server crashed it will not send you to the second server...

1- If  server crash and it not sending players to other server what point use subserver. 
2- how make subserver  in single  ip change port Rebuild or what?
3- why no one using mysql it have many point if we keep data in mysql worlds/players/ also another point is  we can use our server with different ip

**Comment by Alexander9673** [comment]
you can actually

**Comment by Alexander9673** [comment]
you can detect if it closes/crashes, you can automatically reopen one with a different port. but make sure that your http server also supports that feature.

**Comment by Alexander9673** [comment]
it's not called a subserver tho.

**Comment by bexpg1377** [comment]
If i use different port i need use multiple server_data.php Lol

**Comment by bexpg1377** [comment]
I cant use 2server_data.php in One ip  so stop give false info lmao

**Comment by Alexander9673** [comment]
What false info? You can recode .php file so easily to allow dynamic ports. I can also make it on nodejs for webservers to alloe dynamic web server ports

**Comment by Alexander9673** [comment]
You can also recode the python script to make it work. Also you code in C# right? Why not make a webserver there

**Comment by Alexander9673** [comment]
To check for crashes tho, you would have to check if the server port is being used, if it's not, server offline. If it is, it's online

**Comment by bexpg1377** [comment]
> What false info? You can recode .php file so easily to allow dynamic ports. I can also make it on nodejs for webservers to alloe dynamic web server ports

Do it and release on ue github

**Comment by Alexander9673** [comment]
why should i release it @bexpg1377

**Comment by noobsteak** [comment]
He's not appreciating GrowtopiaNoobs work and wants help from GrowtopiaNoobs repo. ????????????

**Comment by bexpg1377** [comment]
> why should i release it @bexpg1377

u said LOL i know u dont know code i just tested you and u failed.

**Comment by bexpg1377** [comment]
> He's not appreciating GrowtopiaNoobs work and wants help from GrowtopiaNoobs repo. ????????????

Apa kontol memek?

**Comment by Lapada** [comment]
> > why should i release it @bexpg1377
> 
> u said LOL i know u dont know code i just tested you and u failed.

u mean ur salty because he didnt spoonfeed you?

**Comment by bexpg1377** [comment]
> > > why should i release it @bexpg1377
> > 
> > 
> > u said LOL i know u dont know code i just tested you and u failed.
> 
> u mean ur salty because he didnt spoonfeed you?

memek anjing bangsat

**Comment by Alexander9673** [comment]
> > why should i release it @bexpg1377
> 
> u said LOL i know u dont know code i just tested you and u failed.

I won't code shit and release it to the public unless it would benefit anyone except me.
You think that i don't code? That's fine. That's your opinion i don't give a fuck about it.

**Comment by xXAbood** [comment]
legit ban this autistic retard hes annoying the fuck out of everyone

**Comment by xXAbood** [comment]
> > > why should i release it @bexpg1377
> > 
> > 
> > u said LOL i know u dont know code i just tested you and u failed.
> 
> I won't code shit and release it to the public unless it would benefit anyone except me.
> You think that i don't code? That's fine. That's your opinion i don't give a fuck about it.

whatever he says, talking more with him will lead you to nothing he just wants attention even if hes made fun of, just ignore him alex

**Comment by bexpg1377** [comment]
> > > > why should i release it @bexpg1377
> > > 
> > > 
> > > u said LOL i know u dont know code i just tested you and u failed.
> > 
> > 
> > I won't code shit and release it to the public unless it would benefit anyone except me.
> > You think that i don't code? That's fine. That's your opinion i don't give a fuck about it.
> 
> whatever he says, talking more with him will lead you to nothing he just wants attention even if hes made fun of, just ignore him alex

Syria pro!!!!

**Comment by xXAbood** [comment]
> > > > > why should i release it @bexpg1377
> > > > 
> > > > 
> > > > u said LOL i know u dont know code i just tested you and u failed.
> > > 
> > > 
> > > I won't code shit and release it to the public unless it would benefit anyone except me.
> > > You think that i don't code? That's fine. That's your opinion i don't give a fuck about it.
> > 
> > 
> > whatever he says, talking more with him will lead you to nothing he just wants attention even if hes made fun of, just ignore him alex
> 
> Syria pro!!!!

yeah turkhackteam close it mr insecure
