### ISSUE TITLE
[QUESTION]  How to Cooldown Command

### ISSUE THREAD

**Issue by bexpg1377** [GrowtopiaNoobs/GrowtopiaServer#1391]
I tryed sleep but sleep make server frozen.

**Comment by Alexander9673** [comment]
You can use timestamps and maps on c++. For the map, you can do it like this
```cpp
std::map<std::string, bool> cooldowns;
```
then what you can do is, if a user uses a command, and them there, then you can try and find a method for c++ that would wait a few seconds, depends on how long the cooldown would be and then remove them from that map by doing `cooldowns.erase("string")`.
The key on that map would be their raw username, while the value would be true/false. You can also use a vector instead, for vectors you would just add their username there, then after the cooldown, you can remove them.
