### ISSUE TITLE
[QUESTION] how to fix levels

### ISSUE THREAD

**Issue by manksetip** [GrowtopiaNoobs/GrowtopiaServer#1395]
so levels at my server is stuck at level 1 0/300

**Comment by YourBoiBusy** [comment]
When player break  make xp+1
Int xp=0;

**Comment by MoanHawks** [comment]
since when @GrowtopiaNoobs add level system 😳

**Comment by YourBoiBusy** [comment]
xD

**Comment by GrowtopiaNoobs** [comment]
@manksetip Please first make PR to add level system and then make issue about level system not working.
