### ISSUE TITLE
[BUG] How to fix, When i break dirt, server crashed

### ISSUE THREAD

**Issue by GuckTubeYT** [GrowtopiaNoobs/GrowtopiaServer#1396]
When i break dirt, server crashed

**Comment by cmdocmd** [comment]
gt noobs cpp doesnt have this bug so if u want to fix it dont use leaked cpp and use the original gt noobs cpp and if u dont want then its probably because u dont have coredata or items.dat

**Comment by YourBoiBusy** [comment]
or maybe breaklevel

**Comment by abood1337** [comment]
lmao make fix for it. try to fix before posting here retard

**Comment by GuckTubeYT** [comment]
> gt noobs cpp doesnt have this bug so if u want to fix it dont use leaked cpp and use the original gt noobs cpp and if u dont want then its probably because u dont have coredata or items.dat

Hmmmm ok
