### ISSUE TITLE
(off-topic issue)

### ISSUE THREAD

**Issue by xXAbood** [GrowtopiaNoobs/GrowtopiaServer#1400]
Hey everyone, so apparently there's an impersonator who is using my name goes with the user @abood1337 . Whatever he or she has posted just know that it isnt me and reporting/sharing it to others would be a really good solution.
Sorry to everyone that had a negative interaction towards that person

**Comment by noobsteak** [comment]
@xXAbood is real. @abood1337 is fake.

**Comment by Azure1337** [comment]
@xXAbood is real, @abood1337 is fake.

imagine faking your identity for attention, what a bum 
really crazy how people be out here faking their identities for attention and acting as if they're cool now.

just be yourself.

**Comment by noobes1337** [comment]
raiterjaki kys, @xXAbood real

**Comment by fiber1337** [comment]
imagine impersonating somebody who is better than you 😳

**Comment by Azure1337** [comment]
> imagine impersonating somebody who is better than you 😳

facts, people be out here faking stuff as if its cool. 🤣

**Comment by noobes1337** [comment]
why would kids be that retards to impersonate somebody

**Comment by YourBoiBusy** [comment]
XXAbood  is real and abood1337 fake one

**Comment by wh1ter0se69** [comment]
Imagine impersonating le and only @xXAbood lol, @abood1337 is fake, real one is @xXAbood 
And his only discord is Abood#1337 don't be fooled people!
P,S: If you ever feel low/bad about yourself, remember this :
At least, you're not bexpg lol

**Comment by ardakurucim** [comment]
ok

**Comment by GuckTubeYT** [comment]
This is a real Abood

**Comment by GuckTubeYT** [comment]
What do i say is correct.
@xXAbood its real

**Comment by GuckTubeYT** [comment]
Retard @abood1337 its copying @xXAbood name for Famous bruh

**Comment by Tron-GT** [comment]
Lol

**Comment by GuckTubeYT** [comment]
Kids want to famous, but fail

**Comment by GuckTubeYT** [comment]
Rip 100%

**Comment by Alexander9673** [comment]
@xXAbood is real, @abood1337 = fake

**Comment by Tron-GT** [comment]
Ik, bruh

**Comment by external1337** [comment]
@xXAbood is the real one, @abood1337 is fake.

**Comment by abood1337** [comment]
shut up retarded. I have internal made in c++ can crash servers even 64gb ram. Show internal if you real abood. I have internal cann show even in my repository i posted internal so don't steal retard gay

**Comment by abood1337** [comment]
> why would kids be that retarded to impersonate somebody

shut up gay im 17 year old and my name is abood i have internal c++

**Comment by Azure1337** [comment]
> > why would kids be that retarded to impersonate somebody
> 
> shut up gay im 17 year old and my name is abood i have internal c++

doesn't make a difference, if you're the real abood then please, join a voice-call.
i've been in a call with abood before and i know how he sounds. so prove it if you're the real abood
doesn't make a difference if you have an internal, anyone can have an internal.

**Comment by Azure1337** [comment]
> shut up retarded. I have internal made in c++ can crash servers even 64gb ram. Show internal if you real abood. I have internal cann show even in my repository i posted internal so don't steal retard gay

dude what do you mean internal internal.
internals don't prove anything you retard.

"show internal if you real abood" bro, abood knows how to make sentences and isnt an indonesian like you.
this is 100% bexpg or someone thats trying to be relevant

**Comment by abood1337** [comment]
> > shut up retarded. I have internal made in c++ can crash servers even 64gb ram. Show internal if you real abood. I have internal cann show even in my repository i posted internal so don't steal retard gay
> 
> dude what do you mean internal internal.
> internals don't prove anything you retard.
> 
> "show internal if you real abood" bro, abood knows how to make sentences and isnt an indonesian like you.
> this is 100% bexpg or someone thats trying to be relevant

shut the fuck up retarded im from saudi arabia my name is abdul rahman abood

**Comment by Hades3377** [comment]
>shut the fuck up retarded im from saudi arabia my name is abdul rahman abood
legit just shut the fuck up, you've been banned in the development discord already, stop impersonating and being retarded and do something productive. you talk like others mistreat you in that discord yet here you are impersonating one of our most prominent members. you need to take more responsibility and actions instead of stealing.

**Comment by xXAbood** [comment]
lol hes banned so lets just close this issue
