### ISSUE TITLE
(Off-topic-issue) 2

### ISSUE THREAD

**Issue by Bexpg0** [GrowtopiaNoobs/GrowtopiaServer#1403]
@bexpgalt is not me i think its "VYTE" but not sure
i never ask for buy my cpp, or i never say sell cpp bevare fake. Also "Vyte i know you reading this you can unlimited ddos me i never will quit make private server also if you keep doing this sh*t fake account then we will see cloudflare protect can Save ur private server or no n1gga little kids imagine using azure bugs in 2020 😂

**Comment by GuckTubeYT** [comment]
Wait, this is Vyte?

**Comment by YourBoiBusy** [comment]
well idk about him lmao

**Comment by Hades3377** [comment]
bexpgalt and the fake abood are probaly people from vytes staff and vyte all i can guess

**Comment by Bexpg0** [comment]
![Screenshot_20200512-023446_Chrome](https://user-images.githubusercontent.com/65194764/81622305-4b701d80-93f9-11ea-85a4-8aae4e7d876a.png)
![Screenshot_20200512-023454_Chrome](https://user-images.githubusercontent.com/65194764/81622307-4e6b0e00-93f9-11ea-84de-86d8962f8c20.png)
 Yeah vyte has many alt

**Comment by xXAbood** [comment]
it isnt, you literally proved urself that u are @abood1337
![image](https://user-images.githubusercontent.com/59313717/81636444-ee8a5c80-9424-11ea-9a20-48d9e03e5331.png)

**Comment by Bexpg0** [comment]
> it isnt, you literally proved urself that u are @abood1337
> ![image](https://user-images.githubusercontent.com/59313717/81636444-ee8a5c80-9424-11ea-9a20-48d9e03e5331.png)

i said its me because Mr.abood threat me if its me e will kill me 😂

**Comment by GuckTubeYT** [comment]
hmmmmm

**Comment by GuckTubeYT** [comment]
INTERESTING!?!?

**Comment by fiber1337** [comment]
@Bexpg0 i mean you impersonated abood why do we trust u you mixed my status + aboods name lol how sad can you be :flushed:

**Comment by Bexpg0** [comment]
> @Bexpg0 i mean you impersonated abood why do we trust u you mixed my status + aboods name lol how sad can you be

Dont trust i dont care
