### ISSUE TITLE
[BUG] Stuck in Logging on

### ISSUE THREAD

**Issue by GuckTubeYT** [GrowtopiaNoobs/GrowtopiaServer#1404]
How to fix stuck in logging on, but at the console = Packet Drop

**Comment by Surekings** [comment]
Maybe sent many packet lol

**Comment by GuckTubeYT** [comment]
> Maybe sent many packet lol

hmmmmmmm

**Comment by abood1337** [comment]
are you retarded? learn c++ /fp -.-

**Comment by fiber1337** [comment]
stfu fake retard imagine being so sad to impersonate someone. :flushed: excuse him @GuckTubeYT he isnt real abood. join Haraku discord for Proof

**Comment by fiber1337** [comment]
also @GuckTubeYT check your OnSuperMain cache. CDNContent must be "62"

string configCDN = "0098/CDNContent62/cache/";

**Comment by Surekings** [comment]
> also @GuckTubeYT check your OnSuperMain cache. CDNContent must be "62"
> 
> string configCDN = "0098/CDNContent62/cache/";

he dont make config.json

**Comment by GuckTubeYT** [comment]
Oh okay, thanks for the information

**Comment by GuckTubeYT** [comment]
> stfu fake retard imagine being so sad to impersonate someone.  excuse him @GuckTubeYT he isnt real abood. join Haraku discord for Proof

just shut him up, and dont care to fake abood

**Comment by cmdocmd** [comment]
just go to refresh_items_data u see isupdating make it false

**Comment by GuckTubeYT** [comment]
> just go to refresh_items_data u see isupdating make it false

Its work, thanks @cmdocmd

**Comment by GuckTubeYT** [comment]
And @Surekings
