### ISSUE TITLE
(off-topic [main])

### ISSUE THREAD

**Issue by fiber1337** [GrowtopiaNoobs/GrowtopiaServer#1407]
Okay. lets get this shit fucking clear. @abood1337 is Fake as fuck. the real abood is @xXAbood (Abood#1337) - Dont get fooled. bexpg is impersonating abood to  fucking blow his reputation since he has a popular community and is just trying to be so fucking sad that he failed impersonating somebody and what fucking annoys me is the fact he is still thinking we are retards and dont know that he is bexpg. 

Join Haraku Discord: https://discord.gg/RxUwgFg

**Comment by external1337** [comment]
Fuck @abood1337 , @xXAbood is the real one. If someone doesnt believe this then you are just braindead. @abood1337 is bexpg and not the real abood.

**Comment by Azure1337** [comment]
im finna start a whole rant if we dont get this noob ass idiot outta here

**Comment by Azure1337** [comment]
> im finna start a whole rant if we dont get this noob ass idiot outta here

and i wont care if i get banned cause i dont like the shit he does

**Comment by abood1337** [comment]
shut up retard mad mad mad mad mad mad mad lol you mad no internal c++ LOLZ

**Comment by fiber1337** [comment]
lol who are u to speak @abood1337 bexpg gay

**Comment by abood1337** [comment]
> lol who are u to speak @abood1337 bexpg gay

shut up retarded fuck

**Comment by GrowtopiaNoobs** [comment]
It seem like he was banned by github before I was able to resolve this issue.
Closing this as this issue is solved.
