### ISSUE TITLE
(unrelated) Discussion

### ISSUE THREAD

**Issue by Hades3377** [GrowtopiaNoobs/GrowtopiaServer#1408]
Can we please stop. All this drama that's been going on could we stop? I request that the parties involved settle it somewhere private eg discord. Like maybe Abood was fine for giving a heads up to everyone for what's been going on with the impersonator. I request we can just ignore the impersonator since we all are aware of the issue. The impersonator BexPg is bringing chaos to this community and smaller new coders who need help is being overshadowed. If bexpg brings up an unrelated or disrespectful issue ignore him. Just take note of the actual person.Bexpgs's nonsense would fall under trolling this repo (as GrowtopiaNoobs made an issue about it) and if we keep on feeding to his attention-seeking it will waste many people's time. So best we just ignore and continue normally.

**Comment by Alexander9673** [comment]
We can ignore him since we all know it's him. The only problem is for new people who ask stuff here. Bexpg might show up and pretend to be abood, obv people will think it's him since they're new. But this can be avoidable if we have some group of people or somone just looking out at the issues and telling that @abood1337 is fake until this is resolved.

**Comment by Hades3377** [comment]
Most we can do is wait for @GrowtopiaNoobs to do something about it.

**Comment by Hades3377** [comment]
please be aware bexpg your trolling in the issues and as such you will get banned permanently from the community as a whole #1258

**Comment by Alexander9673** [comment]
Yeah waiting for @GrowtopiaNoobs is the only wait for this to be resolved. He might be online an hour or so.

**Comment by abood1337** [comment]
are you retarded? i no do anything just post issue how fix tron gtbot and how make magplant you retarded gays say me fake /fp -.-

**Comment by Hades3377** [comment]
Well, abood1337 is directly calling yourself XxAbood which is trolling.We have proof your fake anyways.

**Comment by abood1337** [comment]
> Well, abood1337 is directly calling yourself XxAbood which is trolling.We have proof your fake anyways.

i said im abood1337 not xxabood + im have internal

**Comment by Hades3377** [comment]
This is nothing about your "internal" this is about how your blatantly impersonating someone.

**Comment by abood1337** [comment]
retard i have internal but fake abood no have LOL

**Comment by Hades3377** [comment]
1. Your the fake one implying you dont have it
2. This is a growtopia-server project, not an internal.

**Comment by abood1337** [comment]
you guys dont even know what is internal so shut up Shameen Ali

**Comment by Hades3377** [comment]
my name is jafar niaz??? you probaly got that ss and name from my device which was my moms but thankfully i got my own mac unlike you typing this on your mobile phone.
<img width="1438" alt="Screenshot 2020-05-12 at 6 29 07 PM" src="https://user-images.githubusercontent.com/50758890/81673647-8bc5af00-947e-11ea-8c79-cd42cedb5b00.png">

**Comment by Hades3377** [comment]
Keep commenting, I'll stop responding also, its illegal to reveal my mother's name (doxxing) and thats and big oopsie, now we await your ban

**Comment by abood1337** [comment]
shut up shameen ali there is no name ali and you retards skids cant make internal but i have it HAHAHAHAHHAHAHHHAHAHAH

**Comment by Bexpg0** [comment]
Abood1337, Bexpgalt was not me. Also u are clown

**Comment by cmdocmd** [comment]
@Bexpg0 well both was writing in the same way you do like saying all the time retard or you dont know how to code this things

**Comment by GrowtopiaNoobs** [comment]
It seem like he was banned by github before I was able to resolve this issue.
Closing this as this issue is solved.
