### ISSUE TITLE
"drama"

### ISSUE THREAD

**Issue by raiterjaki** [GrowtopiaNoobs/GrowtopiaServer#1411]
just stop crying everywhere that "he is impersonating me" 'blabla'. No one cares you don't have to post issues that "guys someone is impersonating me!!!" This is not the right place for making issues that "someone is impersonating me". These issues are for people who need help or who found a bug and requests fix.

**Comment by Bexpg0** [comment]
👍

**Comment by Hades3377** [comment]
yes

**Comment by Bexpg0** [comment]
@GrowtopiaNoobs  @Hades3377 @xxabood @abood1337 Troller u must ban  them

**Comment by raiterjaki** [comment]
> @GrowtopiaNoobs @Hades3377 @xXAbood @abood1337 Troller u must ban them

I agree with you for the first time. 👍🏿

**Comment by Bexpg0** [comment]
![Screenshot_20200512-154510_Discord](https://user-images.githubusercontent.com/65194764/81692875-b5bfa700-9467-11ea-9983-d42dc25b5c6c.png)
Also ban @iProgramMC  too he sending virus me

**Comment by iProgramMC** [comment]
That was literally a rttex2png converter that I got from the internet, feel free to delete it 🙂

**Comment by raiterjaki** [comment]
> That was literally a rttex2png converter that I got from the internet, feel free to delete it 🙂

👍🏿 I agree with product iProgramInCpp-03219

**Comment by Bexpg0** [comment]
![20200512_155046](https://user-images.githubusercontent.com/65194764/81693296-5e6e0680-9468-11ea-91a3-1428c1236dbd.png)
Threating??

**Comment by Bexpg0** [comment]
![20200512_155249](https://user-images.githubusercontent.com/65194764/81693484-a725bf80-9468-11ea-94da-ac58e29f91d0.png)
Extract from gt or internet ?

**Comment by Bexpg0** [comment]
as you can see he troller and lier

**Comment by YourBoiBusy** [comment]
shut up nigger bexg0 ur the only one to get ban with ur fake abood account ( abood#1337 nigger)

**Comment by GrowtopiaNoobs** [comment]
@YourBoiBusy Please don't join/start flame war.
@Bexpg0 Please don't fight with others. If you have personal conflict on discord, then please finish it on discord and don't bring it here.
@raiterjaki I think that it might be good to let people to know what is happening till it is solved when it is somehow related to this github repo.

Closing this issue as it is solved.

**Comment by Bexpg0** [comment]
> shut up nigger bexg0 ur the only one to get ban with ur fake abood account ( abood#1337 nigger)

im not black and also dont keep lie its not me

**Comment by xXAbood** [comment]
> > @GrowtopiaNoobs @Hades3377 @xXAbood @abood1337 Troller u must ban them
> 
> I agree with you for the first time. 👍🏿

i doubt it isnt u whos planning that

**Comment by iProgramMC** [comment]
Stop chatting inside closed issues.

**Comment by noobes1337** [comment]
shut the fuck up raiterjaki

**Comment by raiterjaki** [comment]
> shut the fuck up raiterjaki

shut up "pussy retard without "internal""

**Comment by noobes1337** [comment]
h1ghsky how ya doing retard

**Comment by raiterjaki** [comment]
> h1ghsky how ya doing retard

july 23
