### ISSUE TITLE
How Do i Make Status Bot [QUESTION] 

### ISSUE THREAD

**Issue by axnanyt** [GrowtopiaNoobs/GrowtopiaServer#1416]
How Can i make status bot for discord which shows how many players online and up or down

**Comment by Onlyin2** [comment]
It was already answered in issue #1282 and you just need a little python knowledge

**Comment by Alexander9673** [comment]
Well, to avoid using a full discord library, you can just send post requests to Discord.
To send a message, you can send a POST request at this url: `https://discord.com/api/v6/channels/{CHANNEL_ID_HERE}/messages`.
Make sure the `Content-Type` is `application/json` since discord uses json as accepting data from requests. And make sure you pass the right headers. The headers should be like this:
```js
{
  Authorization: "Bot YOUR_BOT_TOKEN_HERE"
}```
For the json, if you would like to send just a message, you can just send it like this:
```json
{
  "content": "Message to send"
}```

@Onlyin2 no need for python btw.

**Comment by Alexander9673** [comment]
You can choose where to place those, for starting up, try putting it just right [here](https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/master/enet%20server%20test/enet%20server%20test.cpp#L2776) then for close, if it's possible on C++ try to check if the process will/has closed. Or you can just check if the port `17091` or whatever port you are using for your server is open.

**Comment by Alexander9673** [comment]
But if you are planning to make commands for he bot, you would need to use Sleepy Discord just like in #1282 , or just use any language you want. For different languages, it's a much harder thing to do.

**Comment by axnanyt** [comment]
> Well, to avoid using a full discord library, you can just send post requests to Discord.
> To send a message, you can send a POST request at this url: `https://discord.com/api/v6/channels/{CHANNEL_ID_HERE}/messages`.
> Make sure the `Content-Type` is `application/json` since discord uses json as accepting data from requests. And make sure you pass the right headers. The headers should be like this:
> 
> ```js
> {
>   Authorization: "Bot YOUR_BOT_TOKEN_HERE"
> }
> ```
> 
> For the json, if you would like to send just a message, you can just send it like this:
> 
> ```json
> {
>   "content": "Message to send"
> }
> ```
> 
> This is possible in any language that has the ability to send these kind of requests. (e.g GET/PATCH/POST/DELETE and more).
> This is possible in C++ as well. If you want to make the bot appear online, and still want to use C++, use sleepydiscord library.
> @Onlyin2 no need for python btw.

Thanks for the help
