### ISSUE TITLE
How can i change My Server port[QUESTION] 

### ISSUE THREAD

**Issue by axnanyt** [GrowtopiaNoobs/GrowtopiaServer#1418]
is there anyway i could change my Server port 17091 to any other

**Comment by Bexpg0** [comment]
Lol

**Comment by noobes1337** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/4a39b79f6ea0cf224f4c436e7eab0462e82d2ba4/enet%20server%20test/enet%20server%20test.cpp#L103

**Comment by GuckTubeYT** [comment]
> is there anyway i could change my Server port 17091 to any other

And you can change at config.json

**Comment by axnanyt** [comment]
> https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/4a39b79f6ea0cf224f4c436e7eab0462e82d2ba4/enet%20server%20test/enet%20server%20test.cpp#L103

Thank you

**Comment by axnanyt** [comment]
> > is there anyway i could change my Server port 17091 to any other
> 
> And you can change at config.json

Thank You

**Comment by GuckTubeYT** [comment]
No problem
