### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by NubVann** [GrowtopiaNoobs/GrowtopiaServer#1420]
**Custom Items 404 bad url**
I already encode the items.dat then i put it into my server folder and i made the server up . But when its up , i got 404 bad url . Is there anything to do with the cpp and xampp? Can anyone explain me step by step on how to fix the problem ?

Discord : Zando#5732

**Comment by raiterjaki** [comment]
Because you are doing it wrongly.

**Comment by NubVann** [comment]
> Because you are doing it wrongly.

How to fix it then??

**Comment by cmdocmd** [comment]
In your case you are trying to add a custom item which means that u added rttex file to items.dat so if your server doesnt find that rttex file it will show 404 you should make ur server read the rttex file..

**Comment by NubVann** [comment]
> In your case you are trying to add a custom item which means that u added rttex file to items.dat so if your server doesnt find that rttex file it will show 404 you should make ur server read the rttex file..

i did put it at my download folder in the vps

**Comment by GuckTubeYT** [comment]
Maybe, you forget to put the custom items file to HTTP Server (htdocs folder)

**Comment by NubVann** [comment]
> Maybe, you forget to put the custom items file to HTTP Server (htdocs folder)

Well yea i just did but maybe i made em wrong i guess .

**Comment by Surekings** [comment]
@NubVann Please close this issue, if you feel that helped you

**Comment by NubVann** [comment]
> @NubVann Please close this issue, if you feel that helped you

Yes ok cause i already know how 😂.
