### ISSUE TITLE
Server crashes randomly

### ISSUE THREAD

**Issue by SSebia** [GrowtopiaNoobs/GrowtopiaServer#1422]
Hello, my server sometimes crashes without proper reason it can be anything. I'm using the release option for win32. I don't have any memory leaks, the server literally will crash after 1 hour of working and the crash reason can be anything even simple command which will NOT crash anymore after restarting the server, is that some kind of overload? I'm sure no one is crashing my server because it was tested on the localhost.

**Comment by MoanHawks** [comment]
Please is you code not from @GrowtopiaNoobs source code

**Comment by SSebia** [comment]
Yes, it is not from Growtopianoobs, I'm just sharing my issue maybe someone else had something similar, etc...

**Comment by xXAbood** [comment]
std::fstream log("logs.txt", std::ios::in | std::ios::out | std::ios::ate);
                    log << cch << endl;
                    log.close();
----------------------------------------------------------------------------------------------------------
that should log whats happening in that hour in the server

**Comment by fiber1337** [comment]
me when logs.txt :flushed:

**Comment by Kazuto12x** [comment]
the problem is that someone ratted your pc with virus called mcdonalds muckbang bang which literally makes your computer fat as shit and makes it obese which is why it crashes from time to time. Keep in mind that the mcdonalds muckbang bang is 560+ lbs.

**Comment by SSebia** [comment]
> ## std::fstream log("logs.txt", std::ios::in | std::ios::out | std::ios::ate);
> log << cch << endl;
> log.close();
> that should log whats happening in that hour in the server

Yes, I'm using cout << cch << endl; but the weird thing that it does not log anything that actually causes the crash.  Another question is that normal that server memory usage increases as you enter worlds?

**Comment by xXAbood** [comment]
did u make it shut down each hour or what

**Comment by SSebia** [comment]
issue closed, I was missing to close some ofstreams that was causing the issue.
