### ISSUE TITLE
OnStoreRequest [Question]

### ISSUE THREAD

**Issue by BieNW** [GrowtopiaNoobs/GrowtopiaServer#1430]
So i'm trying to add New store UI

But why its says 200.000 , i already change the price to 10 , but still says 200.000 when the UI its clicked
https://gyazo.com/bd385f88163ea6cd95e4e93c9609745d

**Comment by Onlyin2** [comment]
Are you sure you changed all the required values?

**Comment by SSebia** [comment]
This is not values, this is banner, DM Sebia#1337 on discord I will explain to you.

**Comment by Bexpg0** [comment]
> This is not values, this is banner, DM Sebia#1337 on discord I will explain to you.

Dont dm he will send you virus lol

**Comment by BieNW** [comment]
Fixed, Thanks Sebia 👍

**Comment by BieNW** [comment]
Fixed, Thanks sebia 👍
