### ISSUE TITLE
<-What point coding growtopia private server->

### ISSUE THREAD

**Issue by Bexpg0** [GrowtopiaNoobs/GrowtopiaServer#1432]
Blank

**Comment by xXAbood** [comment]
i busy with eating carrot

**Comment by noobes1337** [comment]
bexpg's life = blank

**Comment by xXAbood** [comment]
am i bunny i like eating carrot

**Comment by Hades3377** [comment]
not an issue wtf probaly people code it so they can make a game??????retard

**Comment by Hades3377** [comment]
luckily have carrot fp blessing from god to eat so no need code bro watch tom jerry too

**Comment by BieNW** [comment]
🤣

**Comment by Bexpg0** [comment]
Its an issue.  Troll auto ban #1258

**Comment by Bexpg0** [comment]
@GrowtopiaNoobs

**Comment by Alexander9673** [comment]
ya'll should just ignore this kid. Nothing good to do with life.

**Comment by Onlyin2** [comment]
> Its an issue. Troll auto ban #1258

Indeed the reason you should get banned for.

**Comment by GrowtopiaNoobs** [comment]
@Bexpg0 You are banned as of #1258
