### ISSUE TITLE
Private server on notepad

### ISSUE THREAD

**Issue by Bexpg0** [GrowtopiaNoobs/GrowtopiaServer#1433]
Im from syria 13 yrs old cod3r my name abod how to code private server on notepad i very int3rested.!! i know c++ a++ k## p# u+

**Comment by Onlyin2** [comment]
#1258 can you stop being retarded at this point?

**Comment by GramingFoxTeam** [comment]
> #1258 can you stop being retarded at this point?

Hes just a Turkish boy that trolls and dont even know how to code lol

**Comment by cmdocmd** [comment]
@GrowtopiaNoobs please ban this retard

**Comment by Onlyin2** [comment]
> @GrowtopiaNoobs please ban this retard

17 yr old turkish boy that like kidding with skids that think he's kids but he's just kidding with kids and laughing

**Comment by YourBoiBusy** [comment]
shut the fucking up nigga

**Comment by cmdocmd** [comment]
im bexpg 17 years old from turkish code in c++ and c# im kidding with skids and they think im skid but i laugh

**Comment by YourBoiBusy** [comment]
@GrowtopiaNoobs  ban this fucking bitchass retard he killed the community .__.

**Comment by YourBoiBusy** [comment]
im bexpg 17 years old from turkish code in c++ and c# im kidding with skids and they think im skid but i laugh

**Comment by xXAbood** [comment]
actually its
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

**Comment by Surekings** [comment]
**BAN begpg0** 🤣

**Comment by GrowtopiaNoobs** [comment]
@Bexpg0 You are banned as of #1258
