### ISSUE TITLE
[QUESTION]   GrowTale Cpp

### ISSUE THREAD

**Issue by SWE827** [GrowtopiaNoobs/GrowtopiaServer#1436]
If u have GrowTale Cpp Can u send it to Me In discord SwE#0459

**Comment by noobsteak** [comment]
no

**Comment by Surekings** [comment]
wtf stop spamming issues with the same question

**Comment by JadlionHD** [comment]
not related with this repository

**Comment by xXAbood** [comment]
moment

**Comment by GrowtopiaNoobs** [comment]
As said above this isn't related to this repository.
