### ISSUE TITLE
[QUESTION] Howmany cdncontent V3.36 and how to fix error' 404

### ISSUE THREAD

**Issue by Zupooss** [GrowtopiaNoobs/GrowtopiaServer#1443]
HOW TO FIX ERROR 404?
Howmany cdn content V3.36?

**Comment by SSebia** [comment]
use a custom cache, and you won't need to change CDN contents anymore.

**Comment by Onlyin2** [comment]
> use a custom cache, and you won't need to change CDN contents anymore.

Using custom cache will probably disable that IOS players can play. IOS functions in such a strange way.

**Comment by Retro-17** [comment]
> > use a custom cache, and you won't need to change CDN contents anymore.
> 
> Using custom cache will probably disable that IOS players can play. IOS functions in such a strange way.

Nope u must usea Custom Cache which works for iOS my cache works for all platforms, Like vyte's. it is possible.

**Comment by Onlyin2** [comment]
> > > use a custom cache, and you won't need to change CDN contents anymore.
> > 
> > 
> > Using custom cache will probably disable that IOS players can play. IOS functions in such a strange way.
> 
> Nope u must usea Custom Cache which works for iOS my cache works for all platforms, Like vyte's. it is possible.

Strange, for me using a custom cache won't let IOS players login.

**Comment by JUSTNUB** [comment]
> HOW TO FIX ERROR 404?
> Howmany cdn content V3.36?

its 62 :)

**Comment by Onlyin2** [comment]
> HOW TO FIX ERROR 404?
> Howmany cdn content V3.36?

I assume your question has been answered. Close this issue.

**Comment by Zupooss** [comment]
> > HOW TO FIX ERROR 404?
> > Howmany cdn content V3.36?
> 
> its 62 :)

Thanks
