### ISSUE TITLE
[QUESTION] How To Use This?

### ISSUE THREAD

**Issue by TheCodesZ** [GrowtopiaNoobs/GrowtopiaServer#1444]
How to use this?..

**Comment by Onlyin2** [comment]
> How to use this?..

https://www.learncpp.com/
Use this to learn. And check the wiki.

**Comment by TheCodesZ** [comment]
> > How to use this?..
> 
> https://www.learncpp.com/
> Use this to learn. And check the wiki.

ok thanks.. i will close this
