### ISSUE TITLE
Requesting help in C# mysql (off topic)

### ISSUE THREAD

**Issue by YourBoiBusy** [GrowtopiaNoobs/GrowtopiaServer#1448]
**If i want host my C# app with log in and register form in my vps when i put 127.0.0.1 as ip users will get error of tables  things bcz they arent using localhost for making the log in or register how should i host it to my vps? 
in my pc i use 127.0.0.1 and it work because i made tables and everything for it but i want host it to other users that didnt made tables. i dont want them make tables and these things
hope i get a good ideas
(i tried my vps ip it didnt work i checked ports)**
![Login_Regsiter 5_20_2020 10_55_53 AM](https://user-images.githubusercontent.com/61913559/82420560-8c66d280-9a88-11ea-9047-5810127eb9f3.png)

**Comment by raiterjaki** [comment]
https://github.com/willi123yao/GrowtopiaServerCS/issues

**Comment by 1337abood** [comment]
Aren't you the skid who flexed with mysql + c# on project reborn 4? Why are you asking for help now?

**Comment by YourBoiBusy** [comment]
SHUT THE FUCKING UP 
who told ur ass pr4 is C# lol
abd who said i flex lol

**Comment by YourBoiBusy** [comment]
@GrowtopiaNoobs BAN THIS FUCKING BEXG KID

**Comment by bykoi** [comment]
shut the fuck up retard

**Comment by 1337abood** [comment]
Lol are you retarded? What are you talking about? I can show you my VB.Net server + mysql installed on it. I even fixed memory leak.

**Comment by YourBoiBusy** [comment]
retard

**Comment by YourBoiBusy** [comment]
anybody tried to be good with u and unban u but u dont even care
https://gyazo.com/17b09a562ec1039f5ffb34e161e430ae

**Comment by YourBoiBusy** [comment]
and the thing im doing isnt for growtopia i said ( off topic )

**Comment by 1337abood** [comment]
are you retarded? Lol, are you mentally disabled? What are you talking about? I just know that you and your retarded squad (hadi, cmd) are faking making c# server and now you are here asking for help from c#. Lmao. What a cruel world!

**Comment by YourBoiBusy** [comment]
retart squad? did u even tried to build a private server from 0 lines?

**Comment by YourBoiBusy** [comment]
why are u so retarted to be here? didnt u got ban already?

**Comment by bykoi** [comment]
kk gtv3 cpp https://cdn.discordapp.com/attachments/704323080519942264/707585226267951164/unknown.png

**Comment by YourBoiBusy** [comment]
it was linker error that i didnt linked

**Comment by bykoi** [comment]
yeah imagine trying to build it all

**Comment by 1337abood** [comment]
my squad is better than yours. my squad works on c++ growtopia internal (hook). even tho byko thinks he is cool he is using proxy dll.

**Comment by YourBoiBusy** [comment]
i did it already just for checking

**Comment by YourBoiBusy** [comment]
wow! who is ur squad?

**Comment by 1337abood** [comment]
lol skid imaging pasting gtv3. my team works on VB.Net server too.

**Comment by YourBoiBusy** [comment]
pasting gtv3? lol

**Comment by 1337abood** [comment]
People in my squad are: Alioz, Aspiracy, Azure, Cortaz, Hades, Locasater, Paste, Steak, Wry, Noobes. They are all working hard on growtopia c++ internal (hook)

**Comment by 1337abood** [comment]
My squad member noobes made a fully working fishing system without pasting like your team. It just took him 1 minute he is so good at coding that it is trivial for him.

**Comment by 1337abood** [comment]
Here is the video: https://streamable.com/nro995

**Comment by YourBoiBusy** [comment]
who said we pasting ye

**Comment by YourBoiBusy** [comment]
https://gyazo.com/efd48e166d49deed873af1a9bfb752e0

**Comment by YourBoiBusy** [comment]
nice team man!

**Comment by YourBoiBusy** [comment]
wow u made fishing its so fucking cool we cant do it ye?

**Comment by 1337abood** [comment]
Do you even know who is bex? What are you talking about? We are working on growtopia c++ internal (hook). I just wanted to say that you guys are retarded and you guys cant make anything LOLZ. You guys just paste from leaked sources such as gtv3 omg you literally suck fuckin trash black ass Indonesian fucking Syrian.

**Comment by YourBoiBusy** [comment]
wait wait wait u said i flex? what are u sending here? ur flexing with fishes

**Comment by YourBoiBusy** [comment]
1- we arent pasting 
2- im not syrian
https://gyazo.com/efd48e166d49deed873af1a9bfb752e0
ur teammate is saying ur retarted fake abood  lol

**Comment by 1337abood** [comment]
We even made a working tree system (can splice) I can even call tree packet with the c++ growtopia internal (hook) we are working on. We will make a hook function where we can extract growtopia source to a text file and then finding shell and the hack into growtopia database through that shell. And what are you guys doing? FUCKING PASTING BASTARD.

**Comment by YourBoiBusy** [comment]
we have trees working lol wkwkwkww

**Comment by YourBoiBusy** [comment]
https://gyazo.com/ef81a25afaf1c27177483b815a6ddde1

**Comment by 1337abood** [comment]
I can even spawn tree with hooking function called "OnTree" you will not find it with gay ass "hxd" because we can see that function with help of function which lets us see all functions inside growtopia.

**Comment by YourBoiBusy** [comment]
do i care?

**Comment by YourBoiBusy** [comment]
https://gyazo.com/3010402538f0674147bb823b347cd50a
spamming accounts lol

**Comment by 1337abood** [comment]
Do I care your fake tree using cheat engine? NO! Also I just extracted growtopia source!! Holy shit!! i found growtopia source files look:

void GameLogicComponent::OnAdd(Entity *pEnt)
{
	EntityComponent::OnAdd(pEnt);

	LogMsg("GameLogic added");
	GetParent()->GetFunction("OnUpdate")->sig_function.connect(1, boost::bind(&GameLogicComponent::OnUpdate, this, _1));
	GetParent()->GetFunction("OnRender")->sig_function.connect(1, boost::bind(&GameLogicComponent::OnRender, this, _1));

	m_pSlideOverlay = CreateOverlayEntity(GetParent(), "SlideScreen", "interface/blank.rttex", 0,
		-GetScreenSizeYf(), true);
	
	Entity *pTitle = CreateOverlayEntity(m_pSlideOverlay, "Title", "interface/playstep.rttex", GetScreenSizeXf() / 2,
		GetScreenSizeYf() / 3, true);
	SetAlignmentEntity(pTitle, ALIGNMENT_CENTER);

	m_pStep1 = CreateOverlayEntity(m_pSlideOverlay, "Step1", "interface/step1_small.rttex", 0, true);
	m_pStep2 = CreateOverlayEntity(m_pSlideOverlay, "Step2", "interface/step2_small.rttex", 0, true);

	SetupStepEnt(m_pStep1);
	SetupStepEnt(m_pStep2);
	int timerMS = 0;

	LowerSlideScreen();

	//ZoomToPositionFromThisOffsetEntity(pTitle, CL_Vec2f(0, -GetScreenSizeYf() / 2), 1000, INTERPOLATE_SMOOTHSTEP, timerMS);
	GetAudioManager()->Play("audio/intro.wav");

	/*
	timerMS += 4000;
	ZoomToPositionEntityMulti(pTitle, CL_Vec2f(GetScreenSizeXf() / 2, +GetScreenSizeYf() * 2), 1000, INTERPOLATE_SMOOTHSTEP, timerMS);
	timerMS += 1000;
	KillEntity(pTitle, timerMS);
	*/
	Entity *pOverlay = GetParent()->AddEntity(new Entity("Overlay"));
	
	m_pEnergyEnt = CreateTextLabelEntity(pOverlay, "Energy", 10, GetScreenSizeYf() - 50, "0");
	SetupTextEntity(m_pEnergyEnt, FONT_LARGE, 1.0);
	GetApp()->GetFont(FONT_LARGE)->SetSmoothing(false);
	UpdateEnergyText();
	SetTextShadowColor(m_pEnergyEnt, MAKE_RGBA(0, 0, 0, 255));

	m_pDebugEnt = CreateTextLabelEntity(pOverlay, "DebugText", 75, GetScreenSizeYf() - 280, "");
	SetupTextEntity(m_pDebugEnt, FONT_LARGE, 1.0);
	AdvanceStepAnim(); //so both aren't being displayed
}

**Comment by YourBoiBusy** [comment]
fake?!?!!? lol

**Comment by YourBoiBusy** [comment]
@GrowtopiaNoobs  we need find a way for this fucking kid

**Comment by 1337abood** [comment]
It is not fake. I legitimately coded it to extract the growtopia source code into a text file through a hook function called "OnExtractSource". Did you really think it just threw up random code that contains gt functions? I am a reverse engineer I know what it is.

**Comment by YourBoiBusy** [comment]
"Do I care your fake tree using cheat engine? "

**Comment by YourBoiBusy** [comment]
idc about your OnExtractSource
lol

**Comment by xXAbood** [comment]
> It is not fake. I legitimately coded it to extract the growtopia source code into a text file through a hook function called "OnExtractSource". Did you really think it just threw up random code that contains gt functions? I am a reverse engineer I know what it is.

sup raiter

**Comment by 1337abood** [comment]
It is not mine. It is really seth's trap code in Growtopia files so he can get source code of ubisoft updates. I just hooked the function.

**Comment by xXAbood** [comment]
i just said hi and ur not responding

**Comment by 1337abood** [comment]
Hello. I'm a reverse engineer currently working on a VB.Net server. How can I help you?

**Comment by YourBoiBusy** [comment]
lol...
