### ISSUE TITLE
[BUG] how i can crash with internal? if u have source dm me epicgamer#4191

### ISSUE THREAD

**Issue by Raiterjakii** [GrowtopiaNoobs/GrowtopiaServer#1450]
i need crash with internal i will buy source if u want!

**Comment by YourBoiBusy** [comment]
u can ask  the kids that they flex with there codes

**Comment by xXAbood** [comment]
moment

**Comment by raiterjaki** [comment]
lol

**Comment by playingoDEERUX** [comment]
![image](https://user-images.githubusercontent.com/62474734/82444105-f7bd9e00-9aa2-11ea-9aad-56505554d563.png)

**Comment by raiterjaki** [comment]
lol

**Comment by xXAbood** [comment]
![image](https://user-images.githubusercontent.com/59313717/82446898-84bf2200-9ab8-11ea-8769-d88da54876eb.png)

**Comment by xXAbood** [comment]
that moment when u use quasar stub
![image](https://user-images.githubusercontent.com/59313717/82446977-a7513b00-9ab8-11ea-9e82-53def92414a5.png)

**Comment by raiterjaki** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/issues/1258

**Comment by xXAbood** [comment]
> #1258

responding to who

**Comment by raiterjaki** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/issues/1258

**Comment by Raiterjakii** [comment]
fake

**Comment by raiterjaki** [comment]
I don't even live in Istanbul

**Comment by Hades3377** [comment]
#1258 to almost everyone here!!1!1! legit stop being autistic this #1258 stop being the next bexpg

**Comment by Raiterjakii** [comment]
u fake

**Comment by Raiterjakii** [comment]
lel show proof i bexpg

**Comment by raiterjaki** [comment]
I don't live in Istanbul so that's the proof that you are fake no need to argue.

**Comment by Raiterjakii** [comment]
ur not real raiter retard????

**Comment by raiterjaki** [comment]
keep going. it doesn't affect me in any way.

**Comment by Raiterjakii** [comment]
k what ur discord

**Comment by Hades3377** [comment]
yeah im pretty sure you guys have impersonated people before so saying "tHaTs noT mE" doesn't change shit

**Comment by Hades3377** [comment]
literally let this repo follow it's actual issues then messing around, idc who is impersonating who @raiterjaki didn't you call me and abood out for asking peace in impersonating?

**Comment by xXAbood** [comment]
its the same person trying to create drama and gain attention.

**Comment by raiterjaki** [comment]
yeah he is probably from "internal team"

**Comment by Hades3377** [comment]
<img width="602" alt="Screenshot 2020-05-20 at 9 01 44 PM" src="https://user-images.githubusercontent.com/50758890/82449158-5c95ea00-9add-11ea-8c44-63c80c4569a8.png">
<img width="769" alt="Screenshot 2020-05-20 at 9 01 49 PM" src="https://user-images.githubusercontent.com/50758890/82449163-5ef84400-9add-11ea-9827-682346349b9c.png">
??

**Comment by Hades3377** [comment]
these were images from your old issue, please stop, and focus on real issues by real people.

**Comment by raiterjaki** [comment]
I am not posting off-topic issues like how "internal team" did and I'm not crying or getting angry at someone.

**Comment by MoanHawks** [comment]
bykp v4 here 😳

**Comment by raiterjaki** [comment]
yeah

**Comment by xXAbood** [comment]
> I am not posting off-topic issues like how "internal team" did and I'm not crying or getting angry at someone.

ur still talking about urself

**Comment by GrowtopiaNoobs** [comment]
@Raiterjakii You are banned as of #1258

**Comment by playingoDEERUX** [comment]
@xXAbood a lot of people know that I attempted to get access to your device because of the fact that you were trying to abuse us (you failed) and it was the only exceptionary case where I ever touched a rat again.
Also @Raiterjakii is abood.
