### ISSUE TITLE
load balancer

### ISSUE THREAD

**Issue by NotDark** [GrowtopiaNoobs/GrowtopiaServer#149]
How to use that with private server?
 i no sure like what i need do

![image](https://user-images.githubusercontent.com/44568476/54361943-0c362780-46a3-11e9-9c81-981669149890.png)

**Comment by ilyn1337** [comment]
1) Re-write the project.
2) Use MYSQL.
3) Use low-length string encryptor.

**Comment by ritzysw** [comment]
Mysql could actually improve server performance dramatically
