### ISSUE TITLE
Building the code

### ISSUE THREAD

**Issue by CrazyMonkey313** [GrowtopiaNoobs/GrowtopiaServer#153]
I am using Microsoft Visual Studio 2015, Ive opened enet server test.sln with it and ive edited the gazette only and i press build and there is 3415 errors and i cannot build anyone help please?

**Comment by NotDark** [comment]
show the error?

**Comment by CrazyMonkey313** [comment]
> show the error?

there are 3415 errors ... How am i supposed to show all of em

**Comment by SecretHax** [comment]
Try using Visual Studio 2017 Community, I’m working on that IDE

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CrazyMonkey313** [comment]
> Try using Visual Studio 2017 Community, I’m working on that IDE
> 
> Sent with [GitHawk](http://githawk.com)

Hey Ive finished editing what i want and now when i try to build it says "run code on build analysis" ive done that and its done nothing.

**Comment by CrazyMonkey313** [comment]
dw about above, 
and build the code because i've redownloaed, went into vs 2017 and built it, it builds then i successfully builds and doesnt save anywhere. But yea can someone get the source code and can you add "addAdmin("Matty", "1234", 999);" please and give me the exe for it please

**Comment by ilyn1337** [comment]
Errors from linker. Right click to your project then; Configuration Features -> General -> Windows SDK Version, then select Latest one, then again;  Configuration Features -> General -> Toolkit (i think) then select your visual studio version. Then; Configuration Features -> VC++ Directories -> Include Directories, then add this line: `$(VC_IncludePath);$(WindowsSDK_IncludePath);` and Refernce Directories: `$(VC_ReferencesPath_x86);` and Library Directories: `$(VC_LibraryPath_x86);$(WindowsSDK_LibraryPath_x86);`

If solved, dont forget to close this issue...

**Comment by SecretHax** [comment]
>dw about above,  ...

@CrazyMonkey313 I’ll help you. Contact me on discord: SecretHax#0001

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mempler** [comment]
Please don't send only one number anymore. this can be miss leading. Just send the whole number E.G `SecretHax#0001` since that is the only wa

**Comment by SecretHax** [comment]
>Please don't send only one number anymore. this can be miss leading. Just send the whole number E.G `SecretHax#0001` since that is the only way to add somebody ...

@Mempler sry, my githawk app is bugged.. zz

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CrazyMonkey313** [comment]
@SecretHax I've added you my name is Matty
