### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by CrazyMonkey313** [GrowtopiaNoobs/GrowtopiaServer#156]
Ihave finally fixed the issue with compiling the code, I run the run.py and the old server.exe(i downloaded off someone else, please keep in mind it worked before) i log into it just to make an account but it wont let me , it says updating item data 1/65 , Disconnected? Will attempt to reconnect. and just repeats? Can anyone help please

**Comment by ilyn1337** [comment]
1) Get the latest items.dat hash
2) Old server is outdated, compile urs and run it
3) Log into real server and wait until it updates the item data
4) Right click to Growtopia and open the file location
5) Go to cache folder and copy the "items.dat"
6) Go to your server path and paste the items.dat

Note: You have to do step 1 to connect to the server...

**Comment by FuzionVapes** [comment]
Hello Ilyn1337 do you have discord

**Comment by ilyn1337** [comment]
I have but why? @FuzionVapes

**Comment by FuzionVapes** [comment]
I just need help with something

**Comment by SecretHax** [comment]
>1) Get the latest items.dat hash ...

@ilyn1337 Well, my server isn’t using the latest hash and still it’s working :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FKSP** [comment]
Same with mine server :)

**Comment by ilyn1337** [comment]
@SecretHax then pr ur code to this server so people dont ask i cant connect...

**Comment by SecretHax** [comment]
>@SecretHax then pr ur code to this server so people dont ask i cant connect...

@ilyn1337 Hahahah, You’re kidding.
That thing is really rare and I won’t share it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ritzysw** [comment]
You don't need new items.dat hash if you host all texture files on your machine

**Comment by SecretHax** [comment]
>You don't need new items.dat hash if you host all texture files on your machine

@ritzysw Ritzy -.-
Don’t leak that!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mempler** [comment]
But you'll need the hash if you want to host updates :P
