### ISSUE TITLE
[Question] How i can get this ?

### ISSUE THREAD

**Issue by WolfPT** [GrowtopiaNoobs/GrowtopiaServer#159]
![1](https://user-images.githubusercontent.com/45072228/54493222-6838c000-48de-11e9-9276-1230726e500a.PNG)

**Comment by ilyn1337** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/issues/92#issuecomment-441206797

**Comment by WolfPT** [comment]
@ilyn1337 how i can get the with gt bot ?

**Comment by Mempler** [comment]
By modifying the bot.
