### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by xVENUS** [GrowtopiaNoobs/GrowtopiaServer#16]
Hello I wanna ask... I really want to understand to this and I've added u on ur discord I downloaded server.exe and source what should I do next? (Kdyztak cz) u can reply on my discord venus#9880

**Comment by GrowtopiaNoobs** [comment]
Here is tutorial: https://github.com/GrowtopiaNoobs/GrowtopiaServer/wiki/Basic-setup

**Comment by xVENUS** [comment]
Can u make video step by step? Emmm

**Comment by GrowtopiaNoobs** [comment]
I am not planning to do it now, but maybe sometime in future. Closing.
