### ISSUE TITLE
How To Build To Exe Files And Fix Errors!

### ISSUE THREAD

**Issue by Fluthfi** [GrowtopiaNoobs/GrowtopiaServer#160]
![image](https://user-images.githubusercontent.com/44535388/54518096-15bada80-4996-11e9-8676-4f1ddc880e7b.png)

**Comment by SecretHax** [comment]
Install VS 2017 Community with .NET frameworks for c++ and other

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Fluthfi** [comment]
Uh Me Wait 1 Hour To Install It Xd , What Extension I Need To Download?

**Comment by CrazyMonkey313** [comment]
> Install VS 2017 Community with .NET frameworks for c++ and other
> 
> Sent with [GitHawk](http://githawk.com)

Hey i know i should post on my thread but , when i try and join my ps and the compiled server.exe i edited the run.py comes up with this
`Server Launcher (c) Growtopia Noobs
jordan#0495 on discord!
Record growtopia1.com to localhost already found!
Growtopia private server (c) Growtopia Noobs
Updating item data success!
Launching HTTP server! (Python 2.x)
HTTP server is running! Don't close this or GT will be unable to connect!
127.0.0.1 - - [18/Mar/2019 19:29:29] "POST /growtopia/server_data.php HTTP/1.0" 200 -
127.0.0.1 - - [18/Mar/2019 19:29:35] "POST /growtopia/server_data.php HTTP/1.0" 200 -
127.0.0.1 - - [18/Mar/2019 19:29:57] "POST /growtopia/server_data.php HTTP/1.0" 200 -`

and server.exe sits at this 
`Growtopia private server (c) Growtopia Noobs
Updating item data success!
Building items database...
Database is built!`

**Comment by SecretHax** [comment]
>> Install VS 2017 Community with .NET frameworks for c++ and other ...

@CrazyMonkey313 yeah, it’s right, sorry but my githawk app is bugged..

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CrazyMonkey313** [comment]
> > > Install VS 2017 Community with .NET frameworks for c++ and other ...
> 
> @CrazyMonkey313 yeah, it’s right, sorry but my githawk app is bugged..
> 
> Sent with [GitHawk](http://githawk.com)

I've added you my name is `Matty#3632`

**Comment by herothedev** [comment]
@fluthfi even one cmd can make 1000+ errors so what command you revently added so it may cna be error creator :)

**Comment by OverallGod** [comment]
Hey bud you need to re build the files or download the cache files from my video. And extract it to your Growtopia folder. You disconnect in Growtopia right?
