### ISSUE TITLE
Can't debug growtopia bot to get hash

### ISSUE THREAD

**Issue by SecretHax** [GrowtopiaNoobs/GrowtopiaServer#163]
![xd](https://user-images.githubusercontent.com/48394201/54531490-b81e9200-4985-11e9-8464-11536c158c8d.png)

**Comment by SecretHax** [comment]
The error says that I didn't choose the compiler. How to choose it then? What's the location of compiler in QT 2013?

**Comment by OverallGod** [comment]
You could try googling it? I would help you more but my wifi isn't working

**Comment by OverallGod** [comment]
You need to download this 
https://www.qt.io/download-qt-installer?hsCtaTracking=9f6a2170-a938-42df-a8e2-a9f0b1d6cdce%7C6cb0de4f-9bb5-4778-ab02-bfb62735f3e5
