### ISSUE TITLE
I have the hash but I don't know how to get it working

### ISSUE THREAD

**Issue by FuzionVapes** [GrowtopiaNoobs/GrowtopiaServer#165]
Hello Guys

I need a quick fix  

I already finished setting up the server I just need to update it to 2.988 but then I tried adding the hash but its still not working

**Comment by OverallGod** [comment]
Either you put the hash in the wrong place or it's not the right one

**Comment by SecretHax** [comment]
Or maybe he doesn’t have the right items.dat

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
