### ISSUE TITLE
Error connecting

### ISSUE THREAD

**Issue by herothedev** [GrowtopiaNoobs/GrowtopiaServer#166]
Hey,

Do you know how to fix error connecting, error?
I have VPS, i allowed 17019 and 80 ports on firewall, and downloaded visual studio.
My server.exe doesn't give me any error, and it is running without any errors and run.py too, and i updated 127.0.0.1 in run.py to my VPS ip, and it is correct so how i can fix this?

**Comment by OverallGod** [comment]
Make sure it's 17091 UDP not TCP

**Comment by SecretHax** [comment]
> Hey,
> 
> Do you know how to fix error connecting, error?
> I have VPS, i allowed 17019 and 80 ports on firewall, and downloaded visual studio.
> My server.exe doesn't give me any error, and it is running without any errors and run.py too, and i updated 127.0.0.1 in run.py to my VPS ip, and it is correct so how i can fix this?

Step 1: Turn off the firewall. Private and public one. You don't need it on a clear vps...
Step 2: Install XAMPP
Step 3: Put all server files in /xampp/htdocs
Step 4: Run apache from xampp control panel
Step 5: Run server.exe
Step 6: In /growtopia/server_data.php change the ip and port to the right ones. IP ,= ur vps ip, PORT = ur server.exe port.
Done
