### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by herothedev** [GrowtopiaNoobs/GrowtopiaServer#167]
Hey, 

How i cna change World Selection Menu music?

**Comment by mar4ello6** [comment]
In end of "OnSuper" line, edit "choosemusic=audio/mp3/about_theme.mp3"

**Comment by SecretHax** [comment]
>In end of "OnSuper" line, edit "choosemusic=audio/mp3/about_theme.mp3"

@mar4ello6 I think it’s logging in music

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Tryp0** [comment]
@SecretHax mar4ello6 is right -.-

**Comment by ilyn1337** [comment]
find "choosemusic" with CTRL + F. Change about_theme.mp3 to whatever you want: Music list that alloved to use;
`
audio/mp3/about_theme.mp3
audio/mp3/battle_theme_loop.mp3
audio/mp3/digital_rain.mp3
audio/mp3/paddys_day_loop.mp3
audio/mp3/theme.mp3
audio/mp3/theme4.mp3
`

**Comment by SecretHax** [comment]
>@SecretHax mar4ello6 is right -.-

@Tryp0 Well, A.M.A.Z.I.N.G. :D

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
