### ISSUE TITLE
Denying unknown/crashable packets from Growtopia Bot/Peer

### ISSUE THREAD

**Issue by ilyn1337** [GrowtopiaNoobs/GrowtopiaServer#169]
As we all know, Bot attacks now popular... Do someone have any ideas about that? Or do you have any solution about that?

**Comment by SecretHax** [comment]
>As we all know, Bot attacks now popular... Do someone have any ideas about that? Or do you have any solution about that?

@ilyn1337 I have anti packet spam

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ilyn1337** [comment]
@SecretHax its different...

**Comment by SecretHax** [comment]
>@SecretHax its different...

@ilyn1337 2 len packet or NULL packet?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ritzysw** [comment]
There's prob hundreds of ways to crash servers with bot, of which I know like 15. It will take long time to find and fix every single one. Another fix is that you can make captcha (not like gt, it's retarded and easy to bypass), and don't accept any packets from client until captcha was solved

**Comment by ilyn1337** [comment]
Uhh I debug something, when bot connecting to server, (with any ways) packet.dataLength always 61 (blocking this packet is working...).

Also yeah, I will make captcha as you said @ritzysw.

**Comment by ritzysw** [comment]
You can also check if player_age is provided in enter_game packet and if protocol is 44 (bot source is old so it doesnt have that)

**Comment by SecretHax** [comment]
>You can also check if player_age is provided in enter_game packet and if protocol is 44 (bot source is old so it doesnt have that)

@ritzysw how to check the protocol?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ilyn1337** [comment]
@ritzysw oh smart idea 👍
