### ISSUE TITLE
What i'm doing wrong?

### ISSUE THREAD

**Issue by GrowtopiaGame** [GrowtopiaNoobs/GrowtopiaServer#17]
What im doing wrong i've stucked at this point can u please write me what im doing wrong? :dagger: 
![image](https://user-images.githubusercontent.com/43999532/46682348-9ad2e400-cbed-11e8-9b59-6abfdce2e6dc.png)

**Comment by GrowtopiaNoobs** [comment]
You have everything right, check this out: https://github.com/GrowtopiaNoobs/GrowtopiaServer/wiki/Basic-setup

**Comment by xVENUS** [comment]
Then what I should do next I've stucked at this point and dunno what next

**Comment by Dunzap** [comment]
after that im stuck..

**Comment by Mempler** [comment]
I'll close that issue since @GrowtopiaNoobs gave an answer that fits perfectly for this one.
