### ISSUE TITLE
i need help with code

### ISSUE THREAD

**Issue by fargamer** [GrowtopiaNoobs/GrowtopiaServer#171]
Hello can any one give me the source code for banning players from the game ?
thanks

**Comment by OverallGod** [comment]
It doesn't work like that. In my eyes you need to prove yourself and try your hardest to make it yourself and if you have trouble we all will be here to help you

**Comment by OverallGod** [comment]
I think of it like sharing homework that you worked really hard on. And the other person takes it learns nothing and gets full credit. What's going to happen the next time you need "codes"

**Comment by SecretHax** [comment]
>Hello can any one give me the source code for banning players from the game ? ...

@fargamer Hahahahaha, When a toxic indog joins discord and begs for code.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
