### ISSUE TITLE
22 Errors in Project. And can't build the Private server.

### ISSUE THREAD

**Issue by NoobesGT** [GrowtopiaNoobs/GrowtopiaServer#172]
How to fix it?
from the newest version of PRIVATE SERVER OF Growtopia Noobs.

**Comment by SecretHax** [comment]
What's your IDE?

**Comment by ilyn1337** [comment]
Learn C++ first... If you know c++ you should fix errors...

**Comment by OverallGod** [comment]
XD he's gonna take a 6 month course just so he can build a Growtopia server @ilyn1337

**Comment by NoobesGT** [comment]
Visual studio

**Comment by Mempler** [comment]
You know, Nobody can help you if you're not providing:
Screenshots,
Logs,
Errors,
Full IDE name including Version E.G Visual Studio 2019.

**Comment by Mempler** [comment]
And i would appreciate if you delete that repository since it breaks the License Agreement. https://github.com/NoobesGT/GrowtopiaPrivateServer + you recredit yourself with something you haven't wrote.
