### ISSUE TITLE
Found items.dat hashing function

### ISSUE THREAD

**Issue by coldchip** [GrowtopiaNoobs/GrowtopiaServer#173]
Here is the items.dat hashing function i extracted and recreated from Proton SDK

Proton SDK is a Open Sourced SDK that Growtopia Uses. 

The hashing function uses circular shift hash. 

**Note: My code is linux based.** 

```
// Created By ColdChip
#include <iostream>
#include <cstdint>
#include <cstring>
#include <vector>
#include <stdint.h>
#include <string>
#include <fstream>
#include <utility>
#include <sstream>
#include <unistd.h>
#include <limits.h>

using namespace std;

std::ifstream::pos_type filesize(const char* filename)
{
    std::ifstream in(filename, std::ifstream::ate | std::ifstream::binary);
    return in.tellg(); 
}

uint32_t HashString(unsigned char *str, int len)
{
    if (!str) return 0;

    unsigned char *n = (unsigned char *) str;
    uint32_t acc = 0x55555555;

    if (len == 0)
    {
        while (*n)
            acc = (acc >> 27) + (acc << 5) + *n++;
    } else
    {
        for (int i=0; i < len; i++)
        {
            acc = (acc >> 27) + (acc << 5) + *n++;
        }
    }
    return acc;

}

unsigned char *getA( string fileName, int *pSizeOut, bool bAddBasePath, bool bAutoDecompress)
{
    
        unsigned char * pData = NULL;


            //just try to load it from the default filesystem.  Should I create a FileSystemDefault for this to make it cleaner?
        
        FILE *fp = fopen(fileName.c_str(), "rb");
        if (!fp)
        {
            
            //not really an error, we might just want to know if a file exists
            //LogMsg("Warning: Proton FileManager says can't open %s", fileName.c_str());
            //file not found    
            if (!fp) return NULL;
        }

        fseek(fp, 0, SEEK_END);
        *pSizeOut = ftell(fp);
        fseek(fp, 0, SEEK_SET);

        pData = (unsigned char*)new unsigned char[( (*pSizeOut) +1)];
        if (!pData)
        {
            printf("Out of memory opening %s?", fileName.c_str());
            return 0;
        }
        //we add an extra null at the end to be nice, when loading text files this can be useful
        pData[*pSizeOut] = 0; 
        fread(pData, *pSizeOut, 1, fp);
        fclose(fp);

        return pData;
}

int main() {
    uint8_t *pData;
    int size = 0;
    const char filename[] = "items.dat";
    size = filesize(filename);
    pData = getA((string)filename, &size, false, false);

    printf("%i", HashString((unsigned char*)pData, size));
}

**Comment by SecretHax** [comment]
Wow... Can you do also unhashing function?

**Comment by coldchip** [comment]
@SecretHax You can't unhash a 'hash' because it's a one way function and once you hashed a string, it can't be undone.

**Comment by DrOreo002** [comment]
Really cool!, gj

**Comment by SecretHax** [comment]
> @SecretHax You can't unhash a 'hash' because it's a one way function and once you hashed a string, it can't be undone.

Well, I got 40 errors when I compile it...

**Comment by coldchip** [comment]
@SecretHax This is linux based C++.

**Comment by OverallGod** [comment]
Oh nice xD

**Comment by ritzysw** [comment]
This would be good if we atleast knew what original unhashed string is supposed to be

**Comment by coldchip** [comment]
@ritzysw The unhash version is the items.dat contents

**Comment by OverallGod** [comment]
So we can create our own updates?

**Comment by coldchip** [comment]
@OverallGod Yes. If you know how to edit RTTEX files.

**Comment by OverallGod** [comment]
That's awesome @coldchip  rttex files are really easy to edit

**Comment by SecretHax** [comment]
>@ritzysw The unhash version is the items.dat contents

@coldchip So, if you hash the items.dat files content, you will get the hash which server uses.. But how to get it working on windows? Could we chat on discord tho?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NotDark** [comment]
so can decode items.dat?

**Comment by ilyn1337** [comment]
For windows:
https://stackoverflow.com/questions/341817/is-there-a-replacement-for-unistd-h-for-windows-visual-c

**Comment by ritzysw** [comment]
This is hashing method, not decoding method and no you can't, hash is one way process and can't be reversed

**Comment by ilyn1337** [comment]
Or you can get windows fix from here: https://github.com/ilyn1337/ItemsDatUnhashTool
To download tool: https://github.com/ilyn1337/ItemsDatUnhashTool/tree/master/x64/Debug

**Comment by OverallGod** [comment]
Thanks @ilyn1337 and @coldchip

**Comment by OverallGod** [comment]
Also who knows where Ubi hosts the items.dat

**Comment by coldchip** [comment]
@SecretHax coldchip#6359

**Comment by coldchip** [comment]
@OverallGod The items.dat is sent to the client using ENET when the client send `action|refresh_item_data` to the server.

**Comment by OverallGod** [comment]
Could you directly download it?

**Comment by OverallGod** [comment]
Could I make a fake client

**Comment by coldchip** [comment]
@OverallGod The only way to extract the items.dat is creating a fake client. 

This is what is looks like when the server sends the items.dat packet

```0400000010000000FFFFFFFF0000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000F4697................................```

First 56 bytes are just a random identifier followed by another 4 bytes which is the items.dat length and finally the data of the items.dat(the `.......`)

**Comment by OverallGod** [comment]
Hmm I wish it was as easy as 1 2 3

**Comment by GrowtopiaNoobs** [comment]
Closing this issue as the code has been merged.
