### ISSUE TITLE
Hey, again...

### ISSUE THREAD

**Issue by herothedev** [GrowtopiaNoobs/GrowtopiaServer#174]
So, do anyone how to **COMPELETELLY** setup an vps, for growtopia private server, if someone knows ocntact me on discord: Hero#7865

**Comment by OverallGod** [comment]
Look in the wiki also just open the ports and run the server and that's it

**Comment by OverallGod** [comment]
Also if you can't figure it out yourself then I would recommend not getting into the private server business
