### ISSUE TITLE
Updating Core data and descriptions

### ISSUE THREAD

**Issue by OverallGod** [GrowtopiaNoobs/GrowtopiaServer#175]
If I wanted to update these how would I go about doing it?

**Comment by NotDark** [comment]
update manual

**Comment by SecretHax** [comment]
> update manual

Genius ^^

**Comment by OverallGod** [comment]
I know. "Update manual" gives me so much information. It's like a really detailed step by step

**Comment by SecretHax** [comment]
>I know. "Update manual" gives me so much information. It's like a really detailed step by step

@OverallGod It’s as good as dark in everything lol

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by OverallGod** [comment]
XD
