### ISSUE TITLE
I made a Linux version of your code

### ISSUE THREAD

**Issue by coldchip** [GrowtopiaNoobs/GrowtopiaServer#18]
Hello, 

I'm the guy who wanted to make a PHP version of Enet but failed....

I somehow grasped some C++ knowledge and somehow made a Linux version of your code. (I credited you) 

https://github.com/coldchip/growtopiaserver

But i'm stuck somehow. (At the logging on)

The client is sending `0400000026` (messageType=0x04 packetType=0x26)

I don't know what to send back to the client...

I'm using Growtopia client 2.983

And by the way, how can i setup a ENet repeater so that i can capture the data send from the client to the server?

Thanks in advance if you can help me with this :)

**Comment by GrowtopiaNoobs** [comment]
I don't have any idea what this packet does, but I think that you can safely ignore it. Btw I put this comment:

> You can try to use wine (I think it should work fine) or remove Windows.h yourself.
> If I remember corretly you just would need to add following line of code:
> `#define BYTE char` or maybe `typedef char BYTE`
> and then remove SetCtrlHandler call + HandlerRoutine.

in another thread (#11). Have you tried it? But if you want to experiment with making server at your own then I wish you alot of luck. :+1:

**Comment by coldchip** [comment]
Hi, 

Thanks for your reply. 
I had not tried your code with wine but i will do that in the future :)

I'm just curious as how do you find out what each packet does??

Did you use a Enet repeater to capture the data?

**Comment by GrowtopiaNoobs** [comment]
I made basic ENet repeater, but I haven't used it much (there is missing implementation of OnSendToServer). I am using old growtopia decompiled source.

**Comment by coldchip** [comment]
Hi,
Is it possible for you the share the ENet repeater code with me? I really need it 😭.

**Comment by GrowtopiaNoobs** [comment]
Sorry, I don't share it + as I said, there is missing implementation of OnSendToServer so it is mostly useless.

**Comment by Mempler** [comment]
This issue was quite inactive for around 1 month. i'll close that one.
