### ISSUE TITLE
[QUESTION] How to change display name without re-enter?

### ISSUE THREAD

**Issue by RU15** [GrowtopiaNoobs/GrowtopiaServer#181]
I'm using OnNameChanged, but it still require re-enter.

**Comment by ritzysw** [comment]
OnNameChanged requires you to memcpy netid

**Comment by RU15** [comment]
Can help please? I don't good in programming... It don't work: `memcpy(p2.data + 4, &(((PlayerInfo*)(peer->data))->netID), 4);`

**Comment by RU15** [comment]
@ritzysw

**Comment by SecretHax** [comment]
Use that:
`                                               string name;
						GamePacket p3 = packetEnd(appendString(appendString(createPacket(), "OnNameChanged"), name));
						memcpy(p3.data + 8, &(((PlayerInfo*)(peer->data))->netID), 4); // ffloor
						ENetPacket * packet3 = enet_packet_create(p3.data,
							p3.len,
							ENET_PACKET_FLAG_RELIABLE);
						ENetPeer * currentPeer;
						for (currentPeer = server->peers;
							currentPeer < &server->peers[server->peerCount];
							++currentPeer)
						{
							if (currentPeer->state != ENET_PEER_STATE_CONNECTED)
								continue;
							if (isHere(peer, currentPeer))
							{
								enet_peer_send(currentPeer, 0, packet3);
							}
						}
						delete p3.data;`

**Comment by SecretHax** [comment]
Code: [https://pastebin.com/X6H46Ch9](url)

**Comment by RU15** [comment]
@SecretHax Ty for code it work, but only with minimum 5 letter nick. Can I fix it somehow or no?

**Comment by RU15** [comment]
I fixed it. Ty SecretHax!

**Comment by playingo** [comment]
how did u fix it?
