### ISSUE TITLE
How would you make an items.dat ?

### ISSUE THREAD

**Issue by OverallGod** [GrowtopiaNoobs/GrowtopiaServer#183]

**Comment by OverallGod** [comment]
If i am able to make an items.dat i will be able to add my own items

**Comment by OverallGod** [comment]
I think I found a way I just need some help :)
https://github.com/svn2github/ProtonSDK/tree/master/tools/RTPack

**Comment by ilyn1337** [comment]
proton sdk doesnt contain anything about items.dat... you can find some functions but no items.dat

**Comment by OverallGod** [comment]
Hmm I dont know

**Comment by SecretHax** [comment]
Step 1: Open notepad
Step 2: Write '123'
Step 3: Save as items.dat
Done!

**Comment by OverallGod** [comment]
That won't actually do anything xD 😂

**Comment by SecretHax** [comment]
>That won't actually do anything xD 😂

@OverallGod Well, you asked how to make a file, so here you go!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
