### ISSUE TITLE
[QUESTION] Block Pointers and Block Visuals

### ISSUE THREAD

**Issue by ilyn1337** [GrowtopiaNoobs/GrowtopiaServer#184]
Yeah, as you can see here: https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/40ff696d309f20d7272d3fadf336174866a57b8e/enet%20server%20test/enet%20server%20test.cpp#L1828 there is an integer called type. Also yes, 1 is locked area, but its always RED... Not green, yellow and etc... Any ideas???

**Comment by MarmoriPelaa** [comment]
I would go ahead and try this: Set type to 2 in the code. The thing here is that you have to TEST your code quite often and you should experiment with it.
