### ISSUE TITLE
[NEED HELP] How To Fix This?

### ISSUE THREAD

**Issue by partyanimals** [GrowtopiaNoobs/GrowtopiaServer#185]
![error](https://user-images.githubusercontent.com/49124339/55290931-9dc3ca00-5403-11e9-985a-46bb02410bde.png)

Im using Visual Studio Community 2015 and Net.Framework 4.6. Any Solution for this error? Thank's :)

**Comment by Mempler** [comment]
Ignore those errors. Build should complete anyway.

**Comment by ilyn1337** [comment]
@Mempler 2 down emoji xD
