### ISSUE TITLE
How to setup server on web server?

### ISSUE THREAD

**Issue by Zaxior** [GrowtopiaNoobs/GrowtopiaServer#19]

**Comment by coldchip** [comment]
No you can't. Web server uses TCP/IP to transmit the data to the client while Growtopia uses ENET UDP to transmit the data to the server.

**Comment by GrowtopiaNoobs** [comment]
You need to use VPS or your own computer. It **isn't** possible with stuff like 000webhost.com.

**Comment by xVENUS** [comment]
What is best VPS hosting if I understand?

**Comment by ritzysw** [comment]
> What is best VPS hosting if I understand?

https://www.vpsnet.com/ is pretty good vps(i use it) but it doesnt have udp ddos protection so its your choice to buy it or not
