### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by fargamer** [GrowtopiaNoobs/GrowtopiaServer#190]
Hello so today a new update of growtopia came v2.989 and i want the hash of it 
and can anyone tell me how to find the hash ? 
thanks

**Comment by ilyn1337** [comment]
?purge 1000

**Comment by ilyn1337** [comment]
840038818

**Comment by fargamer** [comment]
ok thank you but why when i host a vps and try to connect it keep dc ?

**Comment by SecretHax** [comment]
Check this:[https://github.com/GrowtopiaNoobs/GrowtopiaServer/pull/191](https://github.com/GrowtopiaNoobs/GrowtopiaServer/pull/191)
If you have any other problems - contact me on discord: `SecretHax#0001`
