### ISSUE TITLE
coredata.txt and descriptioms.txt

### ISSUE THREAD

**Issue by Dunzap** [GrowtopiaNoobs/GrowtopiaServer#193]
where exactly do i get them if its not in the wikia anymore

**Comment by NotDark** [comment]
https://github.com/NotDark/GrowtopiaItemDatabase

**Comment by Dunzap** [comment]
I need a 2.989 coredata.txt and 2.989 descriptions.txt

if there isnt any can i have an installer for 2.986 for windows 10 gt

**Comment by willi123yao** [comment]
There is no version specific CoreData.txt and Descriptions.txt, all will work for any version of the server.
