### ISSUE TITLE
Saveset code needed

### ISSUE THREAD

**Issue by Growtopiaprivateserver** [GrowtopiaNoobs/GrowtopiaServer#194]
can i have save set code please i need it :) thanks

**Comment by OverallGod** [comment]
Don't ever ask for "codes" ask for help or learn c++ saving sets really isn't hard at all

**Comment by OverallGod** [comment]
Even if we did have it and we gave it to you. All your going to do is add it then take credit for it without our knowledge

**Comment by SecretHax** [comment]
>can i have save set code please i need it :) thanks ...

@Growtopiaprivateserver Oooh, Can I have 100k $ because I want to buy a rolex?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by OverallGod** [comment]
My point exactly

**Comment by SecretHax** [comment]
>My point exactly

@OverallGod haha

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by QKVLR** [comment]
@Growtopiaprivateserver Do u have a discord ?
