### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by fargamer** [GrowtopiaNoobs/GrowtopiaServer#195]
Hi 
how to make the items save because it dont save for me any one can help ?

**Comment by OverallGod** [comment]
It's not as simple as you ask and we give.🙄😒

**Comment by fargamer** [comment]
contact me discord cmd#4804 ok

**Comment by OverallGod** [comment]
Why

**Comment by SecretHax** [comment]
>Hi  ...

@fargamer how to get 100k $ for a rolex?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fargamer** [comment]
i want to talk with u

**Comment by OverallGod** [comment]
About what?

**Comment by fargamer** [comment]
about this

**Comment by OverallGod** [comment]
There is nothing to talk about and we can talk here

**Comment by fargamer** [comment]
ok do u sell the code for real gt wls then ?

**Comment by OverallGod** [comment]
I don't sell any codes

**Comment by OverallGod** [comment]
I will admit I do know how to save sets I just don't think you should be asking for it.

**Comment by QKVLR** [comment]
fargamer i have save set code u have discord?
