### ISSUE TITLE
ios

### ISSUE THREAD

**Issue by fargamer** [GrowtopiaNoobs/GrowtopiaServer#200]
why when i try to login from ios it keep dc + i did the thing for ios and gt is latest and updated item data

**Comment by SecretHax** [comment]
> why when i try to login from ios it keep dc + i did the thing for ios and gt is latest and updated item data

Use the code from repository.
Use items.dat and hash from my generator: [http://generator.process4ward.com](http://generator.process4ward.com)
It should work then
