### ISSUE TITLE
how can i run the server

### ISSUE THREAD

**Issue by hartanto4s** [GrowtopiaNoobs/GrowtopiaServer#201]
what app do i need to run this server and can someone guide me how to run it?

**Comment by OverallGod** [comment]
Look in the wiki

**Comment by hartanto4s** [comment]
what app do i need .
only python?

**Comment by willi123yao** [comment]
The [**wiki**](https://github.com/GrowtopiaNoobs/GrowtopiaServer/wiki/Basic-setup) has the setup instructions and you just need to ensure you have the requirements stated there including your compiled server exe itself.

**Comment by hartanto4s** [comment]
how to setup the http server, idont undertand the wiki instruction.

**Comment by Mempler** [comment]
There is no other way around. If you dont understand the instructions in the Wiki, then you shouldn't make a GTPS!
I'll close this issue with this sentence.
