### ISSUE TITLE
Still having the same problem 1 year ago

### ISSUE THREAD

**Issue by Dunzap** [GrowtopiaNoobs/GrowtopiaServer#202]
I've already followed the wiki 5 times and also watched some tutorials online, unfortunately i am still having the same error

Record growtopia1.com to already found!

I tried to find out a way to fix it. 
Additional notes:
- I have added all the files required in
- i have ran notepad as administrator and edited hosts
- i have downgraded as coredata.txt and descriptions.txt are at V2.986
- i have ran run. Py as admin and it does not work still.

Can anyone help me?

**Comment by FKSP** [comment]
It's not a problem.. it shows to me and server is working.

**Comment by Dunzap** [comment]
Do you have any solution?

**Comment by FKSP** [comment]
There is no solution because it's NOT a problem

**Comment by ritzysw** [comment]
It says that because run.py tries to add "127.0.0.1 growtopia1.com" into hosts file if it's not already there, or give that message if it is

**Comment by Dunzap** [comment]
It just made me stuck at the login screen.. I waited for 5 minutea and nothing happened

**Comment by OverallGod** [comment]
Maybe you shouldn't have a private server

**Comment by SecretHax** [comment]
> Maybe you shouldn't have a private server

Hahahaha, best

**Comment by NotDark** [comment]
> It just made me stuck at the login screen.. I waited for 5 minutea and nothing happened

did you use the exe in wiki? if yes the items.dat hash is old

**Comment by Dunzap** [comment]
Yes i did, may i please have the newer server.exe? :)

**Comment by Yoayao** [comment]
you can build the server exe use visual studio

**Comment by Dunzap** [comment]
> you can build the server exe use visual studio

Thanks , i have fixed it
