### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by fargamer** [GrowtopiaNoobs/GrowtopiaServer#203]
Hello
so when i close paython it say saving worlds but it dont save it and sometime it save but all the world get crashed like i have to delete all the worlds 
void saveAllWorlds() // atexit hack plz fix
{
	cout << "Saving worlds..." << endl;
	worldDB.saveAll();
	cout << "Worlds saved!" << endl;
}
this code i have for saving world is there anything wrong with it ?

**Comment by SecretHax** [comment]
> cout << "Saving worlds..." << endl;
> worldDB.saveAll();
> cout << "Worlds saved!" << endl;

Change ur code to:
cout << "Saving worlds..." << endl;
enet_host_destroy(server);
worldDB.saveAll();
cout << "Worlds saved!" << endl;
Should help a bit.
When you close your server, use CTRL+C instead of X symbol.

**Comment by Mempler** [comment]
This issue looks invalid to me since i cant reprodce it.
