### ISSUE TITLE
STUCK AT TIMEOUT IF NOT CONNECTING TO LOCALHOST

### ISSUE THREAD

**Issue by atomiclucky** [GrowtopiaNoobs/GrowtopiaServer#206]
Hello, I have tried running this server on 2 platforms: windows and linux. 

When running a server locally on my computer everything works, but when I try connecting my android phone to my computer via LAN it is stuck on a connection timeout.

When running the server on a linux vps, now I can't join from either of my devices and am getting connection timeout.

I don't why is that happening, but the https python server listens to requests all the time and that confirms that it's not a portforwarding or wrong IP issue

**Comment by GrowtopiaNoobs** [comment]
Have you edited python server to redirect you to right address? (Not 127.0.0.1)
