### ISSUE TITLE
[WARNING] Project Cat GTPS Scam Server

### ISSUE THREAD

**Issue by FuzionVapes** [GrowtopiaNoobs/GrowtopiaServer#207]
Project Cat is a GTPS server 
owner have been getting spoon feed by other people by buying the codes for world locks
beware of this server he will try to scam you by buying roles from them

![image](https://user-images.githubusercontent.com/34183719/55669539-15ce3c00-58ab-11e9-8a87-48ed24d6121d.png)

This is the guy who's asking for code for WLs

**Comment by ilyn1337** [comment]
This is Github, not growtopia support page or something like this. Stop shitposting around here...

**Comment by SecretHax** [comment]
> This is Github, not growtopia support page or something like this. Stop shitposting around here...

True

**Comment by GrowtopiaNoobs** [comment]
I think that this issue won't solve anything and normal players usually don't read issues.
So, I am closing this
