### ISSUE TITLE
[ERROR] stucks at located server connecting...

### ISSUE THREAD

**Issue by ardakurucim** [GrowtopiaNoobs/GrowtopiaServer#209]
I have VPS and i try to open my own private server i open port to 80 and 17091 on firewall it stucks at located server connecting how to fix it

**Comment by Yoayao** [comment]
what ur discord tag give me i will teach u

**Comment by ardakurucim** [comment]
i fixed it

**Comment by AliToprak** [comment]
how did u fixed
