### ISSUE TITLE
how to fix can't wear item?

### ISSUE THREAD

**Issue by Yoayao** [GrowtopiaNoobs/GrowtopiaServer#210]
if i try wear a item and it failed to wear something problem on there??

**Comment by FKSP** [comment]
Do you have CoreData.txt in server folder?

**Comment by OverallGod** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/wiki/Basic-setup

**Comment by FKSP** [comment]
Yes, I prefer to read full wiki page.

**Comment by Dunzap** [comment]
> https://github.com/GrowtopiaNoobs/GrowtopiaServer/wiki/Basic-setup

Nenkai removed it so \_'-'_/

**Comment by GrowtopiaNoobs** [comment]
Changed links to NotDark's fork. This should help.
@NotDark Good luck with managing items database.
Closing this issue now
