### ISSUE TITLE
Updating item data failed

### ISSUE THREAD

**Issue by Jotteri77** [GrowtopiaNoobs/GrowtopiaServer#212]
I need help with this: https://cdn.discordapp.com/attachments/420466983750860810/564498802770182183/unknown.png

**Comment by FuzionVapes** [comment]
Use the latest hash

**Comment by OverallGod** [comment]
get the item.dat and put it in your server folder

**Comment by OverallGod** [comment]
look in https://github.com/GrowtopiaNoobs/GrowtopiaServer/wiki/Basic-setup
