### ISSUE TITLE
[ERROR] Builded Server Exe but when connect to gt itk eep  disconnecting

### ISSUE THREAD

**Issue by Yoayao** [GrowtopiaNoobs/GrowtopiaServer#214]
Tittle that already fixed... but i have a problem when i close server exe the server exe are saved the world but when i connect and go to server i saw many world test how do i fix that?

**Comment by herothedev** [comment]
It\s not bug, but if you really want to remove they then, remove these codes from your server.cpp

        worldDB.get("TEST");
        worldDB.get("MAIN");
        worldDB.get("NEW");
        worldDB.get("ADMIN");

and build again then it shouldn\t generate the worlds automatically.
