### ISSUE TITLE
[ERROR/BUG] Worlds Corrupting

### ISSUE THREAD

**Issue by herothedev** [GrowtopiaNoobs/GrowtopiaServer#215]
Hey, 

Do you know why worlds are corrupting so easily and for me worlds corrupting every update, even i just add one command.
So if i enter a world what has made on old update then it crashes/aborts the server.exe.

Is there any fix or no?

**Comment by SecretHax** [comment]
> Hey,
> 
> Do you know why worlds are corrupting so easily and for me worlds corrupting every update, even i just add one command.
> So if i enter a world what has made on old update then it crashes/aborts the server.exe.
> 
> Is there any fix or no?

Well, I optimized my system and after several restarts and autorestarts every 15 min, worlds aren't corrupted.

**Comment by ardakurucim** [comment]
@SecretHax How did u do it ?

**Comment by OverallGod** [comment]
He just told you

**Comment by ardakurucim** [comment]
@OverallGod he didn't say how to do autorestart

**Comment by OverallGod** [comment]
That's easy to do

**Comment by SecretHax** [comment]
That turkish kid sounds like: "Give me the code or I kill you"

**Comment by FKSP** [comment]
SecretHax, it sounds rasist.

**Comment by SecretHax** [comment]
FKSP, I didn’t mean to.
I even made a picture to end racism:
https://www.mediafire.com/view/5t7gyb9h78pi1zr

**Comment by FKSP** [comment]
-_-

**Comment by SecretHax** [comment]
FKSP, I hope you like it

**Comment by ardakurucim** [comment]
Ye give the code or i kill you ( i have boş just say how to do)

**Comment by ardakurucim** [comment]
Ye give the code or i kill you ( i have vds just say how to do auto restart or kill )

**Comment by SecretHax** [comment]
Step 1: Find a building with 10 stages
Step 2: Go on it’s roof
Step 3: Jump off
Done! You auto-restarted yourself!
JUST KIDDING THO! DON’T RAGE XD

**Comment by ardakurucim** [comment]
@SecretHax It works thanks
