### ISSUE TITLE
Unhandled exception at 0x7546C632 in enet server test.exe: Microsoft C++ exception: int at memory location 0x00D5E92C. occurred

### ISSUE THREAD

**Issue by Jotteri77** [GrowtopiaNoobs/GrowtopiaServer#217]
When i try to put anything in world i get error and server crash

**Comment by NotDark** [comment]
try build in release mode

**Comment by Mempler** [comment]
We cant help with that. we cant see your memory, you need to give us Logs, Console output. Ingame behavior and a Memory Dump!

**Comment by Mempler** [comment]
No answer ? ok
