### ISSUE TITLE
how to make a custom SB?

### ISSUE THREAD

**Issue by Yoayao** [GrowtopiaNoobs/GrowtopiaServer#218]
where i can edit and make a custom SB on the cpp?

**Comment by GottaGetThat** [comment]
> This is for issues not questions

Actually, you can ask question here aswell.


> where i can edit and make a custom SB on the cpp?

Check here https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/master/enet%20server%20test/enet%20server%20test.cpp#L2817

**Comment by OverallGod** [comment]
It's in the code just look for it

**Comment by OverallGod** [comment]
Learn a bit about c++

**Comment by SecretHax** [comment]
> > This is for issues not questions
> 
> Actually, you can ask question here aswell.
> 
> > where i can edit and make a custom SB on the cpp?
> 
> Check here https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/master/enet%20server%20test/enet%20server%20test.cpp#L2817

Actually you can't ask questions here because actually it's called "issues" not "Code-Beggers", so please go away all kiddos.
