### ISSUE TITLE
Where do I put the http server? In server.data or a new one?

### ISSUE THREAD

**Issue by Dunzap** [GrowtopiaNoobs/GrowtopiaServer#22]
pls help

**Comment by Dunzap** [comment]
**plslsssss help i really need to play it**

**Comment by GrowtopiaNoobs** [comment]
**Spamming wont help you!!!!** Don't spam, else you won't get ever any help. Everyone can see, that you made issue and there is no reason to spam more.

https://github.com/GrowtopiaNoobs/GrowtopiaServer/wiki/Basic-setup

**Comment by Dunzap** [comment]
i read it but still i don't really know where to run it and do i put it in server_data.php?
...
