### ISSUE TITLE
how to change the way of adding mods

### ISSUE THREAD

**Issue by fargamer** [GrowtopiaNoobs/GrowtopiaServer#222]
what should i do to change the way of adding mods like i mean i dont want to go to tmain and write addAdmin("user", "pass", 999); like i want a to make a new way to do it but how to edit this way like what should i edit to change it 
thanks

**Comment by ritzysw** [comment]
This is issues tab, not "pls give me complete code lelel wkwkwk" tab, I suggest not making server if you aren't even able to do such simple stuff

**Comment by OverallGod** [comment]
That's exactly what I've been telling people @ritzysw

**Comment by fargamer** [comment]
im not saying i want the complete code im asking how to change the way like what should i edit ?????? im not asking for the code

**Comment by fargamer** [comment]
like i want to change the code by me self but what is the code for adding admins where its written so i can edit it ?

**Comment by OverallGod** [comment]
Dude just look in the wiki under BASIC SOURCE EDITS

**Comment by OverallGod** [comment]
It's legit just addAdmin

**Comment by OverallGod** [comment]
And if you want anything different do it yourself. If you don't know how then learn c++ or just don't do it at all. Because I'm not going to walk you through it and hold your hand.

**Comment by OverallGod** [comment]
Another thing is that you don't need to know how to code all you need is to know how to read it then it's just a matter of looking it up and copy and pasting it then after the hard part it's simple. I don't really know c++ but I can read it. I just saved the admins to a file then I have a command that let's me add admins in game. And no you can't have it because I don't believe in Giving people things without them working for it or trying to do it for themselves. So please next time just do it yourself and don't ask others.

**Comment by fargamer** [comment]
are you seriously ?? im not asking about the code and i know how to read c++ and i looked in  BASIC SOURCE EDITS and just letting you know i know alot in c++ and i know i should write and another thing i didnt say if i can have the code or no who said i want a command in the game to add admins where did i say that can you tell where did i say that i said where is the code of adding admins is located because i want to edit the code BY MY SELF im not fking asking for the code JUST TELL ME WHO SAID I WANT A COMMAND IN THE GAME TO ADD ADMINS??? TELL ME WHERE IM FKING SAID THAT READ PROPAPLY WHAT I WANT AND BTW JUST CLOSE IT I DONT WANT IT ANYMORE YOU GUYS DONT HELP AT ALL ONLY ILYAN AND SECRET HAX IS HELPING READ WHAT I SAID PROPAPLY.....

**Comment by fargamer** [comment]
dont tell me anything im sorry but i dont know english propaply and i think u understand what i want wrong just close it

**Comment by fargamer** [comment]
you understood that i want the code but i dont want the code just nvm

**Comment by OverallGod** [comment]
Yeah I don't think you read what I said properly 😂

**Comment by OverallGod** [comment]
I was giving you an example of what I did

**Comment by fargamer** [comment]
well im sorry bro but i didnt get angry and as i said idk english so i may understood u wrong

**Comment by ritzysw** [comment]
>I suggest not making server if you aren't even able to do such simple stuff

**Comment by fargamer** [comment]
hmm as i said close it i dont want it anymore anyways you dont understand what i want you are saying im not able to do simple stuff what is the thing im not able to do...

**Comment by ilyn1337** [comment]
This is about "Issues and some questions about GROWTOPIA SERVER", not C++. I see u have internet connection, don't you? Is google blocked on your country? Are you livin in N.Korea??? Pressing some keybard keys are too hard??? You know how to write big paragraphs but you dont know how to search some stuff on google??? @fargamer

**Comment by fargamer** [comment]
ok so i go to google and search where is addadmin in the source code is located source code from growtopianoobs

**Comment by OverallGod** [comment]
Dude go to the code and click Ctrl F

**Comment by fargamer** [comment]
okay finally a guy told me how to go to the code thank you
