### ISSUE TITLE
[HELP] i open server exe and the world folder keep spam some unknwon world

### ISSUE THREAD

**Issue by Yoayao** [GrowtopiaNoobs/GrowtopiaServer#223]
https://cdn.discordapp.com/attachments/561197511105183754/565550788894523412/Screenshot_2019-04-10_225332.jpg
pls help me with this problem...

**Comment by SecretHax** [comment]
> https://cdn.discordapp.com/attachments/561197511105183754/565550788894523412/Screenshot_2019-04-10_225332.jpg
> pls help me with this problem...

Well, this is actually an attack, not a code issue. Someone made a bot which connects to ur server, makes thousands of random named world and crashes the server.

**Comment by SecretHax** [comment]
I had that problem before, cuz the same guy was attacking my server, but I fixed it..

**Comment by OverallGod** [comment]
Why are people so toxic lol.

**Comment by Yoayao** [comment]
hmmm how to fix that limit the world create?

**Comment by SecretHax** [comment]
> hmmm how to fix that limit the world create?

Well, idk, change the port, maybe it will stop the attacker.

**Comment by MavrickPH** [comment]
@SecretHax How do I change the port?

**Comment by MavrickPH** [comment]
https://cdn.discordapp.com/attachments/531291472658694154/568650873710837763/unknown.png
d4rk? lolicon? and a guy with no name? I visited the website quickly and I saw an invite link to they're server this isn't sure yet so we don't need to blame someone.

**Comment by MavrickPH** [comment]
https://cdn.discordapp.com/attachments/531291472658694154/568650873710837763/unknown.png
d4rk? lolicon? a guy with no name? when I saw that sb I quickly visited that website and it gives the link to they're server but we don't really know so we don't need to blame someone.
