### ISSUE TITLE
Stuck on connecting

### ISSUE THREAD

**Issue by agarrizar** [GrowtopiaNoobs/GrowtopiaServer#225]
Why can't I connect? And can anyone send me the latest possible and working for this private server items.dat? 
![image](https://user-images.githubusercontent.com/25721027/56065012-ee2c1780-5d73-11e9-8dfd-9d92601bce16.png)
![image](https://user-images.githubusercontent.com/25721027/56065036-013ee780-5d74-11e9-9eca-8e7a0fe43a01.png)
![image](https://user-images.githubusercontent.com/25721027/56065055-10259a00-5d74-11e9-8ef2-9432f1d690a5.png)
![image](https://user-images.githubusercontent.com/25721027/56065201-79a5a880-5d74-11e9-8d55-e9f4b975137d.png)

**Comment by Yoayao** [comment]
sure dm me on discord Yaoyao#8043

**Comment by herothedev** [comment]
http://81.169.156.6/generator.html

**Comment by ardakurucim** [comment]
Try Updating Your Hash

**Comment by agarrizar** [comment]
thanks for all the help!
