### ISSUE TITLE
How To Build Server To Exe?

### ISSUE THREAD

**Issue by Fluthfi** [GrowtopiaNoobs/GrowtopiaServer#227]
Hello , Are Someone Can Make Tutorial How To Build This To Exe Files?
Or U Can Give New Exe Files:)
![image](https://user-images.githubusercontent.com/44535388/56080117-1294fc00-5e27-11e9-8ec1-5b0ee8acfdf6.png)

**Comment by agarrizar** [comment]
Can you contact me on discord? AgarRizar0,5K#6145

**Comment by Yoayao** [comment]
open enet server test sln on visual stduio and open enet server test and click build solution ans it will become exe..

**Comment by Dunzap** [comment]
> open enet server test sln on visual stduio and open enet server test and click build solution ans it will become exe..

no exe showed up

**Comment by willi123yao** [comment]
> > open enet server test sln on visual stduio and open enet server test and click build solution ans it will become exe..
> 
> no exe showed up

If the build solution is successful, it will generate the builds in the Release and Debug folders... just go and look for them

**Comment by ardakurucim** [comment]
Build it then go to debug folder
