### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by agarrizar** [GrowtopiaNoobs/GrowtopiaServer#230]
Ok, I'm new to coding etc.
People said I need to update my hash. But I don't know how... I have installed visual studio 2015 community. I don't know what to do with the files. How to open them in Visual Studio and wich one to open? Can someone help me?
Also I have discord if you want to help me ther: AgarRizar0,5K#6145
Thanks!

**Comment by Mempler** [comment]
If you're new to Programming in general then i would recommend to NOT write on this server! This server requires some Advanced and deep knowledge in Programming in general and a basic knowledge in C++! I recommend to watch some youtube videos / read some docs to get into C++ (that's how i learned C++) My first programming language that i learned to understand Programming is Javascript (NodeJS)!

**Comment by agarrizar** [comment]
> If you're new to Programming in general then i would recommend to NOT write on this server! This server requires some Advanced and deep knowledge in Programming in general and a basic knowledge in C++! I recommend to watch some youtube videos / read some docs to get into C++ (that's how i learned C++) My first programming language that i learned to understand Programming is Javascript (NodeJS)!

I just created my server, it was much easier then i thought. But I should learn c++ etc for making extra commands, your right, thanks for your tips too!
