### ISSUE TITLE
error connecting

### ISSUE THREAD

**Issue by Dunzap** [GrowtopiaNoobs/GrowtopiaServer#234]
pls help

**Comment by SecretHax** [comment]
> pls help

Any more details?

**Comment by Mempler** [comment]
we cant help if you don't give us any details!

**Comment by Dunzap** [comment]
When I try to login, (I have already built new server.exe and get latest items.dat and ran run.py and followed the wiki and edited hosts file) a few secs latee, I get the error connecting text. I have already got V.2989 for growtopia
