### ISSUE TITLE
how can i add mod can break bedrock and white door?

### ISSUE THREAD

**Issue by Yoayao** [GrowtopiaNoobs/GrowtopiaServer#236]
where i can find the code on cpp so i can add mod can break bedrock and white door

**Comment by FuzionVapes** [comment]
Read wiki .-.

**Comment by Dunzap** [comment]
#81

**Comment by Yoayao** [comment]
nu i mean i know how addAdmin but i don't how how give like mods have permission to break bedrock

**Comment by fargamer** [comment]
dude dont ask for codes this is github not please please send code if u have error in code ask where dont ask for the whole code

**Comment by Yoayao** [comment]
did i even ask for code? fp see probably

**Comment by Yoayao** [comment]
then how about u buying code

**Comment by OverallGod** [comment]
It's in the wiki under basic source edits

**Comment by SecretHax** [comment]
Well, admins can break white door and bedrock, even in the public source code. If you want to add a new admin, simply add this at the beginning of main function: `addAdmin("username", "password", 999);`

**Comment by GrowtopiaNoobs** [comment]
SuperAdmin can do this - admin with level 999.
Closing
