### ISSUE TITLE
whats this and how do i fix it

### ISSUE THREAD

**Issue by Dunzap** [GrowtopiaNoobs/GrowtopiaServer#237]
So.. I managed to make a private server! It was working until I tried to add admin. I followed #81 answer but when i saved enet server i got this error
so i built the enet server again and named it as server
but when i tried running run.py it happened again
can you pls help?

![welp](https://user-images.githubusercontent.com/44126782/56276698-999ee880-6135-11e9-9068-2d3f77de7d2a.PNG)

Edit: I have restarted the whole process from start to end, it's still happening

**Comment by Yoayao** [comment]
delete all the worlds on the world folder and try again

**Comment by SurekingIGTPS** [comment]
Who know How to make the exe gtps?

**Comment by NotDark** [comment]
> So.. I managed to make a private server! It was working until I tried to add admin. I followed #81 answer but when i saved enet server i got this error
> so i built the enet server again and named it as server
> but when i tried running run.py it happened again
> can you pls help?
> 
> ![welp](https://user-images.githubusercontent.com/44126782/56276698-999ee880-6135-11e9-9068-2d3f77de7d2a.PNG)
> 
> Edit: I have restarted the whole process from start to end, it's still happening

try build in release mode
![image](https://user-images.githubusercontent.com/44568476/56307471-801e9080-6177-11e9-9ad9-c8963576c628.png)

**Comment by OverallGod** [comment]
Try deleting the stuff in the world folder. Abort has been called gives us no information

**Comment by OverallGod** [comment]
If not building in release will fix it. None of that fixes it then it's your error

**Comment by Dunzap** [comment]
> > So.. I managed to make a private server! It was working until I tried to add admin. I followed #81 answer but when i saved enet server i got this error
> > so i built the enet server again and named it as server
> > but when i tried running run.py it happened again
> > can you pls help?
> > ![welp](https://user-images.githubusercontent.com/44126782/56276698-999ee880-6135-11e9-9068-2d3f77de7d2a.PNG)
> > Edit: I have restarted the whole process from start to end, it's still happening
> 
> try build in release mode
> ![image](https://user-images.githubusercontent.com/44568476/56307471-801e9080-6177-11e9-9ad9-c8963576c628.png)

This will help. Thanks a ton!
