### ISSUE TITLE
How to get run.py?

### ISSUE THREAD

**Issue by SurekingIGTPS** [GrowtopiaNoobs/GrowtopiaServer#238]

**Comment by SurekingIGTPS** [comment]
How to get the run.py?

**Comment by OverallGod** [comment]
Dude it's in the wiki

**Comment by SecretHax** [comment]
Use xampp apache server instead of python shitty http server..

**Comment by herothedev** [comment]
I knowed it that u use xampp hahhaha @SecretHax

**Comment by herothedev** [comment]
i use too xD

**Comment by herothedev** [comment]
@SurekingIGTPS from #167 
Step 1: Turn off the firewall. Private and public one. You don't need it on a clear vps...
Step 2: Install XAMPP
Step 3: Put all server files in /xampp/htdocs
Step 4: Run apache from xampp control panel
Step 5: Run server.exe
Step 6: In /growtopia/server_data.php change the ip and port to the right ones. IP ,= ur vps ip, PORT = ur server.exe port.
Done

**Comment by GrowtopiaNoobs** [comment]
All possible help was given and issue got inactive, closing.
