### ISSUE TITLE
How to fix Timed out connection if login own gtps?

### ISSUE THREAD

**Issue by Deveytv** [GrowtopiaNoobs/GrowtopiaServer#239]
Who know how to fix when i login own gtps is say connection timed out. who know to fix it? help me @GrowtopiaNoobs @SecretHax @GrowtopiaNoobs

**Comment by Dunzap** [comment]
> Who know how to fix when i login own gtps is say connection timed out. who know to fix it? help me @GrowtopiaNoobs @SecretHax @GrowtopiaNoobs

redo the whole process or else build a new server.exe and new items.dat

**Comment by SurekingIGTPS** [comment]
@Dunzap Ok i will try my vps is azure 16gb 4vcpu windows server 2019

**Comment by herothedev** [comment]
Firewall

**Comment by willi123yao** [comment]
Make sure your server is properly configured (follow instructions over at the wiki) and that you are using the latest update from this repository. Please also do note to allow the firewall on the server so that you can access it from outside.

Closing this issue as it seems inactive/resolved.
