### ISSUE TITLE
Is there anyway to fix this when i break blocks enet server.exe crashes

### ISSUE THREAD

**Issue by wawa013** [GrowtopiaNoobs/GrowtopiaServer#240]
![image](https://user-images.githubusercontent.com/49781867/56418637-1a8ee900-62ca-11e9-85eb-e98cfb42e86f.png)

**Comment by arshizx** [comment]
same

**Comment by MarmoriPelaa** [comment]
You have to get the latest CoreData.txt and the latest items.dat file and place them to the same folder as your server.

**Comment by GrowtopiaNoobs** [comment]
Answer from @MarmoriPelaa should solve this.
Closing
