### ISSUE TITLE
Error Connecting!

### ISSUE THREAD

**Issue by arshizx** [GrowtopiaNoobs/GrowtopiaServer#241]
i have a problem when i change the host ip to my vps ip in server_data.php, i closed my firewall, install XAMPP, Run apache from xampp control panel, and put all file in xampp/htdocs but it always stuck on error connecting

**Comment by OverallGod** [comment]
Change your hosts or the ip in server data is wrong

**Comment by arshizx** [comment]
wew thx solve it
