### ISSUE TITLE
Can anyone help me my http sever not work with server.exe it works by themself /Please dm Discord Tabasco#6954

### ISSUE THREAD

**Issue by kikou12** [GrowtopiaNoobs/GrowtopiaServer#242]

**Comment by kikou12** [comment]
i mean how to setting up HTTP Server

**Comment by Yoayao** [comment]
#wiki

**Comment by kikou12** [comment]
Not work

**Comment by kikou12** [comment]
U have a http server py file?

**Comment by Yoayao** [comment]
yes i have

**Comment by kikou12** [comment]
Can you send me Discord Tabasco#6954

**Comment by kikou12** [comment]
@yaoyao

**Comment by kikou12** [comment]
@Yoayao

**Comment by herothedev** [comment]
@kikou12 is the ip right? and if you use google cloud platform ( almost everyone uses ) then it wont work.,

**Comment by kikou12** [comment]
How to disable google cloud

**Comment by kikou12** [comment]
One drive also?

**Comment by kikou12** [comment]
@herothedev

**Comment by OverallGod** [comment]
@herothedev I use Google and it works perfectly

**Comment by NotDark** [comment]
if you use google cloud platform you have to add new firewall rule at the google cloud platform website firewall

**Comment by herothedev** [comment]
yes. google cloud platfrom works perfectly if add the firewall rules on the https://cloud.google.com/ not in the VPS.

**Comment by GrowtopiaNoobs** [comment]
I think this is solved
Closing
