### ISSUE TITLE
Bad url bug how to fix?

### ISSUE THREAD

**Issue by Dunzap** [GrowtopiaNoobs/GrowtopiaServer#25]
When i finish all steps and registered,
first it said
Can't find website. Bad url or no internet?
after that it tried again and then it reverted back to the normal gt.
How to fix?

note: i already downgrade

**Comment by Allinol** [comment]
did you turn on the thing via the python script or the server.exe?

**Comment by Tryp0** [comment]
You need to host a server in order to join it. For instance the old python script would help with that, since it starts a HTTP Server at port 80, which enables you to join the server, as the HTTP server replaces the normal gt with the private server

**Comment by Dunzap** [comment]
> You need to host a server in order to join it. For instance the old python script would help with that, since it starts a HTTP Server at port 80, which enables you to join the server, as the HTTP server replaces the normal gt with the private server

I've ran the script but nothing's still happening.

**Comment by Dunzap** [comment]
> You need to host a server in order to join it. For instance the old python script would help with that, since it starts a HTTP Server at port 80, which enables you to join the server, as the HTTP server replaces the normal gt with the private server

I don't know how to run it even though I read the wiki.
Do I run it as admin?

**Comment by Dunzap** [comment]
> You need to host a server in order to join it. For instance the old python script would help with that, since it starts a HTTP Server at port 80, which enables you to join the server, as the HTTP server replaces the normal gt with the private server

There are 4 worlds created but no users
still it brings me back to original growtopia  because of
bad url...

**Comment by Dunzap** [comment]
Nevermind, managed to fix it with some common sense. Closing this

**Comment by LinkTopia2** [comment]
How did you fix it?
