### ISSUE TITLE
Connection timed out... on windows server 2016. (xampp is setupped)

### ISSUE THREAD

**Issue by herothedev** [GrowtopiaNoobs/GrowtopiaServer#250]
So xampp is working. when i go to http://vpsip it works, and i putted all firewalls down. i downloaded items.dat and maked world and players folder. and downloaded coredata and descriptions. and in xampp is setupped as i said in title.

THIS IS NOT MY SERVER PROBLEM, ITS MY FRIENDS, BUT I JUST MAKED THIS ISSUE.

**Comment by NotDark** [comment]
google cloud platform?

**Comment by SurekingIGTPS** [comment]
> google cloud platform?

No, Azure

**Comment by herothedev** [comment]
Hmm @SurekingIGTPS It might be because its win server 2016, some my friends said its not working. or there is some problem but idk what :/

**Comment by Felixcesar15** [comment]
The ports are  forwarded?
