### ISSUE TITLE
For you guys that want a working GrowtopiaPrivateServer

### ISSUE THREAD

**Issue by OmegaLool** [GrowtopiaNoobs/GrowtopiaServer#252]
Feel free to download the one i got working
There is a virus total link (To show you there are no viruses)
This is compiled with GrowtopiaNoobs enet code, this is not mine i just got a working version for everyone that wants it
https://youtu.be/gO77JKKcGCM
It requires vcruntime and python 64 or 32bit to run.
GrowtopiaNoob if you'd like to share this video with your subscribers you're more than welcome to
There's alot of people wanting a working version of it

**Comment by FuzionVapes** [comment]
xD I bet theres a virus or it only works locally not for hosting server

**Comment by OmegaLool** [comment]
> xD I bet theres a virus or it only works locally not for hosting server

It only works locally, you have to add the code in to make it work for hosting a server. And here's the virus total link.https://www.virustotal.com/#/file/7b04050f15de854dd6083104d38d07f07fbfc3809bcf3a7436a9e9a6e5dbf889/detection

**Comment by FuzionVapes** [comment]
I know duh im not dumb

**Comment by fargamer** [comment]
@FuzionVapes project cat lol

**Comment by FuzionVapes** [comment]
You mean the shittiest server who buy commands for wls becaise they cannot afford to make their own

**Comment by herothedev** [comment]
You don't need to add anything to .cpp to make it non local server facepalm. just use xampp or in run.py change 127.0.0.1 to your vps ip. and done

**Comment by MacaylaMarvelous81** [comment]
or ur computer if u dont have a vps

**Comment by GrowtopiaNoobs** [comment]
Closing this issue as the binary is outdated for sure.
