### ISSUE TITLE
how to change port in run py from 80 to 79

### ISSUE THREAD

**Issue by kikou12** [GrowtopiaNoobs/GrowtopiaServer#254]
how to get vps?

**Comment by NotDark** [comment]
why you need change to 79

**Comment by kikou12** [comment]
Nvm

**Comment by kikou12** [comment]
How to open my server online

**Comment by kikou12** [comment]
So other can play

**Comment by kikou12** [comment]
@NotDark

**Comment by NotDark** [comment]
> So other can play

if you only want to play with friend i recommend use hamachi

**Comment by GrowtopiaNoobs** [comment]
There is no reason in using port 79, because GT won't connect to it.
Closing issue
