### ISSUE TITLE
GrowtopiaItemDatabase

### ISSUE THREAD

**Issue by EpogS** [GrowtopiaNoobs/GrowtopiaServer#255]
I Need new CoreData And Descrioptions but i dont know how to use GrowtopiaItemDatabase
Someone can help me?

**Comment by EpogS** [comment]
i found how to use

**Comment by EpogS** [comment]
nope i can't found.. When i Login i get Disconnect I need Your Help

**Comment by FuzionVapes** [comment]
xD @NotDark

**Comment by FuzionVapes** [comment]
https://github.com/NotDark/GrowtopiaItemDatabase

**Comment by EpogS** [comment]
i dont know how to use these i try to use this coredata and descriptions but im getting disconnect

**Comment by FuzionVapes** [comment]
lol

**Comment by NotDark** [comment]
> i dont know how to use these i try to use this coredata and descriptions but im getting disconnect

you need new items.dat hash you can find in pull request

**Comment by GrowtopiaNoobs** [comment]
Solved, closing issue
