### ISSUE TITLE
how do make a super supporter name?

### ISSUE THREAD

**Issue by Yoayao** [GrowtopiaNoobs/GrowtopiaServer#258]
^^^^^^

**Comment by FuzionVapes** [comment]
lol

**Comment by Spotify1337** [comment]
Search SuperSupporter on cpp and make the Supersupporter = true like invis code

**Comment by MacaylaMarvelous81** [comment]
hi yoayao

**Comment by GrowtopiaNoobs** [comment]
Closing this question as answer was given and there was long time of inactivity.
