### ISSUE TITLE
ERROR CODE: 0xc0007b (Application couldnt be started)

### ISSUE THREAD

**Issue by jagerrood** [GrowtopiaNoobs/GrowtopiaServer#259]
The 0xc00007b code error started happening since i upgraded my PC from 32 bit to 64 bit, it happens whenever i run server.exe given by GrowtopiaNoobs. I tried everything to fix it but got no result. If any of you have clue, could you share with me please? This thing is really annoying.

**Comment by FuzionVapes** [comment]
Answer is download visual studio

**Comment by Felixcesar15** [comment]
Compile it using visual studio 2015 community edition  (not sure other compilers work)

**Comment by NoobesGT** [comment]
try installing c++ because you need to have c++'s frameworks

**Comment by willi123yao** [comment]
Please compile the source manually from the latest update as the server.exe given in the wiki is no longer supported. Closing this issue as it seems inactive/resolved.
