### ISSUE TITLE
Properties & Flag

### ISSUE THREAD

**Issue by jagerrood** [GrowtopiaNoobs/GrowtopiaServer#264]
**I couldn't find it but uh... where is wrench properties located at on the .cpp file? Also the gem flag for admins...**

**Comment by Spotify1337** [comment]
Just search wrench or search 16 number you well by find it

**Comment by QKVLR** [comment]
Search on ctrl+f adminflag or devflag

**Comment by jagerrood** [comment]
> Search on ctrl+f adminflag or devflag

No result..

**Comment by Yoayao** [comment]
ctrl + f search coubtry = .../cash_
