### ISSUE TITLE
C++ HELP

### ISSUE THREAD

**Issue by jagerrood** [GrowtopiaNoobs/GrowtopiaServer#265]
So many of you say "learn c++ to code your own server".. well okay but..

1 - Where should i start learning C++?
2 - Do i need to learn c++ fully or basics only?
3 - How long will it take to learn **basics** just to make **private server**?
4 - Where i can learn it?

**Comment by ardakurucim** [comment]
@fargamer but you cant add commands like /find where can i learn it

**Comment by FuzionVapes** [comment]
Idk go at chernobyl maybe you can learn there

**Comment by FuzionVapes** [comment]
By the way if your planning to invest your whole life hosting gtps its just a waste that doesnt get you enough money for the vps

**Comment by ardakurucim** [comment]
@FuzionVapes i have money no problem

**Comment by GrowtopiaNoobs** [comment]
1,4 - Well, I can just say mess around with code and google.
2 - Basics are enough, but if you understand it fully, then you can make better code.
3 - It really depends on person how long it will take you to make private server.
Closing
