### ISSUE TITLE
how to fix this

### ISSUE THREAD

**Issue by fargamerhd** [GrowtopiaNoobs/GrowtopiaServer#267]
![d1](https://user-images.githubusercontent.com/50425684/57456218-0b260e80-727e-11e9-8e11-6e649b935b9c.PNG)
hi why when im trying to add level for people to do /sb it show me this

**Comment by NotDark** [comment]
((PlayerInfo*)(peer->data))->level

**Comment by fargamerhd** [comment]
thanks
