### ISSUE TITLE
Stuck on login

### ISSUE THREAD

**Issue by royallz** [GrowtopiaNoobs/GrowtopiaServer#269]
I have followed all of the instructions on the wiki, but I have been stuck on the login for days now. And yes, I'm using the items.dat of the latest GT version.

![Screenshot_1](https://user-images.githubusercontent.com/50453875/57467482-51359f00-728b-11e9-95ff-ffc95e1dc944.png)

**Comment by fargamerhd** [comment]
build ur own server.exe from enet server test .sln

**Comment by royallz** [comment]
It keeps disconnecting now

![image](https://user-images.githubusercontent.com/50453875/57468824-e8035b00-728d-11e9-86ab-fd81cbf70cba.png)

**Comment by fargamerhd** [comment]
that mean u dont update the hash go update it

**Comment by royallz** [comment]
Do you have the new hash?

**Comment by fargamerhd** [comment]
1385479555

**Comment by royallz** [comment]
It worked, thank you so much!

**Comment by QKVLR** [comment]
Royallz if you done with your issuse pls close the issuse
