### ISSUE TITLE
lag

### ISSUE THREAD

**Issue by fargamerhd** [GrowtopiaNoobs/GrowtopiaServer#270]
so hello guys so im hosting my server in xampp and i tried 3 different vps and each one is more expensive than the other one like the first was 20 dollars secound was 35 dollars and the thid one was 53 dollars but in all vps when 7 people connect to the server it start laggy what should i do to decrease the lag ? thanks

**Comment by NoobesGT** [comment]
Depends from where the vps connection is. eg. If you're in Romania and your vps is from US ofc will be lag. Also depends on how many worlds are made!

**Comment by willi123yao** [comment]
There can be many factors that results in lag, ranging from things such as network latency to server performance, therefore this requires more analysis on your side and thus it might not be an issue related to the code. Thus, there might not be much help that we can offer you and you will need to investigate and find out on your side/server.

Closing this issue as it seems inactive/resolved.
