### ISSUE TITLE
/warn

### ISSUE THREAD

**Issue by jagerrood** [GrowtopiaNoobs/GrowtopiaServer#271]
I just made /warn command but i couldn't find the way to define user like when you do /warn <user> it will warn the player. But i couldn't define it because i dont know, could any of you guys help me?

**Comment by NotDark** [comment]
if(((PlayerInfo*)(currentPeer->data))->rawName == theusername)

**Comment by jagerrood** [comment]
> if(((PlayerInfo*)(currentPeer->data))->rawName == theusername)

What to replace "theusername" with? Because i want it to warn specified user, not only one.

**Comment by jagerrood** [comment]
> if(((PlayerInfo*)(currentPeer->data))->rawName == theusername)

And im getting 2 error:

identifier "currentPeer" is undefined
identifier "theusername" is undefined

**Comment by NotDark** [comment]
> > if(((PlayerInfo*)(currentPeer->data))->rawName == theusername)
> 
> And im getting 2 error:
> 
> identifier "currentPeer" is undefined
> identifier "theusername" is undefined
for theusername add
string theusername = str.substr(6, cch.length() - 6 - 1);

currentPeer thing u can find in /sb

**Comment by jagerrood** [comment]
> > > if(((PlayerInfo*)(currentPeer->data))->rawName == theusername)
> > 
> > 
> > And im getting 2 error:
> > identifier "currentPeer" is undefined
> > identifier "theusername" is undefined
> 
> for theusername add
> string theusername = str.substr(6, cch.length() - 6 - 1);
> that will get username after u type /warn
> 
> currentPeer thing u can find in /sb

thank you so much dark! im tryin now.

**Comment by jagerrood** [comment]
> > > if(((PlayerInfo*)(currentPeer->data))->rawName == theusername)
> > 
> > 
> > And im getting 2 error:
> > identifier "currentPeer" is undefined
> > identifier "theusername" is undefined
> 
> for theusername add
> string theusername = str.substr(6, cch.length() - 6 - 1);
> that will get username after u type /warn
> 
> currentPeer thing u can find in /sb

Everything was fine, uh i couldnt find currentPeer. Could you tell me it?

**Comment by jagerrood** [comment]
> > > if(((PlayerInfo*)(currentPeer->data))->rawName == theusername)
> > 
> > 
> > And im getting 2 error:
> > identifier "currentPeer" is undefined
> > identifier "theusername" is undefined
> 
> for theusername add
> string theusername = str.substr(6, cch.length() - 6 - 1);
> that will get username after u type /warn
> 
> currentPeer thing u can find in /sb

give me ur discord, lets talk there.

**Comment by NotDark** [comment]
![image](https://user-images.githubusercontent.com/44568476/57568053-87525a80-7414-11e9-826f-b6b3de22965b.png)
@jagerrood

**Comment by jagerrood** [comment]
> ![image](https://user-images.githubusercontent.com/44568476/57568053-87525a80-7414-11e9-826f-b6b3de22965b.png)
> @jagerrood

i already have it, gimme discord so i can show.

**Comment by NotDark** [comment]
> > ![image](https://user-images.githubusercontent.com/44568476/57568053-87525a80-7414-11e9-826f-b6b3de22965b.png)
> > @jagerrood
> 
> i already have it, gimme discord so i can show.

d4rk#1337

**Comment by jagerrood** [comment]
> > > ![image](https://user-images.githubusercontent.com/44568476/57568053-87525a80-7414-11e9-826f-b6b3de22965b.png)
> > > @jagerrood
> > 
> > 
> > i already have it, gimme discord so i can show.
> 
> d4rk#1337

sent

**Comment by NotDark** [comment]
> > > > ![image](https://user-images.githubusercontent.com/44568476/57568053-87525a80-7414-11e9-826f-b6b3de22965b.png)
> > > > @jagerrood
> > > 
> > > 
> > > i already have it, gimme discord so i can show.
> > 
> > 
> > d4rk#1337
> 
> sent

what name

**Comment by jagerrood** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/44568476/57568053-87525a80-7414-11e9-826f-b6b3de22965b.png)
> > > > > @jagerrood
> > > > 
> > > > 
> > > > i already have it, gimme discord so i can show.
> > > 
> > > 
> > > d4rk#1337
> > 
> > 
> > sent
> 
> what name

Jager
