### ISSUE TITLE
Error on code!

### ISSUE THREAD

**Issue by jagerrood** [GrowtopiaNoobs/GrowtopiaServer#275]
string warn = str.substr(6 + currentPeerName.length(), str.length() - 6 - currentPeerName.length());

GamePacket p = packetEnd(appendInt(appendString(appendString(appendString(appendString(createPacket(), "OnAddNotification"), "interface/atomic_button.rttex"), "`4Warning `wfrom `4Admin`w: "+ warn, "audio/hub_open.wav"), 0)));

It gives me 4 error:

too many arguments in function
too few arguments in function
appendInt function doesnt take 1 arguments
appendString function doesnt take 3 arguments

**Comment by SurekingIGTPS** [comment]
> string warn = str.substr(6 + currentPeerName.length(), str.length() - 6 - currentPeerName.length());
> 
> GamePacket p = packetEnd(appendInt(appendString(appendString(appendString(appendString(createPacket(), "OnAddNotification"), "interface/atomic_button.rttex"), "`4Warning `wfrom `4Admin`w: "+ warn, "audio/hub_open.wav"), 0)));
> 
> It gives me 4 error:
> 
> too many arguments in function
> too few arguments in function
> appendInt function doesnt take 1 arguments
> appendString function doesnt take 3 arguments

U have discord? ADD me sureking gaming#2019     DM ME

**Comment by jagerrood** [comment]
> > string warn = str.substr(6 + currentPeerName.length(), str.length() - 6 - currentPeerName.length());
> > GamePacket p = packetEnd(appendInt(appendString(appendString(appendString(appendString(createPacket(), "OnAddNotification"), "interface/atomic_button.rttex"), "`4Warning `wfrom `4Admin`w: "+ warn, "audio/hub_open.wav"), 0)));
> > It gives me 4 error:
> > too many arguments in function
> > too few arguments in function
> > appendInt function doesnt take 1 arguments
> > appendString function doesnt take 3 arguments
> 
> U have discord? ADD me sureking gaming#2019 DM ME

its not working.

**Comment by Yoayao** [comment]
show me

**Comment by Yoayao** [comment]
all

**Comment by jagerrood** [comment]
> all

give me your discord.

**Comment by jagerrood** [comment]
> show me

so

**Comment by Yoayao** [comment]
yaoyao#8043

**Comment by Felixcesar15** [comment]
Check your argments to functions

**Comment by GrowtopiaNoobs** [comment]
You have brackets worng
```CPP
GamePacket p = packetEnd(appendInt(appendString(appendString(appendString(appendString(createPacket(), "OnAddNotification"), "interface/atomic_button.rttex"), "4Warning wfrom 4Adminw: "+ warn), "audio/hub_open.wav"), 0));
```

**Comment by GrowtopiaNoobs** [comment]
I gave answer and there were no new replies, so I am closing this.
