### ISSUE TITLE
Why when i edit .cpp why not save on server?

### ISSUE THREAD

**Issue by SurekingIGTPS** [GrowtopiaNoobs/GrowtopiaServer#276]
Please how tell me @SecretHax @GrowtopiaNoobs @NotDark  i need ur help

**Comment by fargamerhd** [comment]
you should change ur server.exe to the new one..

**Comment by SurekingIGTPS** [comment]
> you should change ur server.exe to the new one..

Change what how?

**Comment by fargamerhd** [comment]
u should start debug befor u save the new update and when u start debug just close it and go to ur folders u will see file name debug it have enet server test copy it and move it to ur files delete ur old server.exe and rename enet server test to server.exe

**Comment by QKVLR** [comment]
Debuge on Visual Studio

**Comment by SurekingIGTPS** [comment]
> u should start debug befor u save the new update and when u start debug just close it and go to ur folders u will see file name debug it have enet server test copy it and move it to ur files delete ur old server.exe and rename enet server test to server.exe

Ok Thanks for Info :) I will try

**Comment by FuzionVapes** [comment]
Sureking doesnt even know how to code lol he just depend on others xD omega lul

**Comment by SurekingIGTPS** [comment]
> Sureking doesnt even know how to code lol he just depend on others xD omega lul

IDC What do u say :/

**Comment by Felixcesar15** [comment]
Compile it with visual studio 2015... Google it how to actually compile it...

**Comment by GrowtopiaNoobs** [comment]
I think this is solved.
Closing issue
