### ISSUE TITLE
Admin name display!

### ISSUE THREAD

**Issue by jagerrood** [GrowtopiaNoobs/GrowtopiaServer#280]
I just created something. If mods/admins type something, the chat color turns out to be green/purple. And it's showing <@Jager> in chat. But the issue is it isn't displaying the name as @Jager and it's classic white name (Jager). Is there any way i can fix it?

If so, give me your discord.

**Comment by fargamerhd** [comment]
well just add color code befor the name ez

**Comment by jagerrood** [comment]
> well just add color code befor the name ez

Im talking about name above growtopia character.

**Comment by Felixcesar15** [comment]
Just add color code at the beginning of the name,but idk how to add @ cuz wiki said you can't add it but logging in with @ works

**Comment by playingo** [comment]
make an admin check (e.g if the admin level equals to 999)
and if player is admin , just add in its display name (for example): `#@

**Comment by Craig-13** [comment]
I plugged in `b before my name and i made sure i was 999 but it wouldnt save i am fairly new to c++ but unless i skimmed over somthing it didnt change the name in-game any tips on how to resolve this issue?
