### ISSUE TITLE
Help create gtps

### ISSUE THREAD

**Issue by Spammerbebas** [GrowtopiaNoobs/GrowtopiaServer#282]
Help Me Create Gtps My Vps Is gcloud You Get Dm Kashiap#2060 To You Get Help me Coding gtps Pls:)

**Comment by Felixcesar15** [comment]
Ofc you need to know how to code in cpp (if you know how to code n cpp then discard this)

**Comment by Spammerbebas** [comment]
I am get how code cpp,and me not get save cpp or debug server.exe to my server

**Comment by Felixcesar15** [comment]
So it' means you know to how to code in cpp,but not dont know how to use g cloud?

Google the tutorials for g cloud
It will help you

**Comment by Felixcesar15** [comment]
Btw you visual studio 2015 if you don't have one on your pc

**Comment by ritzysw** [comment]
this honestly sounds like conversation between Africans

**Comment by Felixcesar15** [comment]
Lol

**Comment by Spammerbebas** [comment]
Felixcesar15,I am Get Code Cpp And Get Use Gcloud I Am get Setting firewall Rule In My Gcloud,So,I am Not Get Save .cpp And debug server.exe i am help you to debug server.exe in my server you get help me?

**Comment by Felixcesar15** [comment]
You need to compile using visual studio 2015 on your pc,you can't use other compiler I think?
you need 2-4 gbs of free space (in pc)  I think

**Comment by Spammerbebas** [comment]
Not get visual studio 2019 community?

**Comment by Felixcesar15** [comment]
I think? ask others cuz idk if it's working or not

**Comment by Spammerbebas** [comment]
Ok thanks i am test debug server.exe use visual studio 2015

**Comment by Felixcesar15** [comment]
Oops if you use Windows in gcloud  you need pay extra money
You should use linux cuz it's free
You need to modify the server so it's works for linux
Check coldchip github I think he have linux version

**Comment by Spammerbebas** [comment]
How to Install Gtps In Linux operation?

Dapatkan Outlook untuk Android<https://aka.ms/ghei36>

________________________________
