### ISSUE TITLE
Clothing

### ISSUE THREAD

**Issue by jagerrood** [GrowtopiaNoobs/GrowtopiaServer#284]
Is there any way i can let user wear some item after i type the command?

**Comment by SurekingIGTPS** [comment]
Hello Who have code /save [save set] please Who can help me? Dm discord Sureking GAMING#2019
@SecretHax @jagerrood @GrowtopiaNoobs @NotDark @ericsnth @OverallGod @iRestartz

**Comment by QKVLR** [comment]
I sell cloth save code for wl

**Comment by jagerrood** [comment]
> I sell cloth save code for wl

Whats your discord?

**Comment by jagerrood** [comment]
> I sell cloth save code for wl

dude?

**Comment by QKVLR** [comment]
CAPTAIN#8280

**Comment by Yoayao** [comment]
i have saveset also

**Comment by FuzionVapes** [comment]
Oh dear begging codes here lol what a gaytard

**Comment by jagerrood** [comment]
> Oh dear begging codes here lol what a gaytard

are u talking about me or sureking?

**Comment by Felixcesar15** [comment]
Seth don't make wls for buying codes

**Comment by playingo** [comment]
use ur brain and fix it urself, i mean you wont learn anything if u just copy and paste codes, you can atleast grab some info from the internet but if you ask for the WHOLE code just to copy and paste it, you're definitely on the wrong way building your own server (not actually just servers, coding programs in general.)
Or maybe thats just not something for you, idk.

**Comment by jagerrood** [comment]
> use ur brain and fix it urself, i mean you wont learn anything if u just copy and paste codes, you can atleast grab some info from the internet but if you ask for the WHOLE code just to copy and paste it, you're definitely on the wrong way building your own server (not actually just servers, coding programs in general.)
> Or maybe thats just not something for you, idk.

that what i asked for, i asked for the gamepacket for it but no worries i fixed it, dirux.

**Comment by GrowtopiaNoobs** [comment]
If you are found solution to issue, then please colose issue.
Also please, don't use github page for selling code - this project is AGPL, so you should commit all changes here and not sell them.
Closing issue.
