### ISSUE TITLE
How to fixed getting server andress?

### ISSUE THREAD

**Issue by Spammerbebas** [GrowtopiaNoobs/GrowtopiaServer#285]
How to fixed getting ip andress in gcloud?Me Add Port Tcp And Udp!

**Comment by fargamerhd** [comment]
make sure the ports are opened

**Comment by Felixcesar15** [comment]
Get up address of your vps,then add it to your hosts file

**Comment by GrowtopiaNoobs** [comment]
Helps were given, but there are no more information about issue, so I am closing this.
