### ISSUE TITLE
HELP Me

### ISSUE THREAD

**Issue by Deveytv** [GrowtopiaNoobs/GrowtopiaServer#286]
![image](https://user-images.githubusercontent.com/49722651/57626517-3c754600-75c0-11e9-923e-95c3a5d57875.png)
how to fix? when i login is didnt work

**Comment by fargamerhd** [comment]
dude ....... 
add 
127.0.0.1 growtopia1.com
127.0.0.1 growtopia2.com 
in ur hosts

**Comment by FuzionVapes** [comment]
Stop fucking begging you indog piece of shit... Fix your shitty grammar and learn it by yourself not everyone is going to spoon feed the answers through your mouth

**Comment by Felixcesar15** [comment]
Sorry but...

GTPS does not make you gt God

If you can't do something about gtps,don't ask here
Instead,leave this thing×

**Comment by willi123yao** [comment]
Do ensure that your server is properly configured and correctly setup. Closing this issue as it seems inactive/resolved.
