### ISSUE TITLE
Music (sharp bass, piano etc.)

### ISSUE THREAD

**Issue by playingo** [GrowtopiaNoobs/GrowtopiaServer#289]
I know how to play sound files, the question for me is, how to actually check WHEN a specific tile is playing and then play a sound file (for example, sharp bass "activates" and it plays a music file for it, )
I know it should be possible because MNT actually made something like that.

Edit: would be enough if someone would know how to check when a specific tile is having its turn. my thoughts would be maybe looping  blocks and using duration_cast, but more i do not know so i would appreciate any help.

**Comment by jagerrood** [comment]
let me have your discord, i might resolve some issue.

**Comment by playingo** [comment]
DiruX#4989

**Comment by jagerrood** [comment]
> DiruX#4989

Check my messages, are you ignoring or what :D?
