### ISSUE TITLE
[FIX] real invis doesnt change server pos at all!!111

### ISSUE THREAD

**Issue by playingo** [GrowtopiaNoobs/GrowtopiaServer#294]
also dis doesnt show text bubble or BRB symbol when invisible, but it still shows the eyes for the player who uses invis (but not for others!) and sends fake leave and it shows text when written in invis: 
![image](https://user-images.githubusercontent.com/50752911/57966466-83fa2a00-7952-11e9-8d39-5a7b94a90733.png)

uses oninvis and some stuff that you might be able to figure out yourself. (the oninvis thing is just so the client can see only his eyes (instead of whole body) when invisible because it removes the whole player from the world and adds some stuff back so its still in the world but doesnt really show up.

**Comment by playingo** [comment]
basically better than ritzy's because it also fixes the punch direction when punching players but this code is alot bigger and took me a HUGE while to figure it out.

**Comment by playingo** [comment]
so if your interested to replace your current invis (ritzy's or whatever) with mine you can feel free to ask me DiruX#4989

**Comment by fargamerhd** [comment]
ok add me in discord cmd#4804

**Comment by GrowtopiaNoobs** [comment]
@playingo don't sell any modifications, but commit them to this repo, because this source code is licensed under AGPL.
So, because this is illegal, I am closing issue

**Comment by playingo** [comment]
oh, sorry, didn't know. so there is no way trading modifications for other modification while crediting you atleast? @GrowtopiaNoobs ?

**Comment by QKVLR** [comment]
Can send me the invis code XD

**Comment by GrowtopiaNoobs** [comment]
@playingo Well, it isn't allowed, because all modifications to source code should be made publicly available.
