### ISSUE TITLE
help me what code sound good for sb, like game win sound at gt ori

### ISSUE THREAD

**Issue by SurekingIGTPS** [GrowtopiaNoobs/GrowtopiaServer#296]

**Comment by DrOreo002** [comment]
Go learn cpp

**Comment by ardakurucim** [comment]
just change sound's shortcut in /sb command

**Comment by playingo** [comment]
DrOreo002 "go learn cpp" bet you didn't. also what he is mentioning here has not alot to do with his cpp skills / education or anything.

**Comment by willi123yao** [comment]
> DrOreo002 "go learn cpp" bet you didn't. also what he is mentioning here has not alot to do with his cpp skills / education or anything.

Yeah sure you can continue with your ignorance and insolence and but well that still doesn't change the fact that you don't know how to code and no point reproaching others about it.

**Comment by MacaylaMarvelous81** [comment]
does he want code or help choosing a sound

**Comment by playingo** [comment]
i think he wants help choosing a sound.

**Comment by flossboss** [comment]
Lmfao only 2 people understood what he meant. Everyone else just reads 3 words and start getting mad.

**Comment by GrowtopiaNoobs** [comment]
There is no real answer for this question and noone gave suggestions "what is the best sound" and probably noone will, so I think there is no longer need to keep this open.
