### ISSUE TITLE
Server gave a 404: File not found. Bad url?

### ISSUE THREAD

**Issue by JustinAkaru** [GrowtopiaNoobs/GrowtopiaServer#300]
I don't know what happened. but when I join the server, I get this error. 
https://cdn.discordapp.com/attachments/577421635921903618/579445453347618827/unknown.png

**Comment by Spotify1337** [comment]
You need setup the server on vps

**Comment by JustinAkaru** [comment]
Issue was having something installed that wasn't supposed to be. Something was using port 80 that wasn't growtopia
