### ISSUE TITLE
Problems with Enet Server Test.exe

### ISSUE THREAD

**Issue by Zlarex** [GrowtopiaNoobs/GrowtopiaServer#301]
Title said, btw i dont have vs 2015.

I have experienced some issue with ucrtbased.dll, msvcp140d.dll, and vcruntime140d.dll and boom after i placed all of the required component, throws (0xc000007b) error (Occured when i run enet server test.exe)

*btw: i installed vc_redist64x 2015. But if i install the 2017, it overwrited the 2015 :(

With another name, 2017 installed, and its uninstall the 2015*

But theres no matter with server.exe
So, can server.exe be runned without enet server test.exe?

**Comment by Hades3235** [comment]
enet server test.exe has to be renamed to server.exe.In the case of mscvp140.dll download this https://www.microsoft.com/ru-ru/download/details.aspx?id=48145

**Comment by Zlarex** [comment]
I can run the server.exe normally, but not with enet :(

I have registered msvcp140d.dll to regsvr32.exe (success)

can i run without vs 2015?

**Comment by Zlarex** [comment]
nvm i closed this
