### ISSUE TITLE
need latest server.exe (hash for 2.99)

### ISSUE THREAD

**Issue by Zlarex** [GrowtopiaNoobs/GrowtopiaServer#302]
Currently, i cant write down the code. I dont have VS 2015

i need your help to get the latest server.exe please

**Comment by Spotify1337** [comment]
Just use vs 2017 or 2019 
You need visual studio to get the server exe 
Like enet test server.sln

**Comment by Zlarex** [comment]
can you upload server.exe, i cant download more than 1 GB file due my bad connection, i need the link to download the server

i have tried to host on my http server, it works, but cant joined to game :((

**Comment by MarmoriPelaa** [comment]
You shouldn't be hosting a server with a "bad connection"

**Comment by Zlarex** [comment]
Thats not the point, i need the latest hash written in server.exe due i cant compile via vs 2015

i tried the server.exe for old version, i knew that the hash should be changed for using latest gt version

So, for my pleasure...can someone attach a new server.exe for 2.99?

**Comment by NotDark** [comment]
> Currently, i cant write down the code. I dont have VS 2015
> 
> i need your help to get the latest server.exe please

that is useless if you dont download visual studio

**Comment by Zlarex** [comment]
Watt? I've tried the older version, nothing error just cant log in

I dont need proton sdk to play growtopia...maybe i dont need vs 2015 for executing server.exe

**Comment by GrowtopiaNoobs** [comment]
Remember that exe files uploaded from others can contain malware.
If noone sends server.exe here in one week, then I am closing this issue.

**Comment by MarmoriPelaa** [comment]
Alright, here:
[enet server test.zip](https://www.dropbox.com/s/594oae2oyswmkwt/enet%20server%20test.zip?dl=1)

Also, what GrowtopiaNoobs said is true. Beware of fishy people.

This was compiled on Visual Studio 2017 for Windows 10. It should work for Windows 7 too. NOTE: I have not tested the server as I took code from #248 for future version support, so if it's not working just tell me and I'll try to fix it. You should be fine as long as you have the latest items.dat which can be located at:
%localappdata%\Growtopia\cache\
when you have updated the real gt server.
If this is your first time creating a server, make sure you have all the required files and folders put into the same folder as the server exe.

**Comment by Zlarex** [comment]
Alright, thanks for all of your support ^_^

Thanks to all that help me solve my issue, also thanks for the things that shared here.

Closing this thread now.
(P.S. GrowtopiaNoobs, thanks for looking to this issue ^_^)
