### ISSUE TITLE
Server gave a 404: File not found. Bad url?

### ISSUE THREAD

**Issue by Hades3235** [GrowtopiaNoobs/GrowtopiaServer#304]
mk,i have all the files like server.exe growtopia folder and im using xampp on the vps,but when you log on u get Server gave a 404: File not found. Bad url?

**Comment by Spotify1337** [comment]
You forget 1 things To add that call firewall rules.

**Comment by NotDark** [comment]
> mk,i have all the files like server.exe growtopia folder and im using xampp on the vps,but when you log on u get Server gave a 404: File not found. Bad url?

make a folder call growtopia in htdocs folder and put the file server_data.php into  growtopia folder that in htdocs folder

**Comment by Hades3235** [comment]
Alright m8 thanks.

**Comment by GrowtopiaNoobs** [comment]
Issue is solved.
Closing
