### ISSUE TITLE
Google Cloud Platform help

### ISSUE THREAD

**Issue by PGamingHD** [GrowtopiaNoobs/GrowtopiaServer#305]
I need help with the firewall rules that I need to add to the sites firewall rules cuz people can’t join the servers right now. (If you’re able to help me please DM me on Discord. User: PGamingHD#8032)

**Comment by SurekingIGTPS** [comment]
i can help DM Sureking GAMING#2019

**Comment by Spotify1337** [comment]
just find firewall rules on Google cloud platform website 
Add tcp is 17091
udp is 80 
Target all network 
IP socure 0.0.0.0/0
Then create it

**Comment by PGamingHD** [comment]
@SurekingIGTPS No one with that tag, you posted the wrong one?

**Comment by PGamingHD** [comment]
@Spotify1337 Yeah the problem is that the IP forwarding says "off" and I don't really know how to turn that on.

**Comment by PGamingHD** [comment]
Kinda need help if anyone knows a lot and have his/her own VPS hosted and maybe even a GT server on it DM me on Discord and I'll SS so you can tell me what to do (If you want to help ofc).

**Comment by PGamingHD** [comment]
@Spotify1337 Do I do that on the VPS too or just the site and there's already a TCP 80 one for allowing Http, should I make a new one anyways?

**Comment by Yoayao** [comment]
not in the vps do it on the google cloud website

**Comment by PGamingHD** [comment]
I did that already, 80 TCP is already open so I opened 17091
