### ISSUE TITLE
Crash of server.exe

### ISSUE THREAD

**Issue by Hades3235** [GrowtopiaNoobs/GrowtopiaServer#306]
mk,got all files everythin set up when opening server.exe for xampp the server.exe just crashes kinda annoyin+im using original exe

**Comment by NotDark** [comment]
dont use the exe in wiki

**Comment by jagerrood** [comment]
> mk,got all files everythin set up when opening server.exe for xampp the server.exe just crashes kinda annoyin+im using original exe

compile enet server test.sln to exe and it will work.

**Comment by herothedev** [comment]
Just delete worlds

**Comment by Hades3235** [comment]
@jagerrood i did compile me excuse me,anyways @herothedev ty

**Comment by MacaylaMarvelous81** [comment]
@Hades3235 if you figured it out pls close issue. and yea that happens a lot with broken wolrd

**Comment by willi123yao** [comment]
Please make sure you use the latest update from the repository and like what others have mentioned, do check for other things like worlds and player data.

Closing this issue as it seems inactive/resolved.
