### ISSUE TITLE
Help with trade deal

### ISSUE THREAD

**Issue by jagerrood** [GrowtopiaNoobs/GrowtopiaServer#307]
There was a text what was saying "the deal has been changed" when you put item to trade, which packet is that text?

**Comment by MarmoriPelaa** [comment]
Check the [packet-list.md](https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/master/packet-list.md). It should be OnTextOverlay.

**Comment by jagerrood** [comment]
> Check the [packet-list.md](https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/master/packet-list.md). It should be OnTextOverlay.

alright it works, thanks for help.
