### ISSUE TITLE
Help with report

### ISSUE THREAD

**Issue by jagerrood** [GrowtopiaNoobs/GrowtopiaServer#308]
I just made this but 	if (btn == "reportUser") if (((PlayerInfo*)(peer->data))->rawName) {
						ENetPacket * packet = enet_packet_create(p.data,
							p.len,
							ENET_PACKET_FLAG_RELIABLE);
						enet_peer_send(peer, 0, packet);
						delete p.data;
						GamePacket p = packetEnd(appendString(appendString(appendString(createPacket(), "OnTextOverlay"), "User has been reported.")));
						ENetPacket * packet = enet_packet_create(p.data,
							p.len,
							ENET_PACKET_FLAG_RELIABLE);
						enet_peer_send(peer, 0, packet);

						//enet_host_flush(server);
						delete p.data;
						enet_peer_disconnect_later(peer, 0);
					}

it gives error: 
![Screenshot_5](https://user-images.githubusercontent.com/50234876/57984399-248c3f00-7a64-11e9-88f2-81d9fe3f40f9.png)

I mean it's defined on gamepacket, no clue how to fix.

**Comment by MarmoriPelaa** [comment]
Mainly your style of coding is just more about typing than checking and thinking. Don't get me wrong, it's alright.
First off, when you do multiple if conditions, use braces or && operator to make it clear for you and the others.
Secondly, if you do not show us the context of the problem, we can't help you.
In this case, I inspected your code and hopefully my help will get your problem solved.

About the code:
- You check if the name is true in the second if condition on the first row.
- You define packet twice.
- The rows 2-4 show that you are sending a packet back to the client. Is this supposed to happen? (You might want to remove rows 2-4)
- Variable p is not defined (remove rows 2-4).
- You have one unnecessary appendString on row 7. It should look like:
`GamePacket p = packetEnd(appendString(appendString(createPacket(), "OnTextOverlay"), "User has been reported."));`

There might be other issues in the code, but fix the ones above first.

**Comment by jagerrood** [comment]
> Mainly your style of coding is just more about typing than checking and thinking. Don't get me wrong, it's alright.
> First off, when you do multiple if conditions, use braces or && operator to make it clear for you and the others.
> Secondly, if you do not show us the context of the problem, we can't help you.
> In this case, I inspected your code and hopefully my help will get your problem solved.
> 
> About the code:
> 
> * You check if the name is true in the second if condition on the first row.
> * You define packet twice.
> * The rows 2-4 show that you are sending a packet back to the client. Is this supposed to happen? (You might want to remove rows 2-4)
> * Variable p is not defined (remove rows 2-4).
> * You have one unnecessary appendString on row 7. It should look like:
>   `GamePacket p = packetEnd(appendString(appendString(createPacket(), "OnTextOverlay"), "User has been reported."));`
> 
> There might be other issues in the code, but fix the ones above first.

Thanks! I will surely try it out, mind you share your discord with me?

**Comment by jagerrood** [comment]
> Mainly your style of coding is just more about typing than checking and thinking. Don't get me wrong, it's alright.
> First off, when you do multiple if conditions, use braces or && operator to make it clear for you and the others.
> Secondly, if you do not show us the context of the problem, we can't help you.
> In this case, I inspected your code and hopefully my help will get your problem solved.
> 
> About the code:
> 
> * You check if the name is true in the second if condition on the first row.
> * You define packet twice.
> * The rows 2-4 show that you are sending a packet back to the client. Is this supposed to happen? (You might want to remove rows 2-4)
> * Variable p is not defined (remove rows 2-4).
> * You have one unnecessary appendString on row 7. It should look like:
>   `GamePacket p = packetEnd(appendString(appendString(createPacket(), "OnTextOverlay"), "User has been reported."));`
> 
> There might be other issues in the code, but fix the ones above first.

So we can talk privately without annoying other users.

**Comment by jagerrood** [comment]
> Mainly your style of coding is just more about typing than checking and thinking. Don't get me wrong, it's alright.
> First off, when you do multiple if conditions, use braces or && operator to make it clear for you and the others.
> Secondly, if you do not show us the context of the problem, we can't help you.
> In this case, I inspected your code and hopefully my help will get your problem solved.
> 
> About the code:
> 
> * You check if the name is true in the second if condition on the first row.
> * You define packet twice.
> * The rows 2-4 show that you are sending a packet back to the client. Is this supposed to happen? (You might want to remove rows 2-4)
> * Variable p is not defined (remove rows 2-4).
> * You have one unnecessary appendString on row 7. It should look like:
>   `GamePacket p = packetEnd(appendString(appendString(createPacket(), "OnTextOverlay"), "User has been reported."));`
> 
> There might be other issues in the code, but fix the ones above first.

And nope, not worked. May i have your discord?
