### ISSUE TITLE
Getting connected to the normal GT servers while trying to connect to my PS

### ISSUE THREAD

**Issue by PGamingHD** [GrowtopiaNoobs/GrowtopiaServer#310]
So I'm trying to connect to my Private Server I made, smh I get connected to the normal GT servers when I type in the IP off the server, did I port forward wrong or what's the problem? Probably something I did wrong with the port forwarding, hmu on Discord if you can help me. Discord - PGamingHD#8032

**Comment by NotDark** [comment]
you need edit your host file

**Comment by PGamingHD** [comment]
> you need edit your host file

LMAO ofc I did that already..

**Comment by SurekingIGTPS** [comment]
Lmfao if me stuck at getting server addres right now... before its can but Right now cant

**Comment by jagerrood** [comment]
> > you need edit your host file
> 
> LMAO ofc I did that already..

By checking your issue, you might want to try those:

> Build enet server test.sln on Visual Studio (it will convert it to an .exe file)
> Try adding _127.0.0.1 growtopia1.com_ to your hosts file
> Make sure you ran enet server test.exe and run.py
> Make sure the IP you entered to hosts file is correct and equals to your VPS one

**Comment by jagerrood** [comment]
**Those might solve your issue:**
> Build enet server test.sln on Visual Studio (it will convert it to an .exe file)
> Try adding 127.0.0.1 growtopia1.com to your hosts file
> Make sure you ran enet server test.exe and run.py
> Make sure the IP you entered to hosts file is correct and equals to your VPS one

**Comment by SecretHax** [comment]
And make sure you aren't dumb

**Comment by PGamingHD** [comment]
> And make sure you aren't dumb

Smh I'm just the VPS hoster lmao

**Comment by SecretHax** [comment]
> > And make sure you aren't dumb
> 
> Smh I'm just the VPS hoster lmao

So just contact the developer fp

**Comment by PGamingHD** [comment]
Yeah I did and he doesn't know tf is wrong

**Comment by jagerrood** [comment]
Aren't you the guy who needs rolex @SecretHax

**Comment by FuzionVapes** [comment]
> Lmfao if me stuck at getting server addres right now... before its can but Right now cant

Dat try hard english...........

**Comment by PGamingHD** [comment]
> > Lmfao if me stuck at getting server addres right now... before its can but Right now cant
> 
> Dat try hard english...........

LMAO true

**Comment by FuzionVapes** [comment]
> > > Lmfao if me stuck at getting server addres right now... before its can but Right now cant
> > 
> > 
> > Dat try hard english...........
> 
> LMAO true

he is asking for codes and trying hard to scam his friends to host his server lol
