### ISSUE TITLE
Help with report

### ISSUE THREAD

**Issue by jagerrood** [GrowtopiaNoobs/GrowtopiaServer#311]
**I want to make a report button with wrench and i added this but it gives me error.**
if (btn == "reportUser") if (((PlayerInfo*)(peer->data))->rawName) {
ENetPacket * packet = enet_packet_create(p.data,
p.len,
ENET_PACKET_FLAG_RELIABLE);
enet_peer_send(peer, 0, packet);
delete p.data;
GamePacket p = packetEnd(appendString(appendString(appendString(createPacket(), "OnTextOverlay"), "User has been reported.")));
ENetPacket * packet = enet_packet_create(p.data,
p.len,
ENET_PACKET_FLAG_RELIABLE);
enet_peer_send(peer, 0, packet);

					//enet_host_flush(server);
					delete p.data;
					enet_peer_disconnect_later(peer, 0);
				}
![image](https://user-images.githubusercontent.com/50234876/58009167-85fcee00-7af6-11e9-830b-ffb7ecdb5609.png)

**Please help me solve this! You can give your Discord also!**
Discord: jagerrood#8728

**Comment by GrowtopiaNoobs** [comment]
You are defining variables with same names in same scope. I am usually solving this with simple trick, that I wrap sending of single packet in `{}`.

Also `if (((PlayerInfo*)(peer->data))->rawName) {` doesn't make any sense.
(I haven't checked if there are more errors)

**Comment by jagerrood** [comment]
> You are defining variables with same names in same scope. I am usually solving this with simple trick, that I wrap sending of single packet in `{}`.
> 
> Also `if (((PlayerInfo*)(peer->data))->rawName) {` doesn't make any sense.
> (I haven't checked if there are more errors)

I removed *if (((PlayerInfo*)(peer->data))->rawName) {* and did this: 
if (btn == "reportUser") {
							ENetPacket * packet = enet_packet_create(p.data,
								p.len,
								ENET_PACKET_FLAG_RELIABLE);
							enet_peer_send(peer, 0, packet);
							delete p.data;
							GamePacket p = packetEnd(appendString(createPacket(), "OnTextOverlay"), "User has been reported."));
							ENetPacket * packet = enet_packet_create(p.data,
								p.len,
								ENET_PACKET_FLAG_RELIABLE);
							enet_peer_send(peer, 0, packet);

							//enet_host_flush(server);
							delete p.data;
							enet_peer_disconnect_later(peer, 0);
						}
but still getting the same error and i'm not sure what do you meant by " I wrap sending of single packet in {}."

**Comment by MarmoriPelaa** [comment]
I don't know why my comment disappeared, but [here](https://pastebin.com/KxEbgAZp) is the code.

**Comment by jagerrood** [comment]
> I don't know why my comment disappeared, but [here](https://pastebin.com/KxEbgAZp) is the code.

I fixed it 1 day ago but forgot to close issue, thanks anyway! CLOSING.
