### ISSUE TITLE
Stuck at ”Located server, connecting”!

### ISSUE THREAD

**Issue by PGamingHD** [GrowtopiaNoobs/GrowtopiaServer#313]
So when logging in I get this while The run.py is running, so the server is getting located but doesn’t actually connect fully. Respond down below if u could help me, i’d appreciate it a lot if you could help me!

((Also sorry for posting this much! :/))

**Comment by jagerrood** [comment]
> So when logging in I get this while The run.py is running, so the server is getting located but doesn’t actually connect fully. Respond down below if u could help me, i’d appreciate it a lot if you could help me!
> 
> ((Also sorry for posting this much! :/))

Run .exe also and make correct hosts file

**Comment by JustinAkaru** [comment]
I would say the first part is incorrect, due to an error known as: Error while trying to create Enet server host. I'm pretty sure the host file is correct, assuming that all they need to do is change the IPs.

**Comment by PGamingHD** [comment]
Server.
