### ISSUE TITLE
Mobile Compatibility

### ISSUE THREAD

**Issue by JustinAkaru** [GrowtopiaNoobs/GrowtopiaServer#317]
When trying ios, I get disconnection error, but windows I can play on the latest version. Am I missing anything? Also how do I create the hosts file for android?

**Comment by playingo** [comment]
i guess you'll need the newest hash and items.dat, but since secrethax's website got shutdown, you need to get it by another way.

**Comment by MarmoriPelaa** [comment]
Check #248 for example of getting items.dat hash automatically.

**Comment by NoobesGT** [comment]
Ofc you need a vps or if you want to host it on you router go forward it

**Comment by willi123yao** [comment]
The server supports mobile platforms and it is most likely to be an issue with your setup/configuration which can be due to many reasons like incorrect items data or hash, closing this issue as it seems inactive/resolved.
