### ISSUE TITLE
How to create Player folders and World folders

### ISSUE THREAD

**Issue by rthotbelow** [GrowtopiaNoobs/GrowtopiaServer#32]
in basic-setup it says something about adding player folders and world folders
i have no idea how to do that.

**Comment by FocusedSG** [comment]
u literally just need to right-click and create a folder called players and another one called worlds

**Comment by iNPGT** [comment]
> u literally just need to right-click and create a folder called players and another one called worlds
> ![image](https://user-images.githubusercontent.com/19513208/47293316-6246f780-d63c-11e8-9823-b6e1835bbce8.png)

how to get your files like 
Restart.bat
null
GrowtopiSG.exe
enet server text.exe
worlds_backup

**Comment by GrowtopiaNoobs** [comment]
I think that this can be closed
