### ISSUE TITLE
Connection to PS disabled

### ISSUE THREAD

**Issue by JustinAkaru** [GrowtopiaNoobs/GrowtopiaServer#320]
No matter how I configure my host (google cloud), my firewall, and even my server files, only me and my co-owner can connect to the server. Everyone else just connects to growtopia regular servers. Does anyone know why this is happening?

**Comment by PGamingHD** [comment]
No need to come with the port forwarding is wrong since it's right, here's proof that everything's right!

https://gyazo.com/ca7c156652b89a3ff7d83faeaf2fb669
https://gyazo.com/67d1cd5298c7c1d19f3a3efb3d1d22e9
And yeah, firewall is down.

**Comment by herothedev** [comment]
Hey,

- Make sure on ANDROID in the hosts file is:
youvpsip growtopia1.com
- Make sure that they did allow the VPN connection on ANDROID

- on ios they need to use surge 3
- on ios they need too allow vpn connection

- on pc they need admin permission account
- on pc they need to edit open notepad as administrator
- on pc put to hosts file
yourvpsip growtopia1.com

That's should work, If not then it's player fault.

**Comment by JustinAkaru** [comment]
Now everyone including me connects to regular growtopia, and everything is fixed for me
