### ISSUE TITLE
crash due to void sendnews(ENetPeer * peer) {

### ISSUE THREAD

**Issue by Hades3235** [GrowtopiaNoobs/GrowtopiaServer#321]
```C++
void sendnews(ENetPeer * peer) {
string x = startbox();
	x.append(addlabelicon("`wChangelog", "big", "5956"));
	x.append(addspacer("small"));
	x.append(addlabel("`3- Added /nick", "small"));
	x.append(addlabel("`3- Added /mods", "small"));
    x.append(addlabel("`3- Added /modsb", "small"));
	x.append(addlabel("`3- Added /hide", "small"));
	x.append(addlabel("`3- Updated /mod (you can toggle it now)", "small"));
	x.append(addlabel("`3- Removed a bunch of useless commands", "small"));
	x.append(addlabel("`3- Fixed player leaving bug", "small"));
	x.append(addlabel("`3- Added /news", "small"));
	x.append(addlabel("`3- Fixed /mods", "small"));
	x.append(addlabel("`3- Added /summon", "small"));
	x.append(addlabel("`3- Added /warpto", "small"));
	x.append(addlabel("`3- Added /warp", "small"));
	x.append(addlabel("`3- Added ban system", "small"));
	x.append(addlabel("`3- Added /timeban (ban player until date)", "small"));
	x.append(addlabel("`3- Added /permaban", "small"));
	x.append(addspacer("small"));
	x.append(addlabel("`w- Have fun! -hades,niko", "small"));
	x.append(addspacer("small"));
	x.append("\nadd_button|chc0|Close|noflags|0|0|");
	x.append(endbox());
	sendbox(peer, x);
}
```
when logging on,you see this and immediately crash.Anyone can help me.

**Comment by NotDark** [comment]
> void sendnews(ENetPeer * peer) {
> string x = startbox();
> x.append(addlabelicon("`wChangelog", "big", "5956")); x.append(addspacer("small")); x.append(addlabel("`3- Added /nick", "small"));
> x.append(addlabel("`3- Added /mods", "small")); x.append(addlabel("`3- Added /modsb", "small"));
> x.append(addlabel("`3- Added /hide", "small")); x.append(addlabel("`3- Updated /mod (you can toggle it now)", "small"));
> x.append(addlabel("`3- Removed a bunch of useless commands", "small")); x.append(addlabel("`3- Fixed player leaving bug", "small"));
> x.append(addlabel("`3- Added /news", "small")); x.append(addlabel("`3- Fixed /mods", "small"));
> x.append(addlabel("`3- Added /summon", "small")); x.append(addlabel("`3- Added /warpto", "small"));
> x.append(addlabel("`3- Added /warp", "small")); x.append(addlabel("`3- Added ban system", "small"));
> x.append(addlabel("`3- Added /timeban (ban player until date)", "small")); x.append(addlabel("`3- Added /permaban", "small"));
> x.append(addspacer("small"));
> x.append(addlabel("`w- Have fun! -hades,niko", "small"));
> x.append(addspacer("small"));
> x.append("\nadd_button|chc0|Close|noflags|0|0|");
> x.append(endbox());
> sendbox(peer, x);
> }
> when logging on,you see this and immediately crash.Anyone can help me.

 try like this
set_default_color|`o\n\nadd_label_with_icon|big|`wServer News``|left|5016|\n\nadd_spacer|small|

**Comment by NotDark** [comment]
> > void sendnews(ENetPeer * peer) {
> > string x = startbox();
> > x.append(addlabelicon("`wChangelog", "big", "5956")); x.append(addspacer("small")); x.append(addlabel("`3- Added /nick", "small"));
> > x.append(addlabel("`3- Added /mods", "small")); x.append(addlabel("`3- Added /modsb", "small"));
> > x.append(addlabel("`3- Added /hide", "small")); x.append(addlabel("`3- Updated /mod (you can toggle it now)", "small"));
> > x.append(addlabel("`3- Removed a bunch of useless commands", "small")); x.append(addlabel("`3- Fixed player leaving bug", "small"));
> > x.append(addlabel("`3- Added /news", "small")); x.append(addlabel("`3- Fixed /mods", "small"));
> > x.append(addlabel("`3- Added /summon", "small")); x.append(addlabel("`3- Added /warpto", "small"));
> > x.append(addlabel("`3- Added /warp", "small")); x.append(addlabel("`3- Added ban system", "small"));
> > x.append(addlabel("`3- Added /timeban (ban player until date)", "small")); x.append(addlabel("`3- Added /permaban", "small"));
> > x.append(addspacer("small"));
> > x.append(addlabel("`w- Have fun! -hades,niko", "small"));
> > x.append(addspacer("small"));
> > x.append("\nadd_button|chc0|Close|noflags|0|0|");
> > x.append(endbox());
> > sendbox(peer, x);
> > }
> > when logging on,you see this and immediately crash.Anyone can help me.
> 
> try like this
> set_default_color|`w\n\nadd_label_with_icon|big|Server News|left|5016|\n\nadd_spacer|small|

**Comment by Hades3235** [comment]
@NotDark to replace the void sendnews(ENetPeer * peer) { . ?

**Comment by NotDark** [comment]
> @NotDark to replace the void sendnews(ENetPeer * peer) { . ?

replace like this https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/master/enet%20server%20test/enet%20server%20test.cpp#L3292

**Comment by Spotify1337** [comment]
why you need use void sendnews 😂you can use OnDialogRequest)news list));

**Comment by Hades3235** [comment]
it didnt work with both

**Comment by NotDark** [comment]
> it didnt work with both

no understand why you make like this 
![image](https://user-images.githubusercontent.com/44568476/58175465-bb5e3300-7cd2-11e9-93e7-158c945d57eb.png) x.append thing

**Comment by Spotify1337** [comment]
> 
> 
> it didnt work with both

it was same code on IsIn on OnDialogRequest

**Comment by GrowtopiaNoobs** [comment]
You try to remove slowly stuff to see what line cause crash.
Is this issue already solved or not?
Also you haven't included code for function `sendbox`.

**Comment by Hades3235** [comment]
fixed thanks
