### ISSUE TITLE
How to fixed located server,connecting....?can Help me?

### ISSUE THREAD

**Issue by Spammerbebas** [GrowtopiaNoobs/GrowtopiaServer#323]
How to fixed located server connecting?Me Has been Setting port udp and tcp in firewall And Me run run.py and server.exe And I Am Connect,And Stuck Back In located server,connecting...

**Comment by Spotify1337** [comment]
on vps or pc?

**Comment by herothedev** [comment]
If you on PC: 
- Make sure the ip's on run.py are :127.0.0.1
- Make sure that run.py running.
- Run enet server test.exe

If you on VPS:
- Port forward firewall, or simply put firewall of.
- Make ips on run.py to your vps ip.
- Make sure run.py and enet server test.exe are running.
- If you use something like google cloud platform setup the firewall there too.

That's all, if you did all those, and still not working, you did something wrong.

**Comment by willi123yao** [comment]
Closing this issue as it seems inactive/resolved.
