### ISSUE TITLE
What Code /find same in all gtps

### ISSUE THREAD

**Issue by Spammerbebas** [GrowtopiaNoobs/GrowtopiaServer#325]
What code /find in all gtps because My /find is need item valid

**Comment by fargamerhd** [comment]
u should make it like other gtps dont ask for commands here

**Comment by MarmoriPelaa** [comment]
What fargamerhd said is true. Do not ask for code/commands here. If I had the permission and money to host a forum, I would, and in the forum people could ask for code. Here though, it's very rare people give you code.

**Comment by willi123yao** [comment]
Like what others have mentioned here, this is again not a platform for you to ask for codes and you should instead seek help by showing what you have tried and which parts of your created code that you need help with specifically. (Show us your incomplete code or idea and how it should work, and not asking around for code)

Closing this issue as it seems inactive/resolved.
