### ISSUE TITLE
how do you add special flags for admins and mods

### ISSUE THREAD

**Issue by Hades3377** [GrowtopiaNoobs/GrowtopiaServer#332]
i tried this 
if playerinfo (checkAdmin=setFlag rtsoft_logo.rttex

but it didnt work.could someone teach me on discord Hades#3235

**Comment by Spotify1337** [comment]
just search overlay_cash.rttx you can change the flag on they but if andoird is visual

**Comment by Hades3235** [comment]
doesnt work for me wtf

**Comment by SurekingIGTPS** [comment]
Easy to add just copy the ''/cash_icon_overlay'' and put it at under and change number ur self

**Comment by ardakurucim** [comment]
check isSuperAdminFlag

**Comment by MacaylaMarvelous81** [comment]
as simple as changing `country` in the player's `PlayerInfo`
