### ISSUE TITLE
How to fix when saving world its must delete and not saved like rollback

### ISSUE THREAD

**Issue by SurekingIGTPS** [GrowtopiaNoobs/GrowtopiaServer#333]
@willi123yao @NotDark @SecretHax @iRestartz

**Comment by jagerrood** [comment]
do it by yourself and stop begging for code contionusly retarded

**Comment by SurekingIGTPS** [comment]
> do it by yourself and stop begging for code contionusly retarded

Hey tf i no ask for code -_- Are you hate me? just dont comment.

**Comment by DrOreo002** [comment]
Huh, at the end you're gonna just ask for the code. Stop begging for it please :D

**Comment by fargamerhd** [comment]
void saveAllWorlds() // atexit hack plz fix
{
	cout << "Saving worlds..." << endl;
	enet_host_destroy(server);
	enet_host_destroy(server);
	worldDB.saveAll();
	cout << "Worlds saved!" << endl;
}
that would help a bit

**Comment by jagerrood** [comment]
> > do it by yourself and stop begging for code contionusly retarded
> 
> Hey tf i no ask for code -_- Are you hate me? just dont comment.

"i are hate you" like fucking seriously

**Comment by ritzysw** [comment]
somebody fucking ban this autistic child for real holy shit its so fucking annoying

**Comment by royallz** [comment]
hes entertaining tho

**Comment by jagerrood** [comment]
> somebody fucking ban this autistic child for real holy shit its so fucking annoying

are you hate him?

**Comment by Hades3235** [comment]
*and on discord whose the one telling me everyday im a fucking idiotic coder*
