### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by fargamerhd** [GrowtopiaNoobs/GrowtopiaServer#339]
![d1](https://user-images.githubusercontent.com/50425684/58434367-5472bc80-80cc-11e9-8fb3-fe43dd403720.PNG)
So guys there is a guy crashing my server im not going to say his name but idk how he crash the server but i reliezied that everytime he login the cbits = 0 and then it crash but other player when they login the cbits is 16 so can anyone tell me what is cbits exactly so i can solve the problem ??

**Comment by fargamerhd** [comment]
like all other players when they login the cbits: 16 when the guy who is crashing my server when he login the cbits: 0 so he is crashing it from this

**Comment by fargamerhd** [comment]
@GrowtopiaNoobs
any suggestion ??

**Comment by ilyn1337** [comment]
Just a reminder, this page of github for reporting "issues" on "this project", not about your problem... Close this issue no one will reply it 🤷‍♂

**Comment by NotDark** [comment]
make cant login if cbit = 0

**Comment by fargamerhd** [comment]
yeah what is cbits ? like mac is mac addreass @NotDark cbits is what ?
and btw @NotDark its actually a glitch in enet which ur friend {lapada} is using it so yeah its issue and here is issue tap..

**Comment by fargamerhd** [comment]
and btw its in this project this error is in private servers @ilyn1337

**Comment by playingo** [comment]
imagine if enet was like: 
bool canReceive;
if (canReceive)
sendData(peer, 1, 0, 0);

**Comment by Lapada** [comment]
thanks for the laugh

**Comment by Lapada** [comment]
As @ilyn1337 stated, this is the github page for the server itself and the issues section should only be used for issues regarding the server itself, not your own problem.

**Comment by fargamerhd** [comment]
well @Lapada u are so stupid cuz this issue is not my issue its this project issue so yeah

**Comment by Lapada** [comment]
> well @Lapada u are so stupid cuz this issue is not my issue its this project issue so yeah

Even if that was case, this is not a valid issue report as you've provided no usable information on the bug itself. Issues should only be used for reporting exact bugs with the steps to reproduce them.

With the information you provided, it cannot be verified if it's an issue in this project, or an error that you made.

**Comment by ritzysw** [comment]
imagine saying someone is stupid but not understanding that "cbits" does nothing
