### ISSUE TITLE
/ban help!

### ISSUE THREAD

**Issue by jagerrood** [GrowtopiaNoobs/GrowtopiaServer#340]
so i made /ban command but it just disconnects the user, is there any way i can make like if user will login to game, it will display as "you are banned" or such? if so, whick game packet to use?

**Comment by jagerrood** [comment]
im thinking it could be done with (logStatus = 1) and some other thing

**Comment by ilyn1337** [comment]
find playerlogin path and check bans, then check if peer's tankidname in ban list

**Comment by jagerrood** [comment]
> find playerlogin(write ur ban checker thingy here) path and check bans, then check if peer's tankidname in ban list

the one with static int or playerDB:: ?

**Comment by ilyn1337** [comment]
yes void in playerDB, if tankidname in ban list, disconnect the player with console message and throw -1 (if u want)

**Comment by jagerrood** [comment]
> yes void in playerDB, if tankidname in ban list, disconnect the player with console message and throw -1 (if u want)

i tried something , i can show you via discord?

**Comment by jagerrood** [comment]
> yes void in playerDB, if tankidname in ban list, disconnect the player with console message and throw -1 (if u want)

can i show you what i made via discord?

**Comment by VyteGTPS** [comment]
Do you even save accounts first?

**Comment by jagerrood** [comment]
> Do you even save accounts in first place or any kind of saving.

what do you mean by "saving accounts"?

**Comment by OverallGod** [comment]
if (logStatus == -5) {
								GamePacket p = packetEnd(appendString(appendString(createPacket(), "OnConsoleMessage"), "Whats wrong with you? Your banned!"));
								ENetPacket* packet = enet_packet_create(p.data,
									p.len,
									ENET_PACKET_FLAG_RELIABLE);
								enet_peer_send(peer, 0, packet);
								delete p.data;
								enet_peer_disconnect_later(peer, 0);
							}

**Comment by jagerrood** [comment]
> if (logStatus == -5) {
> GamePacket p = packetEnd(appendString(appendString(createPacket(), "OnConsoleMessage"), "Whats wrong with you? Your banned!"));
> ENetPacket* packet = enet_packet_create(p.data,
> p.len,
> ENET_PACKET_FLAG_RELIABLE);
> enet_peer_send(peer, 0, packet);
> delete p.data;
> enet_peer_disconnect_later(peer, 0);
> }
> 
> You can figure out the rest

thanks! i'll surely try it out

**Comment by VyteGTPS** [comment]
> > if (logStatus == -5) {
> > GamePacket p = packetEnd(appendString(appendString(createPacket(), "OnConsoleMessage"), "Whats wrong with you? Your banned!"));
> > ENetPacket* packet = enet_packet_create(p.data,
> > p.len,
> > ENET_PACKET_FLAG_RELIABLE);
> > enet_peer_send(peer, 0, packet);
> > delete p.data;
> > enet_peer_disconnect_later(peer, 0);
> > }
> > You can figure out the rest
> 
> thanks! i'll surely try it out

wow you are actually that stupid. don't ask help there, go learn some basic codings on c++

**Comment by jagerrood** [comment]
> > > if (logStatus == -5) {
> > > GamePacket p = packetEnd(appendString(appendString(createPacket(), "OnConsoleMessage"), "Whats wrong with you? Your banned!"));
> > > ENetPacket* packet = enet_packet_create(p.data,
> > > p.len,
> > > ENET_PACKET_FLAG_RELIABLE);
> > > enet_peer_send(peer, 0, packet);
> > > delete p.data;
> > > enet_peer_disconnect_later(peer, 0);
> > > }
> > > You can figure out the rest
> > 
> > 
> > thanks! i'll surely try it out
> 
> wow you are actually that stupid. don't ask help there, go learn some basic codings on c++

says who ddoses the servers cuz of jealousy lmao

**Comment by VyteGTPS** [comment]
> > > > if (logStatus == -5) {
> > > > GamePacket p = packetEnd(appendString(appendString(createPacket(), "OnConsoleMessage"), "Whats wrong with you? Your banned!"));
> > > > ENetPacket* packet = enet_packet_create(p.data,
> > > > p.len,
> > > > ENET_PACKET_FLAG_RELIABLE);
> > > > enet_peer_send(peer, 0, packet);
> > > > delete p.data;
> > > > enet_peer_disconnect_later(peer, 0);
> > > > }
> > > > You can figure out the rest
> > > 
> > > 
> > > thanks! i'll surely try it out
> > 
> > 
> > wow you are actually that stupid. don't ask help there, go learn some basic codings on c++
> 
> says who ddoses the servers cuz of jealousy lmao

*says the one who is only successful in gtps and never begged for codings.

**Comment by jagerrood** [comment]
> > > > > if (logStatus == -5) {
> > > > > GamePacket p = packetEnd(appendString(appendString(createPacket(), "OnConsoleMessage"), "Whats wrong with you? Your banned!"));
> > > > > ENetPacket* packet = enet_packet_create(p.data,
> > > > > p.len,
> > > > > ENET_PACKET_FLAG_RELIABLE);
> > > > > enet_peer_send(peer, 0, packet);
> > > > > delete p.data;
> > > > > enet_peer_disconnect_later(peer, 0);
> > > > > }
> > > > > You can figure out the rest
> > > > 
> > > > 
> > > > thanks! i'll surely try it out
> > > 
> > > 
> > > wow you are actually that stupid. don't ask help there, go learn some basic codings on c++
> > 
> > 
> > says who ddoses the servers cuz of jealousy lmao
> 
> *says the one who is only successful in gtps and never begged for codings.

where did i "begged" for codes?

**Comment by VyteGTPS** [comment]
> > > > > > if (logStatus == -5) {
> > > > > > GamePacket p = packetEnd(appendString(appendString(createPacket(), "OnConsoleMessage"), "Whats wrong with you? Your banned!"));
> > > > > > ENetPacket* packet = enet_packet_create(p.data,
> > > > > > p.len,
> > > > > > ENET_PACKET_FLAG_RELIABLE);
> > > > > > enet_peer_send(peer, 0, packet);
> > > > > > delete p.data;
> > > > > > enet_peer_disconnect_later(peer, 0);
> > > > > > }
> > > > > > You can figure out the rest
> > > > > 
> > > > > 
> > > > > thanks! i'll surely try it out
> > > > 
> > > > 
> > > > wow you are actually that stupid. don't ask help there, go learn some basic codings on c++
> > > 
> > > 
> > > says who ddoses the servers cuz of jealousy lmao
> > 
> > 
> > *says the one who is only successful in gtps and never begged for codings.
> 
> where did i "begged" for codes?

are you fucking retarded? you can't even code a fucking ban thats the simpliest thing ever, dummy

**Comment by jagerrood** [comment]
> > > > > > > if (logStatus == -5) {
> > > > > > > GamePacket p = packetEnd(appendString(appendString(createPacket(), "OnConsoleMessage"), "Whats wrong with you? Your banned!"));
> > > > > > > ENetPacket* packet = enet_packet_create(p.data,
> > > > > > > p.len,
> > > > > > > ENET_PACKET_FLAG_RELIABLE);
> > > > > > > enet_peer_send(peer, 0, packet);
> > > > > > > delete p.data;
> > > > > > > enet_peer_disconnect_later(peer, 0);
> > > > > > > }
> > > > > > > You can figure out the rest
> > > > > > 
> > > > > > 
> > > > > > thanks! i'll surely try it out
> > > > > 
> > > > > 
> > > > > wow you are actually that stupid. don't ask help there, go learn some basic codings on c++
> > > > 
> > > > 
> > > > says who ddoses the servers cuz of jealousy lmao
> > > 
> > > 
> > > *says the one who is only successful in gtps and never begged for codings.
> > 
> > 
> > where did i "begged" for codes?
> 
> are you fucking retarded? you can't even code a fucking ban thats the simpliest thing ever, dummy

do you actually have autism? are you mad iviki havent made vid about your gtps or about you hacking him?

**Comment by jagerrood** [comment]
this is the place where we ask for help, not begging for codes?

**Comment by VyteGTPS** [comment]
> this is the place where we ask for help, not begging for codes?

if you are not asking for codes, why you replied to comments that sent codes?

**Comment by jagerrood** [comment]
> > this is the place where we ask for help, not begging for codes?
> 
> if you are not asking for codes, why you replied to comments that sent codes?

because i asked before and got no replies then i had to delete?

**Comment by jagerrood** [comment]
and maybe fixed some shit and realized they arent working?

**Comment by VyteGTPS** [comment]
> > > this is the place where we ask for help, not begging for codes?
> > 
> > 
> > if you are not asking for codes, why you replied to comments that sent codes?
> 
> because i asked before and got no replies then i had to delete?

how its hard to save account when it gets banned????????????????????

**Comment by jagerrood** [comment]
> > > > this is the place where we ask for help, not begging for codes?
> > > 
> > > 
> > > if you are not asking for codes, why you replied to comments that sent codes?
> > 
> > 
> > because i asked before and got no replies then i had to delete?
> 
> how its hard to save account when it gets banned????????????????????

maybe because i just started making gtps recently and know nothing?
