### ISSUE TITLE
why this code no working with water system 

### ISSUE THREAD

**Issue by Spotify1337** [GrowtopiaNoobs/GrowtopiaServer#341]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/06b1401d7808773d7ac5aea7535f12a83ee5a37b/enet%20server%20test/enet%20server%20test.cpp#L1480

**Comment by NotDark** [comment]
> https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/06b1401d7808773d7ac5aea7535f12a83ee5a37b/enet%20server%20test/enet%20server%20test.cpp#L1480

remove that line (that make u cant use CONSUMABLE)   water is consumable
