### ISSUE TITLE
how to add admin?

### ISSUE THREAD

**Issue by kikou12** [GrowtopiaNoobs/GrowtopiaServer#345]

**Comment by jagerrood** [comment]
Search for _tmain, then add this _addAdmin(username, password, level);_

999 is for super admins.
there might be 2 too i dont know but thats how you add

**Comment by kikou12** [comment]
And commands will be in game

**Comment by kikou12** [comment]
?

**Comment by jagerrood** [comment]
> What line is?

you can check Wiki.

**Comment by kikou12** [comment]
After I found _tmain where do I put addAdmin(username, password, level);

**Comment by fargamerhd** [comment]
yea under the tmain u put this line 
addAdmin(username, password, level);
level 999 is for super admin can do /asb with out stop and can use /reset
level 2 is admin can use /asb i think 1 time every 15 mint
level 1 is only to show gem flag
and if u want a command in game to add mods you should do it your self
dont ask for codes here.. its issue tap not please please give me code 
and i recommend for u to read wiki

**Comment by kikou12** [comment]
Doesn't work can send me by video please

**Comment by Yoayao** [comment]
under tmain } then make addAdmin("yourusername" , "yourpassword" , 999); then build it

**Comment by triple14** [comment]
> then make addAdmin("yourusername" , "yourpassword" , 999);

Hey ,  I have added that and it does not work at all :/
