### ISSUE TITLE
how do I combine gtps file and gtps source code?

### ISSUE THREAD

**Issue by kikou12** [GrowtopiaNoobs/GrowtopiaServer#348]

**Comment by ritzysw** [comment]
????????

**Comment by kikou12** [comment]
the py file and server and item,players,world with source code or cpp file

**Comment by ritzysw** [comment]
????????????????????????????????????
imagine being unable to build project

**Comment by kikou12** [comment]
lmao

**Comment by kikou12** [comment]
like when i edit source codes in visual studio and then i run py file nothing changed

**Comment by Hades3235** [comment]
do you understand the meaning of "build solution"

**Comment by kikou12** [comment]
no?

**Comment by kikou12** [comment]
can you explain?

**Comment by Yoayao** [comment]
click on visual studio "build" then click "build solution" and go to debug / release folder long click the enet server test cpp then paste it to the old one then open it

**Comment by NotDark** [comment]
![image](https://user-images.githubusercontent.com/44568476/58626912-7e182780-8308-11e9-80b0-1b3360e92156.png)

**Comment by ardakurucim** [comment]
read wiki

**Comment by kikou12** [comment]
wdym paste it to the old one?
