### ISSUE TITLE
I am new.

### ISSUE THREAD

**Issue by xDemirHD** [GrowtopiaNoobs/GrowtopiaServer#349]
Hello guys! I am new at these private server things. I will host the server with a VDS. Is there anyone who can teach me some basics?

I won’t beg for commands.

**Comment by NotDark** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/wiki

**Comment by coldchip** [comment]
There are services which provides virtual private servers for free like Google Cloud or Amazon Web Service, They will give you free credits and once you used finished, you can pay to continue.

If you choose Google Cloud, you can host it under the virtual compute section. There are different varieties of operating system which you can choose from(Windows, Linux...). 

To host the Growtopia Server(under this repository), you must choose Windows as the Operating System. After that, run it and it should boot up. 

Next, You upload your compiled exe of the Growtopia Server into your Virtual Server. You can use google drive to tranfer into the virtual server. 

Now, Go to the networking tab of the Google Cloud and create an external IP address that will link into your Virtual Server and open the required port(s) for the server. 

*Database*
You can use the file system provided by Windows or you can use Google Cloud Buckets.

**Comment by jagerrood** [comment]
> There are services which provides virtual private servers for free like Google Cloud or Amazon Web Service, They will give you free credits and once you used finished, you can pay to continue.
> 
> If you choose Google Cloud, you can host it under the virtual compute section. There are different varieties of operating system which you can choose from(Windows, Linux...).
> 
> To host the Growtopia Server(under this repository), you must choose Windows as the Operating System. After that, run it and it should boot up. If you prefer to use Linux(Not Recommended), you can use my Growtopia Server from my repository to generate Linux binaries.
> 
> Next, You upload your compiled exe of the Growtopia Server into your Virtual Server. You can use google drive to tranfer into the virtual server.
> 
> Now, Go to the networking tab of the Google Cloud and create an external IP address that will link into your Virtual Server and open the required port(s) for the server. Create a Web Server using XAMPP, open port 80 and host the server_data.php
> 
> _Database_
> You can use the file system provided by Windows or you can use Google Cloud Buckets.
> 
> Sorry for my bad English. :/

is there any free vps service without cc?

**Comment by OverallGod** [comment]
@jagerrood if you don't have a cc don't do it. There are no free vps  services that don't require a cc or db. you probably can't get one because of how young you are.

**Comment by jagerrood** [comment]
> @jagerrood if you don't have a cc don't do it. There are no free vps services that don't require a cc or db. you probably can't get one because of how young you are.

i can get whenever i want?
