### ISSUE TITLE
IP Issue

### ISSUE THREAD

**Issue by HellixBG** [GrowtopiaNoobs/GrowtopiaServer#35]
Hello! I have an issue that whatever ip I put on the enet thing I can't connect to the server. Any solutions?
And can someone do the wiki for the enet thing not the python?
![image](https://user-images.githubusercontent.com/37038659/47384256-495b4680-d70f-11e8-9c6b-dc935d9ab0a7.png)
My files

**Comment by HellixBG** [comment]
Fixed, but now my devices are stuck on Logging on [MouseBoard] on my pc Growtopia crash but on my phone it stays on Logging on anyone can help me?

**Comment by ritzysw** [comment]
use 2.982

**Comment by HellixBG** [comment]
> use 2.982

I'm using 2.982 on my both devices :)
