### ISSUE TITLE
how to change icon/add image in growtopia gazette?

### ISSUE THREAD

**Issue by MacaylaMarvelous81** [GrowtopiaNoobs/GrowtopiaServer#352]
sorry if i shouldn't be putting this here, but how do you change the icon beside the text (lava) or add images in The Growtopia Gazette?

**Comment by ritzysw** [comment]
read packet list from repo, it has most stuff for dialogs

**Comment by jagerrood** [comment]
add_label_with_icon|small|example text|left|item id|

is probably what you are searching for

**Comment by MacaylaMarvelous81** [comment]
oh, thanks! sorry i only read the part about packets
