### ISSUE TITLE
run code when leaderboard guild button thing pressed?

### ISSUE THREAD

**Issue by MacaylaMarvelous81** [GrowtopiaNoobs/GrowtopiaServer#354]
is there an action for the button below the friends tab?

**Comment by ritzysw** [comment]
open cheat engine and search "action|" to see all action types

**Comment by Hades3235** [comment]
isnt the actions somewhere below the commands in the cpp

**Comment by jagerrood** [comment]
> open cheat engine and search "action|" to see all action types

isnt all action's included in packet-list.md or somewhere on pull request?

**Comment by MacaylaMarvelous81** [comment]
idk how to use cheat engine srry

**Comment by VyteGTPS** [comment]
> > open cheat engine and search "action|" to see all action types
> 
> isnt all action's included in packet-list.md or somewhere on pull request?

LOL welcome back.

**Comment by MacaylaMarvelous81** [comment]
i guess i can try and look?/
