### ISSUE TITLE
Ancestrals.

### ISSUE THREAD

**Issue by ardakurucim** [GrowtopiaNoobs/GrowtopiaServer#357]
I'm sorry to bother you, but how do I add ancestral use? Do not give code just tell me how to do

**Comment by fargamerhd** [comment]
well make like cloth_back make for ances

**Comment by ardakurucim** [comment]
@fargamerhd what is the cloth type for ancestral?

**Comment by ardakurucim** [comment]
@fargamerhd is it artifact?

**Comment by Hades3235** [comment]
no
