### ISSUE TITLE
Keeps disconnecting while trying to login

### ISSUE THREAD

**Issue by warmbryan** [GrowtopiaNoobs/GrowtopiaServer#359]
I added the new items.dat (2.991) to the folder where .exe is and it still doing the same thing.

**Comment by warmbryan** [comment]
Issue resolved.

**Comment by SoloQueenYT** [comment]
same LOL i tryed new item.dat and Rebuilding files... Still dont work

**Comment by iWeeti** [comment]
Can you explain what you did to make it work?
