### ISSUE TITLE
About adding admins.

### ISSUE THREAD

**Issue by Dipsh1t** [GrowtopiaNoobs/GrowtopiaServer#37]
"Add at the beginning of function _tmain". I do that. I build it, i try to open it. Boom. It doesnt build the database anymore. Can someone help? I probably need a video on how to add admins. Too confusing.

**Comment by HellixBG** [comment]
addAdmin("username",""password", level);
The username is lowercase 👍

**Comment by Dipsh1t** [comment]
I get exeption not handled error when i do it.

**Comment by MichalUSER** [comment]
you need to have visual studio 2015 and installed all c++
