### ISSUE TITLE
Stuck In LogIn Connect

### ISSUE THREAD

**Issue by Fluthfi** [GrowtopiaNoobs/GrowtopiaServer#39]
![image](https://user-images.githubusercontent.com/44535388/47610591-7fe5d980-da0d-11e8-9898-27ae8c8d7cd2.png)

How I Fix This ? Are Im Need To DownGrade Or Change Phyton 3 
Or Something ?

**Comment by Fluthfi** [comment]
Have PC Link ? Im Not Have That GT Version
Pada tanggal 28 Okt 2018 16:25, "FocusedSG" <notifications@github.com>
menulis:

**Comment by GrowtopiaNoobs** [comment]
You can also try #41

**Comment by Dunzap** [comment]
I'm stuck PLSS HELP ME IVE DO NE EVERYTHINGGGGG

**Comment by HelpmeHelpyous** [comment]
Man... im stuck too

**Comment by GrowtopiaNoobs** [comment]
Closing this, if someone have still problems, then open new issue
