### ISSUE TITLE
Not connecting to server even tho server working 

### ISSUE THREAD

**Issue by Cool123ggcool** [GrowtopiaNoobs/GrowtopiaServer#42]
so i followed the instructions on your server and made the server it loads and every thing but whn i goto login to the admin account it does this please can you help p.s i can access the server files in localhost
im am also running on 2.982  
![console](https://user-images.githubusercontent.com/29491097/47765022-e8f47800-dcbf-11e8-8bf9-7b291886f455.PNG)
![gt](https://user-images.githubusercontent.com/29491097/47765023-e8f47800-dcbf-11e8-884c-41e1aab99040.PNG)
![localhost](https://user-images.githubusercontent.com/29491097/47765024-e8f47800-dcbf-11e8-9e70-9cf7baff9007.PNG)

**Comment by GrowtopiaNoobs** [comment]
Maybe you have put wrong IP somewhere, try use exactly the python script I posted on wiki.

**Comment by Cool123ggcool** [comment]
Thank you it now works plus if you want a growtopia installer for 2.983 hit me up and i an upload it for you :)
