### ISSUE TITLE
Need help on some stuff.

### ISSUE THREAD

**Issue by NeedHelpUrgents** [GrowtopiaNoobs/GrowtopiaServer#43]
Hello! I'm new here, and I have some questions to ask. If you can help me fix, comment pls

1. How to pick up items in Private Server
2. How to WEAR items in private server
3. How to PLAY private server in V2.983?

That's all I have. If anyone can fix it, I'll be appreciated! :)

**Comment by GrowtopiaNoobs** [comment]
1. You can't
2. Look at wiki how to setup server (you have probs missing CoreData.txt)
3. Look at newest pull request, it should probably solve it

**Comment by NeedHelpUrgents** [comment]
okay, thanks

**Comment by GrowtopiaNoobs** [comment]
Everything is answered, so I am closing this
