### ISSUE TITLE
Stuck on LogOn Screen

### ISSUE THREAD

**Issue by NeedHelpUrgents** [GrowtopiaNoobs/GrowtopiaServer#45]
I have:
- Used the new script to update game into V2.983
- Place the newest items.dat in the folder.
- Use 127.0.0.1 growtopia1.com in the "hosts" notepad with Admin
- Downgraded from V.2984 to V.2983
-------------------------------------------------------------------------
Any solutions to it?

**Comment by GrowtopiaNoobs** [comment]
Do you run python script that I posted?

**Comment by NeedHelpUrgents** [comment]
Which python script? Http already did

**Comment by NeedHelpUrgents** [comment]
![whatamimissing](https://user-images.githubusercontent.com/44633069/47896744-d9d11e00-dea9-11e8-9568-820d748800bb.PNG)
What am I missing?

**Comment by Fluthfi** [comment]
> Do you run python script that I posted?

Can U Make Server With Player World Folder Http Or Something Just 1 File In A Rar So We Can Use Server Without Setting Anymore?

**Comment by Dunzap** [comment]
i have the same problem too

**Comment by If1is1then** [comment]
i think we have the same problem, the record growtopia1.com
