### ISSUE TITLE
Need Help on compiling on VS 2017

### ISSUE THREAD

**Issue by Allinol** [GrowtopiaNoobs/GrowtopiaServer#47]
Hello There GT Server Contributors, I've been trying to compile the script with Vs2017 with 2015 core then it successes but then when it is connecting it crashes making the Abort() 

Thanks,

**Comment by xVENUS** [comment]
Try to open in default enet server test do not open enet server.cpp or some files like that

**Comment by NotDark** [comment]
try to remove the Descriptions.txt

or redownload from this link
https://raw.githubusercontent.com/Nenkai/GrowtopiaItemDatabase/master/GrowtopiaItemDatabase/Data/Descriptions.txt

**Comment by Allinol** [comment]
> Try to open in default enet server test do not open enet server.cpp or some files like that



> try to remove the Descriptions.txt
> 
> or redownload from this link
> https://raw.githubusercontent.com/Nenkai/GrowtopiaItemDatabase/master/GrowtopiaItemDatabase/Data/Descriptions.txt
> 
> that happen to me when i edit the Descriptions.txt

Doesn't work

**Comment by MichalUSER** [comment]
It cannot be compiled on visual studio 2017, Just vs 2015.

**Comment by ardakurucim** [comment]
@MichalUSER i compiled it on 2017 why not?

**Comment by MichalUSER** [comment]
@ardakurucim i dont know, anyways i dont use visual studio, i switched to linux, pop os so i dont care about visual studio
