### ISSUE TITLE
Disconnect upon connection

### ISSUE THREAD

**Issue by MarmoriPelaa** [GrowtopiaNoobs/GrowtopiaServer#5]
I encountered this with unmodified code, compiled with Microsoft Visual Studio 2017:
![image](https://user-images.githubusercontent.com/20874339/46156888-332ea780-c283-11e8-95c0-442e1e3f3251.png)
Also if I turn on exceptions an exception occurs and it points to row 727 which looks like this:
https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/153bb967c7d00a06dcf865cf56670c67f4529df6/enet%20server%20test/enet%20server%20test.cpp#L727
Which doesn't make any sense to me.
Please note that I am a beginner in C++ so I have no idea what could cause the error.

**Comment by Vildis** [comment]
Try adding breakpoints in the code and running it in visual studio debug mode and opening the run.py

**Comment by MarmoriPelaa** [comment]
After adding the files, still no success but there is one thing that might be related:
https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/153bb967c7d00a06dcf865cf56670c67f4529df6/enet%20server%20test/enet%20server%20test.cpp#L2908
I assume that I need to join a private server to refresh the item data and then join my own.

**Comment by ritzysw** [comment]
just join some other private server and then your own, it must work

**Comment by GrowtopiaNoobs** [comment]
This line: https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/153bb967c7d00a06dcf865cf56670c67f4529df6/enet%20server%20test/enet%20server%20test.cpp#L2908 isn't related to issue. I fixed that bug already and just forgot that line in code. You can check code behavior, when you uncomment this line: https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/153bb967c7d00a06dcf865cf56670c67f4529df6/enet%20server%20test/enet%20server%20test.cpp#L44

Btw here is link for items.dat download: https://www60.zippyshare.com/v/f9DQ4C7K/file.html
