### ISSUE TITLE
How to find OnSuperMainStartAcceptLogon?

### ISSUE THREAD

**Issue by mar4ello6** [GrowtopiaNoobs/GrowtopiaServer#50]
How to find OnSuperMainStartAcceptLogon and new items.dat?
And if i update server, i have to update CoreData.txt and Descriptions.txt?

**Comment by NotDark** [comment]
you have to debug the growtopia bot make by growtopia noobs  you can find the link 
https://github.com/GrowtopiaNoobs/Growtopia-Bot

**Comment by Mempler** [comment]
as NotDark already mentioned that is exactly what you need. #94 for more information
