### ISSUE TITLE
Is this possible to recreated in Java?

### ISSUE THREAD

**Issue by DrOreo002** [GrowtopiaNoobs/GrowtopiaServer#51]
I'm not sure if I can make this in java or not.., can you tell me if its possible or not?

then if it possible can you tell me how this private server thing work?. Because I got no idea on how this "private server" work. I also has 1 year experience of java, so I know what I'm doing here

Thanks!

**Comment by OverallGod** [comment]
Your the one that knows java you tell me

**Comment by DrOreo002** [comment]
I know java. But I don't know how these private server work, how can I recreate it without knowing how this thing works

**Comment by DabsYt** [comment]
I know good Java too but i searched for vps in Java and seen a few.For no large files and commands you NEED c++ or atleast c# because they support much like Enet(used here) and stuff.My answer is yes,but not worth your time.

**Comment by DrOreo002** [comment]
Yeah, If I've also made a research yesterday and seems like there's no enet lib for java. But there's still a way to do this which is using c++ lang in java using some kind of virutual machine. But still its going to be complicated

So going to use c++ instead, prob I'll try to learn it xD. Thanks
