### ISSUE TITLE
after i try to create an account in 2.984 this happens.

### ISSUE THREAD

**Issue by Dipsh1t** [GrowtopiaNoobs/GrowtopiaServer#53]
![hoiva](https://user-images.githubusercontent.com/44480344/48013989-5411d480-e12e-11e8-99f4-d1910a99da9f.PNG)

**Comment by DrOreo002** [comment]
Got that error to. Prob caused because u didn't set the discord tag, or maybe u have set it but u didn't put any #, which is every discord tag should have

**Comment by PixelTheGreat** [comment]
I'm getting that as well, why not make a prevention for it

**Comment by DrOreo002** [comment]
I'll prob try it.  Not sure

**Comment by Dipsh1t** [comment]
>           Got that error to. Prob caused because u didn't set the discord tag, or maybe u have set it but u didn't put any #, which is every discord tag should have

it doesn't matter how i put it.

**Comment by Dipsh1t** [comment]
fixed it by updating enet server test.cpp. closing it.
