### ISSUE TITLE
`% text

### ISSUE THREAD

**Issue by Hades3235** [GrowtopiaNoobs/GrowtopiaServer#539]
so i made the mods say colored chat but because recently gt changed it to `% cant be used in chat for green,it will be pink instead.You can only use the green if its in your username

**Comment by NotDark** [comment]
> so i made the mods say colored chat but because recently gt changed it to `% cant be used in chat for green,it will be pink instead.You can only use the green if its in your username

you mean `^ ?

**Comment by Hades3235** [comment]
ye
