### ISSUE TITLE
How can i add command scripts without having VS?

### ISSUE THREAD

**Issue by rosenishere** [GrowtopiaNoobs/GrowtopiaServer#540]
How can i add command scripts without having VS? If i cant can someone help me and do it for me? Thanks!

**Comment by Zlarex** [comment]
I tried to compile it via codeblocks, return nothing. I think cant be compiled without vs or create own script for another compiler

**Comment by rosenishere** [comment]
> I tried to compile it via codeblocks, return nothing. I think cant be compiled without vs or create own script for another compiler

well, i need to do it, but i dont have degree in creating own script. i dont know what to do as i need it.

**Comment by ilyn1337** [comment]
you can write ur code with notepad too, but you need some external compilers/linkers/debuggers(if u want)

**Comment by GrowtopiaNoobs** [comment]
Well, scripts aren't supported here, so you need to compile everything. Using VS is easiest way, if you don't use VS, then you will need some other compiler, but except some compile errors, so you should have some knowledge of C++.

**Comment by rosenishere** [comment]
what file do i need to edit to add some scripts?

**Comment by GrowtopiaNoobs** [comment]
There isn't any way to do it, because there would be need to add code for executing scripts and it is impossible in current code state. So you need to get VS else you can't make any changes to server.

**Comment by rosenishere** [comment]
yes, but what file do i need to edit with vs to add scripts?

**Comment by GrowtopiaNoobs** [comment]
You would need to add some script engine https://stackoverflow.com/a/3153436 to `enet server test/enet server test.cpp`, but I guess you wouldn't be able to do it.

**Comment by rosenishere** [comment]
> You would need to add some script engine https://stackoverflow.com/a/3153436 to `enet server test/enet server test.cpp`, but I guess you wouldn't be able to do it.

I have a modified server.exe file how do i modify it?

**Comment by GrowtopiaNoobs** [comment]
You need visual studio to compile new server.exe and you aren't modifiyng the exe, but that source file I told you.

**Comment by GrowtopiaNoobs** [comment]
This question was answered. Closing.
