### ISSUE TITLE
Exe Crash Without reason

### ISSUE THREAD

**Issue by D3c0d33** [GrowtopiaNoobs/GrowtopiaServer#542]
Hello there!,I have a problem EXE When i run it it's error abort()call and I already DELETE The 0KB File and it's not working always error exe What I do? for fix can give me a tips?

**Comment by ardakurucim** [comment]
check your last updates

**Comment by SurekingIGTPS** [comment]
> check your last updates
I'am Already check all And no have error and When run exe it's error Hm maybe my vps? Because My 2nd vps it's 3 GB :joy:

**Comment by playingo** [comment]
someone is crashing ur server and u dont have fix so u cant host server :) that might be because you have stolen or used copied cpps and now your basically screwed up.

**Comment by ilyn1337** [comment]
@SurekingIGTPS you are getting attacked... that's why, so fix ur server :P

**Comment by TrisuDL** [comment]
Ddos are hacking u

**Comment by NoobesGT** [comment]
Maybe you made a mistake in coding.

**Comment by GrowtopiaNoobs** [comment]
You need to provide what part of code is causing crash.
Also if this issue is already solved, then please close it.

**Comment by GrowtopiaNoobs** [comment]
Closing this issue as there was no new activity.
