### ISSUE TITLE
server.exe and cpp file

### ISSUE THREAD

**Issue by kikou12** [GrowtopiaNoobs/GrowtopiaServer#546]
when i edit cpp file or c++ how i save in server.exe

**Comment by SurekingIGTPS** [comment]
Go file name ''Debug'' and click it and you see enet server test.exe click right mouse and cut and,go back and paste and replace it.
**Hope is helping you :smile: **

**Comment by WolfPT** [comment]
And and and and and and. 

pls go learn english

**Comment by SurekingIGTPS** [comment]
shut up Kids don't read and comments sucks!

**Comment by Spotify1337** [comment]
"Debug" is crashing server use realse

**Comment by kikou12** [comment]
Where I can find debug

**Comment by Secrethaxorzzzxxxxxxxxxx** [comment]
> shut up Kids don't read and comments sucks!

Fucking stupid, toxic indog

**Comment by kikou12** [comment]
I’m not indog

**Comment by kikou12** [comment]
And fix your grammar too

**Comment by TrisuDL** [comment]
> > shut up Kids don't read and comments sucks!
> 
> Fucking stupid, toxic indog

Umm you was toxic there tho @Secrethaxorzzzxxxxxxxxxx
