### ISSUE TITLE
OnGuildDataChanged

### ISSUE THREAD

**Issue by OverallGod** [GrowtopiaNoobs/GrowtopiaServer#547]
I know this doesn't really go with this server but I need help and yes I know its the issues tab im very sorry.

I have been using OnGuildDataChanged and I got it to work in a command.
Example : https://i.ibb.co/y565bK2/guilddata.png
I want to send this packet to the user when he enters a world,

I have tried to send the packet when the user spawns.
I have tried to send the packet when the user enters a world.
I have tried to send the packet when they login.
I have tried to send the packet when it loads cloths and weather and gems.
none of them work it doesnt give me the results I want 
(remember https://i.ibb.co/y565bK2/guilddata.png)
any help or tips?

**Comment by SurekingIGTPS** [comment]
I have The GUILD flag but only change Flag example my cmd /changeflag 242 it's flag WorldLock
But if change to guild system i can't because i no have it :joy: 
###XD

**Comment by NotDark** [comment]
> I know this doesn't really go with this server but I need help and yes I know its the issues tab im very sorry.
> 
> I have been using OnGuildDataChanged and I got it to work in a command.
> Example : https://i.ibb.co/y565bK2/guilddata.png
> I want to send this packet to the user when he enters a world,
> 
 

try add this  PlayerInfo*)(peer->data))->country=(PlayerInfo*)(peer->data))->country+"|ShowGuild"

**Comment by playingo** [comment]
the indog got it from another cpp

**Comment by Yoayao** [comment]
ikr

**Comment by OverallGod** [comment]
@playingo who are you talking about lol

**Comment by OverallGod** [comment]
also @NotDark it didnt seem to help.

**Comment by ritzysw** [comment]
adding "|showguild" to end of "country" variable should show guild data on player

**Comment by OverallGod** [comment]
@ritzysw like this "../slider_button|ShowGuild"

**Comment by ritzysw** [comment]
>why do u have "slider_button" as country flag

**Comment by OverallGod** [comment]
because it looks cool lol

**Comment by OverallGod** [comment]
> > why do u have "slider_button" as country flag

because it looks cool lol

**Comment by Spotify1337** [comment]
Dark is dark++

**Comment by OverallGod** [comment]
@ritzysw you didn't answer my question xD

**Comment by ritzysw** [comment]
you didn't ask me anything

**Comment by OverallGod** [comment]
> @ritzysw like this "../slider_button|ShowGuild"

LIKE THIS???

**Comment by OverallGod** [comment]
I did this.
((PlayerInfo*)(peer->data))->country = ((PlayerInfo*)(peer->data))->country + "|showGuild";
cout << ((PlayerInfo*)(peer->data))->country << endl;
sendguilddata(peer, 1796);
the cout is just for testing it outputs ../slider_button|showGuild
The sendguilddata(peer, 1796); is a function that sends what I need I can confirm it works.

**Comment by Mempler** [comment]
No code requests allowed sry, we only allow issues about our software and not "code requests" you can make a feature request though.
