### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ardakurucim** [GrowtopiaNoobs/GrowtopiaServer#548]
I add cloth type for ancestrals but when i use ancestral it crashes the game need help

**Comment by SurekingIGTPS** [comment]
You Miss 1 Words or the code, Focus to it maybe wrong code or words
Hope It's helping you :smiley:

**Comment by ardakurucim** [comment]
@SurekingIGTPS there isn't wrong code i think can you help me ?

**Comment by ardakurucim** [comment]
@SurekingIGTPS i fixed it thank you

**Comment by SurekingIGTPS** [comment]
> @SurekingIGTPS i fixed it thank you

Ok No problem!

**Comment by SurekingIGTPS** [comment]
CLOSED THIS ISSUE BTW
