### ISSUE TITLE
[question] are custom graphics possible?

### ISSUE THREAD

**Issue by MacaylaMarvelous81** [GrowtopiaNoobs/GrowtopiaServer#550]

**Comment by ritzysw** [comment]
you can't create custom items, but you can change items textures, just create folder "cache" in xampp's htdocs folder and place all rttex files in it(every single one), then just edit OnSuperMain thing arguments to your server ip and "cache/" as second argument
to edit textures just use some rttex editor(google) and place new rttex files in htdocs/cache/

**Comment by MacaylaMarvelous81** [comment]
RIP custom graphics crash (i dont use apache or xampps so i tried stuff but it crashes GT when enter world (i edited friend button) but its prob somethin i did wrong maybe i shoulld try again later. thanks tho

**Comment by OverallGod** [comment]
You don't need xampp. Just do what he said but place it in the root of your webserver.

**Comment by ritzysw** [comment]
>xampp is webserver

**Comment by OverallGod** [comment]
@ritzysw 
I know lol im just saying he xampp isnt the only thing he can use.
Also i did what you said it it worked lol.
https://i.ibb.co/z8H3NT8/Capture.png

**Comment by NotDark** [comment]
> @ritzysw
> I know lol im just saying xampp isnt the only thing he can use.
> Also i did what you said it it worked lol.
> https://i.ibb.co/z8H3NT8/Capture.png

@OverallGod you put the game folder in gt folder?

**Comment by ilyn1337** [comment]
you have to trigger growtopia to re-update the items, do something that gt shouldn't check items.dat hash.
