### ISSUE TITLE
What is bluename code 

### ISSUE THREAD

**Issue by Spotify1337** [GrowtopiaNoobs/GrowtopiaServer#552]
Someone know bluename code?

**Comment by SurekingIGTPS** [comment]
xD go learn? Uhm i give u tips want?

**Comment by coldchip** [comment]
@SurekingIGTPS 
<h1>Says the one who begs for code. lol.</h1>

**Comment by coldchip** [comment]
@Spotify1337 

Try using the color code `1
Example: `1<Your Name>

Hopes this helps

**Comment by coldchip** [comment]
@Spotify1337 
Try using the color code \`1
Example: \`1\<Your Name\>

**Comment by Yoayao** [comment]
you mean that 125 level that bluename?

**Comment by Yoayao** [comment]
@coldchip lol yea he thought he pro lol.. even beg for code

**Comment by NotDark** [comment]
> Someone know bluename code?

add |MaxLevel to ((PlayerInfo*)(peer->data))->country

**Comment by playingo** [comment]
@SurekingIGTPS stfu indogyou are the one begging urself!

**Comment by Spotify1337** [comment]
what a cruel world

**Comment by OverallGod** [comment]
@everyone or anyone
If you dont know C++ JUST STOP asking or doing anything code related please.
it just makes everyone mad.

**Comment by Mempler** [comment]
No code requests allowed!
