### ISSUE TITLE
How to get the API key for the server

### ISSUE THREAD

**Issue by TrisuDL** [GrowtopiaNoobs/GrowtopiaServer#553]
How to to make/see API key in the server someone can help?

**Comment by NotDark** [comment]
> How to to make/see API key in the server someone can help?

what you mean api key?

**Comment by TrisuDL** [comment]
I mean i need some kind of API key to use VPS

**Comment by TrisuDL** [comment]
>hi
Test

**Comment by Mempler** [comment]
There are no API keys!
