### ISSUE TITLE
Some Packets I found.

### ISSUE THREAD

**Issue by OverallGod** [GrowtopiaNoobs/GrowtopiaServer#554]
If you could tell me what some of them do that would be great!
00340ff0: OnRender
00341000: OnUpdate
00341010: OnReconnect
00341020: OnSpawn
00341028: OnRemove
00341038: OnRequestWorldSelectMenu
00341058: OnConsoleMessage
00341070: OnSDBroadcast
00341080: OnTalkBubble
00341090: OnTextOverlay
003410a0: OnDialogRequest
003410b0: OnStoreRequest
003410c0: OnStorePurchaseResult
003410d8: OnZoomCamera
003410e8: OnPinchMod
003410f8: OnHelpRequest
00341108: OnCommunityHubRequest
00341120: OnUbiclubRequest
00341138: OnFailedToEnterWorld
00341150: SetHasGrowID
00341160: SetHasAccountSecured
00341178: GrowIDChanged
00341188: OnSuperMainStartAcceptLogonHrdxs47254722215a
003411b8: Growtopia
003411c8: OnSetBux
003411d8: OnParticleEffect
003411f0: OnParticleEffectV2
00341208: Internal memory error 49
00341228: OnItemEffect
00341238: OnAddNotification
00341250: OnStartTrade
00341260: OnForceTradeEnd
00341270: [PACKET_LOG_START]
00341288: OnTradeStatus
00341298: Message Type Log:-
003412b0: OnDisableRemoveIAPScreen
003412d0: Message type: %s received %d times
003412f8: OnSendToServer
00341308: Message Type Log End.
00341320: OnSendToCaptcha
00341330: Game Packet Log:-
00341348: OnToggleBetaMode
00341360: Game Packet type: %s received %d times
00341388: OnSetBetaMode
00341398: Game Packet Log End.
003413b0: OnSetBetaSilent
003413c0: Function Call Packet Log:-
003413e0: OnSendIAPConfirmation
003413f8: Function Packet type: %s received %d times
00341428: OnSetBaseWeather
00341440: Function Call Packet Log End.
00341460: OnSetCurrentWeather
00341478: [PACKET_LOG_END]
00341490: OnRestorePurchases
003414a8: OnRedirectServer
003414c0: OnPlanterActivated
003414d8: OnMagicCompassTrackingItemIDChanged
00341500: OnEmoticonDataChanged
00341518: OnPaw2018SkinColor1Changed
00341538: OnPaw2018SkinColor2Changed
00341558: OnSetRoleSkinsAndTitles
00341570: OnAchievementCompleted
00341588: OnOverrideGDPRFromServer
003415a8: onShowCaptcha
003415b8: OnCaptchaFailed
003415c8: OnItemEffect

**Comment by NotDark** [comment]
OnEmoticonDataChanged for growmoji
OnPlanterActivated for magplant thing
OnTradeStatus for trade gui
OnParticleEffect/OnParticleEffectV2  for Particle Effect [example when level up will show star]
OnSDBroadcast for super duper broadcast
OnForceTradeEnd for force close trade gui
onShowCaptcha for captcha [ 1+1 = ]

**Comment by playingo** [comment]
wow cheat engine strings.

**Comment by Spotify1337** [comment]
How about OnSetGay

**Comment by Mempler** [comment]
You should remove some of the invalid strings that are no packets at all. like `00341360: Game Packet type: %s received %d times`

**Comment by Mempler** [comment]
not an issue though

**Comment by atomiclucky** [comment]
@OverallGod yo where do you put the cout?
