### ISSUE TITLE
PlayerDB:fixColors error

### ISSUE THREAD

**Issue by kikou12** [GrowtopiaNoobs/GrowtopiaServer#555]

**Comment by ritzysw** [comment]
>???????

**Comment by kikou12** [comment]
Cause when I build solution I got this error and when I debug

**Comment by SurekingIGTPS** [comment]
> when I build solution I got this error and when I debug

Ik how to fix there 3 ways to fix ez

**Comment by playingo** [comment]
indog, shut the fuck up you beg for stuff yourself and you dont know anything. @SurekingIGTPS 
also: https://www.youtube.com/watch?v=K0x73RvCXyQ

**Comment by kikou12** [comment]
How to fix?????????

**Comment by GrowtopiaNoobs** [comment]
Please provide more information, such what causes error, error message, etc.

**Comment by Mempler** [comment]
@GrowtopiaNoobs this kind of issue is more invalid, you don't have to ask further information, they'll most likely create a new issue with more information. that holds the issues more clean.
