### ISSUE TITLE
Vps

### ISSUE THREAD

**Issue by TrisuDL** [GrowtopiaNoobs/GrowtopiaServer#556]
So how do i get the vps in the server if there is no API key

**Comment by coldchip** [comment]
I don't understand you. 
Can you please be more detailed; Answer the questions below.

1. What VPS Are you using?
2. What do you mean specifically by "no API Key"?
3. What does your API does?
4. And most importantly, What are you trying to achieve?

**Comment by TrisuDL** [comment]
A:1 Vulture
A:2 notdark said there is no API key
A:3 Idk
A:4 ip id

**Comment by coldchip** [comment]
@TrisuDL 
Here's how you find your external IP on Vultr VPS: 
[https://www.vultr.com/docs/add-secondary-ipv4-address](https://www.vultr.com/docs/add-secondary-ipv4-address)

**Comment by TrisuDL** [comment]
Ok ty im gonna try it i close tgis if works
