### ISSUE TITLE
Host

### ISSUE THREAD

**Issue by xDemirHD** [GrowtopiaNoobs/GrowtopiaServer#557]
Hi Guys! To Local Host, what should I do for HTTP server?
Like, to play with friends, what should I do step by step?

**Comment by ardakurucim** [comment]
127.0.0.1 localhost ip

**Comment by xDemirHD** [comment]
No I mean opening to server to universe.

**Comment by WolfPT** [comment]
Open port

**Comment by coldchip** [comment]
port forward on the router

**Comment by NotDark** [comment]
use hamachi if cant port forward

**Comment by OverallGod** [comment]
Be very careful when opening ports

**Comment by Mempler** [comment]
https://www.vpn.net/
