### ISSUE TITLE
does someone know how to collect DROPPED items/gems properly?

### ISSUE THREAD

**Issue by playingo** [GrowtopiaNoobs/GrowtopiaServer#559]
alright so incase your thinking  that i am asking about break "collecting" gems, i mean that when DROPPED items or gems are collected, then run code.
i thought of packet types maybe, idk. does someone know any possibilities how to set this up?
thanks.

**Comment by Spotify1337** [comment]
maybe push back inventory

**Comment by playingo** [comment]
yeah but i really want that collecting animation

**Comment by ritzysw** [comment]
there aren't easy ways to do it, you would have to store vector of all dropped items, when you collect item it sends packet type 4 with plantingTree being index of dropped item starting from 0, from there you just take id and amount of items from dropped items vector

**Comment by playingo** [comment]
void sendtake(ENetPeer* peer, int netID, int x, int y, int item )
{
	if (item >= 7196) return;
	if (item < 0) return;
	ENetPeer * currentPeer;
	string name = "";
	for (currentPeer = server->peers;
		currentPeer < &server->peers[server->peerCount];
		++currentPeer)
	{
		if (currentPeer->state != ENET_PEER_STATE_CONNECTED)
			continue;
		if (isHere(peer, currentPeer)) {
			PlayerMoving data;
			data.packetType = 14;
			data.x = x;
			data.y = y;
			data.netID = netID;
			data.plantingTree = item;
		 

			BYTE* raw = packPlayerMoving(&data);
			 

			SendPacketRaw(4, raw, 56, 0, currentPeer, ENET_EVENT_TYPE_RECEIVE);
		}
	}
}

**Comment by playingo** [comment]
its broken tho

**Comment by GrowtopiaNoobs** [comment]
Don't forget to call `delete raw;` in your code, else you are getting memory leak and your server can crash after some time. Btw if you make something what is working or partially working, then please open PR.

**Comment by MarmoriPelaa** [comment]
Just thinking aloud: Is there any other way to spawning items on enter instead of the drop button code? I was wondering if you could send all the existing items in an array without the spawn item sound. Because that would be much more efficient as it (maybe) could save bandwidth.

**Comment by playingo** [comment]
new packet probably?
