### ISSUE TITLE
Stuck at LogIn place

### ISSUE THREAD

**Issue by Dunzap** [GrowtopiaNoobs/GrowtopiaServer#56]
Just updated script to V.2984
and did everything needed
buy stuck at logon screen 
help me 
what do i do

**Comment by DrOreo002** [comment]
Stuck?, Well I got no problem when running the server this is prob because you did something wrong on the setup

**Comment by willi123yao** [comment]
As far as I know (by looking from GrowtopiaNoob's source code), either that you are missing the files required for the server to work properly (did you follow the setup instructions over at the [wiki page](https://github.com/GrowtopiaNoobs/GrowtopiaServer/wiki)?), or that you client has a different item database configured than what the server currently supports (you can fix this by copying the items.dat that GrowtopiaNoobs has kindly provided over at the wiki page and replace the one found in your appdata folder under growtopia, not completely sure if thats the correct place but it should be somewhere where you can find your save.dat file)

**Comment by Dunzap** [comment]
ok

**Comment by Dunzap** [comment]
> Stuck?, Well I got no problem when running the server this is prob because you did something wrong on the setup

can u show me how your one looks like i wanna see whats missing

**Comment by Dunzap** [comment]
> > hi
>

**Comment by Dunzap** [comment]
Yesterday something terrifying happened
I don't know if the file is a virus
but i get fake ads on my computer

**Comment by willi123yao** [comment]
> can u show me how your one looks like i wanna see whats missing

server.exe
CoreData.txt
Descriptions.txt
items.dat
players/
worlds/

players/ and worlds/ are folders, you will just need to create 2 empty folder and call them players and worlds.

**Comment by Dunzap** [comment]
> s

**Comment by Dunzap** [comment]
After all those explanations, I'm still stuck.
Got all the things in (for the master server),
Got the items.dat Growtopia Noobs uploaded

**Comment by Dunzap** [comment]
:/

**Comment by Dunzap** [comment]
So uh

**Comment by If1is1then** [comment]
im stuck too even tho i have all in
record growtopia1 error how fixxx

**Comment by Boujee0040** [comment]
@Mempler So.. you know a fix? Please just tell it here

**Comment by Mempler** [comment]
Find the hash by yourself. edit that line and change the hash. https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/f4f30d648557d0dc721ba4b6a9d9153592ed43b8/enet%20server%20test/enet%20server%20test.cpp#L2851

we're not helping you finding the hash since it's something from growtopia's security!

**Comment by Dunzap** [comment]
i have already inserted the hash, now i am experiencing error connecting

**Comment by GrowtopiaNoobs** [comment]
This issue was inactive for long time and alot of issues like this one exists
Closing
