### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by xDemirHD** [GrowtopiaNoobs/GrowtopiaServer#562]
Hello guys which VDS hosting companies do you use to host server?

**Comment by Spotify1337** [comment]
vds or vps 
if vps window server 2012

**Comment by ilyn1337** [comment]
@Spotify1337 "Hello guys which VDS hosting companies do you use to host server?", as you can see here, he is asking for VDS... Are you blind or what?

**Comment by xDemirHD** [comment]
@ilyn1337 Indos should learn English 31938 times
