### ISSUE TITLE
VPS

### ISSUE THREAD

**Issue by TrisuDL** [GrowtopiaNoobs/GrowtopiaServer#563]
So got vps and ip but still if try in mobile no work (was 100% correct ip) ip is
20.90.113.110 growtopia1.com
20.90.113.110 growtopia2.com

**Comment by SoloQueenYT** [comment]
?

**Comment by TrisuDL** [comment]
I mean that ip dosent work what u send so i asled help

**Comment by coldchip** [comment]
@TrisuDL
I checked the IP and it doesn't contain a valid web server on port 80
Did you open the port on the IP Address?
