### ISSUE TITLE
Looking for someone to help code

### ISSUE THREAD

**Issue by SoloQueenYT** [GrowtopiaNoobs/GrowtopiaServer#565]
If you need a Top Role for your server DM me on discord SoloQueen#0322
What can i do to make a better server

-- I code for a living / Share me to your VS server .cpp

-- Active / Ban anyone that's bad in server

-- MORE!!

**Comment by SoloQueenYT** [comment]
GUYS ITS FREE FOR ME TO HELP CODE (helped over 5+ Peps)

**Comment by ritzysw** [comment]
>I code for a living
goes in my memes collection after surekinggtps, thanks

**Comment by SurekingIGTPS** [comment]
> > I code for a living
> 
> goes in my memes collection after surekinggtps, thanks

fk u

**Comment by Hades3235** [comment]
@ritzysw send me link in discord for both

**Comment by ardakurucim** [comment]
@SoloQueenYT i sended

**Comment by ardakurucim** [comment]
@SoloQueenYT accept bro

**Comment by SoloQueenYT** [comment]
@Hades3235 and @ardakurucim whana work together making a server (i can code) if your guys work on VPS

**Comment by ilyn1337** [comment]
@SoloQueenYT no you can't code...

**Comment by SoloQueenYT** [comment]
whana see my VS without me having a team , i did a hole server and im allready hosting it

**Comment by NotDK** [comment]
@SoloQueenYT uhh... no u dont know whats a code... fuck off... dont ask for code... - another kid who wants codes
