### ISSUE TITLE
Free VPS?!

### ISSUE THREAD

**Issue by SoloQueenYT** [GrowtopiaNoobs/GrowtopiaServer#566]
is there anyway theres free VPS??

**Comment by Spotify1337** [comment]
yes have go suicide u self

**Comment by warmbryan** [comment]
Yes there are free VPS and google is your best friend. Don't go around begging and asking for things that you could've googled.

**Comment by OverallGod** [comment]
https://www.google.com/search?q=free+vps&oq=free+vps&aqs=chrome..69i57.3265j0j4&client=ms-android-americamovil-us-revc&sourceid=chrome-mobile&ie=UTF-8
