### ISSUE TITLE
ERROR! Trying to login .... 

### ISSUE THREAD

**Issue by SoloQueenYT** [GrowtopiaNoobs/GrowtopiaServer#567]
https://cdn.discordapp.com/attachments/587395991800512562/587450041564659712/20190609_201559.jpg

**Comment by SoloQueenYT** [comment]
stays at "uploading 1/9"

**Comment by OverallGod** [comment]
If you really know how to code you could fix it really  easily

**Comment by SoloQueenYT** [comment]
ik coding its just Dont Other things like python or Other annoing thigs like this

**Comment by OverallGod** [comment]
Lol what type of coding? This has nothing to do with Python

**Comment by OverallGod** [comment]
Also this really isn't an error. If you could just use your brain. enet_peer_disconnect_later(peer, 0);

**Comment by SoloQueenYT** [comment]
> Also this really isn't an error. If you could just use your brain. enet_peer_disconnect_later(peer, 0);

ok found it in VS now what

**Comment by ritzysw** [comment]
>I code for a living

btw

**Comment by Spotify1337** [comment]
maybe you hash item is old that why stuck on updating item

**Comment by SoloQueenYT** [comment]
i updated the hash item like 4 times and everyhting

**Comment by coldchip** [comment]
@SoloQueenYT
Hint: It has something to do with the platformID when the client is connecting to the server.

**Comment by SoloQueenYT** [comment]
no more error i helped my self

**Comment by SoloQueenYT** [comment]
thx for the help tho

**Comment by SoloQueenYT** [comment]
IM GOING TO CLOSE ISSUE
