### ISSUE TITLE
ipban for notepad

### ISSUE THREAD

**Issue by Spotify1337** [GrowtopiaNoobs/GrowtopiaServer#568]
how to make some notepad like coredata but for ipban

**Comment by SurekingIGTPS** [comment]
Click Right mouse and open with and Use click visual studio and done :smile:

**Comment by Spotify1337** [comment]
Go suicide you self

**Comment by ilyn1337** [comment]
@Spotify1337 Read this https://stackoverflow.com/questions/7868936/read-file-line-by-line-using-ifstream-in-c

@SurekingIGTPS 
### **SIT DOWN DOG**
