### ISSUE TITLE
Looking for a Team Coding Group

### ISSUE THREAD

**Issue by SoloQueenYT** [GrowtopiaNoobs/GrowtopiaServer#569]
Who wants to help code with me and be to be admin in server (i need a VPS for server but ill do most of the coding)

ADD ON DISCORD
SoloQueen#0322

**Comment by ilyn1337** [comment]
How do you think that "ill do most of the coding"? You're asking for asb code that already exist in the vanilla code... Also you don't buy vps, you don't know how to code and giving him/her admin... It seems you need some dls, don't you?

**Comment by SoloQueenYT** [comment]
nea i allready have 7 new commands i didby my self and 3 from my team LOL

**Comment by SoloQueenYT** [comment]
+ its called team work not asdking for Dumb codes i allready know

**Comment by xDemirHD** [comment]
Well he will get some good coders and hire them for new commands open a server earn dls fire them up 
150% indog

**Comment by playingo** [comment]
yeah 10104005% indog qualified person

**Comment by Mempler** [comment]
Not the right place to ask.
