### ISSUE TITLE
Need code for /asb 

### ISSUE THREAD

**Issue by SoloQueenYT** [GrowtopiaNoobs/GrowtopiaServer#570]
Whats /asb ? anyone knows

**Comment by SoloQueenYT** [comment]
how to Edit so only admins can do it and also how to change price for each /sb

**Comment by Hades3235** [comment]
gonna give this to ritzy for his meme compilation

**Comment by SurekingIGTPS** [comment]
xD?

**Comment by Yoayao** [comment]
well it is already edited for admin only ye.. if you want add price for sb command first you need a gem system

**Comment by SoloQueenYT** [comment]
how add gem system (ILL DM YOU ON DISCORD YOAYAO)

**Comment by Mempler** [comment]
No code requests allowed anymore.
