### ISSUE TITLE
How to Edit enet server test.cpp

### ISSUE THREAD

**Issue by mkevinam** [GrowtopiaNoobs/GrowtopiaServer#571]
Please how to edit enet server test.cpp

**Comment by SurekingIGTPS** [comment]
xD? Go click enet server test.sln and click enet server test.cpp at visual studio and go edit :smile: Hope it's helping you

**Comment by Spotify1337** [comment]
You need visual studio 2015,1017 or 2019 for coding enet test server

**Comment by SoloQueenYT** [comment]
Best coding source is may be VS (Visual studios).

**Comment by playingo** [comment]
bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh bruh

**Comment by mkevinam** [comment]
Thank you all for helping me :)

**Comment by NoobesGT** [comment]
learn to open a .cpp extension first lmao
