### ISSUE TITLE
[REQUEST] New coredata

### ISSUE THREAD

**Issue by SurekingIGTPS** [GrowtopiaNoobs/GrowtopiaServer#572]
Im just request :smile:

**Comment by ilyn1337** [comment]
here is my request too: take your pc and jump off with it from cliff

**Comment by Yoayao** [comment]
my request : don't took other cpp and say that is you and your friend make even that isn't .. nab

**Comment by ritzysw** [comment]
> my request : don't took other cpp and say that is you and your friend make even that isn't .. nab

what the actual fuck thats even worse than sureking

**Comment by Spotify1337** [comment]
Go too new file select notepad and type coredata paste on you server file

**Comment by SoloQueenYT** [comment]
ever think positive @ilyn1337 LOL

**Comment by playingo** [comment]
https://youtu.be/K0x73RvCXyQ @everyone

**Comment by ilyn1337** [comment]
bruh momentum

**Comment by Hades3235** [comment]
@playingo love it

**Comment by NotDK** [comment]
My Request: stfu kid and stop asking for codes. bitch go to hell, damn, cant even learn C# or C++... lol like ur not even trying. stop using other people's fucking gtps files, like ur server is shitty asf... cant even improve ur grammar... reverse talk? bro.. im puerto rican, why tf r u talking australian like lmao... just stop asking for requests, codes, and files... ur too young to learn this stuff son... ur only 4

**Comment by NotDK** [comment]
if u cant fucking learn codes... why tf r u still on fucking GitHub... github is for pros... professionals... coders, developers... not sum fucking cunt

**Comment by NotDK** [comment]
u probably downloaded that image LOL

**Comment by NotDK** [comment]
dont google shit up kid

**Comment by NotDK** [comment]
@playingo totally agree on video... 24/7 of the times total that this kid asks for codes...
