### ISSUE TITLE
[QUESTION] What VPS hosting services are compatible with XAMPP hosting?

### ISSUE THREAD

**Issue by flossboss** [GrowtopiaNoobs/GrowtopiaServer#573]
Discord: @Steak#0703

**Comment by playingo** [comment]
definitely every vos should be if you set up xampp on it.

**Comment by flossboss** [comment]
My friend said that my Microsoft Azure Windows 10 VPS is not compatible. Why is that?

**Comment by NotDark** [comment]
> My friend said that my Microsoft Azure Windows 10 VPS is not compatible. Why is that?

if window you can use xampp

**Comment by flossboss** [comment]
I am using XAMPP but it doesn't work. I have the server_data.php in the htdocs folder. It still doesn't work.

**Comment by flossboss** [comment]
@Notdark

**Comment by NotDark** [comment]
> I am using XAMPP but it doesn't work. I have the server_data.php in the htdocs folder. It still doesn't work.

allow the port 80 and 17091

**Comment by flossboss** [comment]
@NotDark already did,
port 80: TCP
port 17091: UDP

**Comment by atomiclucky** [comment]
I run the run.py on my linux vps with screen and then the main server on wine
