### ISSUE TITLE
[HELP] How To Solve This Problem?

### ISSUE THREAD

**Issue by feelja** [GrowtopiaNoobs/GrowtopiaServer#574]
![GT](https://user-images.githubusercontent.com/51743020/59341030-4a3df880-8d31-11e9-987f-c5170da531de.png)

I can't build the server.exe coz i always got this problem. Any solution for the problem? Add me on discord Feelja#8578. Thank's Anyway. Oh btw im using VS Community 2015.

**Comment by Mempler** [comment]
Builds fine on VS Community 2017-2019
