### ISSUE TITLE
Limit

### ISSUE THREAD

**Issue by xDemirHD** [GrowtopiaNoobs/GrowtopiaServer#575]
How to limit max players?

**Comment by herothedev** [comment]
same like u limit 3 accs per ip so u just do same and remove the new playerinfo thing so it counts all players.

**Comment by NotDark** [comment]
> How to limit max players?

just search 17091 in the source and here have number 1024 (that the max player )

**Comment by ilyn1337** [comment]
Max peers is 3072

**Comment by xDemirHD** [comment]
@NotDark + @ilyn1337 thanks to both of you guys.

**Comment by NoobesGT** [comment]
so how @ilyn1337 says add more "F" in front of "0x"
