### ISSUE TITLE
[HELP] Located Server, Connecting...

### ISSUE THREAD

**Issue by flossboss** [GrowtopiaNoobs/GrowtopiaServer#576]
I'm stuck on "Located server, connecting..." on my VPS.

I already allowed port 80 and 17091;
Port 80: TCP
Port 17091: UCP

What's the issue here?

**Comment by flossboss** [comment]
If you could help contact me on discord: Steak#0703 :3 much appreciated.

**Comment by FuzionVapes** [comment]
lol

**Comment by NotDark** [comment]
> I'm stuck on "Located server, connecting..." on my VPS.
> 
> I already allowed port 80 and 17091;
> Port 80: TCP
> Port 17091: UCP
> 
> What's the issue here?

go to the vps panel in the website and add new firewall rule

**Comment by flossboss** [comment]
@notdark is that for google cloud vps?

**Comment by flossboss** [comment]
Add me on discord Steak#0703
