### ISSUE TITLE
Exited cl.exe with code 2

### ISSUE THREAD

**Issue by ardakurucim** [GrowtopiaNoobs/GrowtopiaServer#578]
What is that mean?

![image](https://user-images.githubusercontent.com/48387425/59428614-6bacec00-8de6-11e9-8a95-d00a99df9fda.png)

**Comment by Mempler** [comment]
No idea, you don't give us enough information.

**Comment by OverallGod** [comment]
This happend to me when I was editing the update cloths function

**Comment by OverallGod** [comment]
What did you do to get this outcome

**Comment by ilyn1337** [comment]
It's cause you are not using return on some overload functions. Example:
```cpp
string myString() {
   //There's no return, error occurs.
}
```
Correct:
```cpp
string myString() {
   return "Helllo!";
}
```

**Comment by ardakurucim** [comment]
@OverallGod i just edit gems system and this happened

**Comment by ardakurucim** [comment]
fixed thank you @ilyn1337
