### ISSUE TITLE
How to run the Http server from java?

### ISSUE THREAD

**Issue by DrOreo002** [GrowtopiaNoobs/GrowtopiaServer#58]
So yeah, from the python code I see that it start an http server. Tried to do that in java using HttpServer.create() method and pass the 127.0.0.1 as the host and 80 as the port

But its not working somehow, could you tell me why?

**Comment by GrowtopiaNoobs** [comment]
You need to handle POST requests and also dont forget to edit /etc/hosts.

**Comment by DrOreo002** [comment]
Alright, thanks for the help
