### ISSUE TITLE
How do I stop them from entering like this?

### ISSUE THREAD

**Issue by FliqXs** [GrowtopiaNoobs/GrowtopiaServer#580]
![heheheheheh](https://user-images.githubusercontent.com/49790797/59470998-48178f00-8e42-11e9-874d-e6c6256e41ad.png)

**Comment by Mempler** [comment]
There is no way to stop that, since this is completely client side. but you can stop people from logging in by denying the Request if the name contains `# or whatever the new mod color is.

**Comment by Mempler** [comment]
Or do they register using that name ?

**Comment by fargamerhd** [comment]
make a check when player login if it have ` or thoes thing make them dc

**Comment by ilyn1337** [comment]
Here is good code for you:
```cpp
if (username.find_first_not_of("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789") != string::npos) {
   //Player's name contains illegal chars, disconnect it!
}
else {
   //Player's name doesn't contains any illegal chars, continue your job.
}
```
