### ISSUE TITLE
/pay (player) (amount) help

### ISSUE THREAD

**Issue by Spotify1337** [GrowtopiaNoobs/GrowtopiaServer#581]
how to fix /pay (player) (pay) Like two time string but how to make?

**Comment by ritzysw** [comment]
you are literally not better than sureking if you don't fucking know how to split string using delimiters

**Comment by Spotify1337** [comment]
@ritzysw I didn't say for full code did me say full code what a cruel world?

**Comment by Spotify1337** [comment]
If you don wanna help just don't coment it xD

**Comment by ilyn1337** [comment]
At least ritzy already give you a tip... "Split"

**Comment by SurekingIGTPS** [comment]
> @ritzysw I didn't say for full code did me say for full code? what a cruel world?

xD i can helping you fix /pay

**Comment by ilyn1337** [comment]
github must have ban from repo feature...

**Comment by ritzysw** [comment]
2 retards came along pretty well

**Comment by playingo** [comment]
literally ban the isureking skid

**Comment by OverallGod** [comment]
He clearly doesn't know how to use Google.
