### ISSUE TITLE
Build exe

### ISSUE THREAD

**Issue by xDemirHD** [GrowtopiaNoobs/GrowtopiaServer#582]
How to build exe file in vs2019?

**Comment by FliqXs** [comment]
![click](https://user-images.githubusercontent.com/49790797/59538666-3c3fd180-8f03-11e9-9423-91d16fead5de.PNG)
Open the solution and click this button

**Comment by Spotify1337** [comment]
Me vs 2019 😒

**Comment by xDemirHD** [comment]
@FliqXs I know that thanks, I saw that I didn’t load C++ thingies to vs.

**Comment by GrowtopiaNoobs** [comment]
Seems solved, closing.
