### ISSUE TITLE
do not ask for codes

### ISSUE THREAD

**Issue by NotDK** [GrowtopiaNoobs/GrowtopiaServer#584]
if u dont know C++, or C# then do not ask for that specific library. i can code, i dont need nobody to tell me about codes... im already an adult... i did collage, and its hard to code! listen, why cant u be smart as i am... if you really want a private server, do it yourself... or legit be grateful for what Noob(z) gives u. if he gives u this private server, do not change any code, its hard to learn C# or C++ and you need to be able to do it... usually smart people. just dont even comment about codes. just code in rtsoft's code... for example;

// Growtopia Gazette
add_label_with_icon|big|`wGrowtopia Gazette|left|5016|

add_spacer|small|
add_label_with_icon|small|`2Welcome to GTDK, First Release!|left|8|
add_button|gazette|Continue|left|24|

**Comment by ilyn1337** [comment]
do not ask for codes!!!11
\*1 hour later\*
it's easy to code!!!!111
this page you are on is called issues/maybe questions

**Comment by NotDK** [comment]
@ilyn1337 bitch stfu... u dont even know the issue... and u dont even fuckin know whats going on u dumbass... if u wanna comment memes, go to imgflip.com u fucking handycap.

**Comment by ritzysw** [comment]
14 year old indog spamming issues to show off how bad he is in "coding", okay

**Comment by DrOreo002** [comment]
lmao calling a contributor as a dumbass, smart af
