### ISSUE TITLE
its easy to code a server lol

### ISSUE THREAD

**Issue by NotDK** [GrowtopiaNoobs/GrowtopiaServer#585]
what do u guys mean???

**Comment by ardakurucim** [comment]
you can code it with copy + paste.

**Comment by ilyn1337** [comment]
what is the difference??? i can't spot any differences, only fps text? seems legit. also what is the issue????

**Comment by ardakurucim** [comment]
@ilyn1337's right

**Comment by NotDK** [comment]
@ilyn1337 no u stupid ass, this is for showing surekingigtps on how to make a gtps like a boss...

**Comment by OverallGod** [comment]
I wish github had a age requirement. 
But that probably wouldn't stop anything.

**Comment by ritzysw** [comment]
XDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD did u legit fucking make this shit in paint?
there is no such fps text in real gt, u legit fucking forgot to copy paste leaderboards button, scroll button on top of inventory is too huge
"listen, why cant u be smart as i am..."

**Comment by royallz** [comment]
LMAOOOOOOOOOOO he removed the photo

**Comment by ilyn1337** [comment]
@NotDK i can still see the photo sir
