### ISSUE TITLE
A Gift for SureKingIGTPS

### ISSUE THREAD

**Issue by NotDK** [GrowtopiaNoobs/GrowtopiaServer#586]
First off, gobble up a dick, let that dick flow through ur brain, let it function ur purposes for technology. wait 12 weeks, and we still know ur a blockhead cunt.

so..... the kid who asked for codes... half way through the repository... asked for codes about 1.7 Billion times.

does he know how to code?
he doesnt, he asks and begs for it. lol!

mental asf and cant code for shit! hope it helped u alot!!!

**Comment by DrOreo002** [comment]
Man calm down, he's just a 9 yr kid. It's normal

**Comment by GrowtopiaNoobs** [comment]
This issue have zero value, only hate speech. This won't really help with anything...
Closing.
