### ISSUE TITLE
Is it possible to host a Growtopia Private Server in my system?

### ISSUE THREAD

**Issue by NoobesGT** [GrowtopiaNoobs/GrowtopiaServer#587]
Is it possible to host a Growtopia Private Server in my system? Like with XXAMP will work?

I'll be very happy if someone told me!

**Comment by NotDark** [comment]
> Is it possible to host a Growtopia Private Server in my system? Like with XXAMP will work?
> 
> I'll be very happy if someone told me!

what system

**Comment by NoobesGT** [comment]
I mean in my host

**Comment by fargamerhd** [comment]
well why not ? just open the port and hast it as any vps..

**Comment by ardakurucim** [comment]
@NoobesGT But be careful you can be ddosed easily

**Comment by GrowtopiaNoobs** [comment]
If you have PC with Windows 7/8/10, maybe XP can work too, then yes.
You will also need public IPv4 to make server accessible for everyone.

**Comment by NoobesGT** [comment]
@GrowtopiaNoobs i need you help.. Do you have discord to show me?

**Comment by Mempler** [comment]
Sorry, this is not a forum for asking help on how to run something on your computer. If you want to know
how to run something on your Computer, then i would consider you to get used to your Computer.

**Comment by NoobesGT** [comment]
Sorry scum but here everyone can ask what they want

**Comment by Mempler** [comment]
Excuse me ? This place is not meant to ask those questions, This is the issues tab where we only allow issues related to our code, including bugs crashes etc! if you continue being an toxic guy, we have to block you out of our Repository which means you wont have any access to our Issues anymore!

**Comment by NoobesGT** [comment]
You think that if you made 1 command in this private server you are the b3st coder ever?

**Comment by NoobesGT** [comment]
go kys and stop threatening b1tch

**Comment by DrOreo002** [comment]
lmao calm down
