### ISSUE TITLE
[QUESTION] How can i get input on diaglog request?

### ISSUE THREAD

**Issue by ardakurucim** [GrowtopiaNoobs/GrowtopiaServer#588]
Look up.

**Comment by NotDark** [comment]
add_text_input|

**Comment by ardakurucim** [comment]
@NotDark thank you one more question how can i use answer like str.substr?

**Comment by ritzysw** [comment]
when you use dialog with "add_text_input" client sends dialog_return action packet with name of that input and value of it, u dont need to use substring

**Comment by ardakurucim** [comment]
@ritzysw @NotDark thank u so much.
