### ISSUE TITLE
Hey how to i download gt bot

### ISSUE THREAD

**Issue by ZentaiZber** [GrowtopiaNoobs/GrowtopiaServer#589]
Give me gt bot pls.

**Comment by ilyn1337** [comment]
this is growtopia server not bot, go find correct repo first

**Comment by ZentaiZber** [comment]
-_- idk why someone in here say gt bot?

**Comment by ilyn1337** [comment]
?????????????????????????????????????????????????????????????????????????????????

**Comment by ZentaiZber** [comment]
someone in here say gt bot, and i dont know what is gt bot.

**Comment by GrowtopiaNoobs** [comment]
Here it is https://github.com/GrowtopiaNoobs/Growtopia-Bot

**Comment by SurekingIGTPS** [comment]
> Here it is https://github.com/GrowtopiaNoobs/Growtopia-Bot

It's for Now version growtopia working?
