### ISSUE TITLE
Connecting error...

### ISSUE THREAD

**Issue by RU15** [GrowtopiaNoobs/GrowtopiaServer#59]
My friend again have someone problem... He have Timed out after Located server, connecting.
But server_data is correct...
My server_data:
`server|82.131.34.184 port|17001 type|1 #maint|Server is under maintenance. We will be back online shortly. Thank you for your patience! beta_server|82.131.34.184 beta_port|17001 beta_type|1 meta|localhost RTENDMARKERBS1001`
Please help, again...

**Comment by GrowtopiaNoobs** [comment]
You need to edit python script and not server_data.php.

**Comment by RU15** [comment]
Thank you! It's works.
