### ISSUE TITLE
Vds

### ISSUE THREAD

**Issue by xDemirHD** [GrowtopiaNoobs/GrowtopiaServer#590]
I hired a vds.
Forwarded ports from firewall.
Opened run.py

Still cannot play in ios

**Comment by GrowtopiaNoobs** [comment]
More details are needed:
- Can't play only in ios or other os too?
- Can you access web server? If you can't access web server then copy output of py app.
- Is exe server running, are there any error messages?

**Comment by ardakurucim** [comment]
@xDemirHD try changing enet host on cpp file

**Comment by xDemirHD** [comment]
Resolved
