### ISSUE TITLE
Help! How to load state

### ISSUE THREAD

**Issue by ZentaiZber** [GrowtopiaNoobs/GrowtopiaServer#595]
How to load state? if we have double jump, state = 2 and i save to file and if i enter world state to 2

**Comment by NotDark** [comment]
try save ((PlayerInfo*)(peer->data))->canDoubleJump   (true/false thing)

and when login 

load file here and make if candoublejump thing in your json file == true thing and use this
((PlayerInfo*)(peer->data))->canDoubleJump = true;
sendState(peer);

**Comment by ZentaiZber** [comment]
> try save ((PlayerInfo*)(peer->data))->canDoubleJump (true/false thing)
> 
> and when login
> 
> load file here and make if candoublejump thing in your json file == true thing and use this
> ((PlayerInfo*)(peer->data))->canDoubleJump = true;
> sendState(peer);

I think not work because state when reenter gone -_-

**Comment by NotDark** [comment]
> > try save ((PlayerInfo*)(peer->data))->canDoubleJump (true/false thing)
> > and when login
> > load file here and make if candoublejump thing in your json file == true thing and use this
> > ((PlayerInfo*)(peer->data))->canDoubleJump = true;
> > sendState(peer);
> 
> I think not work because state when reenter gone -_-

then try put to where enter world

**Comment by ZentaiZber** [comment]
> > > try save ((PlayerInfo*)(peer->data))->canDoubleJump (true/false thing)
> > > and when login
> > > load file here and make if candoublejump thing in your json file == true thing and use this
> > > ((PlayerInfo*)(peer->data))->canDoubleJump = true;
> > > sendState(peer);
> > 
> > 
> > I think not work because state when reenter gone -_-
> 
> then try put to where enter world

Where??

**Comment by NotDark** [comment]
> > try save ((PlayerInfo*)(peer->data))->canDoubleJump (true/false thing)
> > and when login
> > load file here and make if candoublejump thing in your json file == true thing and use this
> > ((PlayerInfo*)(peer->data))->canDoubleJump = true;
> > sendState(peer);
> 
> I think not work because state when reenter gone -_-

then try put to where enter world

> > > > try save ((PlayerInfo*)(peer->data))->canDoubleJump (true/false thing)
> > > > and when login
> > > > load file here and make if candoublejump thing in your json file == true thing and use this
> > > > ((PlayerInfo*)(peer->data))->canDoubleJump = true;
> > > > sendState(peer);
> > > 
> > > 
> > > I think not work because state when reenter gone -_-
> > 
> > 
> > then try put to where enter world
> 
> Where??

search You have exited the world. and put above that

**Comment by NotDark** [comment]
![image](https://user-images.githubusercontent.com/44568476/59838006-cd3dff00-9380-11e9-84cb-6353d90983e6.png)

**Comment by ZentaiZber** [comment]
Hmm okay i will try it :)

**Comment by ZentaiZber** [comment]
Not Work -_-

**Comment by ZentaiZber** [comment]
wait the minute so i put only this?
`if (((PlayerInfo*)(peer->data))->doubleJump == true) {
			((PlayerInfo*)(peer->data))->canDoubleJump = true;
			sendState(peer);
		}`
