### ISSUE TITLE
Bug on load gems

### ISSUE THREAD

**Issue by ZentaiZber** [GrowtopiaNoobs/GrowtopiaServer#596]
hey im having bug on load gems when i change account the current account not load but show the first account.

**Comment by NotDark** [comment]
> hey im having bug on load gems when i change account the current account not load but show the first account.

no really bug you need use onsetbux to make the gem show in the gem icon

**Comment by ZentaiZber** [comment]
> > hey im having bug on load gems when i change account the current account not load but show the first account.
> 
> no really bug you need use onsetbux to make the gem show in the gem icon

Thx you sorry im new at c-- :v
