### ISSUE TITLE
How to make argument on action|input

### ISSUE THREAD

**Issue by ZentaiZber** [GrowtopiaNoobs/GrowtopiaServer#597]
Guys how to make a arguments like

> if (str == "/gay") {
>     if (args[0]) {
>         cout << "No Arguments!!" << endl;
>      } else {
>         cout << "Argument: " << args << endl;
>      }

/gay
Output:
`No Arguments!!`
/gay you
Output:
`Argument: you`

**Comment by playingo** [comment]
sendConsoleMsg with the string. should be given in /invis already.
