### ISSUE TITLE
Clothing, Registering and etc.

### ISSUE THREAD

**Issue by Yasinan** [GrowtopiaNoobs/GrowtopiaServer#6]
Why clothing won't work but in your video the clothing work and the registering won't work too.
btw where does the coredata.txt located in the source code or where can I put the coredata

**Comment by ritzysw** [comment]
[https://github.com/Nenkai/GrowtopiaItemDatabase/blob/master/GrowtopiaItemDatabase/CoreData.txt](url)
this is the link to coredata,txt (it's needed to load up all items data), just put it in your core folder of the server and clothes will be fixed

**Comment by Yasinan** [comment]
Core folder of the server wdym? Folder of source code or folder of server. If you mean folder of server how do I put the coredata.txt in the server

**Comment by Yasinan** [comment]
ok sorry im so dumb xd i thought the server has an own file inside xd
