### ISSUE TITLE
Yo how to make delay

### ISSUE THREAD

**Issue by ZentaiZber** [GrowtopiaNoobs/GrowtopiaServer#601]
hey how to make delay if we punch a block it will delay like 10 seconds to get the break Gems

**Comment by NotDark** [comment]
try see /sb code

**Comment by ZentaiZber** [comment]
what do you mean?

**Comment by NotDark** [comment]
> what do you mean?

look at the command /sb code here
the part "Wait a minute before using the SB command again" thing

**Comment by ZentaiZber** [comment]
kk thx you
