### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by arshizx** [GrowtopiaNoobs/GrowtopiaServer#603]
https://gyazo.com/8ad12f2a40891d20a3f8fbad090527eb

What \nadd_ is this? and usage thx

**Comment by NotDark** [comment]
> https://gyazo.com/8ad12f2a40891d20a3f8fbad090527eb
> 
> What \nadd_ is this? and usage thx

\nadd_button_with_icon

**Comment by arshizx** [comment]
@NotDark nope https://gyazo.com/f2e2159dd2105eba7e1bb6b8522183b

**Comment by NotDark** [comment]
> @NotDark nope https://gyazo.com/f2e2159dd2105eba7e1bb6b8522183b

\nadd_button_with_icon|testname|LABEL ITEM|staticBlueFrame|2|111|

**Comment by arshizx** [comment]
@NotDark Thank You So Much :)
