### ISSUE TITLE
How to save all .json mtfk

### ISSUE THREAD

**Issue by ZentaiZber** [GrowtopiaNoobs/GrowtopiaServer#604]

**Comment by NotDark** [comment]
> _No description provided._

change the json name to

((PlayerInfo*)(currentPeer->data))->rawName+".json"

**Comment by ZentaiZber** [comment]
example me more i lazy to experiment haha i need instant

**Comment by NotDark** [comment]
ENetPeer * currentPeer; 
 for (currentPeer = server->peers;
 currentPeer < &server->peers[server->peerCount];
 ++currentPeer)
 {
 if (currentPeer->state != ENET_PEER_STATE_CONNECTED)
 continue;
 
here your save code
change the name part to ((PlayerInfo*)(currentPeer->data))->rawName+".json"

}

**Comment by ZentaiZber** [comment]
kk thx you

**Comment by ZentaiZber** [comment]
is only save online user and how the offline user??

**Comment by NotDark** [comment]
> is only save online user and how the offline user??

yes only save online user and Why do you need save offline user? just save when he be offline

**Comment by ZentaiZber** [comment]
> > is only save online user and how the offline user??
> 
> yes only save online user and Why do you need save offline user? just save when he be offline

Uh me need save all folder in players like worlds

**Comment by ZentaiZber** [comment]
because if i add like isBanned in my code if a user try login it will crash:(

**Comment by NotDark** [comment]
you need add that to your json file or just try this

if (j.count("isBanned") == 1) { // if found you load
((PlayerInfo*)(Peer->data))->ban = j["isBanned"];
 } 	else {
((PlayerInfo*)(Peer->data))->ban = 0;
 }

**Comment by ZentaiZber** [comment]
kk thx you very much :)
