### ISSUE TITLE
XAMPP

### ISSUE THREAD

**Issue by xDemirHD** [GrowtopiaNoobs/GrowtopiaServer#607]
How to use xampp step by step?

**Comment by ilyn1337** [comment]
2 clicks

**Comment by NotDark** [comment]
> How to use xampp step by step?

install xampp and click the start button in the apache row 

open htdocs folder in xampp and make new folder name growtopia and put server_data.php inside

**Comment by xDemirHD** [comment]
Well I didn’t run as administrator so I couldn’t do it. Thanks anyway.

@NotDark
@ilyn1337
