### ISSUE TITLE
Weather and pass.

### ISSUE THREAD

**Issue by RU15** [GrowtopiaNoobs/GrowtopiaServer#61]
Hi! How to change weathers in worlds, is it possible? And how to change pass in file? I have 1 time when my friend forgot pass...

**Comment by FocusedSG** [comment]
Send setweather packet to currentpeer

**Comment by Dunzap** [comment]
> Hi! How to change weathers in worlds, is it possible? And how to change pass in file? I have 1 time when my friend forgot pass...

I have no idea too. its just a bunch of random letters

**Comment by willi123yao** [comment]
The passwords are hashed, so it is impossible to retrieve the password back. Since you need to hash the password first before saving it in the file, your best bet is delete his player file and ask him to recreate his GrowID again.

**Comment by PixelTheGreat** [comment]
i suggest if you don't want it to be hashed, remove all sha256 functions

**Comment by willi123yao** [comment]
Weather command has been added into the main code, please update to the latest code and refer to the latest commit if you want the actual code.
