### ISSUE TITLE
Bad Url

### ISSUE THREAD

**Issue by xDemirHD** [GrowtopiaNoobs/GrowtopiaServer#610]
When I try to login I get Bad Url thing.
• Hash updated

• iOS and PC are working only Android is broken

• That’s All

**Comment by MacaylaMarvelous81** [comment]
maybe your hosts file is wrong?

**Comment by willi123yao** [comment]
Please make sure that your server configuration is correct and you have followed the instruction on the wiki. Do also use the latest update from the repository to ensure everything is updated and correct.

Closing this issue as it seems inactive/resolved.
