### ISSUE TITLE
After Log Part

### ISSUE THREAD

**Issue by xDemirHD** [GrowtopiaNoobs/GrowtopiaServer#611]
Which part is the “after login” part?
I mean the actions which are triggered after logging in?

**Comment by NotDark** [comment]
> Which part is the “after login” part?
> I mean the actions which are triggered after logging in?

action|enter_game

**Comment by xDemirHD** [comment]
Thanks

**Comment by willi123yao** [comment]
Closing this issue as it seems to be resolved and/or is inactive.
