### ISSUE TITLE
Help me?

### ISSUE THREAD

**Issue by ZentaiZber** [GrowtopiaNoobs/GrowtopiaServer#612]
what is code if tree ready to harvest?

**Comment by playingo** [comment]
wow another indog? u won't get code here, and to harvest something, use sendDrop with punch coordinates. we will never share code here.

**Comment by ZentaiZber** [comment]
not this i mean nob

**Comment by ZentaiZber** [comment]
it will drop item without wait to ready to harvest wtf ??
