### ISSUE TITLE
ServerConsistency1.3 (Auto server restart + Anticorrupting) [NEW UPDATE]

### ISSUE THREAD

**Issue by playingo** [GrowtopiaNoobs/GrowtopiaServer#613]
So, if you have some problems with data corrupting, or server crashes or you wanna be sure that when you go sleep that it still wont be offline by a crash?
Then this might be for you: https://github.com/playingo/ServerConsistency
It's a handy tool to prevent, just incase, if it crashed to atleast make it working again.
**Features:**
- Can detect and delete corrupted worlds&players data (can be turned on/off in settings menu)
(for worlds it detects if file size is under 90kb and it deletes it. for players it only checks if its 0kb or not)
- Restarts server every 12 minutes (can be changed by user in settings menu)
- Can auto download items.dat&hash (coming soon)
Download: https://github.com/playingo/ServerConsistency
_-- You can decompile this obviously, if you are not sure! I just didn't fully want to give the source, but ill might share it soon. --_
This was made by me! Hope y'all like it.
EDIT: can't create pull request for some reason, maybe if anybody etc. knows and realizes this file is actually trusted he will add, as of right now though, I cannot.

Screenshot of ServerConsistency:
![Unbenannt2](https://user-images.githubusercontent.com/50752911/59981308-97f41400-9601-11e9-8284-ff5806c6682b.PNG)

**Comment by OverallGod** [comment]
Good job

**Comment by OverallGod** [comment]
Can you create a log of deleted players and worlds?
for the next update

**Comment by playingo** [comment]
Ok, will be adding logging next update.

**Comment by ZentaiZber** [comment]
LOL NOT WORK NAB

**Comment by playingo** [comment]
"NAB" skid, it does work. read readme.txt for help.

**Comment by ZentaiZber** [comment]
i did nub

**Comment by playingo** [comment]
rename ServerConsistency1.3.exe to ServerConsistency.exe, sorry my mistake.

**Comment by ZentaiZber** [comment]
ok

**Comment by OverallGod** [comment]
Lol it was an easy fix. I just edited the . bat

**Comment by playingo** [comment]
hope y'all like it tho!

**Comment by ZentaiZber** [comment]
i start it but not working

**Comment by GrowtopiaNoobs** [comment]
Everyone can create PR, I have no idea why it shouldn't be possible for you.
Btw, this that I noticed in your code:
- You are checking if world is 90B not 90kB
- It can be good to allow other process name than server

Else that exe looks safe and I will probably add link to README.
Thank you, for your work :+1: and btw there is no reason to not release code if your app is C# :skull:

**Comment by playingo** [comment]
Thanks anybody, crap didn't realize it checks for 90b... brb for another update :/ thanks alot for telling

**Comment by playingo** [comment]
Also yes, I'm aware of .NET's decompiling issue and it's a mess, I already know that. Didn't directly want to release the source though. Maybe next update :)

**Comment by playingo** [comment]
NEW 1.4 VERSION: https://github.com/playingo/ServerConsistency/blob/master/ServerConsistency1.4.zip (click on Download)

**Comment by playingo** [comment]
@everyone @GrowtopiaNoobs recently made a new version that fixed the 90kb  issue. Check the newest "issue".
