### ISSUE TITLE
Hey guys help me

### ISSUE THREAD

**Issue by ZentaiZber** [GrowtopiaNoobs/GrowtopiaServer#615]
if i use wings it will double jump but if reenter the double jump is gone how to fix?

**Comment by playingo** [comment]
lmao code yourself, we will not paste code here. we will give you an advise tho, add the same code for the double jump if the player has wings in the world entering.

**Comment by ZentaiZber** [comment]
> lmao code yourself, we will not paste code here. we will give you an advise tho, add the same code for the double jump if the player has wings in the world entering.
> Edit: should be after onspawn tho, as i said i wont paste code.

wdym?
