### ISSUE TITLE
XAMPP issue

### ISSUE THREAD

**Issue by flossboss** [GrowtopiaNoobs/GrowtopiaServer#616]
I installed XAMPP, Run as ADMINISTRATOR, enabled APACHE, added server_data.php but players still can't join. If you can help me hmu on discord: Steak#0703

**Comment by fargamerhd** [comment]
did u even opened the ports ???before the xampp

**Comment by flossboss** [comment]
Yes

**Comment by flossboss** [comment]
Server can be run perfectly using run.py but not with XAMPP @fargamerhd
