### ISSUE TITLE
[HELP] How can i check blocks like signal jammer on or off?

### ISSUE THREAD

**Issue by ardakurucim** [GrowtopiaNoobs/GrowtopiaServer#617]
Up

**Comment by playingo** [comment]
no codes.

**Comment by ardakurucim** [comment]
@playingo can't i check?

**Comment by ardakurucim** [comment]
@playingo i didnt ask for codes

**Comment by NotDark** [comment]
you need find how to do that but i dont help because i dont know too

**Comment by playingo** [comment]
search jammer item id and check if it was hit and then change world properties, the rest u can figure out urself everything is given in the template

**Comment by iProgramMC** [comment]
BlockState is a good hint.

**Comment by ardakurucim** [comment]
forgot to close lol its like blockvisual
