### ISSUE TITLE
How to fix localhost already found

### ISSUE THREAD

**Issue by Dunzap** [GrowtopiaNoobs/GrowtopiaServer#62]
Is this a bug? 
i cant get in and im thinking if this is  the problem
(I have updated the enet server ccp to V2.984)

HOW DO I FIX IT? ANY SOLUTIONS?

**Comment by DrOreo002** [comment]
The error literally said it all

**Comment by Dunzap** [comment]
> The error literally said it all

How do I fix it? Any solution

**Comment by If1is1then** [comment]
k
