### ISSUE TITLE
Should be /nick merged?

### ISSUE THREAD

**Issue by GrowtopiaNoobs** [GrowtopiaNoobs/GrowtopiaServer#621]
I think that #620 is good piece of code, but I am not sure if it won't be problem for some players - breaking some gameplay. React with thumb up or down emoji, so I know if more people want merge or not. Or you can give suggestion how to change it, so it won't break gameplay.

**Comment by ilyn1337** [comment]
@GrowtopiaNoobs change:
```cpp
GamePacket p3 = packetEnd(appendString(appendString(createPacket(), "OnNameChanged"), nam1e));
```
to:
```cpp
GamePacket p3 = packetEnd(appendString(appendString(createPacket(), "OnNameChanged"), nam1e + "``````"));
```
Why?
Cause if your nick is TorBob and you changed it to LOL, your nick will disappear. If you added 5+ '\`' char, LOL will be still visible.

**Comment by MeNoFade** [comment]
@ilyn1337 
This is fixed, no?
string nam1e = "```0" + str.substr(6, cch.length() - 6 - 1);
![image](https://user-images.githubusercontent.com/44878241/60167603-115f5280-980c-11e9-8bbd-b6098d6af66a.png)

**Comment by GrowtopiaNoobs** [comment]
@ilyn1337 @MeNoFade Tell me if I should use fix form @ilyn1337 and I will merge PR.

**Comment by OverallGod** [comment]
Bruh

**Comment by GrowtopiaNoobs** [comment]
Closing this as PR has been merged.
