### ISSUE TITLE
File

### ISSUE THREAD

**Issue by xDemirHD** [GrowtopiaNoobs/GrowtopiaServer#622]
When I try to login in PC or Android it gives an error like

Server gave a 404. File not found.. kinda

How to resolve this problem..?

**Comment by iRestartz** [comment]
Join Real GT First

**Comment by xDemirHD** [comment]
@iRestartz wdym?

**Comment by GrowtopiaNoobs** [comment]
Check if your web server is correctly configured.

**Comment by xDemirHD** [comment]
@GrowtopiaNoobs well, it is.
I use xampp

**Comment by Yoayao** [comment]
setup firewall

**Comment by xDemirHD** [comment]
@Yoayao can I have your discord..?

**Comment by willi123yao** [comment]
Closing issue as it seems inactive/resolved.
