### ISSUE TITLE
Crashing enet 

### ISSUE THREAD

**Issue by moanhawks** [GrowtopiaNoobs/GrowtopiaServer#625]
![Screenshot_2019-06-26-14-27-44-30](https://user-images.githubusercontent.com/52075701/60156287-c69b0600-981e-11e9-828a-0bb0bbcb58b0.png)

Who know how to fix this and what is that mean?

**Comment by GrowtopiaNoobs** [comment]
Please click at stack frame and show me what it shows.

**Comment by moanhawks** [comment]
Can dm me on discord 
Cactus++#9503

**Comment by herothedev** [comment]
That crashing isn't enet problem, it is OS problem.

**Comment by willi123yao** [comment]
Closing this issue as it seems inactive/resolved.
