### ISSUE TITLE
Can U give me Code Door mover? Pls Help

### ISSUE THREAD

**Issue by MENOOBS** [GrowtopiaNoobs/GrowtopiaServer#626]
Help me

**Comment by fargamerhd** [comment]
DONT ASK FOR CODES!!!

**Comment by moanhawks** [comment]
Sudice self then say to god "God can give me door mover code"

**Comment by NotDark** [comment]
> Help me

just try if you put door mover and where you put the door mover will set to white door

**Comment by willi123yao** [comment]
Please do not just ask for codes here, it would be great to provide and show what you have tried and done to resolve this issue and implement the door mover. This is also more of a feature request than an issue directly related to the repository code.

Closing this as it seems inactive/resolved.
