### ISSUE TITLE
release | Private server installer

### ISSUE THREAD

**Issue by niko1802** [GrowtopiaNoobs/GrowtopiaServer#628]
im lazy as hell so i made this app that installs the private server files for you

https://github.com/niko1802/GrowtopiaPrivateServerInstaller

it might be useful for some people here so i thought i would share it

https://i.gyazo.com/54cc9895fc54c869cf72598c064f4b55.mp4

**Comment by MarmoriPelaa** [comment]
Please open a pull request. This is not an issue, but rather and improvement.

**Comment by GrowtopiaNoobs** [comment]
Repository doesn't exists anymore. Closing.
