### ISSUE TITLE
How to make signs and doors labels working?

### ISSUE THREAD

**Issue by mar4ello6** [GrowtopiaNoobs/GrowtopiaServer#629]
What to use or what I should do to make labels working?

**Comment by NotDark** [comment]
> What to use or what I should do to make labels working?

only thing i can tell you 

that is hard make it work you need memcpy

**Comment by playingo** [comment]
you need new offsets but for now you could do something crappy like OnTextBubble or OnTextOverlay stuff. No codes!

**Comment by mar4ello6** [comment]
@playingo Made it already without offsets, OnTextBuuble and OnTextOverlay! Now I have signs as in real GT... But some signs are empty or they crash GT...
