### ISSUE TITLE
Bug with player after quit/leave from world

### ISSUE THREAD

**Issue by MeNoFade** [GrowtopiaNoobs/GrowtopiaServer#63]
Hello Growtopia Noobs.
Can you say, please, how to fix bug, when some player leave world, but his model stay on world for other players. Screen:
![image](https://user-images.githubusercontent.com/44878241/48220501-80348c00-e3a0-11e8-9c25-f06f51005b55.png)

**Comment by NotDark** [comment]
i want to fix too but idk how

**Comment by FocusedSG** [comment]
Something to do with sendplayerleave
