### ISSUE TITLE
How to fix?

### ISSUE THREAD

**Issue by MENOOBS** [GrowtopiaNoobs/GrowtopiaServer#635]
#Help

**Comment by MENOOBS** [comment]
Me dont know code Door move

**Comment by OverallGod** [comment]
KYS

**Comment by NotDark** [comment]
> #Help

fix what

**Comment by ardakurucim** [comment]
lol fix what

**Comment by playingo** [comment]
the indog probably meant how to fix his brain i am not sure

**Comment by willi123yao** [comment]
Please be more specific on what do you need help with and if possible provide relevant evidences/code snippets so that we can help you on this.

Closing as this issue seems resolved and is inactive.
