### ISSUE TITLE
Using Da Vinci Wings? [help]

### ISSUE THREAD

**Issue by playingo** [GrowtopiaNoobs/GrowtopiaServer#639]
alright so I assume you need the newest CoreData.txt (that I couldn't find anywhere) to make it working properly. Any help?

**Comment by MeNoFade** [comment]
Make by you'r self. Ids and names from Item Dumper or something else. Other from CoreData.
![image](https://user-images.githubusercontent.com/44878241/60366643-c9e7ea80-99f4-11e9-813c-a2103874b9ea.png)

**Comment by playingo** [comment]
yo how bout you'll share the coredata w/me (and maybe everyone else whos interested in it) since i do not like to trust third party applications. it would be just nice!

**Comment by playingo** [comment]
@MeNoFade

**Comment by OverallGod** [comment]
@playingo Here because you don't beg. (I think)
https://github.com/OverallGod/GrowtopiaItemDatabase/blob/master/GrowtopiaItemDatabase/CoreData.txt

**Comment by playingo** [comment]
Thanks alot, @OverallGod.
