### ISSUE TITLE
Need help!

### ISSUE THREAD

**Issue by If1is1then** [GrowtopiaNoobs/GrowtopiaServer#64]
I need help on "record growtopia1.com to localhost already found!"
I followed the basic setup from the wiki and downloaded items.dat and server.exe.
I also ran as admin for putting 127.0.0.1 growtopia1.com *IP address correct*

What should i do to solve
> Record growtopia1.com to localhost already found!

**Comment by HelpmeHelpyous** [comment]
it doesnt work

**Comment by GrowtopiaNoobs** [comment]
> Record growtopia1.com to localhost already found!
This is not issue. It means that there is already stored record for growtopia1.com
