### ISSUE TITLE
Wrench Issue

### ISSUE THREAD

**Issue by NoobesGT** [GrowtopiaNoobs/GrowtopiaServer#642]
I havr seen that when i want to wrench someone it shows mine. How can i solve it?

**Comment by NotDark** [comment]
> I havr seen that when i want to wrench someone it shows mine. How can i solve it?

https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/master/enet%20server%20test/enet%20server%20test.cpp#L2249
if (currentPeer = peer){
// show yourself
}
else{
// show other
}

**Comment by NoobesGT** [comment]
thx
