### ISSUE TITLE
Sleep not work? why always disconnect?

### ISSUE THREAD

**Issue by ZentaiZber** [GrowtopiaNoobs/GrowtopiaServer#643]

**Comment by NotDark** [comment]
> _No description provided._

items.dat hash need change

**Comment by ZentaiZber** [comment]
i need change? to make sleep/delay cant disconnecting game?

**Comment by playingo** [comment]
lol, well the thing is if you sleep your server, using chrono for example, obviously the whole program freeze...
if you want to make delayed actions for each player, you may want to throttle the peer's connection for some seconds, or use threading (the most recommended way for timed stuff like respawning, but a little harder to setup, and i believe its not needed really in a private server except your that one who wants to replicate the whole growtopia server, I would strongly recommend to firstly change the half of the code anybody made to firstly setup subservers.)

**Comment by LeaveGT** [comment]
Did you edit the CPP yet if not its the world folder, if you got a VPS its world folder issue its only 80 MB or less in the world folder and my VPS is more memory so i get more worlds i think If thats not it its your save.dat or Update hash

**Comment by LeaveGT** [comment]
Item.dat*

**Comment by ZentaiZber** [comment]
not this i mean @LeaveGT and @NotDark, Thx @playingo
