### ISSUE TITLE
I need help with /warn. Please contact me i need /warn codes! Orbit #4682 on discord

### ISSUE THREAD

**Issue by Orbit4682** [GrowtopiaNoobs/GrowtopiaServer#647]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Stack frame**
If server crashed, then attach screenshot of stack frame and screenshot of code in `enet server test.cpp` where server crashed.

**Server environment (please complete the following information):**
 - OS: [e.g. Windows 7]
 - Experience: [e.g. never launched server; beginner; advanced]
 - Modifications [e.g. none; few changed lines; big changes]

**Client environment (please complete the following information):**
 - Growtopia version: [e.g. V2.91]

**Additional context**

**Comment by arshizx** [comment]
wth its not bug

**Comment by playingo** [comment]
lol, we will not give codes.

**Comment by LeaveGT** [comment]
hmm idk about /warn, but i have /warn code but who nows it works LOL

**Comment by Orbit4682** [comment]
> hmm idk about /warn, but i have /warn code but who nows it works LOL

Can you please send me the /warn codes. I really appreciate if you do. 👍

**Comment by ZentaiZber** [comment]
`if (str.substr(0, 6) == "/warn ") {
    //Code
}`

**Comment by Hades3235** [comment]
lmao sureking goes you come

**Comment by Hades3235** [comment]
You asked for code,you should instead ask for help

**Comment by willi123yao** [comment]
We do not give out free codes here, please either request for help and show what have you tried or done to implement your requested features.

Closing this issue as it seems inactive/resolved.
