### ISSUE TITLE
[QUESTION] How can i make an action on a OnDialogRequest? Like for ban. I click on "BAN" button and the player gets banned

### ISSUE THREAD

**Issue by NoobesGT** [GrowtopiaNoobs/GrowtopiaServer#648]
Can Someone Tell Me?

**Comment by NotDark** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/master/enet%20server%20test/enet%20server%20test.cpp#L2425

example

OnDialogRequest
\nadd_button|banbutton|`4Ban|noflags|0|0|


```C++
if(btn == "banbutton"){

//ban 

}```

**Comment by NoobesGT** [comment]
@NotDark do you have discord? if yes give it to me, need to ask smt

**Comment by SurekingIGTPS** [comment]
if you need make Button command just add if(btn == ''NameCommand''){
I hope it's helping you
