### ISSUE TITLE
Can Give Gem system code?

### ISSUE THREAD

**Issue by DarkFlips** [GrowtopiaNoobs/GrowtopiaServer#649]
i need Gem system code .
Like If break block get gems
Who have the code?
Can give it to me ?

**Comment by playingo** [comment]
No codes, never. Do it yourself.

**Comment by playingo** [comment]
We can only give hints like OnSetBux (is the packet called to visually change gems, not server sidedly though.) server sidedly you gotta think of something, i recommend binary for that

**Comment by NotDark** [comment]
> i need Gem system code .
> Like If break block get gems
> Who have the code?
> Can give it to me ?


https://github.com/GrowtopiaNoobs/GrowtopiaServer/pull/221/files

**Comment by ardakurucim** [comment]
Its not a bug lol

**Comment by LeaveGT** [comment]
Gem System is not a code its all overt the CPP or if you need gems make a Sets Folder and select your player name and see how much gems u need but if you mean Like Ex: SB is 500 Gems thats a Bux / Gem system i can give to you add me on discord 

Binlk HEE#7300

**Comment by LeaveGT** [comment]
Unless its a VoidSendBux..... MAYBE?!

**Comment by DarkFlips** [comment]
What name ur discord? HEE#7300 is wrong
Just add my Discord FlyFlips#9628
I need code like sb is 500gems

**Comment by willi123yao** [comment]
I would like to reinstate that this is not a platform for you to request for codes, please only request for help by showing what you have already done or tried and would like to know where have you gone wrong/need more help with.

Closing this issue as it seems inactive/resolved.
