### ISSUE TITLE
[QUESTION] Bad characters on name

### ISSUE THREAD

**Issue by NoobesGT** [GrowtopiaNoobs/GrowtopiaServer#651]
Sorry for asking for codes, ik how to make this. By bad characters i mean including "@", "`"; "#" etc.
But when i made this and tried to make an account, i broke it.  Thx. I tried this, but its broken.
```C++
if (username.find("`")) return -2;
if (username.find("@")) return -2;
if (username.find("~")) return -2;
if (username.find("!")) return -2;
if (username.find("#")) return -2;
if (username.find("$")) return -2;
if (username.find("^")) return -2;
if (username.find("&")) return -2;
```

**Comment by NotDark** [comment]
> Sorry for asking for codes, ik how to make this. By bad characters i mean including "@", "`"; "#" etc.
> But when i made this and tried to make an account, i broke it. Thx. I tried this, but its broken.
> 
> ```c++
> if (username.find("`")) return -2;
> if (username.find("@")) return -2;
> if (username.find("~")) return -2;
> if (username.find("!")) return -2;
> if (username.find("#")) return -2;
> if (username.find("$")) return -2;
> if (username.find("^")) return -2;
> if (username.find("&")) return -2;
> ```

    https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/master/enet%20server%20test/enet%20server%20test.cpp#L660 already remove for you now 

try do to here https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/master/enet%20server%20test/enet%20server%20test.cpp#L3217

**Comment by NoobesGT** [comment]
> > Sorry for asking for codes, ik how to make this. By bad characters i mean including "@", "`"; "#" etc.
> > But when i made this and tried to make an account, i broke it. Thx. I tried this, but its broken.
> > ```c++
> > if (username.find("`")) return -2;
> > if (username.find("@")) return -2;
> > if (username.find("~")) return -2;
> > if (username.find("!")) return -2;
> > if (username.find("#")) return -2;
> > if (username.find("$")) return -2;
> > if (username.find("^")) return -2;
> > if (username.find("&")) return -2;
> > ```
> 
> https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/master/enet%20server%20test/enet%20server%20test.cpp#L660 already remove for you
> try do to here https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/master/enet%20server%20test/enet%20server%20test.cpp#L3217

@NotDark i need ur discord

**Comment by playingo** [comment]
check tankIDName instead username.

**Comment by ZentaiZber** [comment]
if (username != PlayerDB::getProperName(username) return -2;
