### ISSUE TITLE
[QUESTION] Gems

### ISSUE THREAD

**Issue by noobesgt** [GrowtopiaNoobs/GrowtopiaServer#653]
How can I make like a shop and who bought something to get amount of gems from his database.

**Comment by OverallGod** [comment]
bruh

**Comment by SurekingIGTPS** [comment]
Please don't bullying,He just asking If you don't know just shut up if you know and you want help NoobesGT just help him, Keep it up NoobesGT!

**Comment by ardakurucim** [comment]
Wherever you are saving the gem system. Read there and decrease gems when player bought item

**Comment by Orbit4682** [comment]
> Wherever you are saving the gem system. Read there and decrease gems when player bought item

Hey can u help me with /warn and store system please i really want to help my friends create the server

**Comment by willi123yao** [comment]
It would be appreciated if you can show us what you have tried and done with your code and seek help to improve/solve the current problems/issues of your own code attempt from there. Blindly asking for codes will not get you anywhere and I would like to remind you again that this is not a platform for you to just ask for codes of features.

Closing this issue as it seems inactive/resolved.
