### ISSUE TITLE
[HELP] When adding growmoji to my code, which should I choose?

### ISSUE THREAD

**Issue by flossboss** [GrowtopiaNoobs/GrowtopiaServer#654]
![hmmmmm](https://user-images.githubusercontent.com/49786970/60444833-f6b22280-9beb-11e9-871a-b8b5ef4f89bb.PNG)

**Comment by ardakurucim** [comment]
Yes

**Comment by GrowtopiaNoobs** [comment]
Not 100% sure, but try yes.

**Comment by flossboss** [comment]
Also @growtopianoobs, when I downloaded the ZIP of the recent pr, i built it just fine without that popup but when i go in game and do (lol) i get Ä

**Comment by flossboss** [comment]
What should I do now?

**Comment by moanhawks** [comment]
Go suicide self

**Comment by flossboss** [comment]
Lmao why @moanhawks
Grammar is bad af. Don't wanna curse at you

**Comment by flossboss** [comment]
"g0 sulc1dE s3lF"

**Comment by GrowtopiaNoobs** [comment]
I won't help you much with your issue. I never done much stuff with growmojis, so I cant tell.

**Comment by flossboss** [comment]
Alright I'm closing this issue thanks @growtopianoobs
