### ISSUE TITLE
i wear level 5 ances and it seems like level 1 how can i fix it?

### ISSUE THREAD

**Issue by ardakurucim** [GrowtopiaNoobs/GrowtopiaServer#655]
i guess i couldn't tell when i wear level 5 ances it seems like level 1 how can i fix it?

**Comment by LeaveGT** [comment]
IDK but i can sell my CPP too you?

**Comment by ardakurucim** [comment]
@LeaveGT dont need for codes thank you i can code it myself

**Comment by willi123yao** [comment]
Closing this issue as it seems inactive/resolved. Also, please do not sell/buy code here as this is not the correct platform for you to do so.
