### ISSUE TITLE
How to stop "Entering world"?

### ISSUE THREAD

**Issue by playingo** [GrowtopiaNoobs/GrowtopiaServer#656]
![grafik](https://user-images.githubusercontent.com/50752911/60454055-21739980-9c33-11e9-86b5-f2dd30e9ce44.png)
So recently, I wanted to continue with the bus of the growtopia battle royale mode that I am coding, since the pvp / score stuff is already finished (yes I have successfully managed to detect if another player was punched). 
So, I wanted to make a bus but I wanted that when they jump, they will go out of the bus by setting their player position 2 blocks under the position they currently are. The problem is, I want to stop this "Entering world" thingie. I have already tried multiple string packets but none of them work. (I have tried OnZoomCamera, OnPlayPositioned, OnEnter, OnFailedToEnterWorld) and I've either not made it working or I couldn't even communicate with these packets since I do not completely know each and everything how to use them of each of them.
So if you could tell me how to fix it (I don't need code [still would be nice if you would give though], just a packet or some instruction would be enough for me).
If anyone is interested in this battle-royale mode idea (I've successfully made pvp, as I said) and wants to coorporate (I'll only take people who actually know something and/or helped me in this case), dm me on Discord: DiruX#4989, you can ofc tell me a proper fix/instruction directly in here.
## (yes, it uses an actual timer (server main code obv is independent from it since it can still run its own stuff and doesnt wait for stuff) to set the position no worries i am not using unpackPlayermoving stuff haha lol, oh goshh) ##

**Comment by ritzysw** [comment]
why would it show "entering world" in the first place if you are just simply teleporting players

**Comment by ritzysw** [comment]
![image](https://user-images.githubusercontent.com/43505497/60455600-7b7a5c00-9c3f-11e9-8282-9f7b4dbd740a.png)
"hey guys i can make a different thread"

**Comment by playingo** [comment]
@ritzysw why would it show "entering world" in the first place if you are just simply teleporting players
it does that because i stepped on the portal, and it doesnt go away. and yes it uses threading

**Comment by playingo** [comment]
@ritzysw like, do you get it? entering a portal is client sided and I do *not* know how to tell the client that he should abort visually trying the player to send him into the world

**Comment by playingo** [comment]
ALRIGHT guys, found it. It's OnFailedToEnterWorld (int) + (string) for some reason, have  fun with the packet you can use it for nuke etc aswell i guess.
