### ISSUE TITLE
Selling VPS

### ISSUE THREAD

**Issue by LeaveGT** [GrowtopiaNoobs/GrowtopiaServer#657]
Selling VPS for 8 DLS (quit GTPS / Coding)

Other : 
4 GB Memory (Cool and Fast)
&
MY CPP ( 50+ codes + more!!)
&
LIFETIME! [VPS]

**Comment by LeaveGT** [comment]
Discord : Binlk HEE#7300

**Comment by playingo** [comment]
@GrowtopiaNoobs @LeaveGT I heard it is not allowed to sell stuff like this way (basically a scummy way to earn money actually) with growtopia noobs's code stuff etc.

**Comment by NotDark** [comment]
> Selling VPS for 8 DLS (quit GTPS / Coding)
> 
> Other :
> 4 GB Memory (Cool and Fast)
> &
> MY CPP ( 50+ codes + more!!)
> &
> LIFETIME! [VPS]


i dont think the vps  is LIFETIME

**Comment by GrowtopiaNoobs** [comment]
Well, selling VPS isn't illegal, but it is off topic. Also, there is no way to ensure that buyer won't be scammed.
