### ISSUE TITLE
(Request) I need help setting up the shop, in exchange of gems. Can we please partner up and get this dealt with? Please & Thank you. orbit #4682 (discord)

### ISSUE THREAD

**Issue by Orbit4682** [GrowtopiaNoobs/GrowtopiaServer#658]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ZentaiZber** [comment]
?



















































































?

**Comment by ritzysw** [comment]
indog do you actually not fucking know the meaning of word "template"?
just fucking pasting it without changing anything, nice, gt community is great

**Comment by ZentaiZber** [comment]
stop saying indog motherfacker

**Comment by ritzysw** [comment]
stop being retarded indog

**Comment by Orbit4682** [comment]
Stfu u toxic piece of Sh**


Sent from Yahoo Mail for iPhone


On Tuesday, July 2, 2019, 2:18 AM, Ritzy <notifications@github.com> wrote:


stop being retarded indog

**Comment by ritzysw** [comment]
indogs mad x25

**Comment by Hades3235** [comment]
lmaoo

**Comment by ZentaiZber** [comment]
lmaooo

**Comment by GrowtopiaNoobs** [comment]
No selling of codes. You need to edit template and don't write all information in issue title. Also don't use discord much, because those informations can be useful for others too.
