### ISSUE TITLE
How to save clothes?

### ISSUE THREAD

**Issue by RU15** [GrowtopiaNoobs/GrowtopiaServer#66]
Is it possible to save clothes what i wear?

**Comment by Mempler** [comment]
Of course it is. You need to write the clothing down into the database.

**Comment by mar4ello6** [comment]
> Of course it is. You need to write the clothing down into the database.

But how?

**Comment by RU15** [comment]
> Of course it is. You need to write the clothing down into the database.

I don't know how...

**Comment by Mempler** [comment]
Then i would recommend you to read an book about C++ or youtube videos or just google `how to save data into a file c++`

**Comment by mar4ello6** [comment]
> Then i would recommend you to read an book about C++ or youtube videos or just google `how to save data into a file c++`

I will watch...
