### ISSUE TITLE
How to properly use the white door in the server (when you try to get item main door, it's blank)??

### ISSUE THREAD

**Issue by playingo** [GrowtopiaNoobs/GrowtopiaServer#660]
question in title.
I assume it's something client related though, so server sidedly not possible, uhh..???
tell me what you think here.

**Comment by ritzysw** [comment]
you can't have it in your inventory, clientsided shit

**Comment by playingo** [comment]
i knew it...

**Comment by playingo** [comment]
dang :/ but its ok ill just use a door mover i guess

**Comment by NoobesGT** [comment]
use cheat engine

**Comment by playingo** [comment]
Ok so i found out that when you drop main door, then collect it, you will be able to properly use it!
