### ISSUE TITLE
i need help on source.exe

### ISSUE THREAD

**Issue by Tumppi05098** [GrowtopiaNoobs/GrowtopiaServer#661]
how to make or get working and editable source.exe
i need edit and add roles, level system and /find command

**Comment by Tumppi05098** [comment]
i need add ance too but how i make source?

**Comment by Tumppi05098** [comment]
and how to host? can i host free? i need know fast plz tell me

**Comment by Yoayao** [comment]
> and how to host? can i host free? i need know fast plz tell me

you can't host free

**Comment by playingo** [comment]
you cant host for free usually, you will not get codes here look at pull requests, here you will only get functions and some help but not pure code.

**Comment by Tumppi05098** [comment]
k

**Comment by willi123yao** [comment]
Unofficial/modified source codes/server executables are not supported by us and the original code is available [here in this repository](https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/master/enet%20server%20test/enet%20server%20test.cpp), I would recommend you to start from there if you want to make your own customisations and modifications to the server.

Closing this issue as it seems inactive/resolved.
