### ISSUE TITLE
Disconnect

### ISSUE THREAD

**Issue by CayaNFGL** [GrowtopiaNoobs/GrowtopiaServer#662]
Hello everyone!

I am keep disconnect at stuck.

I have already updated items.dat but still disconnecting.

Is there way to fix it?

Thanks everyone.

**Comment by FliqXs** [comment]
Update your hash

**Comment by CayaNFGL** [comment]
> Update your hash

How to update?

**Comment by CayaNFGL** [comment]
> Update your hash

And what is hash code?

**Comment by CayaNFGL** [comment]
By the way, I have updated it but it still stucks at "Logining....".

**Comment by NotDark** [comment]
> By the way, I have updated it but it still stucks at "Logining....".

try change your items.dat

**Comment by CayaNFGL** [comment]
> > By the way, I have updated it but it still stucks at "Logining....".
> 
> try change your items.dat

How?

**Comment by playingo** [comment]
make sure you have all files and use newest items.dat and hash

**Comment by Yunus971** [comment]
Update your items.dat and hash, If you have any error Yunus.js#1388

**Comment by willi123yao** [comment]
Closing this issue as it seems to be inactive/resolved.
