### ISSUE TITLE
[BUG] I Added gems per block but it goes minus

### ISSUE THREAD

**Issue by NetzCHaxors** [GrowtopiaNoobs/GrowtopiaServer#663]
But i done edit 1337 to 1

**Comment by ritzysw** [comment]
??????

**Comment by NetzCHaxors** [comment]
i done put the code  and it be minus from break 1 block i got -842,150,464

**Comment by CayaNFGL** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/pull/221

**Comment by NotDark** [comment]
> i done put the code and it be minus from break 1 block i got -842,150,464

![image](https://user-images.githubusercontent.com/44568476/60565103-d40f3d80-9d94-11e9-8c3e-a327f44b8e00.png)

change this to 1

**Comment by ardakurucim** [comment]
@NetzCHaxors add int gems = 0; to playerinfo

**Comment by herothedev** [comment]
i fixed it go look latest commit.

**Comment by NetzCHaxors** [comment]
> @NetzCHaxors add int gems = 0; to playerinfo

cand send ss?

**Comment by ardakurucim** [comment]
![image](https://user-images.githubusercontent.com/48387425/60817922-44f39280-a1a5-11e9-8e5e-b7a14b4664df.png)
here

**Comment by GrowtopiaNoobs** [comment]
This issue was answered, so I am closing this.
