### ISSUE TITLE
How to host? i need know fast! plz tell me!

### ISSUE THREAD

**Issue by Tumppi05098** [GrowtopiaNoobs/GrowtopiaServer#664]
how to host i have public id
need know

**Comment by ZentaiZber** [comment]
wdym?

**Comment by Tumppi05098** [comment]
i need know
can tell me how to host own private server

**Comment by ZentaiZber** [comment]
Use vps or you can use ur main computer but only yourself can join

**Comment by Yoayao** [comment]
u can also use "hamachi" but it only for pc user to join

**Comment by Tumppi05098** [comment]
ok ty

**Comment by Tumppi05098** [comment]
but how i host with hamachi

**Comment by playingo** [comment]
@Tumppi05098 hey kid, if you dont know anything that dont do something you dont know anything about.
i assume you dont know shit if you dont even know how 2 host

**Comment by Tumppi05098** [comment]
ty...
