### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ZentaiZber** [GrowtopiaNoobs/GrowtopiaServer#665]
How to add button but use icon like add_label_with_icon

**Comment by flossboss** [comment]
|add_label_with_icon|big or small|TEXT|left|ITEM ID|

**Comment by ZentaiZber** [comment]
-_ -      - - - - - - - -- - - - - - - - -- - - - - - - - -- - - - - - - -- - - - - - - - -- ---------- ---------------- - - - - - - -- - - - - ------ ---------------- - - - -- - - - - - - - -- - - - - - - -- - - - - - - - -- - - - - - -       _ _       -----------------------------------------------------------------------------------------------
