### ISSUE TITLE
[QUESTION] How to handle connection?

### ISSUE THREAD

**Issue by NoobesGT** [GrowtopiaNoobs/GrowtopiaServer#668]
Like when you enter a wrong password to don't be needed enet_peer_disconnect_later().

**Comment by playingo** [comment]
memcpy stuff + action fail stuff.
or however, there is an easier alternative:
calling enet_peer_disconnect_later(peer, 0); in ENET_EVENT_TYPE_RECEIVE will not cause a disconnect, and the user can properly read stuff.
