### ISSUE TITLE
[Question] How to make Auto Restarting in The Exe

### ISSUE THREAD

**Issue by arshizx** [GrowtopiaNoobs/GrowtopiaServer#669]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when the server is crashing

**Describe the solution you'd like**
i want make auto restart so it can auto on when crashing.

**Comment by StackBuddy** [comment]
ServerConsistency, a simple plugin for GTPS written by playingo does the job properly.
Current version is 1.4, deletes invalid file sizes in worlds and players data (most likely corrupted) (simple program but works fine) and it has logging and shows all stuff that needed to be deleted etc.
you can customize restart time / check time and many more in the Settings
Look at: #644

**Comment by arshizx** [comment]
> ServerConsistency, a simple plugin for GTPS written by playingo does the job properly.
> Current version is 1.4, deletes invalid file sizes in worlds and players data (most likely corrupted) (simple program but works fine) and it has logging and shows all stuff that needed to be deleted etc.
> you can customize restart time / check time and many more in the Settings
> Look at: #644

But that plugin make player/worlds data doesnt saved

**Comment by playingo** [comment]
@arshizx use it if it crashes alot, if it crashes alot anyway, then you can doubt that worlds properly save

**Comment by ilyn1337** [comment]
@arshizx don't use any external applications, kick off everyone from the server and do worldDB.saveall();, maybe u need some threading stuff for timing but you can make urself one idk.

**Comment by willi123yao** [comment]
Closing this issue as it seems inactive/resolved.

**Comment by playingo** [comment]
disable showing crash dialog (you cannot debug your program then i guess so rip that) and then write simple c# program that uses a timer to check if process is running. if not, then start the process.
