### ISSUE TITLE
Weather

### ISSUE THREAD

**Issue by mar4ello6** [GrowtopiaNoobs/GrowtopiaServer#67]
How to change weather in world? I tried do it with command, but i failed...

**Comment by NotDark** [comment]
use OnSetCurrentWeather

**Comment by mar4ello6** [comment]
> use OnSetCurrentWeather

But, how? When i tried my commend doesn't work...

**Comment by NotDark** [comment]
GamePacket p = packetEnd(appendInt(appendString(createPacket(), "OnSetCurrentWeather"), weathercode))

**Comment by willi123yao** [comment]
The weather command has been added into the code, please refer to the latest commit to see the actual code that changes weather.
