### ISSUE TITLE
I've got an issue with my code

### ISSUE THREAD

**Issue by noobesgt** [GrowtopiaNoobs/GrowtopiaServer#673]
I'm tryin to get from string the world in where the player is : 
Code:
and ya the worldxDD is the string because when you want to make a button with currentPeer the compiler won't let u to compile with it so i did the string from wrench if you understand me.
>ENetPeer* currentPeer;
						sendPlayerLeave(peer, (PlayerInfo*)(peer->data));
						((PlayerInfo*)(peer->data))->currentWorld = ((PlayerInfo*)(peer->data))->worldxDD;
						sendWorldOffers(peer);

>

**Comment by ardakurucim** [comment]
Did you add worldXDD to PlayerInfo ?

**Comment by NoobesGT** [comment]
yep

**Comment by ilyn1337** [comment]
`((PlayerInfo*)(peer->data))->currentWorld = ((PlayerInfo*)(peer->data))->worldxDD;`
peer exiting the word, arent it? just do:
`((PlayerInfo*)(peer->data))->currentWorld = "EXIT";`

**Comment by noobesgt** [comment]
@ilyn1337 yes but i want like receiving the currentworld from currentpeer and warp to him

**Comment by ardakurucim** [comment]
@noobesgt then use substr

**Comment by willi123yao** [comment]
Closing this issue as it seems inactive/resolved.
