### ISSUE TITLE
<Question> World Cast

### ISSUE THREAD

**Issue by noobesgt** [GrowtopiaNoobs/GrowtopiaServer#675]
How can i make like a 'broadcast' just for the world. Like im pulling a people and sayin that noobesgt pulled gay999 just in the world?

**Comment by ritzysw** [comment]
you can either add your own list of peers in worldDB or just loop through all users and use isHere to check if they are in the same world

**Comment by ilyn1337** [comment]
and then onsetpos, play itemdrop or something like that audio in gt files (for everyone on the world)

**Comment by willi123yao** [comment]
Closing this issue as it seems inactive/resolved.
