### ISSUE TITLE
Question     

### ISSUE THREAD

**Issue by PeoKass** [GrowtopiaNoobs/GrowtopiaServer#677]
how can i build the server.exe      and how can i download wine to ubuntu

**Comment by willi123yao** [comment]
Linux/Ubuntu is not official supported by us and there are a few modified ones available here as mentioned in #720 and discussed in the issue #734. Do note that these modification are not supported by us and made by someone else, any issues you will need to try to figure them out yourself.

Closing this issue as it seems inactive/resolved.
