### ISSUE TITLE
[BUG] Something about Iseek.cpp

### ISSUE THREAD

**Issue by CoolAkramTV** [GrowtopiaNoobs/GrowtopiaServer#683]
It says it's in line 103 and I need help!

**Comment by ardakurucim** [comment]
what is the error exactly

**Comment by CoolAkramTV** [comment]
Here you go: [The error.](https://user-images.githubusercontent.com/30519221/60759248-db258e00-9fd6-11e9-8877-454b298b887a.png)

**Comment by GrowtopiaNoobs** [comment]
- Have you followed Basic Setup page on wiki?
- I would like to ask you about server name `UnkownPlatform.exe` - is it based on official code or anything else?
- Also if you have visual studio can you please show us where code crashed?

**Comment by CoolAkramTV** [comment]
> * Have you followed Basic Setup page on wiki?
> * I would like to ask you about server name `UnkownPlatform.exe` - is it based on official code or anything else?
> * Also if you have visual studio can you please show us where code crashed?

I got it from a user called Unknown Platform on YouTube. If you have an official download, that'd be amazing.

**Comment by OverallGod** [comment]
xD that video is old I'm sorry @CoolAkramTV

**Comment by willi123yao** [comment]
Unofficial/modified builds are not supported by us so please do not open issues regarding these builds (basically any server exe/code that someone gave you or you took from elsewhere which in your case is another YouTuber). You should have contacted those who gave you the files instead.

Only sources compiled with Visual Studio by yourself and built using the source code in the repository without modification will be supported, and these errors should not appear if you have done so in this way.

Closing this issue.
