### ISSUE TITLE
How to send states like Curse and Tape?

### ISSUE THREAD

**Issue by playingo** [GrowtopiaNoobs/GrowtopiaServer#684]
Ok, I've tried some stuff out but it didnt work, tried to modify getState a little etc. Didnt work, now I am confused. Anyone knows what to do here?
Thanks.

**Comment by ilyn1337** [comment]
playerinfo->isCursed = true, sendState(peer)

**Comment by ardakurucim** [comment]
@ilyn1337 i tried it but didnt work on tape

**Comment by GrowtopiaNoobs** [comment]
`isCursed` is not supported in code yet. It needs to be added into function `getState`. Someone can do it and make PR.

**Comment by ardakurucim** [comment]
@GrowtopiaNoobs I edited it but didnt work

**Comment by GrowtopiaNoobs** [comment]
@ardakurucim Have you added right bit shift?

**Comment by NotDark** [comment]
Add more 
val |= info->name << number

**Comment by playingo** [comment]
alright I have tried out some numbers and eventually found curse and ducttape. How about freezing though, does anyone know THAT?

**Comment by playingo** [comment]
alright found all right bitshifts. bitshift for freeze is 11 btw
