### ISSUE TITLE
New Packet 

### ISSUE THREAD

**Issue by moanhawks** [GrowtopiaNoobs/GrowtopiaServer#685]
![IMG_20190706_224242](https://user-images.githubusercontent.com/52075701/60757614-9255ef80-a03f-11e9-817d-5649ba6366f6.jpg)
I found this packet on gt bot but what this packet can do?

**Comment by ilyn1337** [comment]
flaming head, like px crown

**Comment by flossboss** [comment]
"g0 sulc1d3 s3Lf" LOL

**Comment by flossboss** [comment]
smh rude

**Comment by Secrethaxorzzzxxxxxxxxxx** [comment]
> smh rude

fuck off indo bitch

**Comment by moanhawks** [comment]
@flossboss lmao you can suicide self then say to god please god help me fix the growmoji issues xd

**Comment by flossboss** [comment]
@moanhawks lol “g0 suIc1de s3Lf” fucking indog

**Comment by flossboss** [comment]
@moanhawks 🖕

**Comment by playingo** [comment]
KONTAKOGEAENL MEMEAWJRRAK BANRAEGSHBSRSAT GGOBLOK BAAECOET !!!!!!!!!!!
