### ISSUE TITLE
I quit coding..

### ISSUE THREAD

**Issue by LeaveGT** [GrowtopiaNoobs/GrowtopiaServer#688]
I have quit coding need any codes from my old cop (server) just ask me.

**Comment by FliqXs** [comment]
What's your discord name?

**Comment by LeaveGT** [comment]
No have discord, I can get

**Comment by FliqXs** [comment]
Add me FliqX#2001

**Comment by flossboss** [comment]
Steak#0703 would help alot <3

**Comment by OverallGod** [comment]
Dont give it to them. Pull request it

**Comment by noobesgt** [comment]
If you would give me them you will help me and my server so much, My discord: noobesgt#8663

**Comment by ardakurucim** [comment]
@OverallGod is right

**Comment by flossboss** [comment]
I would PR it

**Comment by moanhawks** [comment]
All is nutz

**Comment by GrowtopiaNoobs** [comment]
How others have said, best way is to make PR, so your code is accessible for everyone.

**Comment by tahakocabuga** [comment]
Make It Public Request It is the best way

**Comment by GrowtopiaNoobs** [comment]
Nothing new happened for long time, so I am closing this issue.
