### ISSUE TITLE
Growtopia closing when log in!

### ISSUE THREAD

**Issue by iNPGT** [GrowtopiaNoobs/GrowtopiaServer#69]
I clicked Connect it says: 
logging in as [INPGT]...
and then just closing and wont show world list, how to solve ?

**Comment by iNPGT** [comment]
help me someone

**Comment by iNPGT** [comment]
***i don't understant, i'm*** ***confused***...
***logging in and growtopia closing, it wont show me worldlist :(***

**Comment by DrOreo002** [comment]
Are you using the latest version of gt?

**Comment by iNPGT** [comment]
Im using 2.xx1 dont remember, but not latest, pls help. /cry

**Comment by iNPGT** [comment]
I downladed everything, 
Run.py
Server.exe
itemdata*
Coredata
Descriptions
And etc
So everything is in, starting by python, 3x

**Comment by iNPGT** [comment]
*So, from da source* (***GITHUB***)

**Comment by Mempler** [comment]
You need to run the latest version of GT else you wont be able to connect.
