### ISSUE TITLE
[Bug] OnConsoleMessage space

### ISSUE THREAD

**Issue by moanhawks** [GrowtopiaNoobs/GrowtopiaServer#693]
![IMG_20190711_114316](https://user-images.githubusercontent.com/52075701/61023223-96856280-a3db-11e9-9943-a9cefb5a62ba.jpg)
why when me do /time then have another space like that picture

**Comment by NotDark** [comment]
Did you put \n ? If yes remove \n

**Comment by willi123yao** [comment]
You might have added a newline character by accident or sent a blank message following the command response. Once those are removed, this issue should be resolved.
