### ISSUE TITLE
[BUG] Some of players can't play.

### ISSUE THREAD

**Issue by herothedev** [GrowtopiaNoobs/GrowtopiaServer#694]
**Describe the bug**
Some of players can't play, because they get stuck on updating items (most of them are iOS players, but some of then are android and PC), and yes, they tried to delete cache and play real gt and then the private server. But still stuck on updating items.

**To Reproduce**
1. Open growtopia
2. Connect to private server

**Expected behavior**
That items will update normally.

**Screenshots**
![IMG_20190711_104139](https://user-images.githubusercontent.com/45075181/61031609-8ca63400-a3c8-11e9-8e62-21693068c26a.png)

**Stack frame**
Server didnt crash (and there no errors), but i can send the code here what does it
```C++
if (strcmp(GetTextPointerFromPacket(event.packet), "action|refresh_item_data\n") == 0) {
  if (itemsDat != NULL) {
    ENetPacket * packet = enet_packet_create(itemsDat,
        temsDatSize + 60,
        ENET_PACKET_FLAG_RELIABLE);
    enet_peer_send(peer, 0, packet);
    ((PlayerInfo*)(peer->data))->isUpdating = true;
    enet_peer_disconnect_later(peer, 0);
    //enet_peer_disconnect_later(peer, 0);
    //enet_host_flush(server);
  }
}
break;
```

**Server environment (please complete the following information):**
 - OS: android, ios, pc
 - Experience: beginner
 - Modifications: big changes

**Client environment (please complete the following information):**
 - Growtopia version: 2.994

**Comment by ardakurucim** [comment]
i think its about hash or items.dat

**Comment by herothedev** [comment]
Fixed alr.
