### ISSUE TITLE
What is Missing ?

### ISSUE THREAD

**Issue by tahakocabuga** [GrowtopiaNoobs/GrowtopiaServer#696]
What is Missing Can Anyone Say It Please

![Screenshot](https://user-images.githubusercontent.com/29047652/61077121-66af7c80-a426-11e9-91ff-5b0c2138fdf2.PNG)

**Comment by tahakocabuga** [comment]
I am Stuck On The Login Page

**Comment by FliqXs** [comment]
Update your hash

**Comment by GrowtopiaNoobs** [comment]
Closing this question as there hasn't been new activity for long time.
