### ISSUE TITLE
Can Anyone Send Me New Hash

### ISSUE THREAD

**Issue by tahakocabuga** [GrowtopiaNoobs/GrowtopiaServer#697]
Hello I don't know how to find hash can anyone send the new one

**Comment by FliqXs** [comment]
1412700336

**Comment by moanhawks** [comment]
https://gyazo.com/37f8dbf4fc069c72752947d558a29901

**Comment by tahakocabuga** [comment]
Which is Correct ?

**Comment by herothedev** [comment]
Use this method: #248

**Comment by willi123yao** [comment]
You can either obtain the new hash by connecting to the official Growtopia Server using a bot or using the method like what @herothedev has mentioned.

Closing this issue as it seems to be resolved.
