### ISSUE TITLE
Syntaxes for the Packets

### ISSUE THREAD

**Issue by MeNoFade** [GrowtopiaNoobs/GrowtopiaServer#70]
Hello! I want help. How to find syntaxes for packets? Like i have OnSetCurrentWeather packet. How to find his syntax? For example: packet OnSpawn have syntaxe  "spawn|avatar\nnetID|" + std::to_string(cId) + "\nuserID|" ..., how you find this syntax?

**Comment by Mempler** [comment]
You have 2 choices.
1) Reverse engineer the client. (maybe using old mac os code)
2) Proxy the server and client connection.

**Comment by MeNoFade** [comment]
> You have 2 choices.
> 
> 1. Reverse engineer the client. (maybe using old mac os code)
> 2. Proxy the server and client connection.

On mac os old code don't have syntax, have only standart syntax'es.
