### ISSUE TITLE
How Can I Host Server Public In My PC

### ISSUE THREAD

**Issue by tahakocabuga** [GrowtopiaNoobs/GrowtopiaServer#700]
Hello I will buy a VPS but i want to see how many people will play before. So Can I host Server In My PC ? If Yes HOWWW ?

**Comment by ardakurucim** [comment]
open ports

**Comment by tahakocabuga** [comment]
> pen ports

ben Lil  Enes :D

**Comment by tahakocabuga** [comment]
> open ports

i dk how to do it

**Comment by ID4RKI** [comment]
Yav bi sg

**Comment by NotDark** [comment]
Port forward or use hamachi

**Comment by tahakocabuga** [comment]
> Yav bi sg

sende D4RK GTT nin devi

**Comment by willi123yao** [comment]
I would suggest you go to your router page and find how to configure port forwarding for your router online and do it from there. Don't forget to change the IP address in the python script to match your public IP (which is the IP that your players will connect to).

Closing this issue as it seems to be resolved.
