### ISSUE TITLE
[BUG]  Block Bug

### ISSUE THREAD

**Issue by SurekingIGTPS** [GrowtopiaNoobs/GrowtopiaServer#705]
How to make Like MrSongo block work,Kitty block work to place, i already add to coredata but if i place to world it's can't why? anyone can answer?.

**Comment by MeNoFade** [comment]
![image](https://user-images.githubusercontent.com/44878241/61206734-fa6d9b00-a6fb-11e9-8272-3cf93063759e.png)

**Comment by SurekingIGTPS** [comment]
Ok i will try

**Comment by SurekingIGTPS** [comment]
the arrow? point copy if (tile>=8622) return;  ''8662'' change to id to want work to place block?

**Comment by SurekingIGTPS** [comment]
![image](https://user-images.githubusercontent.com/49722651/61215119-09703f80-a734-11e9-8f7d-1f5283e7637c.png)
i have that but can't place that item id block

**Comment by SurekingIGTPS** [comment]
ok i already know right now
