### ISSUE TITLE
1 HIT BLOCK

### ISSUE THREAD

**Issue by SurekingIGTPS** [GrowtopiaNoobs/GrowtopiaServer#706]
How to make dirt block like 1 punch can destroy?

**Comment by moanhawks** [comment]
Suidce you self then say to god how to make dirt block 1 punch can destroy

**Comment by SurekingIGTPS** [comment]
fix Ur text typing first and then Go talk whatever u say :joy:

**Comment by moanhawks** [comment]
K here
Kill you self then say to god how to make dirt block like 1 punch can destroy 👍

If don't understand then use Google Translate

**Comment by ilyn1337** [comment]
"fix Ur text typing first and then Go talk whatever u say "

**Comment by ID4RKI** [comment]
Wow omg SurekingIGTPS is back lets make a party

**Comment by SurekingIGTPS** [comment]
i already know it now Thanks :D
