### ISSUE TITLE
[BUG] json file

### ISSUE THREAD

**Issue by moanhawks** [GrowtopiaNoobs/GrowtopiaServer#707]
When me ban people why the player json file is reset all to 0?

**Comment by SurekingIGTPS** [comment]
.

**Comment by flossboss** [comment]
"Suidce you self then Go say to god how to make..." player json file change when banned.

if that's what you want :)

**Comment by moanhawks** [comment]
@flossboss god say to me comment at issues GrowtopiaServer git hub

**Comment by moanhawks** [comment]
https://gyazo.com/01897cee6b707852109c43af8b859d1e
Memes @flossboss

**Comment by ardakurucim** [comment]
you should use x

**Comment by ardakurucim** [comment]
you must use new json value and give it ifs

**Comment by flossboss** [comment]
yea because i'm trying to get help while your just being extra in my issue posts.
smh look at this dood

**Comment by flossboss** [comment]
if you aren't going to help anyone, no one's going to help you

**Comment by moanhawks** [comment]
Already fix k @ardakurucim ty
Ima going closed this issues
