### ISSUE TITLE
How do I set the server up?

### ISSUE THREAD

**Issue by RedactedForPrivacyPurposes** [GrowtopiaNoobs/GrowtopiaServer#708]
I read the [wiki page](https://github.com/GrowtopiaNoobs/GrowtopiaServer/wiki/Basic-setup), followed all the steps, pasted the python script, downloaded all the "dependencies", pointed `growtopia1.com` to localhost with my hosts file. Now with the python script and `server.exe` running, I'm stuck on the login with nowhere else to go

![Growtopia 15_07_2019 20_18_14](https://user-images.githubusercontent.com/43325820/61215543-d16dfa00-a73d-11e9-85ce-bb908d4b17f0.png)

Can anybody tell me what happened?

**Comment by ritzysw** [comment]
Try upgrading/downgrading your GT version, updating items.dat hash
