### ISSUE TITLE
How to fix Record growtopia1  to localhost already found

### ISSUE THREAD

**Issue by HelpmeHelpyous** [GrowtopiaNoobs/GrowtopiaServer#71]
can anyone help me plsss
i ned pllsssss

**Comment by DrOreo002** [comment]
delete it then from the host file

**Comment by HelpmeHelpyous** [comment]
But here's what i get after i remove growtopia1 from the host file
![help](https://user-images.githubusercontent.com/44936463/48309516-f6124080-e5b6-11e8-923e-7e0a0d7421e2.PNG)

**Comment by HelpmeHelpyous** [comment]
Unknown error. how to fix?

**Comment by HelpmeHelpyous** [comment]
![help2](https://user-images.githubusercontent.com/44936463/48309538-615c1280-e5b7-11e8-9041-0bd275790e62.PNG)
Here's what happen when i put it back

**Comment by HelpmeHelpyous** [comment]
after that, i would be stuck in logon screen...

**Comment by RU15** [comment]
> after that, i would be stuck in logon screen...

You stuck in logon because you have older version of GT, when server for newer. Update your Growtopia.

**Comment by HelpmeHelpyous** [comment]
I've already did, its the record growtopia1.com thing

**Comment by NotDark** [comment]
your server is old

**Comment by HelpmeHelpyous** [comment]
> your server is old
How do i update my server then

**Comment by learntodlgt** [comment]
The thongs are v2.982 So it wont work very well

**Comment by Dunzap** [comment]
So must I download the server in the newest page of wiki?

**Comment by Mempler** [comment]
Duplicate of #64
