### ISSUE TITLE
[Q] How to... (open this issue)

### ISSUE THREAD

**Issue by herothedev** [GrowtopiaNoobs/GrowtopiaServer#713]
How I can switch from hashPassword to normal password, when player creates account, it saves the password without hashing, is it possible?
I've already tried to remove all hashPassword(password) and making them to password, but now when player creates account, on json file it saves the password as "", and player need to logon with ""  password (without quotes), and i changed to verifyPassword to 
`if (ps == jps)` ps is tankIdPass, and jps is password whats opened from player json file.

**Comment by playingo** [comment]
yes it is possible but you can just recode whole playerLogin system and saving system.

**Comment by herothedev** [comment]
Okay, but why when newnplayer register, it saves on players/playername.json into his password just blank space, not the real password?

**Comment by flossboss** [comment]
@herothedev I just added a new thing that is pass where it shows real pass and password shows hashed pass

**Comment by flossboss** [comment]
```
j["password"] = hashPassword(password);
j["pass"] = password;
```
