### ISSUE TITLE
Searhing for a coding team.

### ISSUE THREAD

**Issue by InjectionZ** [GrowtopiaNoobs/GrowtopiaServer#714]
Im searching for a team to code gtps, My code have friends, take items form dropped and much more, Comment ur discord down below or contact me Injection.#4898

**Comment by playingo** [comment]
ok can you please stop i bet your codes are stolen and you just wanna steal more codes by doing nothing and while you can relax you want someone to code for you. guys, dont go to him. also injectionz thats cringy and looks desperate.

**Comment by Orbit4682** [comment]
come back to xeno, https://discord.gg/EwPGRSR
