### ISSUE TITLE
[Help] CoreData

### ISSUE THREAD

**Issue by MoanHawks** [GrowtopiaNoobs/GrowtopiaServer#715]
Who have new of CoreData this month?

**Comment by SurekingIGTPS** [comment]
why

**Comment by moanhawks** [comment]
You back? Memes of sureking

**Comment by SurekingIGTPS** [comment]
I'm not joking i'm seriously fp i have it but why you asking that :rofl:

**Comment by moanhawks** [comment]
I need for private server

**Comment by InjectionZ** [comment]
> I'm not joking i'm seriously fp i have it but why you asking that 🤣

can you share it?

**Comment by GrowtopiaNoobs** [comment]
Closing this question as it is too old.
