### ISSUE TITLE
BIGGEST CODE LEAK!! 5+ SOURCES, (GTOG SOURCE + lots of vyte codes + MANY MORE)

### ISSUE THREAD

**Issue by playingo** [GrowtopiaNoobs/GrowtopiaServer#717]
join this discord to download: https://discord.gg/XDNaFN9

has world clearing no reenter, /info system with aid gid vid rid sid (hardware information + generally windows infos), full roles system and alot of other sources that also have guilds system, friends, and many more. My source even has hardware ban, /mode (u can change into, forexample thanos or smaller character) and /ipcheck including the plugin that prints out if a vpn was detected or not. also uses threads, so yeah. OBVIOUSLY, alot more too and alot more sources / leaked infos aswell...

If you want to join us, again, use this discord: https://discord.gg/XDNaFN9
you can also share your source with us in order to get the best experience, you can also share new codes if you found them, so we can all profit from it. Currently working on real growtopia signs and custom items, idk if i will succeed though, with the support I might. Thanks!

**Comment by ardakurucim** [comment]
So useful

**Comment by Lapada** [comment]
this contains no "codes" from vyte just a vague recreation and maybe some stolen dialogs

**Comment by VyteGTPS** [comment]
Repeating: those are not my codes if you meant codes from gtps then haven't seen a single one yet, anyways those are Growtopia codes not my. What is this guy even talking about ☻

**Comment by playingo** [comment]
ok it actually has the same shop design as vytes, and some more stuff that makes it good. the BIGGEST SOURCE CODE LEAK thingie is a meme

**Comment by VyteGTPS** [comment]
Shop design has nothing to do with gtps server or coding, me myself stole it from Growtopia guild prize dialog.

**Comment by playingo** [comment]
no problem, still a very useful cpp for others, what about the other stuff that has been cloned? but just better :) except its optimization probably and it doesnt have as many crash fixed and no signs but thats enough i guess. 2 people already actively using it.

**Comment by playingo** [comment]
also not to forget that it has proper world bans

**Comment by flossboss** [comment]
Very helpful

**Comment by Yoayao** [comment]
how to even addadmin???

**Comment by moanhawks** [comment]
Big leak

**Comment by playingo** [comment]
very big

**Comment by atipls** [comment]
actual autism

**Comment by ama6nen** [comment]
bruh cancer

**Comment by playingo** [comment]
![image](https://user-images.githubusercontent.com/50752911/61589887-c2a99c00-abb0-11e9-9f58-5f633f03985f.png)

**Comment by VyteGTPS** [comment]
![image](https://user-images.githubusercontent.com/51130398/61590944-44c3a180-ab6c-11e9-84de-9be7d8a46800.png)

**Comment by playingo** [comment]
@VyteGTPS do you know what it means to have a question mark in the end of your sentence?

**Comment by VyteGTPS** [comment]
![image](https://user-images.githubusercontent.com/51130398/61592600-df7aab00-ab81-11e9-8562-b558356bc18d.png)

**Comment by playingo** [comment]
yes i got them, where is the meme part of it? the meme part probably is that i cant do things w/them anyway but do you know what "tho" means?

**Comment by VyteGTPS** [comment]
BIGGEST CODE LEAK
codes itself
calls it leak

**Comment by playingo** [comment]
@VyteGTPS is that a response to my question? also the title was stolen from some other guy because i had nothing else 2 do.

**Comment by ama6nen** [comment]
![8027a638025aaf65706859e85459fc6b](https://user-images.githubusercontent.com/21124827/61631032-ea246580-ac91-11e9-8192-1e2630a66d8f.png)

**Comment by ritzysw** [comment]
@playingo why rq 2

**Comment by playingo** [comment]
@ama6nen old

**Comment by atomiclucky** [comment]
You can get those dialogs with gt bot lmao
