### ISSUE TITLE
PS4 and Nintendo Switch

### ISSUE THREAD

**Issue by ardakurucim** [GrowtopiaNoobs/GrowtopiaServer#718]
Yo as you guys know growtopia is now in nintendo switch here is my question is this server complitable with nintendo or no?

**Comment by playingo** [comment]
if you dont have your switch homebrewed or jailbreaked then not, theres probably no way to install a modified gt or edit hosts file. although i own a jailbreaked switch, yes you can if its jailbreaked.

**Comment by ardakurucim** [comment]
@playingo so server compatible with switch?

**Comment by playingo** [comment]
yes
