### ISSUE TITLE
[BUG]  How to fix that say [OPEN ISSUES]

### ISSUE THREAD

**Issue by Deveytv** [GrowtopiaNoobs/GrowtopiaServer#719]
How to fix that? if i click the destination is on /bc how to fix that? 
![image](https://user-images.githubusercontent.com/49722651/61450749-f2269180-a981-11e9-9a4b-5cb49eaa051e.png)

**Comment by ilyn1337** [comment]
i see, learn some english maybe?

**Comment by GrowtopiaNoobs** [comment]
I think we got deep enough with this project to delete it :D 

Well, really this code have really bad quality and it is one of reasons why I got away from it. Almost like 50% of code is in main function, which is totally stupid but was fastest to make. Someone can try to rewrite this code to more functions, remove hardcoded weird stuff, but I guess there won't be anyone to do it.

Short answer: Split code to functions.
