### ISSUE TITLE
How to auto hash on growtopia private server

### ISSUE THREAD

**Issue by mkevinam** [GrowtopiaNoobs/GrowtopiaServer#723]
How to get auto hash ?

**Comment by ardakurucim** [comment]
#248

**Comment by herothedev** [comment]
or #356 and put in hash GetHashOf("items.dat").

**Comment by MarmoriPelaa** [comment]
Please, either provide details close the issue if your problem is gone.

**Comment by mkevinam** [comment]
Oh thanks all :)
