### ISSUE TITLE
[BUG] How to fix Bad url gave 404?

### ISSUE THREAD

**Issue by D3c0d33** [GrowtopiaNoobs/GrowtopiaServer#724]
How to fix that? what's wrong [ I use python ]

**Comment by InjectionZ** [comment]
Create folder "growtopia" and put server_data.php inside the folder

**Comment by SurekingIGTPS** [comment]
already but still like that

**Comment by SurekingIGTPS** [comment]
> Create folder "growtopia" and put server_data.php inside the folder

Already but still like that

**Comment by ardakurucim** [comment]
i think you are using leaked cpp i think its broken

**Comment by SurekingIGTPS** [comment]
-_-

**Comment by OverallGod** [comment]
Your really stupid

**Comment by Yoayao** [comment]
sureking aka surequeen

**Comment by herothedev** [comment]
I can give u hint: Its on OnSuperMain thingy (NOT HASH, ANOTHER THING).

**Comment by playingo** [comment]
update cache

**Comment by Deveytv** [comment]
> update cache

How update cache on cpp?

**Comment by Deveytv** [comment]
> update cache

i done update cache **"ubistatic-a.akamaihd.net"),** "0098/CDNContent3/cache/"),** But why like that
![image](https://user-images.githubusercontent.com/49722651/61632437-0a1a5000-acb7-11e9-9f63-98924bcea6b8.png)

**Comment by moanhawks** [comment]
xD why you need close that hash and go use auto hash is easy to use

**Comment by moanhawks** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/pull/248

**Comment by Deveytv** [comment]
> #248

Ok i will try it thanks btw,

**Comment by herothedev** [comment]
CDNContent3 isnt latest.

**Comment by Deveytv** [comment]
> CDNContent3 isnt latest.

So what the latest?

**Comment by herothedev** [comment]
U can use custom cache too, i think. Just change it to your cache directory, not sure, and the latest is i think CDNContent7 or 8 or 9, not sure.

**Comment by Deveytv** [comment]
> U can use custom cache too, i think. Just change it to your cache directory, not sure, and the latest is i think CDNContent7 or 8 or 9, not sure.

Ok hero i will try it.

**Comment by Deveytv** [comment]
> U can use custom cache too, i think. Just change it to your cache directory, not sure, and the latest is i think CDNContent7 or 8 or 9, not sure.

i do CDNContent7 But it's When login [Name] Left, count other's here. but not disconnet.

**Comment by herothedev** [comment]
try then CDNContent8 or CDNContent9.

**Comment by herothedev** [comment]
Try to use own cache, then.

**Comment by Deveytv** [comment]
> Try to use own cache, then.

How?

**Comment by playingo** [comment]
Content10 is the latest

**Comment by GrowtopiaNoobs** [comment]
Is this issue solved?

**Comment by GrowtopiaNoobs** [comment]
Closing this issue as there hasn't been any new activity.
