### ISSUE TITLE
HOW ADD /PAY BUTTON

### ISSUE THREAD

**Issue by Bexps** [GrowtopiaNoobs/GrowtopiaServer#725]
HOW TOO ADD /PAY BUTTON CAN ANYONE GIVE CODE ?

**Comment by ID4RKI** [comment]
code it yourself

**Comment by ardakurucim** [comment]
```else if (str.substr(0, 5) == "/pay") {
code thingie
}```

**Comment by ardakurucim** [comment]
else if (str.substr(0, 5) == "/pay ") {
codes here
}```

**Comment by Deveytv** [comment]
Closed this issue please if you already know @Bexps.

**Comment by Bexps** [comment]
İ wrong write maybe
