### ISSUE TITLE
/PAY CODE 

### ISSUE THREAD

**Issue by Bexps** [GrowtopiaNoobs/GrowtopiaServer#728]
Can anyone Give pay code not button

**Comment by ritzysw** [comment]
kill yourself indog

**Comment by Bexps** [comment]
Stfu i am from turkey! u fking indog

**Comment by ritzysw** [comment]
kill yourself indog

**Comment by niko1802** [comment]
kill yourself indog

**Comment by Deveytv** [comment]
> Can anyone Give pay code not button

Hello there!, i can helping you a little bit for /pay code answer this for continue.

**Comment by DrOreo002** [comment]
This is issue tab, not for asking for free codes lmao

**Comment by Bexps** [comment]
@Deveytv  ok help

**Comment by ardakurucim** [comment]
@Bexps (this message is turkish) kardeşim kod sormayı bırak kendin kodla

**Comment by ZentaiZber** [comment]
lol if someone say code always say indog so funny

**Comment by TrisuDL** [comment]
Hmmmmmm THIS IS ISSUES TAB NOT "beg for commands" TAB

**Comment by playingo** [comment]
INDAAUWLWGGG!! also @Bexps shut the fuck up bitch, fucking turkish immigrant? bruh thats even almost as bad as an indog.  
golden rule guys: indogs/pignoys/turkeys - ALWAYS avoid.

**Comment by ardakurucim** [comment]
@playingo not all turkish are bad wtf

**Comment by herothedev** [comment]
please speak proper english..

**Comment by playingo** [comment]
@ardakurucim yes but thats really rare do have a non autistic indog/turk/pignoy. 0.001% chance

**Comment by iProgramMC** [comment]
You need to:
* Get the gem count to pay
* Check if player has enough gems
* If they do, subtract gem count to pay from player's gems value and add that same count to pay other player's gems. It's really that simple!!

**Comment by GrowtopiaNoobs** [comment]
Closing this issue, as this server doesn't support trading with gems.
