### ISSUE TITLE
How to run on vps linux

### ISSUE THREAD

**Issue by ZentaiZber** [GrowtopiaNoobs/GrowtopiaServer#729]
how to run? i use wine and show error

`0009:err:module:import_dll Library MSVCP140D.dll (which is needed by L"Z:\\home\\gtps2\\server.exe") not found
0009:err:module:import_dll Library VCRUNTIME140D.dll (which is needed by L"Z:\\home\\gtps2\\server.exe") not found
0009:err:module:import_dll Library ucrtbased.dll (which is needed by L"Z:\\home\\gtps2\\server.exe") not found
0009:err:module:attach_dlls Importing dlls for L"Z:\\home\\gtps2\\server.exe" failed, status c0000135
`

**Comment by DrOreo002** [comment]
You might need to use this guy's fork https://github.com/GrowtopiaNoobs/GrowtopiaServer/pull/720

**Comment by ZentaiZber** [comment]
is .dll missing lol

**Comment by ZentaiZber** [comment]
ow wait i test it :D

**Comment by ZentaiZber** [comment]
> wine: cannot find L"C:\\windows\\system32\\enet.exe" wtf? where i get enet.exe

**Comment by DrOreo002** [comment]
You don't need wine to compile it

**Comment by ZentaiZber** [comment]
i try to run but showing this error

**Comment by ZentaiZber** [comment]
we need to compile on linux or windw?

**Comment by DrOreo002** [comment]
Ofc on linux xd

**Comment by ZentaiZber** [comment]
ok thx you i will try compile with ma frend tommorow xD
