### ISSUE TITLE
Admins

### ISSUE THREAD

**Issue by FKSP** [GrowtopiaNoobs/GrowtopiaServer#73]
Can you make admins break locked worlds?

**Comment by Mempler** [comment]
Of couse you can. You need to edit in [this](https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/05ea7aba90e0874f29f608f1d34911832ff1e77d/enet%20server%20test/enet%20server%20test.cpp#L1478) if statement.

**Comment by FKSP** [comment]
Thanks, I made it!
