### ISSUE TITLE
Spawning gems

### ISSUE THREAD

**Issue by OverallGod** [GrowtopiaNoobs/GrowtopiaServer#730]
What do you need to spawn gems. I'm not talking about spawning the item. And how would I spawn different types of gems like the green gem and red gems.

**Comment by ritzysw** [comment]
dropped gems are literally items, quantity 10 would be red gem etc

**Comment by OverallGod** [comment]
Really

**Comment by OverallGod** [comment]
I feel stupid. I don't know why i didn't try that anyway thanks @ritzysw
