### ISSUE TITLE
Clothes bug

### ISSUE THREAD

**Issue by ZentaiZber** [GrowtopiaNoobs/GrowtopiaServer#731]
i cant wear clothes but my clothes can placed

**Comment by Deveytv** [comment]
You get the item from /item [ID]? So You need to put to coredata To access for can wear the item clothes

**Comment by ZentaiZber** [comment]
is working before

**Comment by Deveytv** [comment]
> is working before

Maybe you Replace old coredata accident maybe.

**Comment by ZentaiZber** [comment]
i using linux maybe the problem?

**Comment by ZentaiZber** [comment]
OH FUC I GIVE UP R.I.P VPS LINUX LOL I BUY IT 1 YEARS NOTHING TO DO WITH MY VPS

**Comment by InjectionZ** [comment]
> i cant wear clothes but my clothes can placed

What is the "placed" mean

**Comment by Deveytv** [comment]
> OH FUC I GIVE UP R.I.P VPS LINUX LOL I BUY IT 1 YEARS NOTHING TO DO WITH MY VPS

You use linux? LOL

**Comment by ZentaiZber** [comment]
yes lel because my linux is never use so i try host private server lol

**Comment by herothedev** [comment]
@zentaizber try to figure out from your code whats making it, or edit coredata the right way.
