### ISSUE TITLE
[HELP]: How to add stuff to json (e.g by new update) without making it crash?

### ISSUE THREAD

**Issue by playingo** [GrowtopiaNoobs/GrowtopiaServer#732]
Alright so, my guess is when I try to save more stuff and do not delete players data and it crashes, why: I think its because it reads the values but when a value is notexistent in the json file, it crashes.

So, I want to create a new update but I do not know how to avoid that. Is there maybe a program or something that can insert lines to multiple .json files so you can properly release an update that requires more player saving? or is there a better method?

**Comment by ardakurucim** [comment]
i tried using player database like playerlogin

**Comment by ardakurucim** [comment]
and it works

**Comment by ZentaiZber** [comment]
use mysql instead lol

**Comment by ZentaiZber** [comment]
if (j.count("NewUpdate") == 1) { // if found you load
((PlayerInfo*)(Peer->data))->ban = j["NewUpdate"];
} else {
((PlayerInfo*)(Peer->data))->ban = 0;
}

**Comment by herothedev** [comment]
@zentaizber can teach me how to use mysql on c++ :D?

**Comment by OverallGod** [comment]
```
std::ofstream out("/test/test.json"); j["pi"] = 3.14159; out << std::setw(4) << j << std::endl; float test = j["pi"];
```
Idk if that works

**Comment by playingo** [comment]
@ZentaiZber i doubt you succeeded mysql :)

**Comment by Lapada** [comment]
@playingo yeah bro mysql super hard...

**Comment by playingo** [comment]
yeah, making queries, SUPER HARD. but its unneccessary right now, i mean cmon dude its a private server not a whole fucking uh, gt clone???
also no need for help, wrote a nice little program that loops all files in the players folder and update them, thanks anyways ;3

**Comment by Lapada** [comment]
wow
