### ISSUE TITLE
How to make growtopia private server on linux with g++, and how to compile

### ISSUE THREAD

**Issue by mkevinam** [GrowtopiaNoobs/GrowtopiaServer#734]
How to make growtopia private server on linux with g++, and how to compile?

**Comment by herothedev** [comment]
### Linux
1. Make sure you have the build tools ready for installation. You can download them depending on your distribution.
  * For Ubuntu or Debian-based distributions, simply open a terminal window and type in the command (`$ sudo apt-get install build-essential`)
  * Other distributions, please refer to your package manager and install the one containing g++ and gcc
2. Install ENet from here (http://enet.bespin.org/Installation.html)
3. Clone or download this project and open a terminal window in that folder.
4. Run this command to build the server executable (`$ g++ -o enet server test enet server test.cpp -std=c++11 -lenet`)
5. Now you have your working executable, follow instructions from the [wiki here](https://github.com/GrowtopiaNoobs/GrowtopiaServer/wiki/Basic-setup#setting-up-http-server) to setup your server
6. Start the server by opening terminal window in new server folder and running `$ ./enet server test`
(tutorial taken from @willi123yao 's repo, thanks to him and i edited it little bit. + i never compiled on linux, so idk will this work)

**Comment by herothedev** [comment]
I havent compiled yet because i am still using windows, but i think that will work.

**Comment by mkevinam** [comment]
Thanks

**Comment by mkevinam** [comment]
In file included from stdafx.h:8,
                 from enet server test.cpp:20:
targetver.h:8:10: fatal error: SDKDDKVer.h: No such file or directory
 #include <SDKDDKVer.h>
          ^~~~~~~~~~~~~
compilation terminated.

**Comment by mkevinam** [comment]
How to fix that?

**Comment by herothedev** [comment]
wine? or u didnt use this #720

**Comment by mkevinam** [comment]
Wine cant

**Comment by mkevinam** [comment]
Error

**Comment by herothedev** [comment]
did u add #720?

**Comment by GrowtopiaNoobs** [comment]
Now linux build is supported, please check CI commands (file `appveyor.yml`) for more info.
