### ISSUE TITLE
[BUG] It wont let me sign in.

### ISSUE THREAD

**Issue by BITHUBCO** [GrowtopiaNoobs/GrowtopiaServer#735]
I need help with this. it wont let me sign in because it says I have to update to v2.992 but I have v2.994. If someone knows how to fix this can you please let me know. Thank you.

![upda](https://user-images.githubusercontent.com/53489691/62150983-4ceab200-b2cd-11e9-8b7b-8e0e6baedb57.PNG)

**Comment by ardakurucim** [comment]
try looking action|log

**Comment by moanhawks** [comment]
Just update the growtopia to 2.994 and please change you item.dat at server file 
That well by work

**Comment by BITHUBCO** [comment]
> Just update the growtopia to 2.994 and please change you item.dat at server file
> That well by work

It isnt working.

**Comment by moanhawks** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/issues/735#issuecomment-516659736
Did you use new item.dat ?

**Comment by moanhawks** [comment]
> > Just update the growtopia to 2.994 and please change you item.dat at server file
> > That well by work
> 
> It isnt working.

Did you change new item.dat?

**Comment by Deveytv** [comment]
Hm me same problem like that btw lemme think........

**Comment by herothedev** [comment]
LOL, Just simply search on cpp 2.992 and make it to 2.994, there is 2 answers, make both to 2.994. THIS IS SO EASY...

**Comment by playingo** [comment]
>basically means he uses stolen cpp XD

**Comment by herothedev** [comment]
yep or urs xd (urs B1G LEAK)

**Comment by herothedev** [comment]
+ this is not gt noobs ver of gtserver bug, so please close this.

**Comment by BITHUBCO** [comment]
ty for help.
