### ISSUE TITLE
Williyao123 Yaoyao scammer!. Warning!!! very important

### ISSUE THREAD

**Issue by Bexps** [GrowtopiaNoobs/GrowtopiaServer#739]
![bandicam 2019-07-31 21-30-58-518](https://user-images.githubusercontent.com/53185818/62238109-f9ff2080-b3da-11e9-8bff-54b45cd16d43.jpg)

**Comment by Bexps** [comment]
i give him 4dls for vps+file private server, and give me 3,82 gb ram vps and after want 4dls more for 40gb ram. lol! i said i dont want he ignore me bevare scam dont trust him, and later he said its ur fault, fault ? lol 4dls is 8 euro, vps is (1euro give you 6month 32gb ram) i pay 8euro for 3gb ram vps ?

**Comment by Bexps** [comment]
![bandicam 2019-07-31 21-32-49-028](https://user-images.githubusercontent.com/53185818/62238613-09329e00-b3dc-11e9-999e-86bb93113e44.jpg)

**Comment by moanhawks** [comment]
that was not issues and ik that yaoyao scammer like raterad 
pls close the issues it

**Comment by Bexps** [comment]
@moanhawks  are you fking retarded? this %100 proof yaoyao scammer stfu

**Comment by ardakurucim** [comment]
here is github not growtopia support

**Comment by herothedev** [comment]
+ur own fault bcz no money to buy vps from directly from google/amazon/microsoft/hostwinds/routerhosting tec.

**Comment by herothedev** [comment]
@Bexps + Williyao123 and Yapyao isnt same person...

**Comment by Bexps** [comment]
@herothedev  he is same person  and its no change he is not scammer

**Comment by playingo** [comment]
@Bexps no one cares (this is the wrong place btw) so fuck you, thats a classic kid move.

**Comment by herothedev** [comment]
@Bexps LOL? He isnt same person...

**Comment by Bexps** [comment]
@playingo  fucking stupid kids u ratting people lmao i laugh you kasdjfksafhjdfjadsfh

**Comment by Bexps** [comment]
@herothedev  if you didnt show up mother fucker

**Comment by herothedev** [comment]
Uhm... They are not, can i see (un-edited) screenshot of Willi123yao (real) says im yaoyao. or do you just say cuz on Willi123yaos name is yao end of the name??? (thay doesnt make any sense.

**Comment by playingo** [comment]
@Bexps im not ratting anyone for like 2 years now, you are literally the one who rats himself kid. shut the fuck up now no one cares if hes a fucking scammer you fucking 12 year old turkish immigrant.

**Comment by Mempler** [comment]
As @ardakurucim already said, This is not osu! Support.

Yaoyao is a completely different person and has nothing to do with anyone here!

**Comment by Mempler** [comment]
I can also tell why. @willi123yao has a better English knowledge than that guy.

**Comment by Haojerh** [comment]
Kiddo gay it 100% your fault u didn't say how many ram and keep making the guy mad so the action is normal people will do
