### ISSUE TITLE
Punch effect.

### ISSUE THREAD

**Issue by MeNoFade** [GrowtopiaNoobs/GrowtopiaServer#74]
How change punch effect? It's some packet or no?

**Comment by DrOreo002** [comment]
You'll have to learn cpp and learn how to send packet to the client and thr server.

And yes you'll have to mess around with packets

**Comment by NotDark** [comment]
that is like same   /state

**Comment by MeNoFade** [comment]
> that is like same /state
> search sendstate in source u will found something

Thank you very much!
