### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by triple14** [GrowtopiaNoobs/GrowtopiaServer#741]
Whenever I try to start the server with https://drive.google.com/file/d/11uiY2FA-eiY_qFuet2huruztmxq4qwXQ/view , and I do "Start the server!" it comes up with an 3 errors; 

What do i do, MSVCP140D.dll was not found. VCRUNTIME140D.dll , ucrtbased.dll was not found.
Is there a way to fix this? I already have Microsoft c++ 2015 redistributable  14.0.23026

**Comment by herothedev** [comment]
Install Visual Studio 2015 with C++ plugins.

**Comment by NotDark** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=52685

**Comment by triple14** [comment]
Done everything, UCRTbased.dll is missing.

**Comment by herothedev** [comment]
download it here: 64bit: https://www.dll-files.com/download/c3130cfb00549a5a92da60e7f79f5fc9/ucrtbased.dll.html?c=eVJCOGxlSEc3aHZYV2trb2p0dlZRZz09 32bit:https://www.dll-files.com/download/d2e30ccb8427870b1f8b3c2ecb6563bf/ucrtbased.dll.html?c=eVJCOGxlSEc3aHZYV2trb2p0dlZRZz09 and put it into server.exe folder where is your server.exe and run server.exe as administrator.

**Comment by willi123yao** [comment]
Unofficial/modified builds are not supported by us so please do not open issues regarding these builds (basically any server exe/code that someone gave you), and you should have contacted those who gave you the files instead. 

Only sources compiled with Visual Studio by yourself and built using the source code in the repository **without modification** will be supported, and these errors should not appear if you have done so in this way.

Closing this issue.
