### ISSUE TITLE
Anyone Know all of the packet types?

### ISSUE THREAD

**Issue by OverallGod** [GrowtopiaNoobs/GrowtopiaServer#744]
I know some of them like 7 is for the main door and 11 is for taking items

**Comment by herothedev** [comment]
You can figure them out by adding logging (advenced) into your server (i think u already have), and then just click random things. (idk did u mean this but..)

**Comment by ardakurucim** [comment]
@herothedev its so hard to try it 1 by 1 what is the damn sign packet type

**Comment by herothedev** [comment]
Use GTBot? and playingo told the packet isnt easy to use.

**Comment by OverallGod** [comment]
I was logging it 
i noticed that every time i wrench something 3 comes up.
the reason i started this is to see if anyone figured out some that I haven't.
But thanks anyway @herothedev also I think the bot was patched in the real servers.

**Comment by ritzysw** [comment]
tank update packet type 3 is for tile updates, and bot never got patched

**Comment by herothedev** [comment]
and never will, you just need to fix few things if its not working for u (use GTBOT source and edit it on Qt)

**Comment by herothedev** [comment]
+ @OverallGod if u was wrenching its most likely the 3 yours netid. or the player what was under wrenching.

**Comment by OverallGod** [comment]
@herothedev ritzy already said it was for tile updates. It only showed up when I was wrenching things like a punch jammer

**Comment by atomiclucky** [comment]
0 is the tank update packet,      
18 is the dialog packet

**Comment by InjectionZ** [comment]
what is for checkpoint?
