### ISSUE TITLE
Cannot add Admin

### ISSUE THREAD

**Issue by triple14** [GrowtopiaNoobs/GrowtopiaServer#746]
I add under
`enet_initialize();`
addAdmin(Matty, "123", 999)
and for some reason I cannot do Admin commands or admin things. What should I do?

I've also Added OverallGod's Better Admin System, 
https://github.com/GrowtopiaNoobs/GrowtopiaServer/pull/740/commits/6147a331f5ea99ceda93c8b3ba19dfa3fef8ea12

and edited the player .json files and that does not seem to work. I'm not asking for code, just what should I do?

**Comment by herothedev** [comment]
because its addAdmin("Matty","123",999); not addAdmin(Matty,"123",999);...

**Comment by OverallGod** [comment]
in order for my system to work you need to change the commands.

**Comment by triple14** [comment]
> in order for my system to work you need to change the commands.

Just realised that and im 100% stupid , thanks for the help. I have fixed it!

**Comment by triple14** [comment]
> because its addAdmin("Matty","123",999); not addAdmin(Matty,"123",999);...

Also tried this on my other ps, doesn't work, but ive fixed it thanks

**Comment by herothedev** [comment]
then cloose this issue?

**Comment by triple14** [comment]
> in order for my system to work you need to change the commands.
thanks. I've figured that and understand that.





> because its addAdmin("Matty","123",999); not addAdmin(Matty,"123",999);...
I've tried that , then when I try to build, it says , undefined Matty and wont build

**Comment by NotDark** [comment]
addAdmin("matty", "123", 999);

**Comment by triple14** [comment]
> addAdmin("matty", "123", 999);

That's why! Caps, didn't know why I didn't figure that out LOL
