### ISSUE TITLE
Just got a VPS, PLEASE HELP

### ISSUE THREAD

**Issue by LeaveGT** [GrowtopiaNoobs/GrowtopiaServer#749]
I got a VPS, but what do i do? all i did was setup the xampp and all but how to port faward and all that..

**Comment by LeaveGT** [comment]
also PLEASE do step by step and make it undertandable.

**Comment by NotDark** [comment]
you dont need to port forward if you have vps

now you need make new folder "growtopia" at C:\xampp\htdocs

and put server_data.php inside the growtopia folder also change the ip in server_data.php to your vps ip

now you need allow port tcp 80 udp 17091 in firewall

**Comment by BITHUBCO** [comment]
@NotDark do you change wifi firewall or vps firewall?

**Comment by NotDark** [comment]
> @NotDark do you change wifi firewall or vps firewall?

> vps firewall

**Comment by NotDark** [comment]
> @NotDark do you change wifi firewall or vps firewall?

  vps firewall

**Comment by LeaveGT** [comment]
Outbound or inbound im createding a role becuse..

**Comment by triple14** [comment]
What VPS are you using?(Offtopic)

**Comment by Deveytv** [comment]
Please close this issue if resolved.

**Comment by GrowtopiaNoobs** [comment]
Closing this issue as there was no new activity.
