### ISSUE TITLE
OnParticleEffect syntaxe

### ISSUE THREAD

**Issue by MeNoFade** [GrowtopiaNoobs/GrowtopiaServer#75]
Hello all. Can someone help me? Please say syntaxe for OnParticleEffect or for OnParticleEffectV2. I try find from old MacOs decompiled version, but have tons of variants. I try use int, float, float, float; string, float, float, float; string; int; But it's doesnt work. If someone know, can say syntaxe, please.

**Comment by NotDark** [comment]
i think i found the  syntaxes  but i cant get it work and can i have the decompiled thing?

**Comment by MeNoFade** [comment]
> i think i found the syntaxes but i cant get it work too and can i have the decompiled thing? btw do u have discord?

I don't have discord:( I have macOs old version on Hex-Ray. Maybe it's != decompiled. I think you have this version, too.

**Comment by MeNoFade** [comment]
> i think i found the syntaxes but i cant get it work too and can i have the decompiled thing? btw do u have discord?

![image](https://user-images.githubusercontent.com/44878241/48420453-872a1880-e76b-11e8-92b7-418133971e41.png)
I thought it's syntaxe, but it's doesn't work:(

**Comment by NotDark** [comment]
i found that  is use float float float string intx  
![image](https://user-images.githubusercontent.com/44568476/48420544-a0e05580-e795-11e8-9535-1dbfed2d527b.png)

**Comment by MeNoFade** [comment]
> i found that is use float float float string int
> and where do u get hex-ray? @MeNoFade

I download hex-ray, lol.  Some  floats it's coords?

**Comment by NotDark** [comment]
> > i found that is use float float float string int
> > and where do u get hex-ray? @MeNoFade
> 
> I download hex-ray, lol. Some floats it's coords?

i mean the link of hex-ray one of the float is player coords

**Comment by MeNoFade** [comment]
> > > i found that is use float float float string int
> > > and where do u get hex-ray? @MeNoFade
> > 
> > 
> > I download hex-ray, lol. Some floats it's coords?
> 
> i mean the link of hex-ray one of the float is player coords

https://yadi.sk/d/RG9p6Vqu3NRckp , but this russian site

**Comment by NotDark** [comment]
> > > > i found that is use float float float string int
> > > > and where do u get hex-ray? @MeNoFade
> > > 
> > > 
> > > I download hex-ray, lol. Some floats it's coords?
> > 
> > 
> > i mean the link of hex-ray one of the float is player coords
> 
> https://yadi.sk/d/RG9p6Vqu3NRckp , but this russian site

so i get that  Particle work

just use appendfloat appendintx appendstring

**Comment by MeNoFade** [comment]
> > > > > i found that is use float float float string int
> > > > > and where do u get hex-ray? @MeNoFade
> > > > 
> > > > 
> > > > I download hex-ray, lol. Some floats it's coords?
> > > 
> > > 
> > > i mean the link of hex-ray one of the float is player coords
> > 
> > 
> > https://yadi.sk/d/RG9p6Vqu3NRckp , but this russian site
> 
> so i get that Particle work
> 
> just use appendfloat appendintx appendstring

What you use on String?

**Comment by NotDark** [comment]
s

> > > > > > i found that is use float float float string int
> > > > > > and where do u get hex-ray? @MeNoFade
> > > > > 
> > > > > 
> > > > > I download hex-ray, lol. Some floats it's coords?
> > > > 
> > > > 
> > > > i mean the link of hex-ray one of the float is player coords
> > > 
> > > 
> > > https://yadi.sk/d/RG9p6Vqu3NRckp , but this russian site
> > 
> > 
> > so i get that Particle work
> > just use appendfloat appendintx appendstring
> 
> What you use on String?

string are OnParticleEffect

**Comment by MeNoFade** [comment]
> s
> 
> > > > > > > i found that is use float float float string int
> > > > > > > and where do u get hex-ray? @MeNoFade
> > > > > > 
> > > > > > 
> > > > > > I download hex-ray, lol. Some floats it's coords?
> > > > > 
> > > > > 
> > > > > i mean the link of hex-ray one of the float is player coords
> > > > 
> > > > 
> > > > https://yadi.sk/d/RG9p6Vqu3NRckp , but this russian site
> > > 
> > > 
> > > so i get that Particle work
> > > just use appendfloat appendintx appendstring
> > 
> > 
> > What you use on String?
> 
> string are OnParticleEffect

Sorry, for idiot question, but what you use on IntX and Float? D:. Because for me it's doesn't work:(

**Comment by MeNoFade** [comment]
> s
> 
> > > > > > > i found that is use float float float string int
> > > > > > > and where do u get hex-ray? @MeNoFade
> > > > > > 
> > > > > > 
> > > > > > I download hex-ray, lol. Some floats it's coords?
> > > > > 
> > > > > 
> > > > > i mean the link of hex-ray one of the float is player coords
> > > > 
> > > > 
> > > > https://yadi.sk/d/RG9p6Vqu3NRckp , but this russian site
> > > 
> > > 
> > > so i get that Particle work
> > > just use appendfloat appendintx appendstring
> > 
> > 
> > What you use on String?
> 
> string are OnParticleEffect the float thing is player coords

Thank you very much!
