### ISSUE TITLE
I need the Updated HASH, mine is old

### ISSUE THREAD

**Issue by LeaveGT** [GrowtopiaNoobs/GrowtopiaServer#750]
I dont need auto hash i just need the new hash numbers, also think before typing i see rude comments about you guys dont help each other this is a group to help each other. i just gave away my CPP witch was pro with 0 errors... be more caring or just leave this Github group.

**Comment by flossboss** [comment]
Try #248

**Comment by flossboss** [comment]
If you have ilyn's GTAPI just remove 2 of the functions (I think that's what they are)

**Comment by flossboss** [comment]
Auto hash is the best way to do it in my opinion

**Comment by flossboss** [comment]
Idk about other ways :/

**Comment by willi123yao** [comment]
It would be really appreciated if you can search the issues for how to get new hash as this has been an issue brought up more than several times. 

You might want to take a look at these issues: #20 and #94 

From #20 I quote: ([from GrowtopiaNoobs](https://github.com/GrowtopiaNoobs/GrowtopiaServer/issues/20#issuecomment-429581396))
> There are only two way to get those values:
> 
> 1. Use my bot to extract them from original gt server
> 2. Get start function from cheat engine/decompile gt and then calculate items.dat hash
> 
> And ye, those values look random. First one is probably to protect gt from cheaters who are using older gt versions and second to keep items.dat updated with minimal bandwidth required.

The second method has been found like what @flossboss has said and you can look at #143 or #248 to see how it works or how to add it to your code respectively.

**Comment by GrowtopiaNoobs** [comment]
Closing this issue as it has been answered.
