### ISSUE TITLE
Not really an issue with the code 

### ISSUE THREAD

**Issue by triple14** [GrowtopiaNoobs/GrowtopiaServer#751]
Whenever I get code in the pull requests and put it into the source code I have, the whole source breaks, 300+ errors that aren't related to the pull request stuff I get, its related to random crap and that never happens when I don't paste the code from pull request.

what do I do?

**Comment by willi123yao** [comment]
Please do give examples such as which pull request you are trying to add and make sure you did not make any mistakes while transferring the code over (like putting it into the wrong place or location).

The recommended way is that you use a git client such as Github Desktop to directly get the pull request and it will give you the version of the code with the code added for you.

**Comment by triple14** [comment]
> Please do give examples such as which pull request you are trying to add and make sure you did not make any mistakes while transferring the code over (like putting it into the wrong place or location).
> The recommended way is that you use a git client such as Github Desktop to directly get the pull request and it will give you the version of the code with the code added for you.

Thank you, i'll try GitHub desktop , I try this without that

https://github.com/GrowtopiaNoobs/GrowtopiaServer/pull/646/commits/3ee9bed7c08c0c16aa4e2d245d869c7856c2711a
and it breaks everything

and then I use this

https://github.com/GrowtopiaNoobs/GrowtopiaServer/pull/633

and it breaks everything

**Comment by triple14** [comment]
> Please do give examples such as which pull request you are trying to add and make sure you did not make any mistakes while transferring the code over (like putting it into the wrong place or location).
> The recommended way is that you use a git client such as Github Desktop to **directly get the pull request and it will give you the version of the code with the code added for you.**

im quite stupid, I've downloaded the GitHub desktop and idk what to do(the part where idk what to do is highlighted in bold in the quote.)

**Comment by willi123yao** [comment]
Please refer to GitHub documentation for GitHub Desktop (also, google is your good friend, use it): https://help.github.com/en/desktop/contributing-to-projects/accessing-a-pull-request-locally

These apply only to pull requests not yet approved like #646, but for those approved and accepted will be inside the main code (enet server test.cpp) so you don't need to manually add it.

**Comment by ardakurucim** [comment]
@triple14 i did it wrong delete last } thingie

**Comment by triple14** [comment]
> @triple14 i did it wrong delete last } thingie
@ardakurucim , yeah but when i paste in anyones pull request, it breaks like 50% of the actual source code.

**Comment by flossboss** [comment]
Oh @triple14 you can also just use ilyn's GTAPI and add this to you code
`GetHashOf("PATH OF ITEMS.DAT");`
but make sure you have the GTAPI included and remember to have this added at the top of your code:
`#include "GTAPI.h"`

**Comment by flossboss** [comment]
@triple14 did you check syntax errors? Try putting another } after the code you pasted and if that doesn't position the code then try removing } slowly and see of your errors fix. This minimizes the errors which then should be easier to fix.

**Comment by triple14** [comment]
I've got everything working now! Thanks guys
