### ISSUE TITLE
How to compile x64 ?

### ISSUE THREAD

**Issue by playingo** [GrowtopiaNoobs/GrowtopiaServer#755]
Does anyone know how to? Anyways, i am confused with this: 
![image](https://user-images.githubusercontent.com/50752911/62820613-192e4880-bb67-11e9-90d2-f30771d1b6c4.png)
maybe its an easy solution and im stupid idk

**Comment by atipls** [comment]
i think the problem here is ur incompetence to code

**Comment by OverallGod** [comment]
Lol I know the error. Hit me up on discord @jordan#0495

**Comment by triple14** [comment]
> Lol I know the error. Hit me up on discord @jordan#0495

Add me back please.

**Comment by playingo** [comment]
Issue solved. Needed to use 64bit enet library (included in /enet2) damn i should have known that. anyways, issue closed.
