### ISSUE TITLE
What is the sign packet and how to use it?

### ISSUE THREAD

**Issue by atomiclucky** [GrowtopiaNoobs/GrowtopiaServer#756]
Hey I was wondering does someone know what is the sign bubble packet and how to trigger it? Please provide code example

**Comment by ardakurucim** [comment]
there is no packet for sign i think and its packet type 5 maybe im not sure ( also anybody wont give the information )

**Comment by OverallGod** [comment]
There isn't a packet for it

**Comment by OverallGod** [comment]
I think you need to use pointers

**Comment by playingo** [comment]
i have full signs (see here: 
![image](https://user-images.githubusercontent.com/50752911/62832878-9627f380-bc35-11e9-8410-0c56cc8ffc44.png)) and only thing i can tell u is that
you need to call memcpy like 5-10 times lmao

**Comment by atomiclucky** [comment]
bruh

**Comment by atomiclucky** [comment]
that what i thought

**Comment by atomiclucky** [comment]
you need to use gtbot, perhaps?

**Comment by herothedev** [comment]
yes.

**Comment by atomiclucky** [comment]
yo does anyone know what to change in order gtbot to work

**Comment by herothedev** [comment]
U just need to download Qt 5.3.2 and then edit the build steps, cuz if u dont u just get Makefile, Makefile.Debug and Makefile.Release and i dont know how to setup them correctly for windows.

**Comment by atomiclucky** [comment]
@herothedev you forgot that i need to download tool extension on vs so that i would have the vs 2013 x86 compiler

**Comment by herothedev** [comment]
you alr have... when u donwload the right ver of that u get it automatically..

**Comment by atomiclucky** [comment]
@herothedev yo help me out, i changed the version string but in debug it shows that it's still outdated. Do you know what string to put in?
![paveikslas](https://user-images.githubusercontent.com/49339987/62878018-f18adc00-bd30-11e9-89cc-3cfe11649733.png)
![paveikslas](https://user-images.githubusercontent.com/49339987/62878096-15e6b880-bd31-11e9-8929-36fe62936916.png)

**Comment by moanhawks** [comment]
Ask issues gt bot not here

**Comment by atomiclucky** [comment]
noone responds at that repository

**Comment by herothedev** [comment]
@atomiclucky, you just need to enter new version when u r running gtbot.exe and tgen press enter.

**Comment by atomiclucky** [comment]
no, you need to change the whole packet

**Comment by InjectionZ** [comment]
change protocol to 71

**Comment by atomiclucky** [comment]
yeah i already have done that
