### ISSUE TITLE
[BUG] Growmoji [NEW BUG]

### ISSUE THREAD

**Issue by Deveytv** [GrowtopiaNoobs/GrowtopiaServer#758]
BUG when do example : (lol) (smile) and all emoji cmd when click enter and is not emoji the text is "?" like that

**Comment by herothedev** [comment]
its sambu as me???

**Comment by herothedev** [comment]
#742

**Comment by Deveytv** [comment]
> its sambu as me???

Hm See the FIXED maybe Void

**Comment by herothedev** [comment]
no? u dont understand? when i do (lol) it cames. Ä (smile) = ?, (wl) = Ä, (gem) = ? etc. i dont get this error : "compiler limit: block placed too nesty", i have many voids outside my main, so in main there is 25% of server code anymore.

**Comment by moanhawks** [comment]
Go use void is working to me if use void to string like [void sendAction] code

**Comment by herothedev** [comment]
It doesnt help why there is so many indos that wont understand englishhhh
