### ISSUE TITLE
[BUG & QUESTION] Abort() -> triggered by not empty worlds folder & Question

### ISSUE THREAD

**Issue by Faxtos** [GrowtopiaNoobs/GrowtopiaServer#760]
1. Bugs: Microsoft runtime c++ error when re-execute (close & start again) the run.py (caused by not empty worlds, another that like players is safe)

2. Question: how to add self talk, like when wrench wl in real gt, it shows That area is owned by .... (only to you, not to all player in the world, so, are the OnTalkBubble is used here? and how?)

**Comment by herothedev** [comment]
2. Yes, Ontalkbuble is used, just remove the currentPeer thing lol

1. Install visual studio 2015 or 2017 or 2019 with C++ Coding Extension. And just delete all worlds/players what are 0KB/0B that means they r corrupted so you could use different database, and yes it isnt easy to recode whole database things.

**Comment by Faxtos** [comment]
^ Ok i will try it, thanks...

^^ its annoying to delete again every start the run.py hehe. Thanks for it again, maybe someone have fixed it?

**Comment by herothedev** [comment]
@Faxtos ofc many guys alr did recode whole database to make corruptions that they are dvery rarely happening, i could recommend for u MySQL, it isnt easy.

**Comment by Faxtos** [comment]
Its gonna be fun, i'll try it. Closing

**Comment by Faxtos** [comment]
I found how to fix, just add comment in the begining of `enet_host_destroy`
