### ISSUE TITLE
What is formatting for SetRespawnPos

### ISSUE THREAD

**Issue by InjectionZ** [GrowtopiaNoobs/GrowtopiaServer#763]
What is needed for SetRespawnPos

**Comment by playingo** [comment]
its unneccessary you can externally position your respawn server sidedly.

**Comment by playingo** [comment]
setrespawnpos is used for syncing btw

**Comment by iProgramMC** [comment]
SetRespawnPos is used for checkpoint visuals. 

formatting is as follows:
```
GamePacket packet = packetEnd(appendInt(appendString(createPacket(), "SetRespawnPos"), respos));
memcpy(packet.data + 8, &PlayerNetID, 4);
```

**Comment by iProgramMC** [comment]
Forgot to clear up something, respos is really y*width+x

**Comment by GrowtopiaNoobs** [comment]
Closing this as it was answered.
