### ISSUE TITLE
What is the sign world pointer?

### ISSUE THREAD

**Issue by atomiclucky** [GrowtopiaNoobs/GrowtopiaServer#765]
Ok so there is no sign **packet**.
The sign text and other information get sent with the worldptr.
But the question is how to interpret the gotten data?
This is what I get when I enter the world PARKOUR

 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 222 222x
  0 0 0 0 0 0 22 2 0 0 0 0 1 80 1 b 0 60 31 50 41 52 4b 4f 55 52 20 21 8 22 2 0 0 0 0 1 80 1 b 0 60 31 50 41 52 4b 4f 55 52 20 21 8 6 1 0 0 0 0 0 0 6 1 0 0 0 0 0 0 6 1'1PARKOUR 
 222 222x
  4f 55 52 20 21 8 22 2 0 0 0 0 1 80 1 b 0 60 31 50 41 52 4b 4f 55 52 20 21 8 6 1 0 0 0 0 0 0 6 1 0 0 0 0 0 0 6 1 0 0 0 0 0 0 6 1 0 0 0 0 0 0 6 1 0 0 0 0 0 0 6 1'1PARKOUR 
 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 106 0 0 292 292x
  0 0 0 0 20 0 92 2 0 0 0 0 21 0 2 0 0 ff ff ff ff 0 0 0 0 0 0 0 0 d6 2 0 0 0 0 0 0 0 0 0 0 0 0 20 0 0 0 0 0 0 0 20 0 0 0 0 0 0 0 20 0 e4 8 0 0 0 0 20 c0 00 2d6 0 0 0 8e4 0 0 106 0 106 0 8e4 106 0 0 0 0 8e4 0 0 0 0 8e4 0 106 106 8e4 0 0 0 0 0 0 0 0 0 106 0 0 0 0 0 0 106 0 0 106 8e4 0 0 0 0 8e4 0 0 0 8e4 0 0 0 0 0 106 0 0 0 0 0 0 0 8e4 0 0 0 106 0 0 106 0 0 0 106 0 0 0 8e4 0 106 0 106 0 0 0 292 292x
  0 0 0 0 20 0 92 2 0 0 0 0 1 0 2 0 0 ff ff ff ff 6 1 0 0 0 0 20 8 6 1 0 0 0 0 0 0 0 0 a4 1 0 0 20 0 0 0 0 0 0 0 20 0 0 0 0 0 0 0 0 0 0 0 a4 1 0 0 20 0 8a106 106 0 0 0 0 48a 0 0 0 0 0 0 106 0 8e4 0 0 106 0 0 8e4 0 0 0 0 0 0 0 0 106 8e4 0 0 0 0 0 0 0 0 0 0 106 0 8e4 0 3e6 8e4 3e6 106 0 0 106 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 8e4 0 0 0 0 0 0 0 0 0 0 0 8e4 0 0 8e4 0 0 0 106 0 0 0 0 0 48a 0 8e4 0 6a6 0 0 106 106 220 2601 3160 634c20 742160 602160 d80 ba00 656a64 6f0 6 1 0 8 0 a401 e600 1e600 e600 0 0 e400 9ac0 0 0 0 0 600 600 0 0 0 0 600 1600 10 10 10 10 10 0 10 0 0 0 600 0 0 1600 0 0 0 0 0 0 0 0 0 0 600 600 0 0 0 0 600 1600 600 4000 4000 14000 4000 14000 4000 14000 14000 1e400 140c0 1e400 140c0 1e400 140c0 4000 4000 e400 40c0 e400 40c0 e400 40c0 e400 c0 0 0 0 e00 600 600 1600 1600 600 1600 600 600 600 600 600 600 600 600 1600 1600 1600 1600 1600 1600 1600 1600 1e400 e4c0 1e4c0 6c0 1600 1600 1e400 16c0 10 1e400 16c0 10 1e600 1e600 10 10 600 600 0 0 0 0 10 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1600 600 10 0 1e600 e600 10 600 600 600 600 600 600 600 600 600 1600 600 1600 1600 600 1600 1600 1600 1600 600 1600 600 1600 1600 600 1600 1600 0 0 0 0 e00 600 600 0 0 0 0 0 0 0 0 1600 0 0 0 0 0 e400 1e4c0 c0 0 0 600 600 600 600 0 1e400 c0 2000 120 607263 2068 743a20 322121 1 a401 0 0 9200 200 ff0 0 106 106 0 0 0 0 0 58c 58cx
  0 0 0 0 20 0 8c 5 0 0 0 0 11 0 e 3b 0 60 21 53 6f 6e 67 20 3a 20 60 23 43 72 79 73 74 61 6c 20 53 68 69 70 20 2d 20 50 61 72 74 20 31 20 60 30 43 6f 6d 70 6f 73 65 64 20 62 79 20 60 32 4b 65 6e 6e2d20 612031 2079 0 2404 37600 10 0 a400 0 0 0 a400 0 5 676e 207972 616968 2d7472 206d6f 6e65 42 22b4 ca0 0 20 10 30 30 0 20 38 10 31 1000 3000 1800 11000 3000 3800 2000 80 0 0 0 0 0 2000 2000 2000 2000 2000 0 82000 2000 2000 0 0 2000 0 2000 0 22000 2000 2000 0 0 22000 10 10 2000 0 0 2000 2000 2000 12000 0 49800 2000 2000 2000 2000 2000 2000 0 2000 12000 2000 4a000 0 2000 0 2000 0 1000 10 12000 11800 2000 1000 13800 1000 3000 3800 3000 3000 3000 13800 13800 13800 3000 1000 11000 11800 10 3000 0 2000 2000 2000 3000 10 10 10 0 0 12000 10 10 2000 3000 3000 1800 3000 1000 13000 2000 2000 3800 2000 3000 2000 2000 0 2000 0 0 2000 0 0 2000 1000 3000 3000 3000 3800 3000 3800 3000 0 3000 81000 3000 0 0 0 11000 11000 10 32000 2000 82000 52000 52000 50 52000 52000 52000 0 2000 0 2000 2000 0 12000 12000 10 10 10 2000 32000 0 2000 32000 52000 80 82000 12000 2000 0 80 12000 12000 a2100 356854 526f20 53776f 5228 647261 ffff 1 1 e202 c2 0 fe00 fc02 1602 1600 0 0 0 0 600 600 0 10 1a00 1200 604f4e 52ffff 1a4 101a4 1a4 1a4 301a8 381a4 381a8 116000 646e69 3860 655d6d 6472 6f726f 30 18 10 30 18 a40 20 0 20 a820 0 10 0 20 0 a40 0 a420 20 0 20 a80 a40 a40 a420 a40 a40 a420 a40 a820 a420 a820 0 a80 0 0 c020 20 0 20 20 c000 20 c000 10 30 10 c000 20 20 20 20 20 20 10 0 0 20 0 c030 20 10 20 20 20 0 0 20 c018 38 10 10 38 19 2120 13000 31000 33800 3000 121000 33000 31000 201900 ffff 0 0 0 60 60 0 0 0 e60 e60 0 0 60 e20 15021 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 c00 202160 632120 316874 652072 602160 e40 400 60 60 60 400 400 e40 0 0 0 60 e60 e60 e60 0 0 60 0 0 0 0 60 0 0 60 200 14634 4c2160 697261 726f 2120 11800 13800 b3100 9e106 e20 0 0 c00 0 0 0 59c 2 ff1 0 600 0 14600 1800 1200 0 a402 0 ff0 300 100 180 100 116 5 4000 e400 140c0 4000 4000 e400 1e4c0 e4c0 1e4c0 40c0 4000 4000 4000 e400 140c0 4000 4000 4000 14000 4000 14000 4000 4000 4000 4000 4000 4000 600 600 600 4000 e400 c0 0 0 e400 c0 0 0 0 e400 c0 0 0 0 0 0 e400 c0 600 0 e400 e6c0 e600 e600 e400 c0 0 0 0 0 600 0 600 0 e400 c0 600 600 600 8000 2 11a00 1200 60544e 4c4d4f 1842 a41 1 0 0 0 0 a403 0 11a00 200 606966 617369 554f ffff 0 16000 4f626f 2d31 1 600 1e00 10 10 0 0 600 600 600 1600 1600 1600 600 1600 e400 16c0 600 1600 600 1600 600 1e400 e4c0 16c0 600 1600 600 600 e400 6c0 600 600 1600 600 1e400 6c0 600 1600 600 1600 4000 4000 0 4000 4000 4000 0 0 0 0 0 0 0 0 0 0 0 600 0 600 0 0 e600 0 e600 19a00 10 1e400 c0 10 19a00 18a00 0 600 0 0 0 0 2000 120 607263 6874 652072 602160 60 60 60 60 60 a60 0 1a0 24e34 74206f 6e65 2d57 3832 ff0 0 0 0 a1a 1f02 216b6e 666c70 694150 4f2021 f10b 0 106 106 106 106 106 106 106 20e 0 19a a1a 1202 217420 206570 21ff 8000 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 20 10 10 52000 80 2000 2000 0 48000 2000 0 2000 0 0 0 1000 1800 83000 3000 1000 11000 1800 11800 13000 11000 11000 83800 13000 13800 51800 11800 13000 11800 11000 11000 11000 12000 10 4a000 10 12000 10 10 10 0 2000 81000 13000 12000 12000 10 0 2000 10 12000 10 10 82000 0 2000 0 0 2000 81000 52000 50 52000 52000 52000 52000 52000 52000 80 80 82000 52000 52000 52000 50 52000 80 82000 50 53000 51000 51000 53000 53800 83000 53000 53000 51000 53000 53800 81000 53000 51000 53000 1000 1000 21000 10 10 52000 50 52000 52000 50 50 2000 10 0 80 0 2000 2000 80 10 22000 10 11000 3000 3800 49000 0 80 2000 0 0 0 0 0 2000 0 0 0 0 0 2000 0 0 0 2000 10 2000 2000 0 0 0 0 10 0 2000 10 2000 48000 2000 2000 0 0 2000 0 2000 2000 2000 0 2000 2000 0 0 0 0 0 0 2000 2000 0 2000 2000 2000 0 0 2000 2000 2000 2000 2000 2000 2000 2000 2000 2000 0 2000 2000 2000 2000 48000 12000 0 20 10 10 10 12000 12000 10 12000 12000 10 52000 10 10 10 12000 10 12000 12000 12000 10 12000 50 10 12000 2000 10 2000 2000 0 2000 2000 2000 0 3000 3000 1000 1800 3800 3000 1800 0 2000 2000 12000 0 12000 2000 0 0 2000 10 3800 0 10 2000 50 50 50 50 50 50 50 51000 53800 51000 53800 83000 51000 53800 51000 51000 51000 53000 51800 51000 53800 53000 83000 51800 52000 50 50 50 52000 81800 82000 50 52000 52000 52000 52000 80 52000 52000 52000 52000 50 52000 50 52000 12000 10 12000 0 80 2000 2000 0 2000 20 81000 81000 81000 81800 11800 11000 2000 12000 2000 2000 0 0 0 80 2000 80 2000 0 80 0 82000 0 80 2000 0 80 2000 2000 80 2000 2000 80 2000 80 2000 12000 10 10 0 80 10 2000 2000 10 0 10 12000 10 12000 12000 12000 12000 10 12000 10 12000 10 10 12000 12000 12000 12000 10 10 10 10 12000 10 10 10 12000 10 12000 10 12000 10 10 10 10 12000 10 10 11000 12000 13800 13000 11000 10 12000 10 10 10 10 22100 266553 6576 687474 204632 21a400 0 a405 0 10 10 0 0 0 e400 6c0 0 600 e600 e600 e600 e600 0 600 9a00 0 0 10 600 1e400 16c0 1e400 6c0 1e400 1e4c0 16c0 e400 1e4c0 16c0 1e400 e4c0 16c0 19a00 0 0 600 0 0 0 0 600 10 0 600 0 10 0 10 14000 10 18a00 10 14000 10 10 1e400 1c0 0 0 0 e400 c0 0 0 0 0 0 0 8a00 0 0 4 e400 c0 0 4000 e400 c0 0 0 e400 1c0 10 14000 14000 14000 14000 14000 14000 4000 4000 600 600 600 600 600 600 600 4000 4000 0 10 0 10 0 1600 0 1600 1e600 10 0 10 e00 1600 600 1600 1600 e400 6c0 0 600 0 600 0 0 600 0 0 600 0 0 600 600 1600 600 1600 10 10 0 10 1600 0 0 600 0 0 0 0 8a00 0 4000 0 8a00 0 0 0 0 0 0 0 0 0 0 0 e00 0 0 0 4000 0 0 4000 0 0 0 8a00 0 0 0 0 0 0 0 4000 0 ca00 0 0 0 9200 200 ff540 106 106 292 292x
  0 0 0 0 0 0 92 2 0 0 0 0 1 0 2 0 0 ff ff ff ff 0 0 0 0 0 0 0 0 0 0 0 0 0 0 20 0 0 0 0 0 0 0 20 0 0 0 0 0 0 0 20 0 0 0 0 0 0 0 20 0 6 1 0 0 0 0 20 0 00 0 0 0 0 106 0 0 0 0 0 106 0 106 0 8e4 3e6 3e6 3e6 8e4 8e4 106 0 0 106 0 48a 0 48a 0 0 48a 0 0 48a 0 0 48a 0 8e4 0 0 0 8e4 0 0 106 0 0 106 0 0 0 0 540 0 0 0 540 0 0 0 0 0 0 0 0 0 0 0 0 0 0 8e4 0 0 8e4 0 0 0 0 540 0 0 0 540 0 0 0 48a ee0 ee0x
  0 0 0 0 80 0 e0 e 0 0 0 0 21 0 21 e6 3 0 0 0 0 20 0 0 0 0 0 0 0 0 0 a2 6 0 0 0 0 20 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 40 5 0 0 0 0 0 0 6 1 0 0 0 0 03e6 0 6a2 0 0 540 106 106 0 0 69e 0 0 0 106 0 0 8e4 0 0 106 0 106 0 0 0 0 0 0 0 0 3e6 3e6 0 0 106 0 106 0 0 106 0 0 106 0 0 106 0 0 0 0 0 106 8e4 106 106 0 0 106 106 19a 0 540 540 0 8e4 0 540 540 19a 0 0 8e4 0 0 0 0 8e4 0 0 0 8e4 106 0 540 0 0 19a a1a 4102 216320 206165 6568 342059 6568 2e6b6f 1a4 101a6 300 100 100 300 0 0 0 0 0 200 200 16000 6f6165 2749 7420 65ffff 0 0 2160 522052 0 0 1 c cx
  1 0 0 31 0 1 c 0 60 21 60 34 2a 42 72 6f 6b 65 6e 2a 0 0 0 0 0 0 0 10 0 6 1 0 0 0 0 18 0 1a a 0 0 0 0 39 0 2 2c 0 60 21 54 68 65 20 64 6f 6f 72 20 69 73 20 60 34 4c 4f 43 4b 45 44en*

Is there something useful in this mess?

**Comment by MeNoFade** [comment]
![image](https://user-images.githubusercontent.com/44878241/63103127-2ee7a780-bf85-11e9-91ed-175f6cef22bc.png)
Maybe this is can help you. (This is from GTBot corefunc.h)

**Comment by atomiclucky** [comment]
I'm gonna try to get the full uncorrupted packet and send it raw via private server

**Comment by OverallGod** [comment]
Share your results

**Comment by atomiclucky** [comment]
Cpp is hard, you need to keep track of array size

**Comment by playingo** [comment]
anyways, got signs, trading, consumables, fully working real gt, tree packet to send time data etc., pvp, lava killing after 5hits, display blocks, mannequins, wl and bpm (full block visuals etc) btw thanks 2 @willi123yao 's server it had the stuff i needed to i just used bot on it to spy on them since i leaked their shit and their ip. thats how i got trees but the rest i got by using bot on timecold's server and real gt server (well actually esto / mar4ello got them) but i got the tree packets & code (timecold does too now) and i can say only one thing, even if you got the packet, u need to use reverse engineering to actually understand what to do with the packets :D

**Comment by OverallGod** [comment]
@playingo why are you talking about this? If you have no plans of sharing it then don't talk about it.

**Comment by playingo** [comment]
it just was a tip :D https://www.youtube.com/watch?v=53eiVwZ7A2Y

**Comment by OverallGod** [comment]
@playingo Oh alright :)
