### ISSUE TITLE
/rules

### ISSUE THREAD

**Issue by Bykosw** [GrowtopiaNoobs/GrowtopiaServer#766]
//if you want to add rules, just edit add_textbox|
else if (str.substr(0, 6) == "/rules") {
GamePacket p = packetEnd(appendString(appendString(createPacket(), "OnDialogRequest"),
"add_label_with_icon|big|wIn-game rules``|left|6|\nadd_textbox|`wPrivate Server rules!|\nend_dialog|rule1|Cancel|Back!|"));
ENetPacket* packet = enet_packet_create(p.data, p.len,
ENET_PACKET_FLAG_RELIABLE);
enet_peer_send(peer, 0, packet);
delete p.data;

**Comment by triple14** [comment]
Should've did this in a pull request, but thanks.

**Comment by Bykosw** [comment]
> Should've did this in a pull request, but thanks.

np

**Comment by flossboss** [comment]
You should've used better formatting
```
else if (str.substr(0, 6) == "/rules") { GamePacket p = packetEnd(appendString(appendString(createPacket(), "OnDialogRequest"), "add_label_with_icon|big|wIn-game rules``|left|6|\nadd_textbox|`wPrivate Server rules!|\nend_dialog|rule1|Cancel|Back!|"));
ENetPacket* packet = enet_packet_create(p.data, p.len, ENET_PACKET_FLAG_RELIABLE);
enet_peer_send(peer, 0, packet);
```

**Comment by OverallGod** [comment]
Stop using substr PLEASE 🙏

**Comment by ardakurucim** [comment]
@OverallGod +1 because if i type /rulesdjhwalkdjlawkdjwdlakj it still show rules

**Comment by OverallGod** [comment]
Yeah

**Comment by flossboss** [comment]
oops forgot to change when i retyped lol

**Comment by atomiclucky** [comment]
I think even the real gt uses  substr

**Comment by flossboss** [comment]
Real gt uses substr for alot of things

Before /dance2 was introduced they had
```/dance2929493jfhw8dueuud``` and it would be `/dance`
