### ISSUE TITLE
How to host? i have 2vps but i dont know what i do!

### ISSUE THREAD

**Issue by Tumppi05098** [GrowtopiaNoobs/GrowtopiaServer#768]
How to host? i have 2vps but i dont know what i do!
and i need know fast

**Comment by Tumppi05098** [comment]
Can some one help?

**Comment by moanhawks** [comment]
[https://github.com/NotDark/Gt-private-server/wiki/Basic-setup-Server](url)
pls read this

**Comment by Deveytv** [comment]
i see this issue Resolved maybe, please closed it.
