### ISSUE TITLE
[HELP NEEDED]Setting up with Internet Router

### ISSUE THREAD

**Issue by triple14** [GrowtopiaNoobs/GrowtopiaServer#769]
https://cdn.discordapp.com/attachments/583193091914072064/611522315066408960/sadasdasdas.PNG
which one do I add 80TCP and 17091UDP

**Comment by moanhawks** [comment]
Just create 1 by 1
tcp 80
udp 17091

**Comment by triple14** [comment]
> Just create 1 by 1
> tcp 80
> udp 17091

@moanhawks Where do I put 80 for tcp and 17091 udp in the photo, and what do I put as destination ip

**Comment by moanhawks** [comment]
Name just put Growtopia
UDP
17091
17091
you IP desnation mean you IP vps maybe 

Same with TCP 80

Or you can use python to run the server 
Check it out this link 
[https://youtu.be/tH5rl0wOnY0]url

**Comment by triple14** [comment]
> Name just put Growtopia
> UDP
> 17091
> 17091
> you IP desnation mean you IP vps maybe
> Same with TCP 80
> Or you can use python to run the server
> Check it out this link
> https://youtu.be/tH5rl0wOnY0

@moanhawks Thanks, for the ip ill try my public ip then.

**Comment by herothedev** [comment]
ye u need to use ur public ip if no vps

**Comment by triple14** [comment]
> Name just put Growtopia
> UDP
> 17091
> 17091
> you IP desnation mean you IP vps maybe
> Same with TCP 80
> Or you can use python to run the server
> Check it out this link
> https://youtu.be/tH5rl0wOnY0

@moanhawks @herothedev 
https://cdn.discordapp.com/attachments/583193083793899538/612445097874817042/unknown.png
https://cdn.discordapp.com/attachments/583193083793899538/612444400311730202/unknown.png(this photo has my ip to the right I just cropped it out)

Ive done all that and changed the ip in the start.py and it still doesn't work.

**Comment by triple14** [comment]
I just figured out I needed to allow in my firewall the thing woops

**Comment by playingo** [comment]
one of my older routers had the problem that u couldnt forward udp ports (well it said it was sucessful and it even appeared it the ports forward list) but it just never worked with udp sadly even after turning off firewall. new router does the job nowe

**Comment by RajehTXD** [comment]
GET VPS. HOSTING FROM YOUR OWN HOME SERVER WILL MAKE LAG, SINCE THE PLAYERS DOWNSTREAM IS HIGHER  THAN YOUR Upstream. Yes i ment to capitalize

**Comment by GrowtopiaNoobs** [comment]
Closing this as there was no new activity and attachments have dissapeared.
