### ISSUE TITLE
How to setting run.py on 64 bit vps?

### ISSUE THREAD

**Issue by Deveytv** [GrowtopiaNoobs/GrowtopiaServer#774]
can give me the code/tip? @GrowtopiaNoobs @ericsnth @willi123yao @herothedev

**Comment by herothedev** [comment]
Just download Python 2.7 ?

**Comment by ardakurucim** [comment]
wtf download phyton and use it

**Comment by Deveytv** [comment]
No, the setting fp i use wiki tips but it didn't working on 64 bit

**Comment by Deveytv** [comment]
@ardakurucim Or tell how to use on xampp i done setting xampp/htdocs and put folder growtopia
and then i run my exe it's not up, why? can tell me? @herothedev @ardakurucim

**Comment by flossboss** [comment]
it's easy

download python and use the embed in wiki and paste it into a new document
change 127.0.0.1 to ur vps ip
now save file as "run.py" not "run.py.txt"
then run it and your http server should be up

**Comment by ardakurucim** [comment]
@Deveytv did you open ports?

**Comment by Mempler** [comment]
How to setup everything is all in the wiki! i would recommend you to read the whole thing! and not just skip parts. https://github.com/GrowtopiaNoobs/GrowtopiaServer/wiki/Basic-setup#setting-up-http-server
