### ISSUE TITLE
How do I get the x and y coordinates of the block the peer breaks

### ISSUE THREAD

**Issue by Quamozos** [GrowtopiaNoobs/GrowtopiaServer#778]
When I am trying floating gems with sendDrop, it need x and y coordinates of the block peer breaks. Can anyone help about getting x and y coordinates?

**Comment by Quamozos** [comment]
Btw I am new on GitHub. Please do not swear. And I am new at coding too.

**Comment by atomiclucky** [comment]
punchX and punchY

**Comment by NotDark** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/master/enet%20server%20test/enet%20server%20test.cpp#L3807 

the punchX and punchY

if you want use to drop you need *32

**Comment by Quamozos** [comment]
@NotDark Thanks for information. I will try it.

**Comment by Quamozos** [comment]
@NotDark What do you mean by *32? How i can use it? And how to use PlayerMoving?

**Comment by NotDark** [comment]
> @NotDark What do you mean by *32? How i can use it? And how to use PlayerMoving (or whatever)?

int dropx = x*32;

**Comment by Quamozos** [comment]
Thanks. I will try again. :D

**Comment by Quamozos** [comment]
Didn't work. Can you give your Discord name and tag?

**Comment by playingo** [comment]
basically what ur doing with this * 32 thing is that u basically convert punchx or punchy to x or y. btw i used this example code to get coordinates; 
int dropX = (int)punchX * 32
and then the same for y except X will be Y.
if u want to do it vice versa or u wanna convert X to punchX, then just (int)data->x / 32

**Comment by Quamozos** [comment]
Thanks for information @playingo .

**Comment by Secret-8179** [comment]
Hello Everyone This Is GTIO FULLY FOLDER! If You Want to know what the Password of the Exe Dm Me! Discord name: Secret#8179 And Don't hate me Because There are Someone Of gays Send to me Link 5 Seconds I was lucky Copying the link faster! His Name Valkrie! XD Have Good Time! https://github.com/Secret-8179/GTIOFOLDER

**Comment by iProgramMC** [comment]
> Thanks for information @playingo .

have you figured out collecting packets yet?

**Comment by iProgramMC** [comment]
@Quamozos

**Comment by GrowtopiaNoobs** [comment]
Answers were given and this issue is old, so I am closing this.
