### ISSUE TITLE
[HOW?] How do i update HASH?

### ISSUE THREAD

**Issue by triple14** [GrowtopiaNoobs/GrowtopiaServer#779]
I havent done this before, but i want to update to the newest items.dat i have from growtopia game(Paw DAY 3) and i put it in the server folder and it updates item data then dc and repeat.

Sorry , i havent done this before.

**Comment by atomiclucky** [comment]
You need to use gt bot to get the hash

**Comment by flossboss** [comment]
OR you can use AUTOHAS

**Comment by herothedev** [comment]
or the ilyns GTAPI.h and make hash to GetHashOf('items.dat')

**Comment by GrowtopiaNoobs** [comment]
This question was answered, so I am closing this.
