### ISSUE TITLE
[Help] About json (open issue)

### ISSUE THREAD

**Issue by ardakurucim** [GrowtopiaNoobs/GrowtopiaServer#782]
Is there a quick way to save something into json?

**Comment by NotDark** [comment]
use mysql

**Comment by ardakurucim** [comment]
@NotDark isnt json faster than mysql?

**Comment by herothedev** [comment]
Not rly, if you optimize it its fast as json

**Comment by OverallGod** [comment]
My mysql is really fast because it gets all the data on login and saves it to strings and integers and when they disconnect it updates the database

**Comment by OverallGod** [comment]
Also mysql is allot better because you can save one thing or everything unlike json

**Comment by ardakurucim** [comment]
@OverallGod how can i use it?

**Comment by ardakurucim** [comment]
@OverallGod what is the library of it

**Comment by moanhawks** [comment]
If MySQL I need secure example to connection to gt server so I can use MySQL

**Comment by OverallGod** [comment]
@ardakurucim bruh just go to the mysql page install the c++ driver then change linker settings in the project properties then include <mysql.h>

**Comment by ardakurucim** [comment]
kk understand
