### ISSUE TITLE
[BUG] How to get newest items.dat? 

### ISSUE THREAD

**Issue by Deveytv** [GrowtopiaNoobs/GrowtopiaServer#784]
i already login gt real and open file location but now can't see anyone can help me?

**Comment by Quamozos** [comment]
Right click to your Growtopia shortcut and click "Open file location". And then go to cache folder. You see the newest items.dat. (Do not forget reload items.dat from real gt.)

**Comment by Deveytv** [comment]
> Right click to your Growtopia shortcut and click "Open file location". And then go to cache folder. You see the newest items.dat. (Do not forget reload items.dat from real gt.)

No i alr play gt ori and after i play and click open file location growtopia it's not show cache now see
![image](https://user-images.githubusercontent.com/49722651/63751309-473ab900-c8d9-11e9-98c1-ccc284f83fb1.png)

**Comment by NotDark** [comment]
reinstall gt

**Comment by moanhawks** [comment]
You need update really gt first fp

**Comment by Deveytv** [comment]
> reinstall gt

Hey i have error again, when i login it's always dc i alr use new items.dat and auto hash system but still disconnecting why? can tell me #Dark

**Comment by playingo** [comment]
alright sureking, do you think its smart to create an account so you expect people to help you? even if you werent sureking, its always the same stupid question, always the same claim of a "bug" that isnt actually a bug ur just too afraid to ask private chats for items.dat, instead create a whole github thread for this oh yeahhh classic indog.
definition of insanity!!!

**Comment by Deveytv** [comment]
CLOSED ty for bully lol
