### ISSUE TITLE
[BUG] Help me!!! Open this issue please i need help!

### ISSUE THREAD

**Issue by Deveytv** [GrowtopiaNoobs/GrowtopiaServer#785]
How to fix that? please tell me i alr do auto hash and new items.dat but still like that! pls help! 
![image](https://user-images.githubusercontent.com/49722651/63760656-e8ca0680-c8e9-11e9-9dbb-44dab31ca422.png)

Help me @GrowtopiaNoobs @herothedev @FocusedSG @ericsnth @willi123yao @Mempler

**Comment by playingo** [comment]
i smell sureking

**Comment by Deveytv** [comment]
:man_facepalming: -_- i need help rlly fp

**Comment by yua11** [comment]
He 100% is sureking lol just check he history issues

**Comment by moanhawks** [comment]
that problem maybe is 
You didn't add item.dat or you add something like enet_peer_disconnect

**Comment by Deveytv** [comment]
> that problem maybe is
> You didn't add item.dat or you add something like enet_peer_disconnect

when logging in i didn't see  enet_peer_disconnect

**Comment by Deveytv** [comment]
Ok bug has been fixed by myself. close this issue @willi123yao

**Comment by Deveytv** [comment]
thanks For bullying

**Comment by Deveytv** [comment]
im sureking.

**Comment by Deveytv** [comment]
> @Deveytv tell me how u fixed because i have same problem

im sureking.

**Comment by VyteGTPS** [comment]
indog
