### ISSUE TITLE
crash when enter world 

### ISSUE THREAD

**Issue by learntodlgt** [GrowtopiaNoobs/GrowtopiaServer#79]
i dont have core items, items and etc how to get it and also it crash when enter worlds

**Comment by learntodlgt** [comment]
![image](https://user-images.githubusercontent.com/45086552/48596471-23366880-e994-11e8-8cf1-8f36f62e2338.png)

**Comment by HelpmeHelpyous** [comment]
try closing other apps which are running too?
update cpp?

**Comment by learntodlgt** [comment]
Actually three nothings i wore yet

**Comment by herothedev** [comment]
@learntodlgt do you update the version hash there?

**Comment by iNPGT** [comment]
I got the same issue!

**Comment by GrowtopiaNoobs** [comment]
Closing this issue as there has been long time without any activity.
