### ISSUE TITLE
...............................

### ISSUE THREAD

**Issue by FarhanGT** [GrowtopiaNoobs/GrowtopiaServer#791]
`Help` me :(

**Comment by FarhanGT** [comment]
### Please give a Source About Friend System and Level System
**Thank You <3 Alot**

**Comment by BerkTheDev** [comment]
**Are you kidding? Who cares your requests. Do it yourself.**

**Comment by VyteGTPS** [comment]
> **Are you kidding? Who cares your requests. Do it yourself.**

Hey ddoser, coder, ratter, hard................ +++++++!
You can't even code yourself and begging other people so stop flaming here
![image](https://user-images.githubusercontent.com/51130398/63976598-5a58af00-caba-11e9-9c71-4ccb66c8fa5e.png)

**Comment by playingo** [comment]
@VyteGTPS yes if its indog/filipino/turkish nicknane just ignore dont even answer wasting your time xD cuz this is another example of another immigrant :)

**Comment by VyteGTPS** [comment]
kill yourself

**Comment by RajehTXD** [comment]
somebody kill @FarhanGT -/- Thank you in advance.

**Comment by GrowtopiaNoobs** [comment]
I think that this issue is useless now. Closing
