### ISSUE TITLE
Give me a Source Level System, Report System, Adding Friend System, Guild System, and Auto Color Text if Developer, admin, Mods

### ISSUE THREAD

**Issue by FarhanGT** [GrowtopiaNoobs/GrowtopiaServer#792]
### Thank**You **So**Much**

**Comment by FarhanGT** [comment]
Hehe Title too long :D #791

**Comment by DrOreo002** [comment]
Do not ask for codes here. This is a issue tab and used for issues only

**Comment by FarhanGT** [comment]
@DrOreo002 CAN'T IN ANY TAB LOL HMM??

**Comment by DrOreo002** [comment]
You're clearly blind. Hope GrowtopiaNoobs will take care of you asap haha. Go learn cpp kid ;)

**Comment by ardakurucim** [comment]
Wtf enough

**Comment by moanhawks** [comment]
Why this guys become gay?

**Comment by flossboss** [comment]
He's a cheap version of Dank Memer on Github. 😂

**Comment by herothedev** [comment]
This is worse than ever happened before...

**Comment by Faxtos** [comment]
Learn c++ first instead of requesting some codes

**Comment by OverallGod** [comment]
Please just ducking stop

**Comment by GrowtopiaNoobs** [comment]
Please don't use big text, use shorter issues names, and don't use words "give me".

**Comment by playingo** [comment]
i smell another young lazy immigrant with a small brain or its completely a joke / troll cuz this is over the possible stupidness a human can reach...
meh gt players have reached some stuff already when its about being stupid and crazy :/

**Comment by xXAbood** [comment]
kill urself
