### ISSUE TITLE
[HELP] Can anyone help me with these?

### ISSUE THREAD

**Issue by AnonUgly** [GrowtopiaNoobs/GrowtopiaServer#794]
Hi, I am wanting to throw together a private server for me and a couple friends. Of course I am not expecting anything from asking here, but if anyone is willing to share something about these, that would be awesome. I am wondering how you can have a player start with a blank inventory rather than a bunch of random items, as well as remove sending blank messages when double-tapping enter. Thank you!

**Comment by flossboss** [comment]
Just remove `sendInventory(peer);` after `action|enter_game`

**Comment by flossboss** [comment]
I don't know much about spamming by double tapping the enter key.

**Comment by AnonUgly** [comment]
> Just remove `sendInventory(peer);` after `action|enter_game`

Thanks, i'll look into this.

**Comment by flossboss** [comment]
👌

**Comment by NotDark** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/pull/645 will fix  blank messages

**Comment by Mempler** [comment]
i can help you with that! just replace
```cpp
PlayerInventory inventory;
for (int i = 0; i < 200; i++)
{
    InventoryItem it;
    it.itemID = (i * 2) + 2;
    it.itemCount = 200;
    inventory.items.push_back(it);
}
```
with
```cpp
PlayerInventory inventory;
for (int i = 0; i < 200; i++)
{
    InventoryItem it;
    it.itemID = 0;
    it.itemCount = 0;
    inventory.items.push_back(it);
}
```
I haven't tested it! but it should work.

**Comment by AnonUgly** [comment]
> i can help you with that! just replace
> 
> ```c++
> PlayerInventory inventory;
> for (int i = 0; i < 200; i++)
> {
>     InventoryItem it;
>     it.itemID = (i * 2) + 2;
>     it.itemCount = 200;
>     inventory.items.push_back(it);
> }
> ```
> 
> with
> 
> ```c++
> PlayerInventory inventory;
> for (int i = 0; i < 200; i++)
> {
>     InventoryItem it;
>     it.itemID = 0;
>     it.itemCount = 0;
>     inventory.items.push_back(it);
> }
> ```
> 
> I haven't tested it! but it should work.

Hey! Sorry, but this is what happens when I do what you are suggesting: [https://i.imgur.com/Pv0gVl1.png](url)


> Just remove `sendInventory(peer);` after `action|enter_game`

This also seems to do about the same thing.

**Comment by Mempler** [comment]
Well, you wanted an blank inventory xD

**Comment by AnonUgly** [comment]
> Well, you wanted an blank inventory xD

haha yeah, not _exactly_ what i was looking for. thanks though!

**Comment by AnonUgly** [comment]
I'm going to assume nobody has an answer, so I will close this now.

**Comment by OverallGod** [comment]
Bruh its really easy just use your Brain
