### ISSUE TITLE
AddAdmin

### ISSUE THREAD

**Issue by Mynamebobb** [GrowtopiaNoobs/GrowtopiaServer#795]
How to add admin?
Pls help

**Comment by Mynamebobb** [comment]
but dont know how to put it on

**Comment by herothedev** [comment]
... can you read wiki??? but fine, here is put this after ConsoleHandler `addAdmin("name", "pass", 999);`....

**Comment by Mynamebobb** [comment]
Thanks

**Comment by flossboss** [comment]
I think you can close this now.
