### ISSUE TITLE
Vector same object 

### ISSUE THREAD

**Issue by moanhawks** [GrowtopiaNoobs/GrowtopiaServer#796]
Have someone know how to remove duplicates same object vector?

**Comment by ardakurucim** [comment]
i dont think its bug

**Comment by moanhawks** [comment]
Yes it was not bug but 
[https://gyazo.com/b4066e1d4f927741da31935a6e661d68](url)
Please check it out that link

**Comment by FocusedSG** [comment]
lol make a check if the object is already present in the vector, if it's already present, then break or continue or wtv.

**Comment by FocusedSG** [comment]
```c++
string name = "test";
if (find(vector.begin(), vector.end(), name) != vector.end()) {
//if object is already in vector
}
```
dont ask me how to use it.

**Comment by moanhawks** [comment]
@FocusedSG 
Ty for curl
