### ISSUE TITLE
Explain how dialog return works

### ISSUE THREAD

**Issue by OverallGod** [GrowtopiaNoobs/GrowtopiaServer#803]
So basically I'm working on another project (in java) I'm currently working on dialog return. I just need the information on how to get the button clicked or how the information from the text box gets to the server and how you split it up. Ive already looked at the cch.find("action|dialog return ") == 0) but I think it will help if someone explains it in words

**Comment by OverallGod** [comment]
Nevermind I figured it out

**Comment by OverallGod** [comment]
I made basic account creation with dialog return but currently it saves the password to a text file.But thats not efficient for saving multiple things.  
```
FileWriter fileWriter = new FileWriter(path);
BufferdWriter = new bufferdWriter(fileWriter);
bufferdWriter.write(regpassword);
bufferdWriter.close();
```
I dont know what kind of database to make any recommendations?
I also dont know what kind of encryption the passwords should have and I dont know whats available on java

**Comment by coldchip** [comment]
@OverallGod
You can use MYSQL to store accounts in Java
and you can use sha256 to hash the password.

You must have the mysql java connector library in order to use mysql.

**Comment by OverallGod** [comment]
@coldchip alright thanks I'll attempt mysql and sha256 shouldn't be too hard

**Comment by willi123yao** [comment]
Also, please be reminded that the issues tab is meant for issues and problems related to the code of this repository, and not for other languages or modified versions of the source. You should instead try to first solve the problem yourself, and then ask at the correct places such as where or who you obtained the code from if you are unable to solve the issue.

**Comment by OverallGod** [comment]
@willi123yao yeah I know I'm sorry. I don't have any other way to ask people.
