### ISSUE TITLE
[INFO] Removing the slash prefix { / } from command function also work as something

### ISSUE THREAD

**Issue by RajehTXD** [GrowtopiaNoobs/GrowtopiaServer#805]
This means, CUSTOM Commands!
PS: [I just know it works, but I mean it would be great to bring this up to the fellow coders here.]

**Comment by NotDark** [comment]
yes

**Comment by playingo** [comment]
yes? literally checks for text using the text pointer to read from client, almost the way as gt does

**Comment by RajehTXD** [comment]
i mean i know, i thought it would be great to pull this up to the community, no need for / anymore

**Comment by herothedev** [comment]
Just remove the slash before the cmd?

**Comment by flossboss** [comment]
yes i think

**Comment by MarmoriPelaa** [comment]
Just a thought.. If I would have the permission to host a public server with custom commands without releasing the source, I would make a JSON parser for the commands to make custom behavior on the fly without editing the server itself. If I ever happen to do that, I'll probably make a PR for it at some point. I am up for a challenge but I highly doubt I will ever finish that.

**Comment by RajehTXD** [comment]
this is still open wtf?
