### ISSUE TITLE
How to do ENet timeouts?

### ISSUE THREAD

**Issue by playingo** [GrowtopiaNoobs/GrowtopiaServer#808]
question in title, i want to do a timeout just for the peer so i dont neccessarily need threading for respawning.

**Comment by FocusedSG** [comment]
``enet_peer_timeout`` The parameters are ``(ENetPeer *peer, enet_uint32 timeoutLimit, enet_uint32 timeoutMinimum, enet_uint32 timeoutMaximum)``. All ENet peer functions are here. http://enet.bespin.org/group__peer.html

**Comment by playingo** [comment]
tried, idk what i did wrong

**Comment by VyteGTPS** [comment]
LOLHACKERS
