### ISSUE TITLE
Can Show How To Add admin

### ISSUE THREAD

**Issue by WolfPT** [GrowtopiaNoobs/GrowtopiaServer#81]
![addmin](https://user-images.githubusercontent.com/45072228/48658764-5fcb9800-ea58-11e8-8a25-b8ce47dd50bd.png)

**Comment by MeNoFade** [comment]
put this after cout_ibirialize(); And u need password without hash. Like if you logging with password 123456 you want put 123456, no hash.

**Comment by MeNoFade** [comment]
![image](https://user-images.githubusercontent.com/44878241/48658845-b1c0ed80-ea59-11e8-9805-cffe465882ee.png)

**Comment by WolfPT** [comment]
ty

**Comment by CrazyMonkey313** [comment]
Thanks Does this work and can you make avideo?

**Comment by triple14** [comment]
I add under 
`enet_initialize();`
addAdmin(Matty, "123", 999)

and for some reason I cannot do Admin commands or admin things. What should I do?
