### ISSUE TITLE
Punch/place distation.

### ISSUE THREAD

**Issue by MeNoFade** [GrowtopiaNoobs/GrowtopiaServer#82]
Hello! How change punch or place distation? Help, pls.

**Comment by MeNoFade** [comment]
> Learn cpp first and understand it. And then ask here << Is this to rude for ya?, oh wow sorry man hehe
> 
> If you know cpp very well, its something to do on the player object I believe

I understand and know cpp normal. But this no only cpp. I don't want full code, i want what is responsible punch/place.

**Comment by Mempler** [comment]
i'll close that issue, if you still need help just write something.
