### ISSUE TITLE
Super Supporter Name

### ISSUE THREAD

**Issue by LorenzoRayne** [GrowtopiaNoobs/GrowtopiaServer#821]
Hello so I have an issue regarding to Super Supporter Name , I use it as haveSuperSupporterName and created a command named /supporter it works but if I re enter the world the Super Supporter Name will be gone and if other persons re enter the world they will not be able to see. That's all of it hope someone could help me on it if you do know thanks for helping.

**Comment by herothedev** [comment]
just make that new line to player.jsonnfile when they register, make there state:0, and then when they do /supporter it edits that state:16777217 etc. not helping to do that, cuz i dont have enough time.

**Comment by Deveytv** [comment]
> Hello so I have an issue regarding to Super Supporter Name , I use it as haveSuperSupporterName and created a command named /supporter it works but if I re enter the world the Super Supporter Name will be gone and if other persons re enter the world they will not be able to see. That's all of it hope someone could help me on it if you do know thanks for helping.

Close this issue.
