### ISSUE TITLE
How to Add Tcp/port Firewall+ How desire Port and Port Forward For vps

### ISSUE THREAD

**Issue by kingawesomed2** [GrowtopiaNoobs/GrowtopiaServer#823]
Help ❤🙏

**Comment by herothedev** [comment]
Can you read google cloud docs...

**Comment by NotDark** [comment]
you dont need port forward if you use vps

**Comment by kingawesomed2** [comment]
But im when open python+enet server test not work bad url

**Comment by kingawesomed2** [comment]
@notdark @herothedev

**Comment by herothedev** [comment]
wrong ip on run.py or firewall is on.

**Comment by kingawesomed2** [comment]
@herothedev i need of firewall?

**Comment by Mempler** [comment]
Google.
