### ISSUE TITLE
[BUG] Enet server Test Debug Stopped - Help

### ISSUE THREAD

**Issue by kingawesomed2** [GrowtopiaNoobs/GrowtopiaServer#826]
Hi i host my private server in vps After Online 10-15 People Enet server.exe give error enet server exe stopped What i can do?

**Comment by kingawesomed2** [comment]
@herothedev  @focusedsg @growtopianoobs

**Comment by Deveytv** [comment]
You need vps high vcpu or ram.

**Comment by kingawesomed2** [comment]
@devety i have 8vcpu 30gb ram i need how many more

**Comment by kingawesomed2** [comment]
@deveyty

**Comment by kingawesomed2** [comment]
@deveytv

**Comment by VyteGTPS** [comment]
256gb ram minimum

**Comment by herothedev** [comment]
You need to fix crash bugs, if there is like only 10 players you just need 8gb ram and 2vcpu, there is few go, like players enter some world it might can crash etc.

**Comment by VyteGTPS** [comment]
> You need to fix crash bugs, if there is like only 10 players you just need 8gb ram and 2vcpu, there is few go, like players enter some world it might can crash etc.

no

**Comment by kingawesomed2** [comment]
@vytegtps i get 250gb ram vps and still eror lier noob

**Comment by GrowtopiaNoobs** [comment]
Please post stacktrace, so we can help you. Create new issue if you still have this problem. Closing.
