### ISSUE TITLE
HELP! How i can make all lock works? 

### ISSUE THREAD

**Issue by Tumppi05098** [GrowtopiaNoobs/GrowtopiaServer#827]
I mean world, diamond, bluegem, robotic and etc.
Plz no trolling guys.

**Comment by Tumppi05098** [comment]
Can some one tell me?

**Comment by NotDark** [comment]
> I mean world, diamond, bluegem, robotic and etc.
> Plz no trolling guys.

find 242

and make to this

if(tile==242||tile== dl id || tile == blue gem id and etc)

**Comment by ardakurucim** [comment]
@Tumppi05098 also i think blue gem lock is disabled. You have to fix it

**Comment by Tumppi05098** [comment]
ok ty for helping!
i maybe try fix it

**Comment by VyteGTPS** [comment]
#trash

**Comment by GrowtopiaNoobs** [comment]
This issue was answered, closing.
