### ISSUE TITLE
How to use xampp instead of python http server?

### ISSUE THREAD

**Issue by atomiclucky** [GrowtopiaNoobs/GrowtopiaServer#829]
I know that it's a very newbie question, but it could be helpful, because the python server sometimes crashes.

**Comment by ardakurucim** [comment]
1- install xampp and turn on apache
2- go to xampp/htdocs and put the server_data.php inside of htdocs and change server_data.php to your public ip
3- enjoy ur server

**Comment by VyteGTPS** [comment]
"because the python server sometimes crashes."

**Comment by atomiclucky** [comment]
> 
> 
> "because the python server sometimes crashes."

yeah it does glitch out for me pls don't include me in your stupid memes

**Comment by VyteGTPS** [comment]
your trash codes are the only reason why it does

**Comment by atomiclucky** [comment]
@VyteGTPS yeah i guess you're right... but xampp is still better, right?
