### ISSUE TITLE
How to fix??? 

### ISSUE THREAD

**Issue by Dunzap** [GrowtopiaNoobs/GrowtopiaServer#83]
Record. Growtopia to local host already found

I update everything already
I put the address in hosts
I follow everything from wikia

Still stuck for 1 month and no solutions to it 
Help me plz. Thx

**Comment by MeNoFade** [comment]
What you want fix?

**Comment by learntodlgt** [comment]
Delete the IP in ur hosts

**Comment by Dunzap** [comment]
I want to fix
Record growtopia to local host already found!

If I remove ip address there is the Linux error

**Comment by NotDark** [comment]
> I want to fix
> Record growtopia to local host already found!
> 
> If I remove ip address there is the Linux error

run the run.py as admin

**Comment by GrowtopiaNoobs** [comment]
I am not sure what the issue really is and there probably won't be any answer. If problem persist, then please open new issue.
