### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Avier1** [GrowtopiaNoobs/GrowtopiaServer#836]
I can't find tmain function
Any help? What line is it on?

**Comment by MacaylaMarvelous81** [comment]
somewhere near `main`

**Comment by Avier1** [comment]
> somewhere near `main` (the method definition)
Hm? https://gyazo.com/1c4698ededbf3671357a6553ea772a58
Thats all I see. That isn't the function sadly

**Comment by Avier1** [comment]
Ah  nevermind! Found it, thanks for the help. :D

**Comment by MacaylaMarvelous81** [comment]
you're welcome! please close issue though
