### ISSUE TITLE
[BUG] Updating growtopia issue

### ISSUE THREAD

**Issue by Orbit4682** [GrowtopiaNoobs/GrowtopiaServer#837]
When I create an account, it auto disconnects me then when I relogin it says: update growtopia : It’s also by playingo. Shout out to him

**Comment by MacaylaMarvelous81** [comment]
you already have another issue we don't need 2

**Comment by Deveytv** [comment]
> When I create an account, it auto disconnects me then when I relogin it says: update growtopia : It’s also by playingo. Shout out to him

Try to find 2.994 and u will got gameversion in cpp, and change it to 2.996.

**Comment by VyteGTPS** [comment]
Shout out to him

**Comment by Deveytv** [comment]
> Shout out to him

:joy:, 

> When I create an account, it auto disconnects me then when I relogin it says: update growtopia : It’s also by playingo. Shout out to him
Close this issue.

**Comment by Deveytv** [comment]
> Shout out to him

:joy:, @Orbit4682 Close this issue.
