### ISSUE TITLE
[QUESTION/REQUEST] Mod Zoom/Long Punch

### ISSUE THREAD

**Issue by Avier1** [GrowtopiaNoobs/GrowtopiaServer#839]
How Would I make mod zoom or long punch
i dont see any actions or packets for it

also i want it to be for the role 999

**Comment by InjectionZ** [comment]
OnSpawn

**Comment by NotDark** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/master/enet%20server%20test/enet%20server%20test.cpp#L3597

smstat 1

**Comment by VyteGTPS** [comment]
maybe idiot

**Comment by Avier1** [comment]
> maybe idiot

can't accept that sometimes people don't know shit you know. The world doesn't rely around your brain

"maybe idiot."

**Comment by VyteGTPS** [comment]
"also i want it to be for the role 999"
lel

**Comment by Avier1** [comment]
> "also i want it to be for the role 999"
> lel

yes me dumb >:c
