### ISSUE TITLE
[Question] Just got my vps, help me

### ISSUE THREAD

**Issue by Orbit4682** [GrowtopiaNoobs/GrowtopiaServer#842]
I use Microsoft Azure for my vps. I do not know how to create the firewalls with 'port 80 and 17091'

Please help me if you can 👍

**Comment by moanhawks** [comment]
Open firewall rules then add
Then go azure website find firewall rules 
Inbound 
Add 17091 80
Outbound 
80

**Comment by Orbit4682** [comment]
@moanhawks Appreciate it dude! :D

**Comment by Orbit4682** [comment]
@moanhawks What is your discord so i can dm you

**Comment by moanhawks** [comment]
> @moanhawks What is your discord so i can dm you

MaonHawks#0001

**Comment by GrowtopiaNoobs** [comment]
Closing this issue, because it was answered.
