### ISSUE TITLE
[BUG] Other command's Not work HELP!

### ISSUE THREAD

**Issue by Deveytv** [GrowtopiaNoobs/GrowtopiaServer#844]
Hello there!, I want ask why mine /copyset,/gsm no work but it's correct code, can help me? 
[ NO NEED BULLYING ]

**Comment by ritzysw** [comment]
Hey Im ARE not is Worked my Commands /fuckingautism .. Fk HELP how.. ?! no Bullied PLEASE..

**Comment by Deveytv** [comment]
ok fixed nvm. lol
