### ISSUE TITLE
How To Build Server For Mobile and Connect without Virtual host

### ISSUE THREAD

**Issue by Devops12321** [GrowtopiaNoobs/GrowtopiaServer#845]
How ?? :)

**Comment by NotDark** [comment]
Cant

**Comment by GrowtopiaNoobs** [comment]
You can do it, but it isn't anything easy and noone tried it. You will need to modify `/etc/hosts`, launch http server on your phone and build server for android (this is not supported and there isn't any fork which support this).

**Comment by moanhawks** [comment]
Termux terminal 

G++ Linux 

Apache2 run server like php

**Comment by Devops12321** [comment]
@GrowtopiaNoobs  My Wrong I Mean how to make .exe for android

**Comment by Devops12321** [comment]
![Screenshot_20190926-211951_YouTube](https://user-images.githubusercontent.com/55599636/65714583-15696d80-e0a4-11e9-894c-eecf087b7e58.jpg)

**Comment by Devops12321** [comment]
Like this
