### ISSUE TITLE
How To Build .exe For anroid 

### ISSUE THREAD

**Issue by Devops12321** [GrowtopiaNoobs/GrowtopiaServer#846]
Look ss There gtace And when press gtace its auto connect private server how i can do it like this.

**Comment by Devops12321** [comment]
![Screenshot_20190926-211951_YouTube](https://user-images.githubusercontent.com/55599636/65714876-a3ddef00-e0a4-11e9-860b-52c458444f2d.jpg)

**Comment by moanhawks** [comment]
It was apk 
Use visual andoird to make apk gt

**Comment by MacaylaMarvelous81** [comment]
exe is windows executable

**Comment by NotDark** [comment]
just edit the ip in the apk with notepad

**Comment by mar4ello6** [comment]
Use hex editor and edit addresses of gt to your own

**Comment by herothedev** [comment]
or notepad++ then ctrl + f then find growtopia1.com and chabge it to ur ip and then press save

**Comment by MarmoriPelaa** [comment]
I made a project for this needy dude. Oh well, check my repo GTPatcher-Android for a java program for that.

**Comment by playingo** [comment]
sureking bruh.
also there is a file called "libgrowtopia.so" it does have stuff like ip and some internal gt functions.

**Comment by GrowtopiaNoobs** [comment]
You need to edit apk URL, if you want to connect to private server or somehow edit hosts file.
