### ISSUE TITLE
[Question] Set Up domain 

### ISSUE THREAD

**Issue by moanhawks** [GrowtopiaNoobs/GrowtopiaServer#847]
If me use domain to play Growtopia private server is can right? 

Example:
127.0.0.1 growtopia1.com <<< IP
If domain
customdomain.com growtopia.com

**Comment by kingawesomed2** [comment]
No

**Comment by MacaylaMarvelous81** [comment]
no because of the hosts file. in surge 3 you can

**Comment by herothedev** [comment]
host file need ip domain cant be domain domain.
