### ISSUE TITLE
How Save Clothes can send me screen shot or code pls

### ISSUE THREAD

**Issue by WolfPT** [GrowtopiaNoobs/GrowtopiaServer#85]
Can help me save cloth pls

**Comment by Dunzap** [comment]
Try checking closed posts I think one of them has it (not sure)

**Comment by DrOreo002** [comment]
Stop this mate, I know you really want a good Growtopia private server, but we cannot do everything for free here.

As far as I know saving clothing is kinda hard to make it to work properly. You have to learn a lot of thing such as Database management, CPP, (Database lang like JSON, MySql, etc). For those who have write access, could you please close this thanks.

**Comment by Mempler** [comment]
and btw, it's an duplicate of #66
