### ISSUE TITLE
How do I find a new packet

### ISSUE THREAD

**Issue by MainCmd** [GrowtopiaNoobs/GrowtopiaServer#850]
How do I find a new packet

**Comment by herothedev** [comment]
with GT-Bot and debugging it.

**Comment by MainCmd** [comment]
> with GT-Bot and debugging it.

What is GT-Bot ? and how can I install

**Comment by FocusedSG** [comment]
Packets can be found by de-compiling the game client. Or you can just simply open Growtopia.exe with notepad++ and search for packets. Try searching for "OnConsoleMessage" then you will see it.

**Comment by moanhawks** [comment]
Open cheat engines then search On

**Comment by MainCmd** [comment]
Thanks
