### ISSUE TITLE
ItemData.txt

### ISSUE THREAD

**Issue by iProgramMC** [GrowtopiaNoobs/GrowtopiaServer#853]
Can someone give me the tool to make an ItemData.txt from Growtopia?

**Comment by MarmoriPelaa** [comment]
"Can someone give me the tool"

Who said that there was a tool for that? How about making one yourself?

**Comment by iProgramMC** [comment]
> "Can someone give me the tool"
> 
> Who said that there was a tool for that? How about making one yourself?

Dude. You realize, I'm not a bot? I won't make 5000+ item definitions! My goodness.
Half of them are dupes (for seeds) and half are items. I won't bother making my own. Is there a tool for Growtopia to extract the Item Data?

**Comment by moanhawks** [comment]
Wdym ItemData.txt?

**Comment by iProgramMC** [comment]
> Wdym ItemData.txt?

the file required for item infos and properties

**Comment by MarmoriPelaa** [comment]
Sorry, I was a bit aggressive on this one. I meant that you could make a tool to extract the CoreData.txt from the fandom wiki pages, not to make the CoreData.txt itself. Besides, why would you need ALL of the items anyways? Just make the ones available that you want and fill in their data manually. It's not as difficult to understand the CoreData.txt format as trying to understand items.dat.

Summary: No, there's no tool for obtaining CoreData.txt currently because nobody has made one.

**Comment by MarmoriPelaa** [comment]
Alright, I looked up something and this [sitemap](https://growtopia.fandom.com/sitemap-newsitemapxml-index.xml) is found in the robots.txt of Growtopia Fandom Wikia: You can fetch some item info there if you want. It's a list of all of the pages on that wiki, of which you could search the needed info for populating the CoreData.txt

**Comment by hadiGTPS** [comment]
Idk what you mean with itemdata.txt 
Maybe u mean items id or decompiling items.dat if you mean decompiling items.dat then thats hard for u unless ur some vyte💀

**Comment by iProgramMC** [comment]
> Idk what you mean with itemdata.txt
> Maybe u mean items id or decompiling items.dat if you mean decompiling items.dat then thats hard for u unless ur some vyte💀

I meant CoreData.txt.

**Comment by ritzysw** [comment]
>if you mean decompiling items.dat then thats hard for u unless ur some vyte💀
unless u are a retarded 10 year old in the body of 17 year old who doesn't know anything about coding

**Comment by iProgramMC** [comment]
> > if you mean decompiling items.dat then thats hard for u unless ur some vyte💀
> 
> unless u are a retarded 10 year old in the body of 17 year old who doesn't know anything about coding

I would agree to this but you seem pretty toxic. but yeah, it is definitely hard (you have to decrypt that shit, and reverse-engineer it, which is tough)

**Comment by hadiGTPS** [comment]
> > if you mean decompiling items.dat then thats hard for u unless ur some vyte💀
> 
> unless u are a retarded 10 year old in the body of 17 year old who doesn't know anything about coding

Why are you mad oh nvm bro u got exposed by vyte

**Comment by iProgramMC** [comment]
I figured it a couple of weeks ago, the hardest parts are about name decoding (already released to the public as open source), action type to blockType mapping, omitting lots of small details which could be used to avoid hardcoding, editableType and itemCategory mapping to properties etc. The rest are simple.

**Comment by GrowtopiaNoobs** [comment]
Closing this issue as it has been answered and tool for decoding items.dat has been created.
