### ISSUE TITLE
SetRespawnPos

### ISSUE THREAD

**Issue by ardakurucim** [GrowtopiaNoobs/GrowtopiaServer#855]
Does anyone know how to use SetRespawnPos packet?

**Comment by moanhawks** [comment]
It was same like OnSetPos

**Comment by InjectionZ** [comment]
> It was same like OnSetPos

yes, use it with checkpoint you'll get the effect

**Comment by ardakurucim** [comment]
@InjectionZ tried but it crashed my growtopia 🤔

**Comment by herothedev** [comment]
i tried too and crashed server AND growtopia lol

**Comment by NotDark** [comment]
x+(y*world width)

**Comment by ardakurucim** [comment]
@NotDark no eff

**Comment by ardakurucim** [comment]
@NotDark fixed
