### ISSUE TITLE
the sign visuals thread

### ISSUE THREAD

**Issue by atomiclucky** [GrowtopiaNoobs/GrowtopiaServer#859]
I finally have came to a conclusion that it's not the worldPtr that sends the block information, but a packet (yes, a packet!), that you need to send via SendPacketRaw. And it looks something like this:
4 0 0 0 5 0 0 0 0 0 0 0 0 0 0 0 8 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 18 0 0 0 23 0 0 0 19 0 0 0 20 0 0 0 0 0 1 0 2 4 0 98 114 117 104 255 255 255 255 56

(Yes, I know that you need to send not integers, but raw bytes of data)

The 4 in the packet I think stands for a block visual packet and the last  10 or so chars are responsible for transmitting the message (in this case bruh)

Now the question is where are the coordinates of the sign and how they should be formatted? (as punchx and punchy, or what...)

I'm asking this because I know, that the majority of people have already figured this out and there was already some code leaks.

Thank you, have a great day.

**Comment by NotDark** [comment]
the xy should be the 18 and 23

**Comment by MarmoriPelaa** [comment]
Interesting. We are approaching a brighter future. Off-topic: I Wonder how collecting dropped items is handled. The item ID seems to change on the client and so it is unusable

**Comment by atomiclucky** [comment]
Nah it's not working, I suppose 18 and 23 is not the x and y or that you need something more than this packet, maybe worldptr then? idk really...

**Comment by NotDark** [comment]
> Nah it's not working, I suppose 18 and 23 is not the x and y or that you need something more than this packet, maybe worldptr then? idk really...

this is the right packet

**Comment by iProgramMC** [comment]
hey guys can you provide some code as me trying to send the data through SendPacketRaw crashes the game?

**Comment by iProgramMC** [comment]
@atomiclucky how did you find this packet?

**Comment by atomiclucky** [comment]
oh yeah i should close it
