### ISSUE TITLE
[REQUEST / QUESTION] How To make kick system or ban

### ISSUE THREAD

**Issue by WolfPT** [GrowtopiaNoobs/GrowtopiaServer#86]
How To make kick system or ban

**Comment by coldchip** [comment]
@DrOreo002
Please note that this isn't your average Facebook or any other social media. This is GitHub. We are supposed to help each other and not to mock users on their experience with C++. If you have a valid answer then you'd answer or else you'd keep your mouth shut.

**Comment by ritzysw** [comment]
@coldchip 
this is "issues" tab, people should at least add [REQUEST] in title so we know that its request, otherwise they should ask why any issues happen

**Comment by DrOreo002** [comment]
@ritzysw agree with you

@coldchip sorry but if I gave him the code and telll him how but he didn't understand cpp, then it would be a waste :)

**Comment by Habchy** [comment]
@DrOreo002 I mean all of the code taken from this repo and modified is supposed to be made public according the license. But many have taken it and expanded on it and completely ignored that.

**Comment by Mempler** [comment]
Yea, we know that, and we're not happy about that. People should follow the license, else we could DMCA takedown their servers for not following the license agreement.

Spoiler alert: we wont. To much work / money we would have to put in.

**Comment by Mempler** [comment]
But ofc, we dont mind if they have our permission.
