### ISSUE TITLE
[question] how i can start with multiple servers 

### ISSUE THREAD

**Issue by NotDark** [GrowtopiaNoobs/GrowtopiaServer#860]
So in the todo list have this 

Try possible to write multiple servers which only share between themselves possibly world list, player list and broadcast queue

i try to do that but i no sure where i start from 

like what i need to use?

**Comment by moanhawks** [comment]
Go ask juantlo 👌

**Comment by herothedev** [comment]
Where is he?

**Comment by VyteGTPS** [comment]
use brains

**Comment by moanhawks** [comment]
> Where is he?

In dark server

**Comment by herothedev** [comment]
okhe

**Comment by playingo** [comment]
@NotDark firstly setup 2 servers with 2 different ports and try to redirect client into connecting to different server without dc
btw: if u think its onsendtoserver / onredirectserver ur wrong, except onsendtoserver is indirectly triggered after you did the server sided part according to some ppl
