### ISSUE TITLE
Admin level

### ISSUE THREAD

**Issue by TrisuDL** [GrowtopiaNoobs/GrowtopiaServer#862]
Ok so i have issue im new coeder and idk what is admin level so can somebody tell me?

**Comment by Bykosw** [comment]
adminlevel wont work in growtopianoobs source, probably todo, but you can make checks like that: `if (getAdminLevel(((PlayerInfo*)(currentPeer->data))->rawName, ((PlayerInfo*)(currentPeer->data))->tankIDPass) > 999` the example allow people to do the thing only with adminlevel 999, higher, you can change adminlevel from json file.

**Comment by Bykosw** [comment]
I meant that it will not work in gtnoobs source as addAdmin, but you can do checks of this type.

**Comment by TrisuDL** [comment]
Thank you so much
