### ISSUE TITLE
how to make chat like green backround?

### ISSUE THREAD

**Issue by Deveytv** [GrowtopiaNoobs/GrowtopiaServer#865]
Here i want ask, how to make Like when you talk the backround is blue and how to make it green?

TAG : @NotDark @FocusedSG @bykosw

**Comment by atomiclucky** [comment]
bruh just change the appendintx to 2

**Comment by herothedev** [comment]
change appendIntx 0 to smh else like 3 and it changes the color..

**Comment by moanhawks** [comment]
idk why he tag dark and FocusedSG even byko is bad coding c++

**Comment by atomiclucky** [comment]
> 
> 
> idk why SureMeme tag dark and FocusedSG even byko is bad coding c++

because no matter how advanced in c++ you are, you can always change appendint

**Comment by playingo** [comment]
surememe at its peak: always asking about stuff before trying out himself for ONCE
