### ISSUE TITLE
how to learn c++?

### ISSUE THREAD

**Issue by gdnxdd** [GrowtopiaNoobs/GrowtopiaServer#866]

**Comment by ardakurucim** [comment]
https://www.learncpp.com/

**Comment by FocusedSG** [comment]
A fun and interactive way to learn C++: https://getmimo.com/

**Comment by atomiclucky** [comment]
lol totally related to gtps

**Comment by herothedev** [comment]
he asked how to learn c++, not how to learn c++ ENet.

**Comment by niko1802** [comment]
ok @herothedev

**Comment by GrowtopiaNoobs** [comment]
This issue was answered, so I am closing this.
