### ISSUE TITLE
Ritzy 234 lines /kick code [gtps3 0MfG .LEAKED ]

### ISSUE THREAD

**Issue by VyteGTPS** [GrowtopiaNoobs/GrowtopiaServer#870]
https://pastebin.com/raw/z9bZrPVK

talking trash about other 'coders' but meanwhile, coding 234 lines of /kick

**Comment by VyteGTPS** [comment]
![image](https://user-images.githubusercontent.com/51130398/66275033-7ad01200-e88d-11e9-8cc6-43024859a822.png)

**Comment by ritzysw** [comment]
the meme actually tries to speak
![image](https://user-images.githubusercontent.com/43505497/66275057-a7842980-e88d-11e9-8d6e-fc2894c65e69.png)
![image](https://user-images.githubusercontent.com/43505497/66275068-ae12a100-e88d-11e9-9a4c-d18b9896310a.png)
![image](https://user-images.githubusercontent.com/43505497/66275071-b2d75500-e88d-11e9-8ba0-194b5d00214d.png)

**Comment by VyteGTPS** [comment]
"lul I coded it on purpose"

**Comment by VyteGTPS** [comment]
lying 24/7 
![image](https://user-images.githubusercontent.com/51130398/66275121-309b6080-e88e-11e9-9ddd-a87cdcdb73e3.png)

**Comment by VyteGTPS** [comment]
ok lets play minecraft randomizer 
or BLOCK

**Comment by VyteGTPS** [comment]
or best part when you lied that your 'girlfriend' blocked me instantly not just because u begged her to block me

**Comment by ritzysw** [comment]
good job first stage
![image](https://user-images.githubusercontent.com/43505497/66275219-275ec380-e88f-11e9-88cf-a852432c4f17.png)

**Comment by VyteGTPS** [comment]
sure, you can keep 4th one

**Comment by VyteGTPS** [comment]
![image](https://user-images.githubusercontent.com/51130398/66275347-5164b580-e890-11e9-9920-8ab0ac98cbbb.png)

**Comment by VyteGTPS** [comment]
![image](https://user-images.githubusercontent.com/51130398/66275351-5f1a3b00-e890-11e9-99bf-8746e0dd32a5.png)

**Comment by hadiGTPS** [comment]
LOLOLOL RITZY SAID SOME STUFF ABOUT ME BEING NOOB CODER SAD LIFER BRO 😂❤️
Quick Question Bro How Many Bytes in An Int64?

**Comment by VyteGTPS** [comment]
![image](https://user-images.githubusercontent.com/51130398/66314140-4192b300-e91c-11e9-89a2-3c39698b4088.png)

**Comment by ritzysw** [comment]
LOL!!! AxonSimpleUI (2).exe get it LOLLL xDDD

**Comment by VyteGTPS** [comment]
crash gtps when?

**Comment by ritzysw** [comment]
![image](https://user-images.githubusercontent.com/43505497/66320152-fa5def80-e926-11e9-8f8e-da4107ec8eb8.png)
coredata when?

**Comment by VyteGTPS** [comment]
how is this meme, keep selling it for 500$

**Comment by ritzysw** [comment]
![image](https://user-images.githubusercontent.com/43505497/66320316-4741c600-e927-11e9-88dd-db57d050ac57.png)
the greatest part is that u did pay me

**Comment by VyteGTPS** [comment]
you haven't seen the greatest part, lemme find leLEL

**Comment by hadiGTPS** [comment]
I just upload full edit of coreitems

**Comment by ritzysw** [comment]
poor braindead retard hard +++++++++............... !!!!!!!!! doser, ratter :D hard ++!!!;;;;;;;;;;;;;;;;;;;;;!!!.....!

**Comment by VyteGTPS** [comment]
[send 2k$/month or I spam the same packet over and over]

**Comment by VyteGTPS** [comment]
lel 
![image](https://user-images.githubusercontent.com/51130398/66321479-4e69d380-e929-11e9-80fe-e58df3a65fa6.png)

**Comment by VyteGTPS** [comment]
![image](https://user-images.githubusercontent.com/51130398/66321494-545fb480-e929-11e9-9750-4d2786569eab.png)

**Comment by ritzysw** [comment]
![image](https://user-images.githubusercontent.com/43505497/66321617-88d37080-e929-11e9-8b4c-90b0ff528859.png)

**Comment by ritzysw** [comment]
![image](https://user-images.githubusercontent.com/43505497/66321625-8bce6100-e929-11e9-8b8d-13c539dfaab8.png)

**Comment by ritzysw** [comment]
![image](https://user-images.githubusercontent.com/43505497/66321679-a43e7b80-e929-11e9-8f7b-4ad3b118a1d2.png)

**Comment by VyteGTPS** [comment]
i think that doesnt change the fact that your /kick code is still 234 lines

**Comment by ritzysw** [comment]
i think that doesnt change the fact that u take 1 year old out of context stuff and actually try to make argument out of it

**Comment by VyteGTPS** [comment]
its like 1monnth old

**Comment by ritzysw** [comment]
i stopped making anything related to gt servers half a year ago, now try again

**Comment by VyteGTPS** [comment]
playingo: old

**Comment by ritzysw** [comment]
what

**Comment by VyteGTPS** [comment]
how all of this is old if you still lying about me in every discord group you know lol

**Comment by VyteGTPS** [comment]
you would be nothing without me lol

**Comment by ritzysw** [comment]
>how all of this is old if you still lying about me in every discord group you know lol

proof

>you would be nothing without me lol

i can say the same for you

**Comment by ritzysw** [comment]
also nice changing topic retard

**Comment by VyteGTPS** [comment]
yes admit like I havent seen sm chats hahahwahh

**Comment by ritzysw** [comment]
still waiting

**Comment by VyteGTPS** [comment]
'i can say the same for you'''''''''''''''''''''' 
yes you created gtps
translated:
you left ur shit server bcuz it was so dead to gain something from my server

**Comment by VyteGTPS** [comment]
translated part 2: crying and lying everywhere bcuz u didnt got 50bgls from dupes

**Comment by VyteGTPS** [comment]
now lets play minecraft randomizer or blocked

**Comment by VyteGTPS** [comment]
"and no im not coming back" (crying emote):(crying emote):(crying emote):(crying emote)

**Comment by ritzysw** [comment]
![image](https://user-images.githubusercontent.com/43505497/66322589-0d72be80-e92b-11e9-8a1f-04e7b6b10e76.png)
stage 2
>you left ur shit server bcuz it was so dead to gain something from my server

translated:
i left cuz u begged me to join so u could actually have some kind of server
>translated part 2: crying and lying everywhere bcuz u didnt got 50bgls from dupes

translated part2: delusional braindead 10 year old who plays growtopia every day for hours to find dupes

**Comment by VyteGTPS** [comment]
depression

**Comment by ritzysw** [comment]
also inability to accept the fact that nobody needs you

**Comment by VyteGTPS** [comment]
LEL nobody needs me, but someone needs you, ;point of life;
might use stage 4 bcuz nobody needs me

**Comment by VyteGTPS** [comment]
& I'm good alone 
you can't do anything without someone

**Comment by ritzysw** [comment]
>& I'm good alone
you can't do anything without someone

you use people to make shit for u, you dont know a single coding language, you scam everybody and lie to everyone, literally the saddest life u can really imagine

**Comment by VyteGTPS** [comment]
how is this "using" if im buying something lol, provide proof because haven't seen anything real you said

**Comment by VyteGTPS** [comment]
bro stop ama might bully me, everyone hates me tero mcc blabla

**Comment by VyteGTPS** [comment]
you care everything ppl say and accept it how sad

**Comment by ritzysw** [comment]
changes the topic IMMEDIATELY

**Comment by ritzysw** [comment]
actually sadder than rubby

**Comment by VyteGTPS** [comment]
there is no topic, just ur "trash talking", because you didnt receive 50bgls

**Comment by ritzysw** [comment]
>because you didnt receive 50bgls
>translated part2: delusional braindead 10 year old who plays growtopia every day for hours to find dupes

also changes topic immediately again

**Comment by VyteGTPS** [comment]
bcuz the only 2 things you care was "gtps role" and "50bgls"

**Comment by VyteGTPS** [comment]
![image](https://user-images.githubusercontent.com/51130398/66323690-d8676b80-e92c-11e9-87c0-3c9dd366eb57.png)

**Comment by VyteGTPS** [comment]
![image](https://user-images.githubusercontent.com/51130398/66323709-ddc4b600-e92c-11e9-94c1-ba7110be586e.png)

**Comment by ritzysw** [comment]
changes the topic for the third time, how can u be more sad than this braindead child

**Comment by ritzysw** [comment]
nice use of github issues btw, i guess its too much for your 10 iq to understand what its actually meant for

**Comment by VyteGTPS** [comment]
then stop running from the truth in discord
> blocks everywhere
> trying to deny
> lies to everyone
> still talks about "vyte" after few months

**Comment by ritzysw** [comment]
>blocks everywhere

![image](https://user-images.githubusercontent.com/43505497/66324001-64799300-e92d-11e9-898c-5bddce93299c.png)

>trying to deny

i dont deny the fact that u are 10 year old braindead child
>lies to everyone

lies as in tells everyone the truth about your sad life
>still talks about "vyte" after few months

you are quite literally obsessed with me

**Comment by VyteGTPS** [comment]
yes so obsessed, if you would stop lying in sm and other stuff no one would mention you anywhere

**Comment by ritzysw** [comment]
>stop lying in sm

>lies as in tells everyone the truth about your sad life

**Comment by ritzysw** [comment]
imagine actually being unable to face the truth, i guess playing growtopia 24 hours a day makes u become retarded

**Comment by VyteGTPS** [comment]
"unable to face the truth"

**Comment by VyteGTPS** [comment]
provide something real

**Comment by VyteGTPS** [comment]
bcuz everyone knows you are lying and being retarded since 2016~?~?~?

**Comment by ritzysw** [comment]
![image](https://user-images.githubusercontent.com/43505497/66324459-26c93a00-e92e-11e9-9bad-033793b1efd0.png)
>provide something real

**Comment by VyteGTPS** [comment]
ok go apply to gt mods ezpz

**Comment by ritzysw** [comment]
how is that even fucking remotely related you autist

**Comment by VyteGTPS** [comment]
you opened the topic "post random stuff" so ? ?

**Comment by ritzysw** [comment]
ok so anything that shows how retarded you are is considered random stuff now

**Comment by VyteGTPS** [comment]
aUtISTIc RETARD 
![image](https://user-images.githubusercontent.com/51130398/66324762-b838ac00-e92e-11e9-95db-693b644d206c.png)

**Comment by ritzysw** [comment]
"LOllLL u LIE TO everyone LOLLLl"
![image](https://user-images.githubusercontent.com/43505497/66324898-0188fb80-e92f-11e9-867e-22599540b5f0.png)

**Comment by VyteGTPS** [comment]
yes you lied to ama and others to gain "reputation" =FFFF

**Comment by VyteGTPS** [comment]
using my name everywhere for everything in ur life

**Comment by ritzysw** [comment]
>using my name everywhere for everything in ur life

>you are quite literally obsessed with me

**Comment by ritzysw** [comment]
im basically your idol, now stand on ur knees braindead child

**Comment by VyteGTPS** [comment]
idol LOOOOl idol of blocking everyone and then lying after

**Comment by VyteGTPS** [comment]
ok Sasha, open gtps server because pockets struggling

**Comment by VyteGTPS** [comment]
your 600$ 
![image](https://user-images.githubusercontent.com/51130398/66325237-8ecc5000-e92f-11e9-8c38-aa94a8aa837e.png)

**Comment by VyteGTPS** [comment]
![image](https://user-images.githubusercontent.com/51130398/66325252-968bf480-e92f-11e9-9912-589245bef05d.png)

**Comment by ritzysw** [comment]
![image](https://user-images.githubusercontent.com/43505497/66325272-9e4b9900-e92f-11e9-9403-156bbf2ef07f.png)
hit me up when u stop being braindead, when u stop changing topics, when u stop lying about everything, when u stop scamming everybody

**Comment by VyteGTPS** [comment]
no one is going to hit you up lol

**Comment by VyteGTPS** [comment]
![image](https://user-images.githubusercontent.com/51130398/66325452-f387aa80-e92f-11e9-9d30-3b2130697800.png)

**Comment by ritzysw** [comment]
![image](https://user-images.githubusercontent.com/43505497/66325560-216cef00-e930-11e9-99e2-6d33b2f238a3.png)

**Comment by VyteGTPS** [comment]
good job you failed again 

ISP: | Tele2 Mobile
-- | --

**Comment by ritzysw** [comment]
still waiting for some new "arguments"

**Comment by VyteGTPS** [comment]
https://privnote.com/Nozt9EAt#66n4dkYPd

**Comment by ritzysw** [comment]
akk.li/pics/anne.jpg

**Comment by Bykosw** [comment]
what the fuck

**Comment by VyteGTPS** [comment]
supposed to be *gtps3 code leak * by famous coder ritzy but welcome

**Comment by Bykosw** [comment]
who wanna bet how much comments will be in this issue

**Comment by GaskyUZI** [comment]
100 is the end

**Comment by Siekea** [comment]
Ah

**Comment by niko1802** [comment]
how to i get the newest items.dat with ida hack/?

**Comment by Siekea** [comment]
show wl first

**Comment by niko1802** [comment]
u first

**Comment by Siekea** [comment]
uuuuuuuu first

**Comment by niko1802** [comment]
![image](https://user-images.githubusercontent.com/48137608/66415513-65c9bf00-ea04-11e9-962d-00a087cfb41a.png)
here my 72 wls

**Comment by Siekea** [comment]
rich

**Comment by niko1802** [comment]
aha i knewer u are noob

**Comment by Siekea** [comment]
fakara you!!11

**Comment by niko1802** [comment]
when i smelling u be like:
uh oh
stinkyy
poopiee

**Comment by Siekea** [comment]
ok report

**Comment by niko1802** [comment]
nono i just joke please please dont report ok i was just joke ahah i love u ahahaa so many joke lol!!!!

please no report

**Comment by Siekea** [comment]
-.......--- ok friendd 
![Screenshot_2](https://user-images.githubusercontent.com/46885879/66417828-2057c280-ea01-11e9-84a6-a5003aa073c0.png)

**Comment by playingo** [comment]
FIGHT FIGHT FIGHT BEEF BEEF BEEF gogogogogogo vyte ritzy battle now gogogogo!!111

**Comment by Siekea** [comment]
> FIGHT FIGHT FIGHT BEEF BEEF BEEF gogogogogogo vyte ritzy battle now gogogogo!!111

show proof

**Comment by niko1802** [comment]
![image](https://user-images.githubusercontent.com/48137608/66418165-2bfbb700-ea0a-11e9-87bf-a51640653f07.png)

**Comment by Siekea** [comment]
xD bro no bully him bro XD xD xdddd xDDD stop bro we friendly bro :/ :(

**Comment by niko1802** [comment]
ok sorry mr siekea bro 👊

**Comment by playingo** [comment]
knockout punchout right left yeyeye 111!!

**Comment by Siekea** [comment]
ah

**Comment by VyteGTPS** [comment]
3mins ago
![190CECB6-C68D-4776-A360-1F94731D9249](https://user-images.githubusercontent.com/51130398/66418296-741ad980-ea0a-11e9-80f4-696c18299897.jpeg)

**Comment by Siekea** [comment]
show

**Comment by niko1802** [comment]
siekea

**Comment by Siekea** [comment]
i ddos LEL!! xDDdd

> 3mins ago
> ![190CECB6-C68D-4776-A360-1F94731D9249](https://user-images.githubusercontent.com/51130398/66418296-741ad980-ea0a-11e9-80f4-696c18299897.jpeg)

**Comment by playingo** [comment]
YA YA YA YA ALL IN GO GO GO road 1k comments big drama rage quit wtf vyte ritzy situation wrf breaking news

**Comment by Siekea** [comment]
proof?!!?!??!!?!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by playingo** [comment]
watchout amateurz atipls and then anybody coming in 💥 💥 🔫

**Comment by niko1802** [comment]
![image](https://user-images.githubusercontent.com/48137608/66418660-3c606180-ea0b-11e9-8395-165ec57132f7.png)
guys finnish people are SOO crazy how they showing poop in video.. so crazy guys

**Comment by Siekea** [comment]
🎲

**Comment by playingo** [comment]
YES DISGRACEFUL AND EPIC CONTENT WATCH NOW ON AMATUREZ FINTUBE

**Comment by niko1802** [comment]
actual comedian

**Comment by VyteGTPS** [comment]
loooool i got items.json file i decoded it omg its me ritzy who did it!!
calls it peak
![image](https://user-images.githubusercontent.com/51130398/66507799-88c5a300-ead8-11e9-9672-0cee0e9eaa77.png)

**Comment by VyteGTPS** [comment]
or best part lying that we used that arab guy credit card on fortnite lol, never used it

**Comment by VyteGTPS** [comment]
![image](https://user-images.githubusercontent.com/51130398/66507967-e1953b80-ead8-11e9-9aa9-b279b9b7a2b5.png)

**Comment by VyteGTPS** [comment]
fucking retarded lier holy shit thanks god for these pics
![image](https://user-images.githubusercontent.com/51130398/66508173-346ef300-ead9-11e9-984f-7953f419ed63.png)
![image](https://user-images.githubusercontent.com/51130398/66508206-4355a580-ead9-11e9-9fbd-5be22e1eca37.png)


![image](https://user-images.githubusercontent.com/51130398/66508071-0b4e6280-ead9-11e9-891e-ea03cf34bd32.png)
![image](https://user-images.githubusercontent.com/51130398/66508080-0e495300-ead9-11e9-9b57-6e0c6515e83f.png)
