### ISSUE TITLE
[BUG] Worlds not saving

### ISSUE THREAD

**Issue by Avier1** [GrowtopiaNoobs/GrowtopiaServer#871]
Hey, I'm new so I don't know if this is a bug or...

Anyways please if I could get some advice, Thanks.

**Comment by Zlarex** [comment]
Check here #197. also this is a temporary way to prevent the crash

**Comment by herothedev** [comment]
Just add into ExitHandler sleep(30000); before exit();

**Comment by Avier1** [comment]
Thanks. @Zlarex
