### ISSUE TITLE
[Coreitems] FREE COREITEMS.Dat

### ISSUE THREAD

**Issue by hadiGTPS** [GrowtopiaNoobs/GrowtopiaServer#872]
https://cdn.discordapp.com/attachments/537324452908630017/620743672815681536/CoreData.txt

**Comment by moanhawks** [comment]
CoreData from dark 👍

**Comment by playingo** [comment]
coreitems.dat

**Comment by GrowtopiaNoobs** [comment]
This had enough time to get attention, so I am closing it.
