### ISSUE TITLE
[END OF ROTZY]

### ISSUE THREAD

**Issue by playingo** [GrowtopiaNoobs/GrowtopiaServer#876]
hadigtps wtf Indo lele big ego lele "me friends with sethmumu i can strike u down lele also me have GTPS in end of name lel so anybody my friend too lele"

**Comment by playingo** [comment]
**end of rotzy including his gf betzy

**Comment by ritzysw** [comment]
"END OF ROTZY" talks about "hadigtps", unexpected playingo behavior

**Comment by playingo** [comment]
not going to have an argument to this... just nah...... nah.

**Comment by ritzysw** [comment]
you already know by fact that you will end up raging and saying "LOLL FAKE SM CREATE FAKE ACCOUNT..." whenever i use that as media

**Comment by playingo** [comment]
no argument, yet another time.

**Comment by Siekea** [comment]
shut the fuck up retard and show wl

**Comment by playingo** [comment]
![C2DBA0CE-7646-45F7-81C4-CD65889C665A](https://user-images.githubusercontent.com/50752911/66422244-a37d1680-ea09-11e9-9376-5f0bf4de68a3.jpeg)
HAH I AM NOW PROEST AND PROER THAN U BTW ME LAGI INDONESIA 👍 

Show dl nub

**Comment by moanhawks** [comment]
oof issues become issues racist

**Comment by Siekea** [comment]
“oof” in 2k19 retard

**Comment by playingo** [comment]
gtps in a nutshell: be some kid and spam github poor anybody has to listen to all of this crap

**Comment by playingo** [comment]
now show some respect ✊
