### ISSUE TITLE
[BUG] Enet Server Test Just Closing

### ISSUE THREAD

**Issue by Avier1** [GrowtopiaNoobs/GrowtopiaServer#878]
Ok, I commented out the line where it has 
`enet_host_destroy(server);`
but now I can't launch enet server test.

#197

**Comment by VyteGTPS** [comment]
sign packet tingz

**Comment by MarmoriPelaa** [comment]
DO NOT comment out lines that do the cleanup. This line is responsible for freeing the resources the server uses. Now, reboot the device the server is running on. This should free up the port for the server. Finally, leave the line as it used to be.
