### ISSUE TITLE
Want to know? how to create a private server (Video???) Vote: Yes or No! Show your comment!

### ISSUE THREAD

**Issue by SecretSC** [GrowtopiaNoobs/GrowtopiaServer#881]

**Comment by playingo** [comment]
we dont care and this is the wrong tab

**Comment by VyteGTPS** [comment]
we dont care and this is the wrong tab #teamplayingo

**Comment by MainCmd** [comment]
we dont care and this is the wrong tab #teamplayingo #teamvyte

**Comment by ardakurucim** [comment]
we dont care and this is the wrong tab #teamplayingo #teamvyte #teammaincmd

**Comment by lapadick** [comment]
fuck off idiot

**Comment by SecretSC** [comment]
Stfu please?

**Comment by SecretSC** [comment]
Did i say u care about it i just asked if someone need

**Comment by SecretSC** [comment]
Fuck ur self idiot

**Comment by SecretSC** [comment]
Who said u should care about it ? I am just asking if someone need tutorial

**Comment by SecretSC** [comment]
Who said u should care about it ? I am just asking if someone need tutorial

**Comment by niko1802** [comment]
no

**Comment by iProgramMC** [comment]
no

**Comment by herothedev** [comment]
no

**Comment by InjectionZ** [comment]
yes

**Comment by Avier1** [comment]
Yea definitely

**Comment by arshizx** [comment]
**No**

**Comment by flossboss** [comment]
yes

**Comment by EndGameGTPS** [comment]
Yes Please

**Comment by sanderDijkxhoorn** [comment]
No

**Comment by JadlionHD** [comment]
no

**Comment by EndGameGTPS** [comment]
Yes Please

**Comment by GrowtopiaNoobs** [comment]
Closing this as it got enough time to get attention.
