### ISSUE TITLE
How to change status of items/update it?

### ISSUE THREAD

**Issue by MeNoFade** [GrowtopiaNoobs/GrowtopiaServer#89]
Hello! Who know what respond for changing items status? Like sign, vend, world lock color and others? I thought this some packet, but i don't find even roughly like this. 
What can be responsible for this?

**Comment by ritzysw** [comment]
make custom items.dat

**Comment by MeNoFade** [comment]
> make custom items.dat

For add some item to vend for sell want custom items.dat? Ok..:( Thanks for info.
