### ISSUE TITLE
Error #3 when Saving Worlds

### ISSUE THREAD

**Issue by ipr0gr4mipas2** [GrowtopiaNoobs/GrowtopiaServer#9]
Title ^^

**Comment by GrowtopiaNoobs** [comment]
Do you have created folder worlds?

**Comment by GrowtopiaNoobs** [comment]
Reopening issue, because @ipr0gr4mipas2 want to fix this himself.

**Comment by GrowtopiaNoobs** [comment]
Seems like noone is going to fix this. Closing
