### ISSUE TITLE
How to find hash items.dat?

### ISSUE THREAD

**Issue by MeNoFade** [GrowtopiaNoobs/GrowtopiaServer#91]
I drop new items.dat from cache, but it's doesn't work, i get dc everytime.
![image](https://user-images.githubusercontent.com/44878241/48903380-7153dc00-ee6c-11e8-89db-eb369b40bc9b.png)

**Comment by Mempler** [comment]
That's because you need the latest save.dat hash. you need to send it in the OnSuper packet!

**Comment by MeNoFade** [comment]
> That's because you need the latest items.dat hash. you need to send it in the OnSuper packet!

Can more info? This? 
![image](https://user-images.githubusercontent.com/44878241/48906004-2f2e9880-ee74-11e8-9641-8acee4b63d56.png)

**Comment by Mempler** [comment]
Exactly. that's not the latest hash. the latest hash is something with -6.............. i can't tell, sorry. you need to find out what hash.

**Comment by MeNoFade** [comment]
How to find hash? Ik that nobody will say, but maybe...

**Comment by WolfPT** [comment]
WTH İTS İMPOSİBLE CAN SAY WHERE İ CAN FOUND WHERE İ CAN SEE
