### ISSUE TITLE
How to find hash items.dat?

### ISSUE THREAD

**Issue by MeNoFade** [GrowtopiaNoobs/GrowtopiaServer#92]
Hello! How to find hash items.dat? If someone know, can say what need for this, please and how to find. At least approximately ;(

**Comment by MeNoFade** [comment]
Oh, it's find by cheat engine. Sorry for this theme.

**Comment by Mempler** [comment]
One way is to reverse engineer the latest client. The other way is to put a proxy between you and the server and read all packets.

**Comment by MeNoFade** [comment]
> One way is to reverse engineer the latest client. The other way is to put a proxy between you and the server and read all packets.

Can say programm name for getting and read packets?

**Comment by DrOreo002** [comment]
Its called Ida pro

**Comment by MeNoFade** [comment]
> Its called Ida pro


Ida pro can only check hex, no?

**Comment by Mempler** [comment]
No, you can decompile the latesz growtopia.exe and look into the obfuscated code.

**Comment by MeNoFade** [comment]
> No, you can decompile the latesz growtopia.exe and look into the obfuscated code.

ik, but he don't have items.dat hash. Only OnSuper... I want hash (screen red frame)
![image](https://user-images.githubusercontent.com/44878241/48912070-b20c1f00-ee85-11e8-81e1-3cd751390edf.png)

**Comment by Mempler** [comment]
I thin you missunderstand me. I mean you can find the hashing function there.

**Comment by MeNoFade** [comment]
> I think you missunderstand me. I mean you can find the hashing function there.

Yes, i missunderstand you on start. But how find this function? Here don't have some hash info (only player connect hashes: hash, hast2, fhash)

**Comment by Mempler** [comment]
Well yea, i wont help to do illegal things.

**Comment by MeNoFade** [comment]
> Well yea, i wont help to do illegal things.

illegal?

**Comment by Mempler** [comment]
Decompilling the growtopia source is illegal.

**Comment by Mempler** [comment]
You could just make a proxy, thats not illegal.

**Comment by MeNoFade** [comment]
> You could just make a proxy, thats not illegal.

I don't know what programms needed. I think for getting packets need wireshark, but what need for decrypt packets?

**Comment by Mempler** [comment]
You need to use a library called enet because enet compresses the data so it's useless to use wireshark.

**Comment by NotDark** [comment]
> You need to use a library called enet because enet compresses the data so it's useless to use wireshark.

do you know any tutorial video for that? to make proxy

**Comment by Mempler** [comment]
No, there is no kind of tutorial for that (only for other librarys then enet). Sorry :(

**Comment by willi123yao** [comment]
The documentation for ENet can be found [over here](http://enet.bespin.org/usergroup0.html), and I would suggest you taking a look and see if there is anything you might need to build your own client or proxy to obtain the hash.

**Comment by NotDark** [comment]
> Hello! How to find hash items.dat? If someone know, can say what need for this, please and how to find. At least approximately ;(

@MeNoFade you can debug gt noob's gt bot to get

**Comment by GrowtopiaNoobs** [comment]
Closing this, as autohash has been added.
