### ISSUE TITLE
Can someone give new hash items.dat?

### ISSUE THREAD

**Issue by MeNoFade** [GrowtopiaNoobs/GrowtopiaServer#94]
Hello! Can someone give new hash items.dat? Please

**Comment by DrOreo002** [comment]
Don't want to break ur hopes but I don't think someone will give it that easy. It took a lot of times to find, and efforts.

**Comment by MeNoFade** [comment]
> Like what many others have said here, there are only 2 ways to find the hash, first being you intercept the connection to growtopia either using a proxy or a bot client to fetch the latest hash, or manually calculate it by decompiling the growtopia source and figuring out the function that generates the hash.
> 
> Also, do note that creating another issue when you have already made one regarding the same topic(#92) will NOT help you to get the answer more quickly on here, and I would suggest you to try and figure out the problem by taking into consideration what the various other people have suggested to you.

In #92 topic i want help "How to find it". In this topic i beg give finded hash.

**Comment by willi123yao** [comment]
Like I said, it is almost the same thing, also either no one has the hash or no one is currently willing to give the hash for you just like that. Begging for things will not get you anywhere much, only hard work and effort put in would yield results and hopefully get what you are looking for.
