### ISSUE TITLE
Updating item Stuck

### ISSUE THREAD

**Issue by WolfPT** [GrowtopiaNoobs/GrowtopiaServer#95]
![hep](https://user-images.githubusercontent.com/45072228/48944328-47b3b700-ef37-11e8-9953-348b23f9b434.PNG)
i stucking on Updating items how i can fix

**Comment by Mempler** [comment]
You need to update your items.dat hash, you can find one by writting your own Proxy or reverse engineering the client.

I wont help with reverse engineering nor the Proxy.
but what i can tell is, use the bot from GrowtopiaNoobs to get the latest items.dat hash.
https://github.com/GrowtopiaNoobs/Growtopia-Bot

**Comment by Mempler** [comment]
#94 if you want further information.

**Comment by WolfPT** [comment]
how i can use this growtopia bot :)

**Comment by ardakurucim** [comment]
Im using latest hash and items.dat but still getting error
