### ISSUE TITLE
[Question] is this possible to edit items.dat?

### ISSUE THREAD

**Issue by NotDark** [GrowtopiaNoobs/GrowtopiaServer#96]
edit items.dat is possible?

**Comment by DrOreo002** [comment]
Yes, some other contributor for this project madr a custom item for gt

**Comment by MeNoFade** [comment]
> Yes, some other contributor for this project madr a custom item for gt

He have his server? If have, can you give link?)

**Comment by DrOreo002** [comment]
@NotDark
Not sure, but he managed to do it

@MeNoFade
He's planning to make a gt server not sure when it will came out

**Comment by Mempler** [comment]
To make custom items you need to be able to decode the items.dat, then add your item. Then you need to encode your items.dat.

You'll need an working hashing function to get the items.dat hash from your modified items.dat.

**Comment by MeNoFade** [comment]
> To make custom items you need to be able to decode the items.dat, then add your item. Then you need to encode your items.dat.
> 
> You'll need an working hashing function to get the items.dat hash from your modified items.dat.

What is programm encode it? Proton sdk?

**Comment by MeNoFade** [comment]
> > To make custom items you need to be able to decode the items.dat, then add your item. Then you need to encode your items.dat.
> > You'll need an working hashing function to get the items.dat hash from your modified items.dat.
> 
> What is programm encode it? Proton or something special for growtopia?

**Comment by NotDark** [comment]
> To make custom items you need to be able to decode the items.dat, then add your item. Then you need to encode your items.dat.
> 
> You'll need an working hashing function to get the items.dat hash from your modified items.dat.

do you know how to decode? like use what tool

**Comment by ipr0gr4mipas2** [comment]
Who is the person that added a custom GT item?

**Comment by Mempler** [comment]
We're not allowed to say that, you need to find out by yourself instead of asking!
