### ISSUE TITLE
Need Help...  Server give a 404 error not found file or...bad url

### ISSUE THREAD

**Issue by Devops12321** [GrowtopiaNoobs/GrowtopiaServer#964]
![FS](https://user-images.githubusercontent.com/55599636/66677823-2a80f780-ec73-11e9-8cb6-0001bb936ac8.jpg)
i open my server in vps when people try connect in pc this happen. i already test login real gt first after reopen and login but still not working. im not using xampp for http i using python 2.997 with this error coming

**Comment by LorenzoRayne** [comment]
Update your CDNCONTENT to newest

**Comment by herothedev** [comment]
23

**Comment by Deveytv** [comment]
Yep, I see problem has been solved? Close this issue @Devops12321

**Comment by iProgramMC** [comment]
I fixed it by deleting cache. You can try that.

**Comment by SecretSC** [comment]
Search in the cpp on CDNCONTENT and you will see in front the CDNCONTENT there 2 numbers change them to 23 and Then you will fix the problem:)

**Comment by Devops12321** [comment]
@Jadlionhd  @SecretSC  Thank you very Much ❤

**Comment by VyteGTPS** [comment]
> Search in the cpp on CDNCONTENT and you will see in front the CDNCONTENT there 2 numbers change them to 23 and Then you will fix the problem:)

hard
