### ISSUE TITLE
[BUG] My enet server test.exe  auto shutdown

### ISSUE THREAD

**Issue by Devops12321** [GrowtopiaNoobs/GrowtopiaServer#968]

**Comment by iProgramMC** [comment]
can you describe how the bug happens?

**Comment by Devops12321** [comment]
@iProgramMC  i when do /unban [name] my enet server test.exe auto shutdown or every 1 hour auto shut down

**Comment by iProgramMC** [comment]
code?

**Comment by Devops12321** [comment]
@iProgramMC  i dont know why shut down.

**Comment by MarmoriPelaa** [comment]
You have to compile it by yourself. There are currently no prebuilt binaries for this.

**Comment by iProgramMC** [comment]
probably memory leak, check your mem usage

**Comment by GrowtopiaNoobs** [comment]
Answers were given and there is not enough details to provide real help, so I am closing this.
