### ISSUE TITLE
Help me stuck on Located server, connecting...

### ISSUE THREAD

**Issue by ZentaiZber** [GrowtopiaNoobs/GrowtopiaServer#969]
![image](https://user-images.githubusercontent.com/51924277/66818880-32d57d00-ef68-11e9-9483-d95e4eb5527a.png)

help me fix this my friend buying vps google cloud but cant connect to the fucking private server

**Comment by cmdocmd** [comment]
open ports

**Comment by NotDark** [comment]
add tcp 80 udp 17091 to the google cloud firewall (In the website)

**Comment by JadlionHD** [comment]
Make a new rule in firewall with advanced security. inbound rules, then do what dark said. TCP 80 and UDP 17091. If your problem solved please close this issue.

**Comment by GrowtopiaNoobs** [comment]
Answer was given and there was no new activity, so I assume it is solved.
