### ISSUE TITLE
HELP! Lets END THIS Virus GAME...

### ISSUE THREAD

**Issue by Devops12321** [GrowtopiaNoobs/GrowtopiaServer#971]
Hello,As u know breaworlds... in [google play] maybe you dont know like a growtopia but 2d versions. steal save.dat permissions your photo/sd etc. i found pc versions in this website,  if you know how to use cheat engine maybe there some bugs ??? http://breaworldsgame.com/download
you can dowland in here! help me find  bugs. and down this trash game.

**Comment by moanhawks** [comment]
oof this is issues Growtopia Server not about another game

**Comment by Devops12321** [comment]
@moanhawks  okey people why here ?  asking for help. maybe someone interest

**Comment by herothedev** [comment]
btw do u have even any proofs expect ytubers saying that it steals LOL. + who even care ur private server save.dat ...

**Comment by niko1802** [comment]
i hate this 2d version of growtopia

**Comment by Siekea** [comment]
yea bro virus!!111

**Comment by iProgramMC** [comment]
> i hate this 2d version of growtopia

yeah minecraft is 4d, growtopia is 3d and this shit is 2d heheheh

**Comment by VyteGTPS** [comment]
l0lz i didnt got free mod so its virus game =]

**Comment by Devops12321** [comment]
@VyteGTPS  if you dont believe me dowland. and get ready hacked :  ) also in google play permission sd-storage access photo access f***full network access*** etc.

**Comment by Siekea** [comment]
send proof on discord now!! waiting... -_-

**Comment by Siekea** [comment]
@Devops12321 Pixel Worlds and Growtopia has the same permissions lol.
Photo and storeage access etc
And it doesnt even request storage permission u idiot kid

**Comment by niko1802** [comment]
siekea its obviously  hacker spacker smack save.dat stealer photo stealer steal internet wifi ddos connection hack.

stop trying to trick us.
 that one youtuber said its scam so its scam FUCK YOU

**Comment by iProgramMC** [comment]
All games that save their data to internal memory (not root) need file permissions. Usually that wouldn't be an issue. "Full" network access is also something you should not worry about.


I haven't found a single Android save.dat stealer for GT, perhaps it's stored in GT's own /data/ folder, which is inaccessible by other apps

**Comment by herothedev** [comment]
I don't get it why they say this is "virus" game if one youtuber said it, maybe the youtuber just hates the developer who made cubic planet (real save.dat stealer). And if i remeber right, it wasnt him, it was the other developer who added the stealer. So think and use own brains, and youtubers are NOT always right.

**Comment by Siekea** [comment]
> siekea its obviously hacker spacker smack save.dat stealer photo stealer steal internet wifi ddos connection hack.
> 
> stop trying to trick us.
> that one youtuber said its scam so its scam FUCK YOU

FUCK YOU STOP ANNOYING ME WTFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

**Comment by kingawesomed2** [comment]
Cubic Planet Made By Breaworlds Developer And He sold Cubic Planet to Laken. After Laken Steal Over 1000+ Save.dat "He said in discord" And After Breaworlds Developer Create New Game With New Code And Again Sold To Laken.

**Comment by herothedev** [comment]
fp... IT WAS @Korean who made save.dat stealer are u guys little bit -IQ?

**Comment by VyteGTPS** [comment]
> fp... IT WAS @korean who made save.dat stealer, bruh..

fp indog fp

**Comment by anysz** [comment]
lol

**Comment by GrowtopiaNoobs** [comment]
Closing this issue, because it is not related to this server.
