### ISSUE TITLE
entering a world rarely crashes. (actual issue) [BUG] 

### ISSUE THREAD

**Issue by playingo** [GrowtopiaNoobs/GrowtopiaServer#973]
Entering a world rarely crashes, needs to be fixed @GrowtopiaNoobs .
It's I guess better that it doesnt crash at all.

**Comment by VyteGTPS** [comment]
green wl tingz....

**Comment by atomiclucky** [comment]
yeah doesnt crash for me must be your major improvement in gameplay

**Comment by playingo** [comment]
@VyteGTPS ok no need, vyte is right (thanks). I didnt check if the stream failed + its fixed in general now when loading the "green wl tingz"
