### ISSUE TITLE
[Question] Port of question 

### ISSUE THREAD

**Issue by WoofHax** [GrowtopiaNoobs/GrowtopiaServer#974]
If my enet server test exe is crashing the port is open or closed?

**Comment by flossboss** [comment]
I believe it is still opened.

**Comment by kingawesomed2** [comment]
Yes Ur code Wrong znoob

**Comment by playingo** [comment]
@kingawesomed2 u cant code yourself kid indog

**Comment by kingawesomed2** [comment]
Alive
