### ISSUE TITLE
How to end ddos? some guy ddos my server 24/7 (sad)

### ISSUE THREAD

**Issue by Tumppi05098** [GrowtopiaNoobs/GrowtopiaServer#979]
how to stop ddos?
Finland ddosing my server... -_-

**Comment by herothedev** [comment]
1. DDoSsing is illegal, so you need to report him to discord team with proofs etc. 2. Only way to stop DDoSsing is just blocking ports.

**Comment by atomiclucky** [comment]
it's probably not ddosing, but crashing. You can't find the difference, though.

**Comment by WoofHax** [comment]
Just block he IP in rules firewall

**Comment by Growtopia3** [comment]
@Tumppi05098 he doesnt ddos he uses crashing to freeze The server so stfu u kiddo
-Nabsi#1337
Btw oot homo

**Comment by VyteGTPS** [comment]
> 1. DDoSsing is illegal, so you need to report him to discord team with proofs etc. 2. Only way to stop DDoSsing is just blocking ports.

"Only way to stop DDoSsing is just blocking ports." :DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
 retard.

stop using google cloud vps

**Comment by Tumppi05098** [comment]
ty @Growtopia3 
entä jos oonki :D

**Comment by herothedev** [comment]
@VyteGTPS amm... other vpses have too firewall???
