### ISSUE TITLE
Linux(ubuntu) can't get it working properly

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [GrowtopiaNoobs/GrowtopiaServer#982]
I can build cmake etc, but the g++ -o enet server test enet server test.cpp -std=c++11 -lenet or g++ -o "enet server test" "enet server test.cpp" -std=c++11 -L. -lenet -iquote. or another can't find it anymore these all won't work, please let me know if you could help me (discord:  ZYKI#9871)

**Comment by herothedev** [comment]
u need to install build-tools..

**Comment by sanderDijkxhoorn** [comment]
I did

**Comment by Switchry** [comment]
install enet

**Comment by sanderDijkxhoorn** [comment]
I installed everything so, (missing files)

**Comment by Switchry** [comment]
we need to see the install logs

**Comment by sanderDijkxhoorn** [comment]
I am using only a command shell how can I send the logs?

**Comment by sanderDijkxhoorn** [comment]
First of all I run these command:
- sudo apt-get install build-essential -works
  - cd "enet server test" -works
  - cd "enet2" -works
  - cmake CMakeLists.txt -works
  - make -works
  - cp libenet.a ../libenet.a -works
  - cd .. -works
  - g++ -o "enet server test" "enet server test.cpp" -std=c++11 -L. -lenet -iquote. -not works

says:
g++:  error o: No such file or directory
g++: error: enet server test: no such file directory

**Comment by herothedev** [comment]
u didnt write "enet server test" u did write enet server test...

**Comment by sanderDijkxhoorn** [comment]
I did both

**Comment by sanderDijkxhoorn** [comment]
The error is with the “”

**Comment by sanderDijkxhoorn** [comment]
I just copy and paste the code that is in that file

**Comment by sanderDijkxhoorn** [comment]
Alright I got it setu
