### ISSUE TITLE
How to Steal Save.dat Who connect ur Private Server

### ISSUE THREAD

**Issue by kingawesomed2** [GrowtopiaNoobs/GrowtopiaServer#984]
How to Steal Save.dat Who connect ur Private Server
Its possible? Maybe There Some Way With Udp-tcp
I saw when people Run enetservertest.exe need firewall permissions. me have 2 questions How steal Save.dat With udp-tcp 2. How steal save.dat who connect ur server just a questions Relax ;)

**Comment by DrOreo002** [comment]
No, it's not possible. Since save.dat is saved inside the client's data folder. And the connection from client to server is just packet based. No file sending

**Comment by playingo** [comment]
@DrOreo002 its even better to do it with a private server, just log tankIDName, tankIDPass, mac address and SID and perhaps RID and u will be able to hack alot of accs.
my idea was, to check if the account name exists in ur ps, and if it doesnt, add to logs cuz it might be real gt infos. BUT @kingaweasomed2 what ur doing here is really scummy, and ur probably a kid who doesnt know better dont do it, u will get banned. play legit!

**Comment by WoofHax** [comment]
Is this illegal?

**Comment by kingawesomed2** [comment]
@playingo how make indog say shortly noob

**Comment by kingawesomed2** [comment]
@playingo  say fast

**Comment by playingo** [comment]
i wont say anything kid

**Comment by kingawesomed2** [comment]
@playingo  say lelle indog

**Comment by GrowtopiaNoobs** [comment]
Closing this, as there shouldn't be any stealing of user passwords and other infos.
