### ISSUE TITLE
[Help] Super Supporter Name

### ISSUE THREAD

**Issue by flossboss** [GrowtopiaNoobs/GrowtopiaServer#985]
Is there a way to automatically give a person with a certain admin level super supporter name?

**Comment by coldtopia** [comment]
yes :trollface:

**Comment by Switchry** [comment]
https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/8643d39a38c64a046421af081a12e57a93c9bfe4/enet%20server%20test/enet%20server%20test.cpp#L3463

add ```
((PlayerInfo*)(peer->data))->haveSuperSupporterName = true;
````

**Comment by flossboss** [comment]
@coldtopia plz help

@Switchry when using better admin system, it doesn’t work :v

**Comment by WoofHax** [comment]
@flossboss I think you issues is level admin problem

**Comment by Switchry** [comment]
put the code around here
https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/8643d39a38c64a046421af081a12e57a93c9bfe4/enet%20server%20test/enet%20server%20test.cpp#L3456

if (adminlevel(((PlayerInfo*)(peer->data))->rawName) == adminlevel u want) {
((PlayerInfo*)(peer->data))->haveSuperSupporterName = true;
}

**Comment by flossboss** [comment]
Not working ✌️

**Comment by WoofHax** [comment]
@Switchry fp he using int admin level #740

**Comment by flossboss** [comment]
I fixed
