### ISSUE TITLE
[BUG] Can't Connect to my Private server

### ISSUE THREAD

**Issue by rheein** [GrowtopiaNoobs/GrowtopiaServer#988]
I'm using Ubuntu 18.04, I have also port forwarded and allow firewall but I still can't connect to my server.
![Screenshot_7](https://user-images.githubusercontent.com/51084175/67631633-91d1b500-f8cb-11e9-828f-f58ed090b2fa.png)

**Comment by Switchry** [comment]
did u disabled ufw

**Comment by rheein** [comment]
yea, im using firwalld

**Comment by rheein** [comment]
ufw List:
![Screenshot_8](https://user-images.githubusercontent.com/51084175/67631826-ff7ee080-f8cd-11e9-82c0-ab13364528b1.png)

Firewalld List:
![Screenshot_10](https://user-images.githubusercontent.com/51084175/67631833-16bdce00-f8ce-11e9-8c79-20dbe112faf2.png)

Iptables List:
![Screenshot_9](https://user-images.githubusercontent.com/51084175/67631834-1de4dc00-f8ce-11e9-9205-ff46b684ae31.png)

**Comment by Switchry** [comment]
can u show what error u got?

**Comment by rheein** [comment]
i didnt get any error on the screen

![Screenshot_4](https://user-images.githubusercontent.com/51084175/67632503-859f2500-f8d6-11e9-8410-a90eeb9d7c38.png)

**Comment by Switchry** [comment]
how about on gt

**Comment by rheein** [comment]
Nope

**Comment by rheein** [comment]
do i need run.py?

**Comment by rheein** [comment]
i also already add ip to my hosts file
xxx.xxx.xxx growtopia1.com

**Comment by sanderDijkxhoorn** [comment]
> I'm using Ubuntu 18.04, I have also port forwarded and allow firewall but I still can't connect to my server.
> ![Screenshot_7](https://user-images.githubusercontent.com/51084175/67631633-91d1b500-f8cb-11e9-828f-f58ed090b2fa.png)

How could you make the server even start on ubuntu? I am stuck at g++ -o "enet server test" "enet server test.cpp" -std=c++11 -L. -lenet -iquote. it gives tje errors:
g++: error o: No such file or directory
g++: error: enet server test: no such file directory

**Comment by rheein** [comment]
have you tried this?
`  build_script:
  - sudo apt-get install build-essential
  - cd "enet server test"
  - cd "enet2"
  - cmake CMakeLists.txt
  - make
  - cp libenet.a ../libenet.a
  - cd ..
  - g++ -o "enet server test" "enet server test.cpp" -std=c++11 -L. -lenet -iquote.
`

**Comment by rheein** [comment]
@sanderDijkxhoorn is it working?

**Comment by sanderDijkxhoorn** [comment]
> @sanderDijkxhoorn is it working?
at g++ -o "enet server test" "enet server test.cpp" -std=c++11 -L. -lenet -iquote. part it doesn't work, errors: 
g++: error o: No such file or directory
g++: error: enet server test: no such file directory

**Comment by sanderDijkxhoorn** [comment]
I am trying out : https://github.com/coldchip/growtopiaserver, on my mac but when I connect it says  please login with growid when I try login with for an example mwi password ss it dsays succesfully then says at updating bad error 404 or soemthing

**Comment by rheein** [comment]
@sanderDijkxhoorn Add my discord Rheein#7515

**Comment by WoofHax** [comment]
@rheein Growtopia Noobs just update config.json port file did you add that file?

**Comment by rheein** [comment]
@WoofHax i added the config.json with content
`{
"port": 17091
}`

**Comment by herothedev** [comment]
if u use gcloud bruh u need to edit there too firewalls..

**Comment by WoofHax** [comment]
@herothedev not just only gcloud fp 
Aws,gpc,azure

**Comment by rheein** [comment]
Im not using gcloud, but ill try that

**Comment by rheein** [comment]
```
$ iptables -I INPUT -p tcp --dport 80 -j ACCEPT
$ iptables -I INPUT -p udp--dport 17091  -j ACCEPT

$ firewall-cmd --add-port=80/tcp --permanent
$ firewall-cmd --add-port=17091 /udp--permanent

$ sudo ufw allow 80/tcp
$ sudo ufw allow 17091/udp
```

**Comment by rheein** [comment]
i added run.py and start it
![Screenshot_1](https://user-images.githubusercontent.com/51084175/67649568-2c81d080-f96c-11e9-9cdd-0b79e311cc3a.png)

**Comment by rheein** [comment]
Fixed but the server auto crash when i entered world

**Comment by WoofHax** [comment]
Add this file 
worlds 
players 
If clothes don't work mean you need to add coreData for dat clothes

**Comment by sanderDijkxhoorn** [comment]
I have all those added it works I can do everything if I’m sure accept for placing/breaking
