### ISSUE TITLE
[BUG] How can i connect my private server to WAN 

### ISSUE THREAD

**Issue by Granger-spec** [GrowtopiaNoobs/GrowtopiaServer#989]
i only can play on LAN

**Comment by sanderDijkxhoorn** [comment]
no shit

**Comment by sanderDijkxhoorn** [comment]
heard of port forwarding?

**Comment by Granger-spec** [comment]
ye but it shit I think i tried all port forwarding but this shit is not working

**Comment by MarmoriPelaa** [comment]
Requirements:
- ADSL
- Static ip
- Knowledge of the dangers of port forwarding.

Finally, just [search port forwarding on google](www.google.com/search?q=port+forwarding).
