### ISSUE TITLE
How to make a sign

### ISSUE THREAD

**Issue by IndogLelele** [GrowtopiaNoobs/GrowtopiaServer#991]
please give me a clue to make a sign work

**Comment by NotDark** [comment]
![image](https://user-images.githubusercontent.com/44568476/67654549-dec79100-f988-11e9-8068-48722abd50c0.png)

**Comment by IndogLelele** [comment]
Is work?

**Comment by flossboss** [comment]
Nice name :v

**Comment by IndogLelele** [comment]
oh thank you is work :)

**Comment by iProgramMC** [comment]
#967
