### ISSUE TITLE
[BUG] linux server crash

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [GrowtopiaNoobs/GrowtopiaServer#992]
server crashes when punching/breaking and placing locks it will instant crash error:
terminate called after throwing an instance of 'int'
Aborted (core dumed)

**Comment by MarmoriPelaa** [comment]
Put CoreData.txt in the same folder as the binaries.

**Comment by sanderDijkxhoorn** [comment]
> Put CoreData.txt in the same folder as the binaries.

I have coredata in ever folder (testing) nothing works)

**Comment by sanderDijkxhoorn** [comment]
I did not even edit a single thing to the cpp
