### ISSUE TITLE
[QUESTION] New chat

### ISSUE THREAD

**Issue by flossboss** [GrowtopiaNoobs/GrowtopiaServer#993]
So the tag is [S] for OnConsoleMessage.
How do you change it to [MSG] or [ADMIN]?
![djjdjwr](https://user-images.githubusercontent.com/49786970/67717701-9b7b1b80-f9a4-11e9-9675-25f5d90fa41f.png)
![eegg](https://user-images.githubusercontent.com/49786970/67717702-9c13b200-f9a4-11e9-9712-c68e2a7264c0.png)

**Comment by MarmoriPelaa** [comment]
Use GrowtopiaBot to analyze packets and msg the bot stuff in real GT. Then read from cout for example.

**Comment by flossboss** [comment]
I don't have GTBot. That's why I'm asking on Github.

**Comment by NotDark** [comment]
add int

**Comment by Granger-spec** [comment]
Do u have the latest items file where can i find the latest?

**Comment by SteakNeedCpp** [comment]
Pls me need omg pls fast

**Comment by flossboss** [comment]
> Do u have the latest items file where can i find the latest?

Go to Growtopia file location it should be in cache folder

**Comment by flossboss** [comment]
@notdark thanks I'll try
