### ISSUE TITLE
Vds Or vps BETTER?  And which vps or vds service better

### ISSUE THREAD

**Issue by kingawesomed2** [GrowtopiaNoobs/GrowtopiaServer#999]
Which vps or vds service better i dont like google cloud or microsoft azure anyone know another vps or vds can 50 people join

**Comment by playingo** [comment]
do you even know what a fucking vps is without googling rn young boy?

**Comment by Devops12321** [comment]
vds

**Comment by herothedev** [comment]
bruh its VPS = Virtual Private Server, Does VDS = Virtual Drivate Server LOL. but there like tons of those just search from google vps

**Comment by ardakurucim** [comment]
drivate

**Comment by Switchry** [comment]
virtual dedicated server*

**Comment by GrowtopiaNoobs** [comment]
I don't think there is big difference in term of hosting small private servers. Closing this issue, bacause it is too old.
